### ISSUE TITLE
🙏Add export to xlsx feature

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#1008]
### 🖋 Description

Add export to xlsx feature

### 🏞 What problem does this feature solve

The main difference between csv and xlsx is that xlsx can support **combined cells**

### 🧐 Suggest the API

The xlsx libs are usually large, so my suggestion is to let parent component pass a xlsx lib instance to the S2SheetComponent. That way, users do not need to install xlsx lib if they don't need this feature.

**Comment by wozien** [comment]
自己用 sheetjs 把 csv 转一下吧
