### ISSUE TITLE
🐛自定义ColCell后列名会被格式化

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#1014]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.3.0 ～      |
| @antv/s2-react | -         |

### 🖋 Description
设置自定义colcell后，列名的文本会按照meta中设置的formatter进行格式化。

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/c8bbcaab

**Comment by lijinke666** [comment]
刚试了下, 明细表和透视表都有这个问题

**Comment by lijinke666** [comment]
ref: https://github.com/antvis/S2/pull/845
