### ISSUE TITLE
🙏是否可以支持透视表合计浮动在顶部或者底部，或者透视表可以设置浮动哪行

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#1020]
### 🖋 Description
是否可以支持透视表合计浮动在顶部或者底部，或者透视表可以设置浮动哪行
### 🏞 What problem does this feature solve
![image](https://user-images.githubusercontent.com/24189636/150083727-39c5aed7-055f-4154-bacb-2dec64fa728e.png)
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by stone-lyl** [comment]
设置:  reverseLayout: false  就满足总计在底部

![image](https://user-images.githubusercontent.com/20497176/151509515-68a30df6-ab01-4449-8d16-1024fac42319.png)

**Comment by cylnet** [comment]
截图里就是用的这个 ，但是无法设置浮动在底部，想实现浮动底部，自己看起来也比较清楚

**Comment by stone-lyl** [comment]
此功能将在S2 升级 G 5.0 后支持
