### ISSUE TITLE
🐛windows系统 chrome49下官网demo报错

### ISSUE THREAD

**Issue by zhaozailin** [antvis/S2#1021]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -         |

### 🖋 Description

windows系统 chrome49下官网demo报错
![image](https://user-images.githubusercontent.com/6063677/150088179-02a27ea4-369a-4e25-afaa-4b299dbce361.png)

### 💻 System information
chrome: v49.0, window

**Comment by lijinke666** [comment]
目前 chrome 的版本是 97, 有没有一种可能, 你升级下版本再试一试
