### ISSUE TITLE
🐛 s2更新机制上的缺陷

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#1029]
### 🖋 Description
s2 core以及react组件在使用上都发现一个问题： 很多传入属性的变化并不被感知从而没有刷新表的配置

1. react组件上 的event handler 类型的 props，比如 onColCellClick onColCellHover等等，这些handlers只在表组件第一次Mount后绑定一次，后续这些props更新也不会做重新绑定。 所以不管传入的func怎么变，始终还是第一次传入的。       既然作为react组件的props开放出来，props本身变了肯定需要对其做相应更新。
![image](https://user-images.githubusercontent.com/15276351/150319675-6622a34f-49db-4fa9-8336-75c3623013db.png)

目前实际用写这些func时只能传入一个对象，通过闭包来拿到最新的属性。

2. s2options中的customInterctions， 传入的交互发生改变时也不会感知然后对交互进行增删和更新。
![image](https://user-images.githubusercontent.com/15276351/150321351-bac71caa-8263-4485-977b-f2bb08304fff.png)

个人觉得 交互配置 可以单独作为API 放出让用户 手动注册销毁管理。 如果作为配置项开放出来的话，配置改变了就应该相应生效

**Comment by stone-lyl** [comment]
1. 底表是会去监听 props 的改变，然后执行方法的。但不知道你是如何去更新的方法的哈。
![image](https://user-images.githubusercontent.com/20497176/151507647-1634284e-c4e7-459b-b385-f349b3f874af.png)
2.  s2 是向外抛出了 S2Event 事件，提供给用户使用。不知道是否满足你的要求
 docs: https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic

**Comment by Esorakouki** [comment]
@stone-lyl  
1. 截图里bindEvent这个函数虽然本身会更新，但执行只会在mount后执行一次吧。
2. 我想描述的是 我想通过s2Option里的 CustomInteractions 来传入自定义的一些交互，但比如如果一开始使用的交互A，CustomInteractions：[ A ]；后面将交互A改为B，CustomInteractions： [B], 表格上注册的交互还是A
