### ISSUE TITLE
使用 S2Event.DATA_CELL_CLICK  数值单元格点击 交互的问题

### ISSUE THREAD

**Issue by XiaJunjie2020** [antvis/S2#1042]
### 🖋 Description
![image](https://user-images.githubusercontent.com/59437931/150739884-0279e33e-6e45-44d3-9bcc-dd814aed7d10.png)

如图红框所示：
1.代码中使用data-cell:click事件。
2.单击表格中 ‘7789’ 单元格，第一次点击在偏左侧空白区域，第二次点击在数值‘7789’上，右侧控制台分别出现两次不同的打印。只有第二次点击在数值上，控制台target.attrs中才有text，font等信息，否则取不到值。
或者说，有没有另外的方法，能够当我单击数值单元格的时候，获取单元格中数值等信息。

### 😊 Expected Behavior
点击在单元格内，无论单击在空白区域或者数值区域，都能拿到target.attrs.text

### 😅 Current Behavior
使用data-cell:click，只有单击在数值单元格中的数值上才能拿到单元格中的值

**Comment by stone-lyl** [comment]
你说的这种情况确实存在哈，所以我们更推荐使用 getCell 去获取单元格信息，这样应该可以获取正确的信息。
你看一下是否满足你的需求。
![image](https://user-images.githubusercontent.com/20497176/151511985-6b250237-a16c-4d1e-b16f-db630324d285.png)

**Comment by lijinke666** [comment]
内部实现中, 单元格和 单元格内的文字 是两个不同的图层, 所以同一个单元格内不同的光标位置, 拿到的 target 不一样, 请参考楼上写法

**Comment by XiaJunjie2020** [comment]
OK!Good job.Thanks.
