### ISSUE TITLE
🐛当不同父节点下存在相同子节点时高级排序出错

### ISSUE THREAD

**Issue by kakacookie** [antvis/S2#1065]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |1.7.0|
| @antv/s2-react |1.6.1|

### 🖋 Description
(有两张 png + 四张gif，文件较大，请等待加载~)
#### 1. 场景：不同父节点的子节点相同
[![image.png](https://i.postimg.cc/6QfzJLNz/image.png)](https://postimg.cc/Ff100SzJ)
###### 🤔 Steps to Reproduce
当`sortParams`设置了`sortBy: ['第一市', '第二市', '第三市', '第四市']`时，操作高级排序改变顺序，只有第一父节点下的子节点重新排序。
[![pk9kt-tffue.gif](https://i.postimg.cc/8PKzwsXY/pk9kt-tffue.gif)](https://postimg.cc/D8GhwfTQ)
###### 🤔 原因
```JavaScript
// packages/s2-core/src/utils/sort-action.ts:72
export const sortByCustom = (params: SortActionParams): string[] => {
  const { sortByValues, originValues } = params;
  const sortedListWithPre = sortByValues.map(
  // ❌ 一直匹配到的是 originValues 中第一个以 item 结尾的数据项
    (item) => originValues?.find((i) => endsWith(i, item)) || item,
  );
  return getListBySorted(originValues, sortedListWithPre);
};
```
###### 🤔 Steps to Reproduce
当`sortParams`不设置`sortBy`时，选择手动排序，点击任意排序操作按钮，DOM 更新错误。
[![pw0en-qu9dp.gif](https://i.postimg.cc/xThcncGz/pw0en-qu9dp.gif)](https://postimg.cc/6yV9h6mW)
###### 🤔 原因
```JavaScript
// packages/s2-react/src/components/advanced-sort/custom-sort.tsx:73
// key 是数组 splitOrders 的元素，存在重复值
<li
  key={value}
  className={`${ADVANCED_PRE_CLS}-split-value`}
  title={value}
>
```
###### 🤔 Steps to Reproduce
当`sortParams`设置了`sortBy: ['第一市', '第二市', '第三市', '第四市', '第五市', '第六市']`时，操作手动排序改变顺序，第二父节点下的子节点未按指定顺序排序。
[![hogkq-h4ok6.gif](https://i.postimg.cc/Hkxk18kQ/hogkq-h4ok6.gif)](https://postimg.cc/Cz3gj1D1)
###### 🤔 Steps to Reproduce
当`sortParams`不设置`sortBy`时，选择手动排序，点击任意排序操作按钮，DOM 更新错误。
[![bmtxc-me3pc.gif](https://i.postimg.cc/B6svyYLv/bmtxc-me3pc.gif)](https://postimg.cc/wtfHRkkK)
### 🔗 Reproduce Link
https://codesandbox.io/s/compassionate-leftpad-c6bdl?file=/src/config.json

**Comment by lijinke666** [comment]
🐂 🍺
