### ISSUE TITLE
🙏平铺模式展示时，如果只有一个分类，小计会消失

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#1078]
### 🖋 Description
![image](https://user-images.githubusercontent.com/33095737/153532141-07a841ef-f72a-4aa6-a641-44101cd9914c.png)
配置如下
totals: {
        row: {
          showGrandTotals: false,
          showSubTotals: true,
          reverseLayout: true,
          reverseSubLayout: true,
          subTotalsDimensions: ['DATE'],
        },
 },
当日期作为小计时，如果日期下面只有一个分类时，小计就不会展示，但是这个分析还有子分类，希望展示小计

### 🏞 What problem does this feature solve
建议可以确定一下是不是末尾的分类，如果末尾的分析只有一项时可以取消小计，如果不是末尾的分类，只有一项时也建议展示小计

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
> 先说图中的问题，表现确实是符合预期的，当：
> 
> * row1：时间 time
> * row2：类型 type
> * row3：子类型 sub_type
> 
> 如果已知 row2 维度只有 1 个取值，倒是可以配置一个 row2 的小计，满足你目前的看数诉求 🤔
> 
> 但是主要如果 row1、row2 都只有 1 个且要展示小计，其实就会多很多空白区域出来。 <img alt="CleanShot 2022-02-11 at 16 25 18@2x" width="799" src="https://user-images.githubusercontent.com/6716092/153559217-6154157b-c9e3-49ee-ad73-a0cc799e6819.png">
> 
> 我们内部讨论一下

但是至少能展示，多空白只是样式问题，看不到小计是可用性问题，我们不应该限制

**Comment by lcx-seima** [comment]
目前小计使用 `options.total.[row|col]` 来配置：
```
{
  "showSubTotals": boolean;
  "subTotalsDimensions": string[];
}
```
为实现上述始终展示小计项的配置需求，且不改变用户原有配置的表现，我觉得可以将小计配置项扩展为：
```
type SubTotalsShowMode = 'compact' | 'always';

{
  "showSubTotals": boolean | SubTotalsShowMode;
  "subTotalsDimensions": string[];
}
```
- false：关闭小计
- true：开启小计，默认为 'compact' 模式，即汇总的维度值小于 2 类，不展示小计（现有行为）
- SubTotalsShowMode：开启小计，'compact' 略，'always' 模式即始终展示小计行（本 ISSUE 期待行为）

@xingwanying 以上，你觉得如何？

**Comment by lcx-seima** [comment]
内部讨论，只要用户配置了小计，则全量展示。
