### ISSUE TITLE
🐛 useResize 高度自适应不work

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#1079]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -     1.8    |
| @antv/s2-react | -   1.8      |

### 🖋 Description

高度自适应监听的容器不正确

**Comment by YardWill** [comment]
adaptive为false的情况下，setOptions 宽和高，无法修改canvas容器大小。

**Comment by stone-lyl** [comment]
使用 1.9 版本 s2 和 s2-react 无法复现此问题
