### ISSUE TITLE
🤔 角头/行头/列头/单元格 之间的textAlign是会有冲突的么

### ISSUE THREAD

**Issue by gx371368714** [antvis/S2#1084]
### 🖋 Description
 比如设置了单元格的textAlign是left, 列头的textAlign是right, 此时只有列表头的最后一行是跟随单元格的设置, 并且列表头的textAlign不生效,  角头的设置也是如此,   想要的效果就是这几个的textAlign可以单独设置.

**Comment by wjgogogo** [comment]
@gx371368714 你是怎么设置的对齐方式呢？能否贴一下实例代码

**Comment by gx371368714** [comment]
@wjgogogo 
![image](https://user-images.githubusercontent.com/23494148/154193183-301b23ec-8a94-4301-8a19-904dda2ca4d3.png)
最终我传入的配置是这样的.  发现列表头最后一行的左右对齐方式是跟随单元格的设置的

**Comment by wjgogogo** [comment]
1. 因为列头有一个滑动居中的特性，所以通常情况下列头的对齐时不生效的，除非重写ColCell
2. 列头最后一个级保持和单元格的设置是为了整体阅读的统一，这是特性，不是bug

**Comment by xingwanying** [comment]
结论，开放全部角头的textAlign

**Comment by wjgogogo** [comment]
@gx371368714 自定义对齐文档参见：https://s2-preview-pr-1128.surge.sh/zh/docs/manual/advanced/custom/cell-align
