### ISSUE TITLE
🐛 图表中不应该出现总计，因为没有配置

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#1100]
承接：https://github.com/antvis/S2/issues/1078

修复后出现的bug
配置的还是只展示日期的小计，目前状态是出现总计，但是由于没有给总计的数据，所以全部为0，如下图

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/33095737/154421643-09588b62-3890-4ad3-967d-08e4a60282a3.png">

| Package      | Version |
最新版本

**Comment by lcx-seima** [comment]
麻烦提供一下复现的 demo（options、dataCfg 的配置情况）

**Comment by yanhcao** [comment]
> 麻烦提供一下复现的 demo（options、dataCfg 的配置情况）

1078issue中有，平铺模式展示，小计数据是我们自行传入的，但是最上面一行出现了小计
