### ISSUE TITLE
行头空的情况下，不显示数据🐛

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#1103]
### 🏷 Version
1.9.1

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.9.1      |
| @antv/s2-react | -   1.9.1      |

### 🖋 Description
行头空的情况下，只有列头，不显示数据，

### ⌨️ Code Snapshots

![image](https://user-images.githubusercontent.com/24189636/154605158-35291120-d86c-4043-9ccb-fc10ef4d7bea.png)

**Comment by lijinke666** [comment]
没有行头不显示数据目前是预期的, 你这种情况更像是希望明细表支持多列头模式, 这个在排期中

**Comment by lijinke666** [comment]
请使用明细表多级列头模式 https://s2.antv.antgroup.com/zh/examples/layout/custom-header-group/#custom-table-col-header
