### ISSUE TITLE
🤔表格不支持复制吗？配置了enableCopy不生效，帮忙看看

### ISSUE THREAD

**Issue by daisy0123** [antvis/S2#1113]
### 🖋 Description

<img width="721" alt="image" src="https://user-images.githubusercontent.com/11910330/154952424-31d9a347-e8da-42aa-a436-abeac5e016ec.png">
配置了enableCopy不生效

### 😊 Expected Behavior
配置了enableCopy生效，可以复制
### 😅 Current Behavior
目前不生效 不支持复制表格数据

**Comment by daisy0123** [comment]
没有报错，我的预期的能够和dom那样复制数据下来，目前只能右键复制表图片，但是预期是想复制数据。

**Comment by lijinke666** [comment]
没懂你啥意思， enableCopy 对应的是 `ctrl + c` 复制数据啊， 你说的右键复制表图片是啥意思？

**Comment by daisy0123** [comment]
噢噢 现在可以了。感谢回答。
