### ISSUE TITLE
🤔vue 使用s2 如何实现排序icon 如图

### ISSUE THREAD

**Issue by daisy0123** [antvis/S2#1115]
### 🖋 Description
<img width="828" alt="image" src="https://user-images.githubusercontent.com/11910330/154962587-55a01541-9585-4dc5-a8e5-25f86a760ea0.png">
vue 使用s2 如何实现这样的排序icon。
目前实现代码：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/11910330/154962655-1a23d7ad-3a4d-4f50-9b5a-522bd72166a7.png">
目前这样使用的效果：
<img width="698" alt="image" src="https://user-images.githubusercontent.com/11910330/154962968-70dbc247-c1a3-468e-b8f7-f5adff39f55c.png">

### 😊 Expected Behavior
<img width="828" alt="image" src="https://user-images.githubusercontent.com/11910330/154962587-55a01541-9585-4dc5-a8e5-25f86a760ea0.png">
### 😅 Current Behavior
<img width="698" alt="image" src="https://user-images.githubusercontent.com/11910330/154962968-70dbc247-c1a3-468e-b8f7-f5adff39f55c.png">

**Comment by xingwanying** [comment]
https://s2.antv.vision/en/examples/custom/custom-cell#col-cell

使用自定义列头的hook，重写 drawActionIcons 方法可以实现

**Comment by daisy0123** [comment]
好的 感谢
