### ISSUE TITLE
🤔单元格能否自定义为图片 视频 音频  渲染？

### ISSUE THREAD

**Issue by daisy0123** [antvis/S2#1116]
### 🖋 Description
单元格能否自定义为图片 视频 音频 渲染？
### 😊 Expected Behavior
希望单元格能支持图片 视频 音频 渲染
### 😅 Current Behavior
目前未找到实现方法

**Comment by lcx-seima** [comment]
- 请参考自定义单元格 override DataCell 父类方法 https://s2.antv.vision/zh/examples/custom/custom-cell#data-cell
- DataCell 底层使用了 antv/g 的 group，参考：https://g.antv.vision/zh/docs/api/group 自有组合使用

**Comment by xingwanying** [comment]
s2是基于 canvas绘制的，视频音频暂时是不支持的呢

**Comment by daisy0123** [comment]
请问这个之后有打算支持吗？

**Comment by lijinke666** [comment]
没有打算支持, 并且也无法支持, 如果有单元格内渲染音/视频的场景, 请使用其他使用 dom 绘制的表格

**Comment by daisy0123** [comment]
好的
