### ISSUE TITLE
🙏  s2 react 组件 ctrl+c copy 成功之后有 message 反馈

### ISSUE THREAD

**Issue by BBSQQ** [antvis/S2#1119]
### 🖋 Description
ctrl+c copy 成功之后有 message 反馈
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
可以通过监听copy事件，react中监听原生事件参考

``` ts
 useEffect(() => {
    s2Ref.current.on(S2Event.GLOBAL_COPIED, (data) => {
      message.success('复制成功');
    });
    return () => s2Ref.current.off(S2Event.GLOBAL_COPIED);
  }, []);
```

或者react组件直接使用 `onCopied ` 事件回调
