### ISSUE TITLE
🙏 s2-react adaptive 为 true 时无须设置宽高

### ISSUE THREAD

**Issue by pddpd** [antvis/S2#1122]
### 🖋 Description
设置了 width 和 height 之后，s2-react adaptive 在数据更新时无法及时自适应（@antv/s2-react @1.9.0）。表现为，表格初始化时，是 adaptive 的，但是数据更新后，会优先使用 width 作为表格宽度，需要操作一下表格才会 adaptive。理论上，设置了 `adaptive: true` 就不再需要设置宽高了吧。

总结下：
🐛 `adaptive: true` 时，手动设置的宽高应该无效
🙏 `adaptive: true` 时，宽高非必选

### 🏞 What problem does this feature solve
![Feb-22-2022 17-35-12](https://user-images.githubusercontent.com/15177000/155104254-3d79ac9f-c38f-417e-871c-fe76e2c9c4b0.gif)
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by stone-lyl** [comment]
设置 getContainer 后，可监听外部高度，[可参考](https://s2.antv.vision/zh/docs/manual/advanced/adaptive#react-%E7%BB%84%E4%BB%B6)
```js
import { SheetComponent } from '@antv/s2-react';

const adaptiveRef = React.useRef<HTMLDivElement>();
const containerId = 'containerId';

<div
  id={containerId}
  style={{
    width: 600,
    height: 400,
  }}
  ref={ adaptiveRef }
>
  <SheetComponent
    adaptive={{
      width: true,
      height: false,
      getContainer: () => adaptiveRef.current // 或者使用 document.getElementById(containerId)
    }}
  />
</div>
```

**Comment by stone-lyl** [comment]
数据修改后表格自适应失效

**Comment by stone-lyl** [comment]
这个 [demo ](https://stackblitz.com/edit/react-ts-1eub6j?file=index.tsx ) 应该是满足你说的条件，但未复现 GIF 中的效果

**Comment by pddpd** [comment]
> 这个 [demo ](https://stackblitz.com/edit/react-ts-1eub6j?file=index.tsx) 应该是满足你说的条件，但未复现 GIF 中的效果

复现出来了（[demo fork](https://stackblitz.com/edit/react-ts-azmwnh)）。如果 `options` 每次传入的是新的对象而不是已有的对象，就会出现 gif 里的问题。

![image](https://user-images.githubusercontent.com/15177000/156138910-844b0df1-f1f6-4681-a0b5-218dc282654b.png)

**Comment by stone-lyl** [comment]
你好，因为 options 中 宽高的改变是会对表格展示宽高产生影响的。当 adaptive = true 时，会监听表格内的容器。

  对于这类情况，建议您将 adaptive 进行以下设置。 [点击查看demo](https://stackblitz.com/edit/react-ts-h3gqrl?file=index.tsx )
```js
  adaptive={{
              width: true,
              height: true,
              getContainer: () => sheetContainerRef.current,
            }}
```
