### ISSUE TITLE
✨ s2-vue 建设计划

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#1124]
坑位地址
https://github.com/antvis/S2/tree/s2-vue/packages/s2-vue

TODO：

- [x] 工程化
- [ ] 单测
- [ ] 表组件
   - [x] 透视表
   - [x] 明细表
- [ ] 分析组件
   - [x] Tooltip 
   - [x] 分页
   - [ ] 导出
   - [ ] 表头
   - [ ] 高级排序
   - [ ] 下钻
   - [ ] 行列维度切换
- [ ] 官网

> 在原文档基础上增加 react 和 vue 版分类，vue版暂无的写建设中，敬请期待

* 教程
	- [ ] quick start
	* 进阶教程
		- [ ] 获取表格实例
		- [ ] 表格自适应
* API
  * 组件
  	- [ ] 表组件
  	- [ ] 分页  

- [ ] 一级tab 增加 Vue3.0 示例  

* 基础教程
	* 分析组件
		- [ ] Vue3.0 示例  （Demo codesandbox）一篇 md，iframe 嵌入
			* 透视表
			* 明细表
			* Tooltip 1个
			* pagination

**Comment by xingwanying** [comment]
整体架构分层，目录结构可参考 [s2-react](https://github.com/antvis/S2/tree/master/packages/s2-react)

**Comment by lijinke666** [comment]
done. https://github.com/antvis/S2/releases/tag/%40antv%2Fs2-vue-v1.0.0
