### ISSUE TITLE
🙏 支持分组视图

### ISSUE THREAD

**Issue by linjc** [antvis/S2#1138]
### 🖋 Description
如下图，支持多组显示，共用一个表头
### 🏞 What problem does this feature solve
![20220225110754](https://user-images.githubusercontent.com/23377681/155646730-6ebf34bb-5fa1-4f71-8438-35d2c2580e00.jpg)
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
这个看起来跟树状布局的区别主要是增加了组别间的分割色块？但就这个表来说，目前的 s2 来实现是比较吃力的，更适合用 antd table 来绘制

**Comment by yanghuanrong** [comment]
目前的s2 是否可以支持这样的界面效果了呢
