### ISSUE TITLE
🐛树形结构有二级树有汇总时，第一次渲染数据正确，折叠再展开后，二级汇总数据错误

### ISSUE THREAD

**Issue by jfok1972** [antvis/S2#1153]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -         |
| @antv/s2-react | -         |

### 🔗 Reproduce Link
https://s2.antv.vision/zh/examples/analysis/totals#calculate

在options中加入 hierarchyType: "tree", 
    const s2Options = {
      width: 600,
      height: 480,
      hierarchyType: "tree", // 加入这一条
      // 配置小计总计显示
      totals: {...}
树形结构折叠后再展开， 市的小计数变成了省的小计数

折叠之前 杭州总计是3，折叠后展开，总计变成了省总计 26

**Comment by doucheng** [comment]
我同样遇到这样的问题

**Comment by doucheng** [comment]
NB 感谢~
