### ISSUE TITLE
🙏 页面设置 transform scale 缩放后，鼠标光标错位

### ISSUE THREAD

**Issue by geekFeier** [antvis/S2#1155]
### 谢谢了！！

**Comment by lijinke666** [comment]
请查看 [这篇文章](https://s2.antv.vision/zh/docs/manual/faq#%E7%88%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E4%BD%BF%E7%94%A8%E4%BA%86-code-classlanguage-texttransform-scalecode-%E5%90%8E%E5%9B%BE%E8%A1%A8%E9%BC%A0%E6%A0%87%E5%9D%90%E6%A0%87%E5%93%8D%E5%BA%94%E4%B8%8D%E6%AD%A3%E7%A1%AE)
