### ISSUE TITLE
🐛明细表，排序问题不正确，且不应该为分组排序

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#1156]
[[### 🏷 Version
明细表，排序问题不正确，且不应该为分组排序

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -         |
| @antv/s2-react | -         |

### 🖋 Description
明细表在点击排序的情况下，还是组内排序

### 🔗 Reproduce Link
https://antv-s2.gitee.io/zh/examples/react-component/sheet#table
### 😊 Expected Behavior
![image](https://user-images.githubusercontent.com/24189636/158097571-7d83a1e7-70b7-40b1-a3b1-9c87d2614cdd.png)
明细表升序的情况下
![image](https://user-images.githubusercontent.com/24189636/158097628-a684c1dc-8b1f-44a4-af3a-fc286c73773e.png)
还是组内排序
### 💻 System information

](https://antv-s2.gitee.io/zh/examples/react-component/sheet#table)](https://antv-s2.gitee.io/zh/examples/react-component/sheet#table)

**Comment by zxc0328** [comment]
官网例子的数据问题，已修复
