### ISSUE TITLE
🐛小计、总计文档有误

### ISSUE THREAD

**Issue by XiaJunjie2020** [antvis/S2#1158]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | v1.11.0      |
| @antv/s2-react | -         |

### 🖋 Description

[小计总计 | S2 文档](https://antv-s2.gitee.io/zh/docs/manual/basic/totals#1-%E9%85%8D%E7%BD%AE%E8%81%9A%E5%90%88%E6%96%B9%E5%BC%8F)

上述文档中，配置聚合方式 代码如下：calcTotals 与 row、col 在同一级

![image](https://user-images.githubusercontent.com/59437931/157361516-7a46659b-7ad6-457e-8ca7-8cc307c806ff.png)

### 🔗 Reproduce Link

使用一个没有传入 小计、总计 数据的示例

 [主题 | S2](https://antv-s2.gitee.io/zh/examples/theme/default#default)

### 🤔 Steps to Reproduce

在 s2Options 中加入如下正确配置

```
// 配置小计总计显示
      totals: {
        row: {
          showGrandTotals: true,
          showSubTotals: true,
          reverseLayout: false,
          reverseSubLayout: false,
          subTotalsDimensions: ['province'],
          calcTotals: {
            aggregation: 'SUM'
          },
          calcSubTotals: {
            aggregation: 'SUM'
          }
        },
        col: {
          showGrandTotals: true,
          showSubTotals: true,
          reverseLayout: false,
          reverseSubLayout: false,
          subTotalsDimensions: ['type'],
          calcTotals: {
            aggregation: 'SUM'
          },
          calcSubTotals: {
            aggregation: 'SUM'
          }
        },
      }
```

### 😊 Expected Behavior

实际上，calcTotals 应是 row、col 的字段

**Comment by stone-lyl** [comment]
感谢你的反馈，也欢迎参与到 S2 的贡献中。[贡献指南](https://s2.antv.vision/zh/docs/manual/contribution)
