### ISSUE TITLE
🐛 options 更改后宽高不生效

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#1159]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | - 1.11.0      |
| @antv/s2-react | -  1.11.0       |

### 🖋 Description
当初始宽度较小，更新为更大的宽度，内容宽度不生效

Demo https://stackblitz.com/edit/react-ts-eymcdd?file=index.tsx

**Comment by pddpd** [comment]
从更大宽度更新为更小宽度，也会有相同的问题。（交换 demo 里两个 options 可以复现）
![image](https://user-images.githubusercontent.com/15177000/157364505-138e29c1-d2c2-42f3-a0aa-13abef5860a8.png)

**Comment by stone-lyl** [comment]
Duplicate of #1122
