### ISSUE TITLE
🐛  Safari has problem rendering component

### ISSUE THREAD

**Issue by superfive666** [antvis/S2#1164]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -  1.10.0    |
| @antv/s2-react | - 1.11.0  |

### 🖋 Description
Safari is unable to render the `canvas`.

### ⌨️ Code Snapshots
![image](https://user-images.githubusercontent.com/7760702/157638912-44fb8924-027c-4448-bedf-85cab1a5684d.png)
![image](https://user-images.githubusercontent.com/7760702/157639020-a368de08-0b44-4077-a90d-2b8d0d0760d0.png)

### 🤔 Steps to Reproduce
Open the demo page using Safari:
https://s2.antv.vision/en/examples/case/proportion#group-drill-down

### 😅 Current Behavior
Unable to see the `SheetComponent` `canvas`

### 💻 System information
Safari

**Comment by superfive666** [comment]
![image](https://user-images.githubusercontent.com/7760702/157640494-764c6312-0c7a-49d9-9642-44b03d90b0d6.png)

**Comment by superfive666** [comment]
有人吗？哈哈

**Comment by lijinke666** [comment]
我们尽快处理下，感谢你的反馈

**Comment by superfive666** [comment]
您好，其实问题还是没有修复。
`adaptive` 参数会导致表格无法呈现。
请参考如下截图：
![image](https://user-images.githubusercontent.com/7760702/158725650-c545215a-2274-405a-88bd-c0f40b077023.png)

**Comment by superfive666** [comment]
您好，还请麻烦尽快帮忙看看。感谢。🙏 @lijinke666

**Comment by superfive666** [comment]
Checked is working now. Thanks much~

**Comment by lijinke666** [comment]
Ok, six six six
