### ISSUE TITLE
包依赖问题

### ISSUE THREAD

**Issue by xuanxiaoxiao** [antvis/S2#1165]
问题场景：
Package|Version
--|:--:
@antv/s2|1.11.0
@antv/s2-react|1.11.0

当我使用s2-react时，最终打包结果比使用s2的时候大很多
目前对项目的影响：使用了s2-react导致了JavaScript内存溢出，排查出的问题是因为项目本身含的模块较多，在引入了s2-react之后相当于加了最后一根稻草。问题已经用其他方式处理过了，但是我有点不能理解为什么s2-react项目会有这么多的依赖。
这也算是一个风险，不知道这个问题是否有办法解决

---
使用s2的代码
![使用s2代码](https://user-images.githubusercontent.com/57079772/157639393-4eb61e97-9e37-4ce6-90e5-7babcc62f276.jpg)

使用s2时build的结果
![image](https://user-images.githubusercontent.com/57079772/157639450-8da0718c-1f4f-46b0-b500-ddf0baeaa2ff.png)

---
使用s2-react的代码
![使用s2-react代码](https://user-images.githubusercontent.com/57079772/157639525-071e7b60-f1c4-4611-a6d9-8bddf7f23ca8.jpg)

使用s2-react时build的结果
![image](https://user-images.githubusercontent.com/57079772/157639584-7c5d05be-d264-4406-a0e1-9e3b5db2bf2b.png)

**Comment by lijinke666** [comment]
`s2-react` 依赖如下, 构建产物肯定是比 `s2-core` 大的
![image](https://user-images.githubusercontent.com/21015895/158965740-c1cf5645-c511-4ea1-beb0-ef300d697316.png)

> 为什么s2-react项目会有这么多的依赖

对 "多" 的定义是什么? 这些都是一些常规的依赖包吧? 有风险的意思是? `s2-react` 定位是开箱即用, 会有很多配套的分析组件, 如果你不需要, 完全可以使用 `s2` 开发, 另外我们提供 `esm` 的打包文件, 支持按需引入
