### ISSUE TITLE
🐛透视表中除了 dataCell，其他行头列头的formatter 都无法使用

### ISSUE THREAD

**Issue by stone-lyl** [antvis/S2#1187]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -         |
| @antv/s2-react | -         |

### 🖋 Description
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/20497176/158608606-1059207e-e67d-45a6-98b0-05eeeb1a6030.png">

**Comment by lijinke666** [comment]
这个pr https://github.com/antvis/S2/pull/1120 删掉了, 感觉需要回滚

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/1219
