### ISSUE TITLE
🐛 S2  react 图表宽高不能动态修改

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/S2#1193]
**描述：在 react 图表中，当 动态传入 宽高 给 图表时，宽高不发生改变**

![image](https://user-images.githubusercontent.com/26690191/158922192-5f0644c3-8ef2-4278-804d-d1407f79b51d.png)
![image](https://user-images.githubusercontent.com/26690191/158922203-bd97de2f-098d-4945-a257-f86117de7f27.png)

**复现：**
https://stackblitz.com/edit/react-da6yvk?file=src%2Fcom.jsx

版本：@antv/s2  1.12.2

**Comment by lijinke666** [comment]
ref #1159
