### ISSUE TITLE
🐛  基础透视表设置 “自定义 tooltip 挂载容器”  getContainer 后，容器样式 设置了 absolute 定位，导致 提示框错位

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/S2#1206]
描述：前提是 容器设置了 绝对定位，再设置 自定义 tooltip 挂载容器后，提示框错位

![image](https://user-images.githubusercontent.com/26690191/159654170-a3113ad4-3d55-445c-9bd9-7581dca8c835.png)

@antv/s2 版本：1.12.0

**Comment by xingwanying** [comment]
把 transform 去掉应该不会存在这个问题了吧？

**Comment by rabbit-tian** [comment]
你好，我们这边研究过了，产品层的架构实在不太好改，希望 S2 这边能解决下这个问题呢

**Comment by rabbit-tian** [comment]
复现地址：https://codesandbox.io/s/twilight-sun-1n8u1e?file=/index.html
提示框的位置在屏幕外了，可以在控制台看提示框位置

**Comment by yeesunday** [comment]
> 复现地址：https://codesandbox.io/s/twilight-sun-1n8u1e?file=/index.html 提示框的位置在屏幕外了，可以在控制台看提示框位置

@xingwanying @qubaomingg 你好，如上面复现地址，貌似该问题在最新版还是有错位
