### ISSUE TITLE
🐛  容器设置了 绝对定位，框选背景错位

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/S2#1209]
描述：前提是 容器设置了 绝对定位，框选背景错位

![image](https://user-images.githubusercontent.com/26690191/159870564-be8f73a5-ccc5-4530-a26c-98d9300d1bc4.png)

@antv/s2 版本：1.12.0

**Comment by xingwanying** [comment]
应该不是容器设置了 absolute 的原因，看下是不是设置了 transform 属性

**Comment by rabbit-tian** [comment]
复现地址：https://codesandbox.io/s/twilight-sun-1n8u1e?file=/index.html
提示框的位置在屏幕外了，可以在控制台看提示框位置
