### ISSUE TITLE
🤔透视表-行头和数据滚动条怎么设置成一个

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/S2#1221]
### 🖋 Description
"@antv/s2": "^1.12.1"

设置rows为[]，图表不显示数据，而设置rows有值后行头和数据就会分裂

![企业微信截图_16486282775379](https://user-images.githubusercontent.com/50241817/160786994-7729de27-afab-47c4-9b4f-317f788fcd8c.png)

### 😊 Expected Behavior
需求：只要一个横向滚动条

**Comment by lijinke666** [comment]
透视表默认冻结行头, 可手动关闭 https://s2.antv.vision/zh/docs/api/general/S2Options

```ts
const s2Options = {
  frozenRowHeader: false
}
```
