### ISSUE TITLE
🐛自定义树衍生指标绘制问题

### ISSUE THREAD

**Issue by wujincun** [antvis/S2#1230]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |  1.13.1         |
| @antv/s2-react |  1.12.1     |

### 🖋 Description
自定义树的模式下（hierarchyType: 'customTree'），没有数据的单元格中(没有key值和数据的行里)的衍生指标值，会被当前列的最后一行的数据占位（空单元格在renderDeriveValue方法中data收到的值就是当前列的最后一项数据）
![image](https://user-images.githubusercontent.com/17509674/161197863-f158a304-9551-4dca-bc4f-f9576b8ea14c.png)

### ⌨️ Code Snapshots

s2DataConfig
![image](https://user-images.githubusercontent.com/17509674/161198278-a54608cd-5be0-4534-a101-9a396aa5d17f.png)
s2Options
![image](https://user-images.githubusercontent.com/17509674/161198391-57fc939f-d5f1-40cf-a103-88f7288ed771.png)

### 😊 Expected Behavior
没有数据就不显示
### 😅 Current Behavior
没有数据的单元格中(没有key值和数据的行里)的衍生指标值，会被当前列的最后一行的数据占位
### 💻 System information

chrome: v99.0, mac

**Comment by xingwanying** [comment]
请问这边用到的 renderDeriveValue 方法是参考官网 KPI 趋势分析表的方法么？可以贴下具体方法看下么？

**Comment by wujincun** [comment]
renderDeriveValue 参考的官网KPI趋势分析表的方法，项目中已经通过补全key值和空值进行解决
<img width="885" alt="image" src="https://user-images.githubusercontent.com/17509674/165289625-c3de0db0-0707-43e5-bf9e-5b2997ea44e7.png">

**Comment by wujincun** [comment]
@xingwanying 谢谢你,采用新的demo文档衍生指标绘制正常，性能也提升了

**Comment by xingwanying** [comment]
单独的环比靠右是没有支持的，目前只支持整体靠左或者靠右，可以参考自定义单元格的方式实现
demo：https://s2.antv.vision/zh/examples/custom/custom-cell#data-cell
具体趋势分析表中的绘制方法可以参考源码：https://github.com/antvis/S2/blob/ef907db2e870638115e5b905ccf6963de4c4ddd1/packages/s2-core/src/utils/text.ts#L325

进度条方式在开发中，可以期待下

**Comment by wujincun** [comment]
@xingwanying 好的，谢谢你，趋势分析表的demo中我看到originalValueField的使用，但是没有看到相应的说明，请问下这个字段的使用场景是？

**Comment by lijinke666** [comment]
@wujincun  `originalValueField` 用于点击数值后出现的tooltip中, 显示原始值, 场景是可能单元格中显示的是格式化后的值, 需要在 tooltip 额外显示一个格式化前的值  
![image](https://user-images.githubusercontent.com/21015895/165431307-71090c80-c5cd-4a96-8472-5b665095973b.png)

**Comment by wujincun** [comment]
@lijinke666 好的，谢谢啊

**Comment by xingwanying** [comment]
https://github.com/antvis/S2/blob/ef907db2e870638115e5b905ccf6963de4c4ddd1/packages/s2-core/src/utils/text.ts#L325 详情见这篇文档
