### ISSUE TITLE
目前对customSvg的fill支持不太友好. 希望可以支持一下🙏

### ISSUE THREAD

**Issue by gx371368714** [antvis/S2#1232]
![image](https://user-images.githubusercontent.com/23494148/161224762-79c6dc0d-0ab4-4e03-a474-881524ae59c4.png)

**Comment by lijinke666** [comment]
没看懂你的问题是什么?

**Comment by xingwanying** [comment]
目前 s2 对 svg 的文件解析的确没有做的很好，但要去支持各种情况的 svg 文件 roi 较低， 暂时没有计划去做。这边给到的建议是提供的 svg 尽量标准化，都用 path 路径绘制，（最好无分组……）能保证解析成功
