### ISSUE TITLE
🐛透视表 「树状结构」下，打开「高级排序」，省份排序失效

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/S2#1235]
透视表 「树状结构」下，打开「高级排序」，省份排序失效

![image](https://user-images.githubusercontent.com/26690191/161363456-996871d0-05eb-4ab4-837c-537f8387fda7.png)

@antv/s2 版本：1.13.1
@antv/s2-react 版本：1.12.1

**Comment by XiChaoMing** [comment]
同样问题+1
