### ISSUE TITLE
表头的文字超出后不显示...(兼容icon)

### ISSUE THREAD

**Issue by gx371368714** [antvis/S2#1236]
![image](https://user-images.githubusercontent.com/23494148/161364677-542e8056-856e-4add-8b09-9ff7f24180e0.png)
 希望和单元格一样, 同时要兼容icon,  就是文字部分是...  要留足够的位置正常显示icon

**Comment by lcx-seima** [comment]
<img width="380" alt="CleanShot 2022-04-28 at 17 30 01@2x" src="https://user-images.githubusercontent.com/6716092/165722839-e922a28b-5bc3-46c4-af8e-d03657583cd6.png">

未复现，请尝试升级新版或提供复现 demo。
