### ISSUE TITLE
optoins.style的layoutWithType从compact变到adaptive后, 表格显示不正确

### ISSUE THREAD

**Issue by gx371368714** [antvis/S2#1237]
![2022-04-02 14 39 48](https://user-images.githubusercontent.com/23494148/161370605-92195a16-05a1-4a6e-b252-9712a9afa1dd.gif)
左侧表头宽度为自动时, 使用adaptive, 固定宽度时, 使用compact,   
从自动变为固定值, 表格显示正确, 
从固定值变为自动, 表格显示错误

**Comment by lijinke666** [comment]
使用的什么版本? 按照 issue 模板来填写应该不难吧

**Comment by lijinke666** [comment]
未能复现, 请尝试使用最新版本, 或提供可复现 codesandbox demo

![Kapture 2022-04-06 at 10 08 41](https://user-images.githubusercontent.com/21015895/161881715-eadab85f-b00f-4304-8a05-656c047e33ad.gif)
