### ISSUE TITLE
🐛使用Safari浏览器基本打不开你们的官网，卡在loading界面

### ISSUE THREAD

**Issue by ZmSama** [antvis/S2#1241]
### 🖋 Description
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/45474353/162109314-9dfc0619-f8b6-44c4-9ca6-3040d6f99782.png">

### 结果
刷新多次都是出现上图的报错、谷歌浏览器没问题，如果你们有空可以看看这个小问题

### 💻 System information
M1 芯片的Mac

**Comment by lijinke666** [comment]
ref #1164
