### ISSUE TITLE
🐛 明细表中meta给了format后，列头名称也被format了

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#1255]
### 🏷 Version
v1.14.0
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/33095737/163344779-be3d8afb-3145-495c-bde3-9115823fe52d.png">

效果：列头不能被format，只有value被format，应该是最近版本修改出现的问题

**Comment by lijinke666** [comment]
这个pr https://github.com/antvis/S2/pull/1249 已经修复了, 请留意近期发布
