### ISSUE TITLE
🐛行列切换后，数据没了。官网例子。

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#1264]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.14.0         |
| @antv/s2-react | 1.13.0        |

### 🔗 Reproduce Link

访问：

https://s2.antv.vision/zh/examples/react-component/header#default

把【城市】从行头拖到列头，点击确定。然后数据就消失了

**Comment by kilik52** [comment]
我感觉这个bug并没有被修复。 不知道你们官网更新了没有，官网依然能重现。并且我自己拉下来@antv/s2-react-v1.14.0和@antv/s2-v1.15.0，本地也能重现。我详细说明下重现步骤和我认为的问题所在。

第一步：访问官网地址：https://s2.antv.vision/zh/examples/react-component/header#default
第二步：点开【行列切换】按钮。把行头的所有字段拖入列头。如下图所示：


<img width="850" alt="截屏2022-04-23 上午10 12 21" src="https://user-images.githubusercontent.com/37238/164865390-20650bed-ee12-41b1-8dfe-f9f5861469c1.png">

第三步：点击确认，你可以看到数据没了，如下图所示：

<img width="753" alt="截屏2022-04-23 上午10 14 02" src="https://user-images.githubusercontent.com/37238/164865508-2553c066-b3ba-412b-9444-b08d7299886b.png">

## 我认为的问题所在

我认为原因出在`dataCfg.fields.valueInCols`这个配置项上。当rows/columns某一边为空的时候，valueInCols并没有自动调整。

## 我认为的解决方案

当rows/columns某一边为空的时候，valueInCols要自动做调整，不能按照配置来。其余情况按照配置项来。

## 目前的解决方案

我目前可以用<Switcher>组件来让fields变成可控状态。在每次fields被改变时修改对应的`dataCfg.fields.valueInCols`配置项。但这么做的话，header里面的`switcherCfg: { open: true }`配置项就是个摆设了。

**Comment by wjgogogo** [comment]
@kilik52 你说的这个问题不算是bug了，算是一个新 feature。
我们设计的切换组件本来目的就是单纯为了快速的进行行列切换，即单纯更改rows和columns的值，当某一个维度确实没有值时，就不应该显示数据，比如我们只是在dataCfg里面如此设置也是同样效果。在你的场景里面，可以需要即使某一维度(rows/columns)为空，依旧显示数据。当在其他用户场景里，没有数据反而符合他们的认知。

我们后续可以增加一个类似`autoAdjustValueInCols`这样的配置，当打开时，就按你上述的场景来处理，否则就和目前保持一致

**Comment by kilik52** [comment]
@wjgogogo 如果从这个角度上看这个问题的话。那我觉得valueInCols也应该在行列切换的组件里面可以操控。不然的话，当rows+columns的总数就只有1个的话，你切换行列动作是无法单独通过行列切换组件完成的。valueInCols的配置也可以表达成【values行列切换】，在语境上也属于这个组件的范畴。

个人看法。
