### ISSUE TITLE
🤔请问如何框选并复制rows里面的值

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#1266]
### 🖋 Description

例如下图：

<img width="601" alt="截屏2022-04-18 上午9 45 00" src="https://user-images.githubusercontent.com/37238/163741884-2cc0eabf-97be-4fd9-9958-f65edeeaefa6.png">

如何框选sku列的前几行，并且复制到剪贴板？

**Comment by lijinke666** [comment]
1. 行列头不支持框选, 支持单/多选
2. 目前不支持单独复制行/列头, 后续有支持的计划
