### ISSUE TITLE
格式化导出，并未导出格式化之后的数据

### ISSUE THREAD

**Issue by weibalangzi** [antvis/S2#1268]
### 🖋 Description
将表头的人员id转换为真实姓名后，使用“下载格式化数据”导出文件，发现表头的人员并未展示真实姓名，而是原始数据中的人员id；
https://codesandbox.io/s/provit-vihdc6?file=/src/dataConfig.ts
### 😊 Expected Behavior
导出的文件中展示格式化之后的内容(如demo中的‘陈皮’)；
### 😅 Current Behavior
当前导出后，excel打开显示的是人员id

**Comment by stone-lyl** [comment]
可以尝试一下 s2 1.17.0 版本，现在已经支持了这个功能
