### ISSUE TITLE
🙏tooltip不延迟，默认的hoverFocus，出现的toolTip为800ms，有一定延迟，希望有配置不延迟的能力

### ISSUE THREAD

**Issue by klfzlyt** [antvis/S2#1277]
### 🖋 Description
tooltip不延迟，默认的hoverFocus，出现的toolTip为800ms，有一定延迟，希望有配置不延迟的能力
### 🏞 What problem does this feature solve
tooltip延迟出现，有顿感
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  tooltipDelay  |  number  |  800  |  toolTip出现的延迟时间(ms)  |

**Comment by lijinke666** [comment]
hoverFocus 是设计师专门设计的效果，我理解你是想要 鼠标 hover 数值单元格的时候出现 tooltip，hoverFocus 不是干这个事情的, 建议通过自定义交互来实现 https://s2.antv.vision/zh/examples/interaction/custom#row-col-hover-tooltip
