### ISSUE TITLE
🐛明细表 字段名含有`-`时 copy出来的数据为`undefind`

### ISSUE THREAD

**Issue by bigZhang131** [antvis/S2#1283]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -    1.15.0-alpha.1     |
| @antv/s2-react | -   1.14.0-alpha.1      |

### 🖋 Description
- 明细表 字段名含有`-`时copy出来的数据为`undefind`

### ⌨️ Code Snapshots
![image](https://user-images.githubusercontent.com/87478398/164437168-e61685e4-3f0b-4eba-bb0c-f21ff57e8722.png)

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/7713aa01
#### 在明细表下
  - 选中字段名含有`-`的单元格 使用ctrl+c快捷键进行复制
复制出来的数据为undefind

**Comment by YardWill** [comment]
https://github.com/antvis/S2/pull/1234
