### ISSUE TITLE
🤔如何在S2表格中绘制迷你图来显示数据趋势

### ISSUE THREAD

**Issue by zzcypc** [antvis/S2#1294]
### 🖋 Description
本人想要在S2表格中绘制迷你图来显示数据趋势，示意图如下所示：
![image](https://user-images.githubusercontent.com/18070429/164960785-0382fe70-af54-467f-bcc0-81eaec8efb43.png)

参考demo链接：https://www.highcharts.com.cn/demo/highcharts/sparkline

本人想咨询S2开发团队，今后是否有支持在单元格中绘制mini图表的打算；当前有没有可以实现这个功能的路径。
### 😊 Expected Behavior

- 能够在单元格中绘制图表
- 绘制出来的图表带有交互功能

### 😅 Current Behavior

- 当前S2不具备直接在单元格中渲染图表的功能
- 想要实现这样的功能只能通过重写DataCell来实现，具体实现步骤如下（以Echarts为例）：
  1. 在S2外部渲染Echarts图表
  2. 将图表转为image
  3. 通过DataCell的addShape方法，添加单元格背景图片
 实现效果如下图所示：
![image](https://user-images.githubusercontent.com/18070429/164963620-9ba30ac1-5d00-4d30-9488-4960ce9c0ecf.png)
尽管实现了在单元格中渲染图表，但是图表只是静态的图片，失去了交互功能。
- 另一种实现思路是在单元格点击后出现的菜单中渲染图表，但这样完全改变了交互方式

**Comment by lijinke666** [comment]
> 当前有没有可以实现这个功能的路径

目前不支持, 如果非要实现的话, 可参考这个 demo 的子弹图绘制 https://s2.antv.vision/zh/examples/case/kpi-strategy#basic , 需要你熟悉 `AntV/G` 和 Canvas 的使用, 换句话来说你需要自己绘制一个折线图

S2 底层使用 [AntV/G](https://g.antv.vision/zh/docs/guide/introduce) 来做绘制, 想要在单元格类渲染其他图表的话, 必须要使用同样使用 `AntV/G` 做绘制的图表库, 如 `G2`, `G2Plot`

> 今后是否有支持在单元格中绘制mini图表的打算

下半年计划支持万能图, 支持嵌入基础折柱饼图、条形图、子弹图, 可访问 [2022年规划](https://www.yuque.com/antv/vo4vyz/kp88il)

> 另一种实现思路是在单元格点击后出现的菜单中渲染图表，但这样完全改变了交互方式

确实, 基于现状, 目前性价比最高的做法, 是将趋势图绘制在单元格外, 建议可以在单元格内绘制一个 icon, 点击 icon, 调用 `s2.showTooltip({ content: '你的趋势图组件' })` 通过 tooltip 来显示你的迷你图, 或者参考 [这个例子](https://s2.antv.vision/zh/examples/react-component/tooltip#operation), 

![image](https://user-images.githubusercontent.com/21015895/165209695-9eff4f0d-2bee-427a-992d-bc384eff1447.png)

**Comment by liran19960215** [comment]
请问现在支持透视表插入mini图组件吗？我看了官网的例子，目前只有react版本的趋势表类型支持，vue版本的透视表支持某个单元格插入简单的折线图吗
https://s2.antv.vision/zh/examples/react-component/sheet/#strategy-mini-chart
