### ISSUE TITLE
🐛【交叉表】大数据量的表格，随着屏幕大小，或者父级自适应高度宽度，浏览器直接卡死

### ISSUE THREAD

**Issue by 407312683** [antvis/S2#1296]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/28719321/165010660-ac931144-7c73-48be-8189-224faf37157e.png">

demo链接：https://codesandbox.io/s/nameless-waterfall-ow2i5m?file=/src/components/HelloWorld.vue

**Comment by 407312683** [comment]
![image](https://user-images.githubusercontent.com/28719321/164967220-33d3e7b5-5fed-46c5-978f-4cf950b52406.png)

**Comment by wjgogogo** [comment]
@407312683 你好，通过你的demo来看：
* 你的本意是想通过debounce减少函数调用，但实际上只是在每次`listenResize`函数中新建了一个dobounce函数，并没有达到你的目的 
* 在数据量特别大时，render耗时会比较久，可能超过debounce函数的timeout，所以建议也加上`{trailing:false}`配置
修复demo参考：https://codesandbox.io/s/jiao-cha-biao-suo-fang-qia-dun-forked-vyyq33?file=/src/components/HelloWorld.vue
