### ISSUE TITLE
🤔 s2支持表格数据分组展示吗？

### ISSUE THREAD

**Issue by wangzhenggui** [antvis/S2#1298]
### 🖋 Description
请问一下，S2能做到下面这种效果吗？对数据进行一个分组处理展示
### 😊 Expected Behavior
![image](https://user-images.githubusercontent.com/26643553/164981326-6ebf2f3d-0a9a-4bf0-9379-549ca6e5408a.png)

**Comment by lijinke666** [comment]
要实现你的这种 UI 肯定是不现实的, 不过支持自定义树自定义你的分组结构 https://s2.antv.vision/zh/docs/manual/advanced/custom/category-tree

**Comment by Nuh123** [comment]
> 要实现你的这种 UI 肯定是不现实的, 不过支持自定义树自定义你的分组结构 https://s2.antv.vision/zh/docs/manual/advanced/custom/category-tree

想问下这边不现实具体是指那些方面？看有暴露一批自定义hooks，也没有这样的能力吗？刚了解这个东西还在看文档。

**Comment by Nuh123** [comment]
> 要实现你的这种 UI 肯定是不现实的, 不过支持自定义树自定义你的分组结构 https://s2.antv.vision/zh/docs/manual/advanced/custom/category-tree

想问下实现这种ui不现实具体是指那些方面？看有暴露一批自定义hook，也没有这样的能力吗？刚了解这个东西还在看文档。

**Comment by Nuh123** [comment]
看飞书和语雀都有上述风格的表格，也都是基于 canvas 来渲染的。
