### ISSUE TITLE
🐛theme.ts 及  data-cell.ts 编译时报错

### ISSUE THREAD

**Issue by gdtimes** [antvis/S2#1303]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -    1.15.0      |
| @antv/s2-react | -         |

### 🖋 Description

angular项目，import { PivotSheet  } from '@antv/s2'; ng s 编译报错：
Error: ../node_modules/@antv/s2/esm/cell/data-cell.d.ts:31:5 - error TS2416: Property 'getIconStyle' in type 'DataCell' is not assignable to the same property in base type 'BaseCell<ViewMeta>'. 
  Type '() => IconCfg | undefined' is not assignable to type '() => IconTheme'.
    Type 'IconCfg | undefined' is not assignable to type 'IconTheme'.
      Type 'undefined' is not assignable to type 'IconTheme'.

Error: ../node_modules/@antv/s2/esm/common/interface/theme.d.ts:18:9 - error TS2411: Property 'red' of type 'string | undefined' is not assignable to string index type 'string'.
Error: ../node_modules/@antv/s2/esm/common/interface/theme.d.ts:19:9 - error TS2411: Property 'green' of type 'string | undefined' is not assignable to string index type 'string'.

本地对对应d.ts文件内容做如下临时修改, 编译通过：
（1）@antv/s2/esm/common/interface/theme.d.ts
semanticColors: {
        red?: string;
        green?: string;
        [key: string]: string;
    };
--》
semanticColors: {
        red: string;
        green: string;
        [key: string]: string;
    };

（2）@antv/s2/esm/cell/data-cell.d.ts
 getIconStyle(): IconCfg | undefined;     ---》 getIconStyle(): any;

### ⌨️ Code Snapshots
@antv/s2/esm/common/interface/theme.d.ts
semanticColors: {
        red?: string;
        green?: string;
        [key: string]: string;
    };

@antv/s2/esm/cell/data-cell.d.ts
 getIconStyle(): IconCfg | undefined; 

### 😊 Expected Behavior
  修订错误，不报错
### 😅 Current Behavior
  编译不通过
### 💻 System information
vscode：
package.json: 
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@antv/s2": "^1.15.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.7",
    "@angular/cli": "~12.2.7",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "^4.3.5"
  }

**Comment by lcx-seima** [comment]
辛苦提供一个公开的 repo 我 clone 到本地看看？
