### ISSUE TITLE
🤔在 100w 大数据量场景下的疑惑

### ISSUE THREAD

**Issue by fikyair** [antvis/S2#1308]
使用 canvas 和常规使用了 虚拟滚动的 dom  来比较，canvas 的优势在哪里，为什么现在市面上关于在线表格的处理方案包括 S2 都是基于 canvas 来做的。有些疑惑，期待解答。

**Comment by lijinke666** [comment]
可以看一下这篇文章: https://www.yuque.com/antv/vo4vyz/srtq5q#TLwdn
