### ISSUE TITLE
🙏支持预设各列宽百分比而不是等宽

### ISSUE THREAD

**Issue by 1061875478** [antvis/S2#1315]
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
目前不支持百分比的方式，但是可以自己按照维度名定义宽：
参考这个例子 https://antv-s2.gitee.io/zh/examples/layout/custom#custom-width

**Comment by zeyongTsai** [comment]
@xingwanying 明细表按照这个设置列宽没有作用，不知道是不是我没有找到正确的使用方式，如果有必要的话，我可以补充一个在线示例
