### ISSUE TITLE
🐛 hover不到tooltip的bug

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#1320]
### 🏷 Version
最新

### 🖋 Description

1. 添加行头/列头/单元格tooltip功能
2. 页面加载完毕后直接点击左上角列头标题tooltip，发现出现tooltip后，鼠标hover不到tooltip不上
3. 鼠标去点击其余的单元格（如表格内部）
4. 再返回点击列头标题tooltip，发现鼠标可以hover进去tooltip了

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/33095737/167533853-1c4484ce-af68-4d55-8143-7ec57ff5e3bb.png"/>

![s2](https://user-images.githubusercontent.com/33095737/167533976-bc023245-96e3-48e5-8a73-71f98e07b868.gif)

### 🔗 Reproduce Link
复现问题的demo链接：https://riddle.alibaba-inc.com/riddles/d50d5692

```ts
import React from 'react';
import ReactDOM from 'react-dom';
import { SheetComponent } from '@antv/s2-react';
import '@antv/s2-react/dist/style.min.css';

fetch(
  'https://gw.alipayobjects.com/os/bmw-prod/2a5dbbc8-d0a7-4d02-b7c9-34f6ca63cff6.json',
)
  .then((res) => res.json())
  .then((dataCfg) => {
    const s2Options = {
      width: 600,
      height: 480,
      tooltip: {
        showTooltip: true,
        row: {
          showTooltip: false,
        },
      },
    };

   const CustomTooltip = () => <div> demo </div>;
  const onColCellClick = (value) => {
    if (!value?.viewMeta) {
      return;
    }
    const { spreadsheet, id } = value.viewMeta;
    
      const position = {
        x: value.event.clientX,
        y: value.event.clientY,
      };
      spreadsheet.tooltip.show({
        position,
        content: <CustomTooltip />,
      });
  };

    ReactDOM.render(
      <SheetComponent
        sheetType="pivot"
        adaptive={false}
        dataCfg={dataCfg}
        options={s2Options}
        onColCellClick={onColCellClick}
        onCornerCellClick={onColCellClick}
      />,
      document.getElementById('container'),
    );
  });

```

**Comment by yanhcao** [comment]
> ### 你要找的是不是 (You may look for issues):
> 1. 55% [🐛 明细表中meta给了format后，列头名称也被format了 #1255](https://github.com/antvis/S2/issues/1255)
> 2. 53% [🐛 s2更新机制上的缺陷 #1029](https://github.com/antvis/S2/issues/1029)
> 3. 50% [🐛. 树状模式列头非叶子节点点击无法高亮整列 #1306](https://github.com/antvis/S2/issues/1306)
> 4. 50% [🐛 图表中不应该出现总计，因为没有配置 #1100](https://github.com/antvis/S2/issues/1100)
> 5. 50% [🐛 下钻场景下的总计/小计展示错误 #953](https://github.com/antvis/S2/issues/953)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

不是

**Comment by lijinke666** [comment]
临时方案: 在角头点击显示 tooltip 后 添加 hover 拦截, 角头比较特殊, 没有选中状态

```tsx
import { InterceptType } from '@antv/s2'

spreadsheet.tooltip.show({
  position,
  content: <CustomTooltip />,
});

spreadsheet.interaction.addIntercepts([InterceptType.HOVER]);
```

**Comment by yanhcao** [comment]
> 

感谢，那我暂时用这个方案，后续如果需要修改的话告诉我一下哈

**Comment by lijinke666** [comment]
> > 
> 
> 感谢，那我暂时用这个方案，后续如果需要修改的话告诉我一下哈

新版本已经兼容了角头的处理，可升级体验
