### ISSUE TITLE
希望可以实现一个遮罩层下的全屏功能

### ISSUE THREAD

**Issue by IEalpha** [antvis/S2#1328]
### 🖋 Description
希望可以实现一个遮罩层下的全屏功能，使得图表能更加直观方便展示🙏
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
您好，我们计划在 react 组件层的 header 组件增加一个全屏按钮，但如果您使用的是 s2-core, 可以参考
https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API
自行在业务层实现全屏功能
