### ISSUE TITLE
如何进行列冻结操作呢🤔

### ISSUE THREAD

**Issue by xiaoxiao992** [antvis/S2#1330]

**Comment by lcx-seima** [comment]
https://s2.antv.vision/zh/docs/api/general/S2Options

- frozenRowHeader
- frozen...

**Comment by lijinke666** [comment]
1. 你的 issue 只有一个标题, 什么描述都没有, 所以没有表达 透视表的列冻结, 还是明细表的列冻结
2. 按照 issue 模板填写问题应该不难吧?
3. 使用文档/API文档/图表示例 都有列冻结的相关介绍和 demo, 文档也可以直接搜索

https://s2.antv.vision/zh/docs/manual/basic/sheet-type/table-mode#%E5%BA%8F%E5%8F%B7

https://s2.antv.vision/zh/docs/api/general/S2Options

![image](https://user-images.githubusercontent.com/21015895/168943818-3f6dc1f6-aafd-4075-a6b5-63619e5998cf.png)

所以:

文档已经写的非常清楚了, 请认真阅读文档再提问
文档已经写的非常清楚了, 请认真阅读文档再提问
文档已经写的非常清楚了, 请认真阅读文档再提问

https://s2.antv.vision/zh/examples/interaction/basic#frozen
