### ISSUE TITLE
🐛values为row模式、且totals有col的配置的时候，row的totals也会显示出来。

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#1337]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | latest        |
| @antv/s2-react | latest       |

### 🖋 Description

简单来说，就是以下配置的组合之后，row的totals会错误地显示出来。正确的行为是row的totals不显示。

### ⌨️ Code Snapshots

```js
const s2DataConfig = {
     fields: {
        columns: ['type'],
        values: ['price', 'cost'],
        valueInCols: false,
      },
}

const s2Options = {
     totals: {
        row: {
          showGrandTotals: false,
        },
        col: {
          showGrandTotals: true,
        },
     },
}
```

### SnapShot

<img width="627" alt="截屏2022-05-15 21 44 06" src="https://user-images.githubusercontent.com/37238/168476101-ea2486f7-614f-4ca6-8ada-42015bfe7321.png">

### 🔗 Reproduce Link

https://codesandbox.io/s/romantic-ellis-69bt2f?file=/index.ts

**Comment by lcx-seima** [comment]
确实有 bug，我们尽快修复
