### ISSUE TITLE
How disable show out-line text 🤔

### ISSUE THREAD

**Issue by isublimity** [antvis/S2#1342]
### 🖋 Description

When i try render data : 

```

Line1 = '123\n123\n123\n234' 
Line2 = 'AA\nBB\nCC\nDD'

```

### 😊 Expected Behavior

Hidden BB,CC,DD, ...123 row`s 

### 😅 Current Behavior

<img width="444" alt="Tabs2lines" src="https://user-images.githubusercontent.com/1861412/168686004-6efb91b4-64e3-4767-bb7e-ee1453ae3952.png">

How disable|hide new line? Only filter pre render?

**Comment by xingwanying** [comment]
If you just want to formate the display data you can try setting the param of S2DataConfig.meta.formatter. 
Here is the demo:
https://codesandbox.io/s/elated-cherry-34dhww
