### ISSUE TITLE
隐藏功能相同项会出现隐藏尖头不见了🐛

### ISSUE THREAD

**Issue by xiaoxiao992** [antvis/S2#1344]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -         |
| @antv/s2-react | -         |

**Comment by xiaoxiao992** [comment]
https://s2.antv.vision/zh/examples/case/kpi-strategy#basic
![截屏2022-05-18 下午2 29 02](https://user-images.githubusercontent.com/17865307/168972207-d770efb9-214f-4f07-9fc4-50dbbe0db212.png)
你们zi自己的例子也这样的呢，一直点击隐藏，就出现这样回不来的问题了

**Comment by xiaoxiao992** [comment]
![截屏2022-05-18 下午2 29 02](https://user-images.githubusercontent.com/17865307/168972486-33e1ff8f-b02d-48de-90a5-311d4a44cccc.png) 操作后
![截屏2022-05-18 下午2 30 41](https://user-images.githubusercontent.com/17865307/168972559-b1325c40-33a7-4ef2-b4ec-d35f76b97b2f.png)操作前

**Comment by lijinke666** [comment]
使用的什么版本?

**Comment by xiaoxiao992** [comment]
我本地  "@antv/s2": "^1.16.0",
    "@antv/s2-react": "^1.15.0", 然后你们官网是什么版本我不确定
