### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by wujincun** [antvis/S2#1355]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   ^1.17.0      |
| @antv/s2-react | -    ^1.15.1     |

### 🖋 Description
hideMeasureColumn 为true的配置，数值多列时同样生效，且只展示一列数值
<img width="829" alt="image" src="https://user-images.githubusercontent.com/17509674/169201655-3daefd86-5322-4a53-ab73-13341636631d.png">

### ⌨️ Code Snapshots
s2Options = {
    "height": 400,
    "width": 600,
    "tooltip": {
        "operation": {
            "hiddenColumns": false
        }
    },
    "style": {
        "colCfg": {
            "hideMeasureColumn": true
        }
    },
    "headerActionIcons": [],
    "hierarchyType": "tree",
    "totals": {
        "row": {
            "showSubTotals": true,
            "reverseSubLayout": false,
            "subTotalsDimensions": [
                "a7f33e01",
                "a98df03f",
                "a5671b5b"
            ],
            "calcSubTotals": {
                "aggregation": "SUM"
            }
        }
    }
}

### 😊 Expected Behavior
<img width="685" alt="image" src="https://user-images.githubusercontent.com/17509674/169202351-3cf6c7f9-dd76-41e4-b26b-c4befdef99fa.png">

### 😅 Current Behavior
<img width="698" alt="image" src="https://user-images.githubusercontent.com/17509674/169202252-de6ad270-4745-4d2e-b400-7ef8597f4e05.png">

### 💻 System information
chrome: v99.0, mac

**Comment by lijinke666** [comment]
不好意思, 这里是文档写错了, 只要配置了 `hideMeasureColumn`, 都会隐藏, 和数值个数没有关系, 如果你想只有一个才生效, 判断一下 `fields.values` 个数即可

```ts
const dataCfg = {
  fields: {
     ...
     values: ['A']
  }
}

const hideMeasureColumn = dataCfg.fields.values.length === 1

const s2Options = {
  style: {
    colCfg: {
      hideMeasureColumn,
    },
  },
}
```
