### ISSUE TITLE
🐛 Confusing textAlign behavior of "Grand total cell"

### ISSUE THREAD

**Issue by Dhalsimzhao** [antvis/S2#1357]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -  1.17.0    |
| @antv/s2-react | -         |

### 🖋 Description
S2 PivotSheet

When I set ```hideMeasureColumn``` to true or false, the grand total cell has a different ```textAlign``` behavior.
The column grand total cell uses the ```textAlign``` style of ```DataCell``` when set ```hideMeasureColumn``` to ```false```, but hard code the style when ```hideMeasureColumn``` is set to ```true```

### ⌨️ Code Snapshots
```js
/* col-cell.ts */
protected getTextStyle(): TextTheme {
  const { isLeaf } = this.meta;
  const textStyle = this.getOriginalTextStyle();
  const hideMeasureColumn =
    this.spreadsheet.options.style.colCfg.hideMeasureColumn;
  let textAlign: TextAlign;
  let textBaseline: TextBaseline;
  if (isLeaf && !hideMeasureColumn) {
    textAlign = this.theme.dataCell.text.textAlign;
    textBaseline = this.theme.dataCell.text.textBaseline;
  } else {
    // 为方便 getTextAreaRange 计算文字位置
    // textAlign 固定为 center
    textAlign = 'center';
    textBaseline = 'middle';
  }
  return { ...textStyle, textAlign, textBaseline };
}
```

### 🔗 Reproduce Link
https://codesandbox.io/s/great-andras-jj1jr7

### 🤔 Steps to Reproduce
1. Create a PivotSheet
2. Set options which made the column grand total cell display as a leaf node 
3. s2.render()

### 😊 Expected Behavior
The column grand total cell should renders with ```boldText``` style of ```ColCell```

### 😅 Current Behavior
Shown in the codesandbox link

### 💻 System information
chrome: 101.0, windows 10

**Comment by wjgogogo** [comment]
@Dhalsimzhao This feature is designed for a purpose, sheet will change col cell text position dynamically while scrolling: ![](https://gw.alipayobjects.com/zos/antfincdn/LAv2EKaGS/CleanShot%2525202022-03-03%252520at%25252018.01.33.gif)

so we make a difference between measure and non-measure cell in col header  for better reading：
* non-measure cells dynamic position 
* measure cells use data cell alignment
you can find more detail in the [alignment docs](https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-align]#%E5%88%97%E5%A4%B4%E5%AF%B9%E9%BD%90%E6%96%B9%E5%BC%8F)
> ps: we just have Chinese version docs for now, please use some translation tool 😑

**Comment by wjgogogo** [comment]
ref: #1227
