### ISSUE TITLE
🐛换行问题，文字中含有\n换行符，期待有个overflowY

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1358]
### 🏷 Version
1.15.0
| Package      | Version |
| -------------- | --------- |
"@antv/s2": "^1.15.0",
"@antv/s2-react": "^1.14.0",

### Sheet Type

- [ ] TableSheet

### 🖋 Description
含有换行符会溢出

### 😊 Expected Behavior
不超出，有个类似的overflowY。或者内部滚动条
### 😅 Current Behavior
![image](https://user-images.githubusercontent.com/15354455/169289672-391105ce-f202-449e-a054-eea3adaa8e85.png)

超出溢出，比较难看
### 💻 System information
mac os

chrome: latest

**Comment by lijinke666** [comment]
目前还做不到多行文本的支持, 规划中

**Comment by Eve-Sama** [comment]
这个需求我们这边也有需要. 嘤嘤说是明年才能有的功能, 那我就期望1月份就能上这个功能吧  :)

**Comment by poemshi** [comment]
这个问题我也有，求支持

**Comment by wozien** [comment]
mark

**Comment by lijinke666** [comment]
多行文本 2.0 版本支持 https://github.com/antvis/S2/pull/2383

**Comment by lijinke666** [comment]
resolved #2383
