### ISSUE TITLE
🐛 Pivot Sheet linkFields options of value fields not working

### ISSUE THREAD

**Issue by Dhalsimzhao** [antvis/S2#1361]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.17.0      |
| @antv/s2-react | -         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
Pivot Sheet linkFields options of value fields not working. Only TableSheet TableDataCell could work with linkFields.

### ⌨️ Code Snapshots
```ts
export class TableDataCell extends DataCell {
  protected drawTextShape() {
    super.drawTextShape();
    this.drawLinkFieldShape();
  }

  protected drawLinkFieldShape() {
    const { linkFields = [] } = this.spreadsheet.options.interaction;
    const linkTextFill = this.theme.rowCell.text.linkTextFill;

    super.drawLinkFieldShape(
      linkFields.includes(this.meta.valueField),
      linkTextFill,
    );
  }

  protected drawBorderShape() {
    super.drawBorderShape();
    if (this.meta.colIndex === 0) {
      this.drawLeftBorder();
    }
  }
}
```

### 😊 Expected Behavior
Both dimension and measure Fields could work with linkFields
### 😅 Current Behavior
Only dimension fields work.
### 💻 System information
chrome: 101.0, windows 10

**Comment by wjgogogo** [comment]
@Dhalsimzhao linkFields only used for row cell in pivot sheet, and col cell for table sheet, you can more detail in [link field docs](https://s2.antv.vision/zh/docs/manual/advanced/interaction/link-jump)
ps: we just have Chinese version docs for now, please use some translation tool 😑
