### ISSUE TITLE
🙏希望实现简单的数据编辑功能

### ISSUE THREAD

**Issue by sunweiguang** [antvis/S2#1363]
### 🏞 解决数据填报需求

**Comment by GoldSubmarine** [comment]
请问有大概的时间节点吗？比如一个月或半年 @lijinke666

**Comment by lijinke666** [comment]
预计下半年内置

你可以自行尝试下: 目前可以获取对应单元格的坐标，在单元格上添加一个绝对定位的div蒙层 ，里面渲染input, 编辑完后更新表格数据触发重新渲染，来实现一个简易编辑表格

**Comment by GoldSubmarine** [comment]
![image](https://user-images.githubusercontent.com/22909744/176135586-baa8514b-d70e-417c-83b4-321c593d0654.png)

选中一个单元格，修改数据后，进行滚动，input框超出table后没有消失

**Comment by lijinke666** [comment]
> ![image](https://user-images.githubusercontent.com/22909744/176135586-baa8514b-d70e-417c-83b4-321c593d0654.png)
> 
> 选中一个单元格，修改数据后，进行滚动，input框超出table后没有消失

好的, 我们处理下 cc @YardWill

**Comment by YardWill** [comment]
#1508

**Comment by serializedowen** [comment]
已在s2-react层支持

**Comment by hanfengcan** [comment]
> 已在s2-react层支持

请问Vue支持吗
