### ISSUE TITLE
🐛 树状模式下开行序号行头分割线绘制优化

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#1370]
### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 😅 Current Behavior

![image](https://user-images.githubusercontent.com/10885578/170409498-73cfe4d1-a5f7-459f-bbfa-aed59758a9b4.png)

### 😊 Expected Behavior
![image](https://user-images.githubusercontent.com/10885578/170409409-47d94099-34a2-486f-a8b7-0a45c5eb2ecd.png)

**Comment by wjgogogo** [comment]
ref: https://github.com/antvis/S2/pull/1966
