### ISSUE TITLE
🐛tooltip功能无效

### ISSUE THREAD

**Issue by easydatavis** [antvis/S2#1406]
// 3. 添加配置
            const options = {  
                width: 1800,
                height: 600,
                hierarchyType:'grid',    //行头的展示方式，grid：平铺网格结构， tree： 树状结构。 customTree: 自定义树状结构
                tooltip: {
                    showTooltip: true,
                    row: {
                    showTooltip: false,
                    },
                },
            };

![微信截图_20220602173111](https://user-images.githubusercontent.com/53335368/171601449-dea7bff7-d35a-4e23-aecb-e36006a9bc84.png)

**Comment by lijinke666** [comment]
https://s2.antv.vision/zh/docs/manual/basic/tooltip#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by easydatavis** [comment]
> ```
>  // 3. 添加配置
>         const options = {  
>             width: 1800,
>             height: 600,
>             hierarchyType:'grid',    //行头的展示方式，grid：平铺网格结构， tree： 树状结构。 customTree: 自定义树状结构
>             tooltip: {
>                 showTooltip: true,
>                 row: {
>                 showTooltip: false,
>                 },
>             },
>         };
> ```
> 
> ![微信截图_20220602173111](https://user-images.githubusercontent.com/53335368/171601449-dea7bff7-d35a-4e23-aecb-e36006a9bc84.png)



> https://s2.antv.vision/zh/docs/manual/basic/tooltip#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

还是没有效果

**Comment by lijinke666** [comment]
1. 你的描述没有说明你用是 React 版本, 还是 Core 版本
2. 文档已经写的很清楚了

![image](https://user-images.githubusercontent.com/21015895/171610475-92b267d3-a9bb-4fdf-be2f-5511d1111a74.png)

3. 数值单元格的提示框是点击才会出现, 而不是 [放] 上去
![image](https://user-images.githubusercontent.com/21015895/171610609-d9d1014f-1b45-42c5-b0f1-91db2a5242fb.png)

4. 请按照 Issue 的模板进行提问

**Comment by easydatavis** [comment]
> 1. 你的描述没有说明你用是 React 版本, 还是 Core 版本
> 2. 文档已经写的很清楚了
> 
> ![图片](https://user-images.githubusercontent.com/21015895/171610475-92b267d3-a9bb-4fdf-be2f-5511d1111a74.png)
> 
> 3. 数值单元格的提示框是点击才会出现, 而不是 [放] 上去
>    ![图片](https://user-images.githubusercontent.com/21015895/171610609-d9d1014f-1b45-42c5-b0f1-91db2a5242fb.png)
> 4. 请按照 Issue 的模板进行提问

（1）我使用的是Core版本，最新的版本
（2）无论是点击还是放上去都没有效果
（3）我通过F12审查元素，发现有一个空白的div在页面上，但里面没有数据，基本确定应该是一个bug
![微信截图_20220602183954](https://user-images.githubusercontent.com/53335368/171612531-24d2880a-02cd-4873-8e61-71042fae9bcf.png)

**Comment by lijinke666** [comment]
文档写的已经很清楚了吧，已经说了 core 版本不渲染tooltip ，需要使用tooltip 请用 react 版本或者自定义
