### ISSUE TITLE
🤔单元格自定义图片可以自适应吗

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#1410]
### 🖋 Description
我想在一些列表数据展示图片，比如订单列表，产品库存等显示产品的图片，现在通过自定义单元格背景图会变形
### 😊 Expected Behavior
单元格背景图可以等比例缩放，并居中显示；
### 😅 Current Behavior
目前自定义单元格背景图会拉伸图片，造成图片变形，就没有展示图片的意义了，

**Comment by lijinke666** [comment]
目前不支持, 图片等展示场景, 更推荐用普通的 DOM 表格, 如 antd

**Comment by xiaochong44** [comment]
那有点太遗憾了，我是使用这个表格进行bi工具的开发，因为S2的分析确实很强，但是bi又要求可以展示图片，如power bi 这些工具都支持，

**Comment by lijinke666** [comment]
目前主要定位为看[数]分析, 后续会考虑支持自定义 DOM 节点单元格, 和单元格内绘制迷你图等能力, 敬请期待.
