### ISSUE TITLE
🐛表格自适应BUG

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#1411]
### Sheet Type table
开启自适应后，如果祖先容器有使用scale进行缩放，那么控件监听到的是缩放后的大小，导致无法填充满父容器
其它react版本也有同样的问题

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by xiaochong44** [comment]
https://codesandbox.io/s/lucid-lovelace-jenso3
我只是在官方domo上修改了一样样式，自适应就出现了问题

**Comment by xiaochong44** [comment]
@stone-lyl 请大神们看看这个bug

**Comment by stone-lyl** [comment]
因为子元素的宽高肯定是受父元素影响的，缩放后不充满整个父级是正常的展示。
如果你希望你的子元素（表格），不受父元素影响，可以设置 adaptive = false  + 设置 options  的宽高

**Comment by xiaochong44** [comment]
> 因为子元素的宽高肯定是受父元素影响的，缩放后不充满整个父级是正常的展示。 如果你希望你的子元素（表格），不受父元素影响，可以设置 adaptive = false + 设置 options 的宽高

既然设置了自适应宽高，就应该一直等于父元素的大小的，这样才是合理的吧。如父元素是宽800，自适宽时表格也是宽800，如果整个页表缩放50%，父元素变成400了，而表格直接变成200了，而且鼠标的响应也全部错乱了，这怎么也不合理呀，如果表格和父元素一样也变成400，鼠标响应也正常了。

**Comment by stone-lyl** [comment]
> > 因为子元素的宽高肯定是受父元素影响的，缩放后不充满整个父级是正常的展示。 如果你希望你的子元素（表格），不受父元素影响，可以设置 adaptive = false + 设置 options 的宽高
> 
> 既然设置了自适应宽高，就应该一直等于父元素的大小的，这样才是合理的吧。如父元素是宽800，自适宽时表格也是宽800，如果整个页表缩放50%，父元素变成400了，而表格直接变成200了，而且鼠标的响应也全部错乱了，这怎么也不合理呀，如果表格和父元素一样也变成400，鼠标响应也正常了。

是的，应该是这样，我理解错了
