### ISSUE TITLE
🐛在明细表中，冻结列导致hover展示的边框样式有误

### ISSUE THREAD

**Issue by Christine-Only** [antvis/S2#1416]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     ^1.15.0    |
| @antv/s2-react |     ^1.14.0     |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### ⌨️ Code Snapshots

<img width="554" alt="image" src="https://user-images.githubusercontent.com/42272524/172346354-648d3a7a-0fb9-46f2-8a9f-fda3b7e398ca.png">

### 🤔 Steps to Reproduce

在明细表中，当设置frozenColCount：1时，hover到第二列的任一个单元格时，会发现hover的左侧边框丢失

### 😊 Expected Behavior

在明细表中，当设置frozenColCount：1时，hover到第二列的任一个单元格时，边框完整展示

### 😅 Current Behavior
<img width="684" alt="image" src="https://user-images.githubusercontent.com/42272524/172348578-7070a3ad-f67d-4e5c-af75-3751677d1df4.png">

**Comment by YardWill** [comment]
![image](https://user-images.githubusercontent.com/16497201/210521928-ae019eff-e9c0-4377-8f93-64d4b7a64f0c.png)
已修复
