### ISSUE TITLE
🤔 请问明细表，如何实现隐藏表头

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1420]
### 🖋 Description
![image](https://user-images.githubusercontent.com/46083022/172598943-de928095-2522-42f5-b74d-b47191ddc181.png)
如何隐藏，上图中圈出来的地方呢

### 😊 Expected Behavior
![image](https://user-images.githubusercontent.com/46083022/172599091-c8fff1a2-c9a4-452e-8df8-800af70354af.png)

**Comment by lijinke666** [comment]
暂不支持
