### ISSUE TITLE
🤔 表格排序问题

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1422]
### 🖋 Description
你好，有点问题想请教下：
1. 明细表是否可以支持配置， 选择 单/多字段排序么
2. 排序按钮是否可以排序换成下面的形式
![image](https://user-images.githubusercontent.com/46083022/172772737-50f09100-2e3d-4a55-80e7-e24c2f92087a.png)

### 😊 Expected Behavior
1. 明细表点击字段排序，点击另一个字段，前一个字段排序取消

### 😅 Current Behavior
1. 明细表点击字段排序，点击另一个字段，前一个字段排序依然村

**Comment by stone-lyl** [comment]
1. 明细表本身排序就是会被覆盖的。 我先对 A 进行了排序，再对 B 进行排序。那 A 的排序是无效的。
如果你说的是，我们官方demo 上，排序 icon 的展示问题的话，那可能是一个展示bug：
<img width="632" alt="image" src="https://user-images.githubusercontent.com/20497176/172775010-d3a11619-60c1-4004-add6-bada3d68f7de.png">

2. 这个你可以通过自定义 icon  + 自定义排序完成
文档：
headerActionIcon : https://s2.antv.vision/zh/docs/common/header-action-icon/#headeractionicon
自定义icon demo： https://s2.antv.vision/zh/examples/gallery#category-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87
自定义排序： https://s2.antv.vision/zh/docs/manual/basic/sort/custom

**Comment by xiaochong44** [comment]
@stone-lyl 请问一下s2-vue的排序点击并不会排序，这个是BUG吗？官网上的demo也不会排序，只是一个展示的tooltip

**Comment by stone-lyl** [comment]
> tooltip

应该是的😂

**Comment by feEden** [comment]
@stone-lyl 基于自定义 icon + 自定义排序，该如何实现点击后，将当前单元格的 排序按钮 换成升序按钮呢

**Comment by stone-lyl** [comment]
现在的排序功能，是没有传递出对应的 sortMethod 的。
如果你希望通过修改 icon，实现你现在的需求
![image](https://user-images.githubusercontent.com/20497176/172844606-a2cc09bb-2a45-419b-9e7d-636b4431a87d.png)
我建议的方案是：
自定义 行列头操作图标，1. 在 headerActionIcons.action 中配置自定义的tooltip 。
2.  在 tooltip.operator.onClick 中获取到配置的升级序， 
3. 再通过 传入  tooltip.operator.onClick 中的函数回调 配置自定义排序规则。
 自定义icon :  https://s2.antv.vision/zh/examples/custom/custom-icon#custom-header-action-icon
自定义排序：https://s2.antv.vision/zh/docs/manual/basic/sort/custom#2-%E7%BB%B4%E5%BA%A6%E5%80%BC%E5%88%97%E8%A1%A8sortby

**Comment by feEden** [comment]
@stone-lyl 我现在通过自定义的icon 的action. 能推断出sortMethod，也能实现排序，现在就差提换成相应的排序图标
![Uploading image.png…]()
想问下，有提供方法去替换么，在知道sortMethod的情况下

**Comment by feEden** [comment]
@stone-lyl 我现在通过自定义的icon 的action. 能推断出sortMethod，也能实现排序，现在就差提换成相应的排序图标
![Uploading image.png…]()
想问下，有提供方法去替换么，在知道sortMethod的情况下

**Comment by feEden** [comment]
通过动态控制 icon 实现了

**Comment by lijinke666** [comment]
> 通过动态控制 icon 实现了

来个 PR ? 给官网加个 Demo

**Comment by Chasen-Zhang** [comment]
@feEden  自定义icon 的位置怎么控制，比如右对齐？
