### ISSUE TITLE
🐛列缩放后出现横向滚动条，滚动条未滚动到最右侧时，列分割线不能拖动

### ISSUE THREAD

**Issue by zeyongTsai** [antvis/S2#1437]
### 🏷 1.19.0

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.19.0    |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet

### 🖋 Description

拖动角头的列宽，可能出现角头的所有列存在一个横向的滚动区域，在横向滚动条未滚动到最右侧的情况下，鼠标移动到角头和列头的分割线上并不显示“可拖动改变列宽”的光标，按下鼠标并拖动也没有任何效果。

### ⌨️ Code Snapshots

https://s2.antv.vision/zh/examples/interaction/basic#click-highlight

### 🔗 Reproduce Link

https://s2.antv.vision/zh/examples/interaction/basic#click-highlight

### 🤔 Steps to Reproduce

以上面的官方demo为例。
1.  拖动角头和列头之间的分割线到画布的中心位置，角头(实际显示在行头)和列头都会出现滚动条，滚动条默认在左侧
2.  再次尝试拖动角头和列头之间的分隔条，光标未变化，不能拖动
3.  将行头区域的滚动条拖动到最右侧
4.  重复2的行为，可拖动改变列宽

### 😊 Expected Behavior
始终能正常拖动改变角头和列头的区域占比宽度

### 😅 Current Behavior
滚动条未滚动到右侧时不能拖动改变宽度

### 💻 System information

5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33

**Comment by lijinke666** [comment]
能否贴一个 gif 呢?

**Comment by zeyongTsai** [comment]
@lijinke666 

![7575757](https://user-images.githubusercontent.com/8591261/174046896-bdcd2dba-b3a3-4bda-b5f2-c2d56ceaca64.gif)

**Comment by lijinke666** [comment]
@wjgogogo  没记错的话, 当时重构角头热区的时候, 是故意这样设计的? 行头没有滚动条, 或者滚动条在最右边才会显示角头热区, 如果不是那就是 BUG 了

![Kapture 2022-06-17 at 13 06 57](https://user-images.githubusercontent.com/21015895/174229038-0926154c-b84d-4dd7-9a79-c73b11d51a3e.gif)

**Comment by wjgogogo** [comment]
@zeyongTsai 这个是专门的设计，不是bug
