### ISSUE TITLE
🤔能否根据数据动态的设置单元格的对齐方式？

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1448]
### 🖋 Description
因为数据放回的格式不确定，所以固定的设置对齐方式不符合需求。
### 😊 Expected Behavior
能动态设置单元格的对齐方式 https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-align
### 😅 Current Behavior
现在好像不行

**Comment by Chasen-Zhang** [comment]
有的列是字符串，我希望左对齐，有些列是数字我希望右对齐

**Comment by Chasen-Zhang** [comment]
感觉还是要自定义

**Comment by lijinke666** [comment]
目前请通过自定义单元格来实现, 后面这类诉求有更多反馈时会考虑主题配置支持回调

1. 自定义单元格, 重写 `getTextStyle` 方法
2. `this.meta` 拿到单元格信息, 根据当前数据的类型动态设置 textAlign
