### ISSUE TITLE
🤔表格柱状图能否支持负数反向绘制呢？

### ISSUE THREAD

**Issue by daisy0123** [antvis/S2#1451]
这样的效果，对于这列的数据存在负数和正数的情况下，长这样
![image](https://user-images.githubusercontent.com/11910330/174213862-ab497270-4fa1-471b-9f78-37266cbca6e2.png)
对于都为正数
![image](https://user-images.githubusercontent.com/11910330/174214124-39b3e666-de1e-4773-8f74-a91a9abefa3d.png)

**Comment by wjgogogo** [comment]
duplicate with #1324
