### ISSUE TITLE
🤔接近序号那边的hover左边的border 看不到了

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1452]
### 🖋 Description
![image](https://user-images.githubusercontent.com/15354455/174267295-d69d4b58-74c7-4952-a791-9f99f33ae984.png)

🤔接近序号那边的hover左边的border 看不到了， 被序号遮住了？
### 😊 Expected Behavior
🤔接近序号那边的hover左边的border能看到
### 😅 Current Behavior
![image](https://user-images.githubusercontent.com/15354455/174267295-d69d4b58-74c7-4952-a791-9f99f33ae984.png)

**Comment by lijinke666** [comment]
反馈 bug 请选择

![image](https://user-images.githubusercontent.com/21015895/174272211-fc8c34f5-7fa5-4b06-a595-dcb7b05691a5.png)

然后根据模板填写信息, 最新版本有尝试过?

**Comment by Chasen-Zhang** [comment]
> 反馈 bug 请选择
> 
> ![image](https://user-images.githubusercontent.com/21015895/174272211-fc8c34f5-7fa5-4b06-a595-dcb7b05691a5.png)
> 
> 然后根据模板填写信息, 最新版本有尝试过?

是最新版
