### ISSUE TITLE
🤔点击单元格focus之后，再移动鼠标，hover就失效了，怎么让hover重新激活呢

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1454]
### 🖋 Description
点击单元格focus之后，再移动鼠标，hover就失效了，怎么让hover重新激活呢

https://user-images.githubusercontent.com/15354455/174273134-297e3011-a783-4b44-8eae-9fc87cb97c92.mov

### 😊 Expected Behavior
鼠标移动能重新激活hover
### 😅 Current Behavior
如视频

**Comment by xingwanying** [comment]
再点击一下，取消点击态

**Comment by lijinke666** [comment]
https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E9%87%8D%E7%BD%AE%E4%BA%A4%E4%BA%92

多看文档, 或者建议直接加答疑群吧, 这种使用问题就不要提 issue 了,

**Comment by Chasen-Zhang** [comment]
> https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E9%87%8D%E7%BD%AE%E4%BA%A4%E4%BA%92
> 
> 多看文档, 或者建议直接加答疑群吧, 这种使用问题就不要提 issue 了, 感谢!

您好，你们的文档我都有认真的看，您发给我的文档我也是有看的，但是并没有解决我的问题啊。我觉得这个是问题。请您认真的看下我的视频反馈可以么，你这个重置是在表格外点击下。
