### ISSUE TITLE
🐛style中的布局类型变化时, 无法自由切换

### ISSUE THREAD

**Issue by gx371368714** [antvis/S2#1462]
https://codesandbox.io/s/youthful-framework-e46duf?file=/app.tsx

从compact切换到adaptive时会出现这个问题

**Comment by wjgogogo** [comment]
@gx371368714 你好，由于我们底层使用的是`lodash.merge`来做属性合并，对于`lodash`来说，如果清空以前的属性，需要将新的属性设置为`null`:
![image](https://user-images.githubusercontent.com/17964556/174934770-036a6240-b61e-4dce-ab41-91307afccb03.png)
https://codesandbox.io/s/jovial-ellis-v23igt?file=/app.tsx
