### ISSUE TITLE
🐛交叉透视表小计空值时报错

### ISSUE THREAD

**Issue by alanleung04** [antvis/S2#1467]
https://github.com/antvis/S2/blob/68fec65e8bafb990015890684f4a9d2ee872a0f9/packages/s2-core/src/utils/data-set-operate.ts#L52
这段代码升级之后没有去掉了旧版本的可选链，导致在处理小计/总计的时候，碰上空值的情况就报错
![image](https://user-images.githubusercontent.com/25760708/174603195-e0d3a70d-7f01-4729-b595-3de14fad479d.png)
![image](https://user-images.githubusercontent.com/25760708/174603234-8b750f06-19b7-48a1-9116-ca0ec34bda39.png)

**Comment by lcx-seima** [comment]
感谢反馈，现在最新版本已修复。请删掉依赖重装试试。

**Comment by alanleung04** [comment]
> 感谢反馈，现在最新版本已修复。请删掉依赖重装试试。

好像没看到有更新。。。上面贴的代码是两个多小时前刚更新的，更新完之后，发版就出问题了
