### ISSUE TITLE
🐛 自定义行高，读取数组 index 溢出导致报错

### ISSUE THREAD

**Issue by iamdhj** [antvis/S2#1500]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     latest     |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

设置特定自定义行高，并且数据在特定长度的情况会导致 undefined 读取数据异常

### ⌨️ Code Snapshots

```
import { TableSheet } from '@antv/s2';

const container = document.getElementById('container');

 const s2DataConfig = {
  fields: { columns: ['city'] },
  data: [],
}
for (let i = 0; i < 10; ++i) {
  s2DataConfig.data.push({ city: `广州${i}` })
}

const s2Options = {
  width: 600,
  height: 480,
  style: {
    colCfg: { height: 30 },
    cellCfg: { height: 44.3 },
  },
}

const s2 = new TableSheet(container, s2DataConfig, s2Options)
s2.render()

```

经调试排查发现是根据容器高度获值不正确，对应源码
https://github.com/antvis/S2/blob/939e7b2ec5ebb9653120c5b488264bf56424b955/packages/s2-core/src/facet/table-facet.ts#L500-L503

 viewportHeight 扣掉表头和其它一些高度后刚好是 443，计算出来 yMax 为 10 比数据长度大

### 🔗 Reproduce Link

[问题重现地址](https://codesandbox.io/s/table-sheet-out-of-bounds-740e4k?file=/src/index.js)

### 🤔 Steps to Reproduce

1.使用简单的模拟数据，不设置 `colCfg` 和 `cellCfg` 高度，正常渲染
2.设置特定高度，表格报错读取越界，`Cannot read properties of undefined`

### 😊 Expected Behavior
正常渲染，读取值逻辑增加非空判断避免出现类似问题

### 😅 Current Behavior
自定义高度为 44.3 会出现读取错误，导致渲染异常
自定义高度设置为 44 或者 45 则不会出错
### 💻 System information

Microsoft Edge v103

**Comment by iamdhj** [comment]
已补充 [问题重现地址](https://codesandbox.io/s/table-sheet-out-of-bounds-740e4k?file=/src/index.js)

**Comment by lijinke666** [comment]
@serializedowen 看下新版是否还有该问题

**Comment by lijinke666** [comment]
1.x 和 2.x 版本都已修复
