### ISSUE TITLE
🙏 给表格配置widthByFieldValue后的一些问题

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1506]
### 🖋 Description
如下示例：
https://codesandbox.io/s/sweet-heyrovsky-1x470d?file=/src/App.tsx

1. 配置widthByFieldValue，如果父容器宽度大于表格宽度，表格并不会充满，而且宽度等于widthByFieldValue的字段之和
2. 明细表配置widthByFieldValue对象，key取的是meta的name字段，而不是field, 无法保证唯一性，这样会导致如果有相同的列名，想配置不同的宽度（比如：可视化中相同字段，配置不同的聚合方式），没办法做到

### 🏞 What problem does this feature solve
1. 希望能够实现配置了widthByFieldValue，把配置的字段宽度，当作最小值，当配置的字段宽度小于父容器的宽度的时候，自动充满

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by wjgogogo** [comment]
@feEden 感谢你的反馈。
1. `widthByFieldValue`的配置的优先级是最高的，是在s2默认的提供的宽度布局不满足用户场景时使用的，所以如果在`widthByFieldValue`存在的前提下还去进行自适应布局，实际上违反了这个配置的设计原则。也许在你的场景下，你需要补齐，但是在别的用户的场景下又需要完全以配置为准。因此对于第一点来说，还是需要的你这边来处理
2. 针对第二点，确实是配置上的不足，我们会在后续优化
