### ISSUE TITLE
🤔 关于DataCellCallback 的用法

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1507]
### 🖋 Description
想自定义明细表某一列的textAlign，表头可以通过CellCallback实现，请问数据部分能控制么？

**Comment by lijinke666** [comment]
和列头一样, 自定义 dataCell. 根据 meta 的  `colIndex` 或者 `valueField` 确定你想更改的列头对应的数据单元格, 重写 `getTextStyle`, 覆盖 `textAlign` 即可

```ts
class CustomDataCell extends DataCell {
  getTextStyle() {
    if (this.meta.valueField === 'fieldA') {
      return {
        ...super.getTextStyle(),
        textAlign: 'left',
      };
    }
    return super.getTextStyle();
  }
}
```

后面我们会在 theme 配置部分增加 hook, 方便根据单元格信息修改主题的场景
