### ISSUE TITLE
🐛冻结右侧列，无showSeriesNumber时，左侧数据被清空

### ISSUE THREAD

**Issue by Bernicechl** [antvis/S2#1513]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] TableSheet

### 🖋 Description

冻结右侧列数字设为非0，注释掉showSeriesNumber时，左侧数据被清空
### 🤔 Steps to Reproduce

https://antv-s2.gitee.io/zh/examples/interaction/basic#frozen
1.冻结右侧列数字设为非0
2.注释掉showSeriesNumber

**Comment by lijinke666** [comment]
cc @YardWill @zxc0328 , 本地能复现

**Comment by lcx-seima** [comment]
ref #1562 已修复

官网部署一次即可

**Comment by Bernicechl** [comment]
您发给我的信件已经收到。
