### ISSUE TITLE
🐛s2-vue,s2-react未配置s2DataConfig.fields.values时，不期望列出现排序按钮

### ISSUE THREAD

**Issue by hexf00** [antvis/S2#1514]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.22.0    |
| @antv/s2-react |    1.20.0      |
| @antv/s2-vue   |   1.1.0       |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

react-s2 , vue-s2上都遇到的一个问题，未配置values时候，不期望列出现排序，也与下钻功能冲突。

因为我是使用 vue-s2 ，发现就算动态增加了values，列依然出现排序按钮。

react-s2 可以在下面简单复现：

https://s2.antv.vision/zh/examples/react-component/drill-dwon#for-pivot  

注释 s2DataConfig.fields 的 values（提交本issue时位于第20行）。

![lQLPJxZ2lX5rdxXNBI3NBY-wXVvOcjeGn5ACw1qw0cBUAA_1423_1165](https://user-images.githubusercontent.com/9587872/177069892-1be92ef0-ac03-456e-b027-e60e32cbffd2.png)

### ⌨️ Code Snapshots

```
    const s2DataConfig = {
      fields: {
        rows: ['province', 'city'],
        columns: ['type'],
        // values: ['price'],
      },
      meta,
      data,
    };

```

### 🔗 Reproduce Link

https://codesandbox.io/s/32v2tf

我这边没跑起来，是从实例那边生成的

### 😊 Expected Behavior

期望没有排序按钮。

### 😅 Current Behavior

现在会显示排序按钮

### 💻 System information

Edge:103.0.1264.44 
Win11

**Comment by lijinke666** [comment]
直接关闭默认 icon 就好了吧 

```ts
const s2Options = {
  showDefaultHeaderActionIcon: false
}
```

**Comment by lijinke666** [comment]
1. 关闭默认 icon

```ts
const s2Options = {
  showDefaultHeaderActionIcon: !s2DataConfig.fields.values.length
}
```

2. 下钻 有 `displayCondition` hook, 你可以自己决定显示条件

```ts
const partDrillDown = {
  displayCondition: (meta) => {
    // 你自己的判断条件
    return true
  },
}

<SheetComponent partDrillDown={partDrillDown} />
```
