### ISSUE TITLE
🙏期望@antv/s2-react能兼容react18

### ISSUE THREAD

**Issue by chenchengwork** [antvis/S2#1518]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.22.0    |
| @antv/s2-react |      1.20.0    |

### 🖋 Description

Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by astragier** [comment]
Why is the issue inactive while the last commit says the development will be scheduled?

**Comment by lijinke666** [comment]
resolved https://github.com/antvis/S2/pull/2373
