### ISSUE TITLE
🙏支持行头单元格内容的复制

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#1527]
### 🖋 Description
使用enableCopy开启的快捷键复制功能，目前在交叉表（grid)下，行头的单元格是无法单独选中然后复制的，点击行头然后ctrl+c 其实选中和复制的是当前行头下的数值单元格的值

希望有方法能够复制到行头单元格内的文本
![image](https://user-images.githubusercontent.com/15276351/177465934-a2a61e8a-f19f-4835-a8ad-a9d0d1472e4b.png)

**Comment by stone-lyl** [comment]
我看和这个issue 相似： https://github.com/antvis/S2/issues/1150
你是想在选中 行头 或者 列头的情况下可复制呢？还是选中数据单元格时，可以复制出带行列头的 数据单元格数据呢？

**Comment by stone-lyl** [comment]
如果选中 行/列头的复制时，你又希望是怎么样的效果呢？
<img width="632" alt="image" src="https://user-images.githubusercontent.com/20497176/179920721-2cdf3cd5-461c-446d-b06d-2f34173e5248.png">
