### ISSUE TITLE
🙏能不能导出的时候，保留样式呢，比如合并单元格之类的

### ISSUE THREAD

**Issue by yzkno1** [antvis/S2#1551]
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by lijinke666** [comment]
不支持

**Comment by wozien** [comment]
如果要实现的话，有啥思路吗？

**Comment by MonsterXue** [comment]
> 如果要实现的话，有啥思路吗？

我目前是通过copyData拿到原始数据，然后再手动合并单元格用XLXS设置['!merges']再导出

**Comment by renruijun** [comment]
这个功能感觉还是很有必要的，目前不支持就只能依赖服务端处理
