### ISSUE TITLE
🙏能否支持列宽自适应

### ISSUE THREAD

**Issue by alanleung04** [antvis/S2#1564]
### 🖋 
交叉透视表的列宽能否根据数据自适应或者支持换行？
数据比较长的时候出现省略号，非常影响用户体验

**Comment by lijinke666** [comment]
这个确实是 Canvas 绘制的弊端, 自动换行这个功能后期会支持

**Comment by tobemaster56** [comment]
列宽自适应需求 + 1

**Comment by guizhichao** [comment]
列宽自适应需求 + 1

**Comment by linghuam** [comment]
列宽自适应需求 + 1

**Comment by woshishade** [comment]
@lijinke666 请问近期会有自动换行的开发需求吗？

**Comment by lijinke666** [comment]
> 列宽能否根据数据自适应

这个 latest 版本目前是支持的, 见评论 https://github.com/antvis/S2/issues/1114#issuecomment-1788575668

> 支持换行

目前在开发中, 2.0 版本会支持 https://github.com/antvis/S2/pull/2383
