### ISSUE TITLE
🤔如何在单元格点击事件中获取额外透传参数呢

### ISSUE THREAD

**Issue by 2256184693** [antvis/S2#1567]
### 🖋 Description
在正常使用中，假如使用文档示例的数据来渲染表格可以正常使用，但是只能传递一个string到单元格中。
```
// 文档中的形式
const data = [
  {
    province: "浙江",
    city: "杭州",
    type: "家具",
    sub_type: "桌子",
    price: "1",
  },
];
// 假如元数据中家具有自己的`key`值，该如何传递才能在单元格中获取到这类额外字段呢？？？
const data = [
  {
    province: "浙江",
    city: "杭州",
    type: "家具",
    // type: '2',此时表格展示成了2，获取到的key但丢失了文本。
    sub_type: "桌子",
    price: "1",
  },
];
```
假如现在type字段下的单元格展示的是 **家具**, 我想在单元格点击后的业务逻辑中，获取到它对应的`key`值（比如家具的`key`为2）。我该用什么方式来获得呢？

### 😊 Expected Behavior

希望能在单元格中能够获取到一些业务透传下来的额外字段，用于点击事件后的业务逻辑中。

### 😅 Current Behavior

单元格中只能获取到对应的展示字符串和meta信息，无法获得透传字段。

**Comment by xingwanying** [comment]
![image](https://user-images.githubusercontent.com/10885578/179453905-f8741e89-2d93-4116-ba8b-4c9de64bb7e9.png)

**Comment by 2256184693** [comment]
@xingwanying  示例中是DataCell，我想问下 RowCell和ColCell可以实现类似的透传吗？
