### ISSUE TITLE
🤔 表格渲染后，有没有对应的生命周期方法呢

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1568]
### 🖋 Description
查看interface，发现存在onAfterRender, onBeforeRender, 但是并不会执行

### 😊 Expected Behavior
希望，表格render完之后，能有个生命周期回调函数

### 😅 Current Behavior
onAfterRender, onBeforeRender 没有执行

https://codesandbox.io/s/eager-glade-bwtyvf?file=/index.tsx

**Comment by lcx-seima** [comment]
的确第一次没有触发，后续是会触发的。
简单看了下和内部绑定事件的顺序有关。是个 BUG。

**Comment by lcx-seima** [comment]
目前，如果想在第一次渲染时回调，可以试试 `props.getSpreadSheet`。
