### ISSUE TITLE
🐛Firefox 下svg的icon不显示

### ISSUE THREAD

**Issue by meyergin** [antvis/S2#1571]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |    v1.23.0      |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
Firefox 102 最新版本，svg的icon都不显示
线上demo：https://s2.antv.vision/zh/examples/case/kpi-strategy#basic
展示效果：
![image](https://user-images.githubusercontent.com/7495191/179203542-18d20316-07b0-4ec8-be9d-539695423a54.png)
树形结构的icon没有展现，chrome下正常

### ⌨️ Code Snapshots
gui-icon.ts catch到error

GuiIcon Minus load error 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 5198, … }
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: <img src="data:image/svg+xml;utf-8…11\">\n\t</path>\n</svg>">
​
isTrusted: true
​
originalTarget: <img src="data:image/svg+xml;utf-8…11\">\n\t</path>\n</svg>">
​
returnValue: true
​
srcElement: <img src="data:image/svg+xml;utf-8…11\">\n\t</path>\n</svg>">
​
target: <img src="data:image/svg+xml;utf-8…11\">\n\t</path>\n</svg>">
​
timeStamp: 5198
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
styles-eb1c8c4f5fa173696878.js:21853:703

**Comment by wjgogogo** [comment]
可能关联的issue: #334  @xingwanying

**Comment by lijinke666** [comment]
应该是这个原因: https://stackoverflow.com/questions/30733607/svg-data-image-not-working-as-a-background-image-in-a-pseudo-element/30733736#30733736

**Comment by meyergin** [comment]
it works well now, thanks a lot!
