### ISSUE TITLE
🤔 如何实现数据单元格的多行显示

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1572]
### 🖋 Description
想实现下面的样子：
![image](https://user-images.githubusercontent.com/46083022/179216475-7204da7a-bcdc-4a7e-81c9-6de0b574802c.png)

一个单元格，可以有多行，并且每一行，可以自定义一些样式

**Comment by xingwanying** [comment]
可以参考下这个 demo 的数据格式
https://s2.antv.vision/zh/examples/case/proportion#group-drill-down
