### ISSUE TITLE
🐛Click 和DoubleClick的警告

### ISSUE THREAD

**Issue by wangyik1989** [antvis/S2#1580]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2-vue   |  v1.1.0    |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

Vue3 demo版本 下钻数据透视表，单击或者双击表单元格或者是表外空白处，会提示Click doubleClick 需要在emits声明的警告，
React版本不会出现上述清况。
Component emitted event "doubleClick" but it is neither declared in the emits option nor as an "onDoubleClick" prop.
### 🔗 Reproduce Link
官方提供的demo链接可重现这个问题..
https://codesandbox.io/s/s2-vue-hwg64q

**Comment by lijinke666** [comment]
ref https://github.com/antvis/S2/pull/1623
