### ISSUE TITLE
🤔isScrollToBottom()，返回值有问题

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1586]
使用**鼠标滚轮**滚动到底时，sheet.facet.isScrollToBottom(scrollY)这个值一直为**false**
但是这时候，再用**鼠标点击**滚动条，向下拖拽一下滚动条，sheet.facet.isScrollToBottom(scrollY)这个值就为**true**;

**视觉上感觉滚动条没有真正的到底，只是数值到底了
因为使用鼠标按住滚动条向下拖拽时，滚动条还是可以向下移动一点。**

![b351815d5d0e1a69231b4293b8daf9c](https://user-images.githubusercontent.com/26482193/179881673-4d17ad00-2fbe-4eb2-902f-32b9dce781fd.jpg)
![29d4784936fe42e9e1def22d515bba7](https://user-images.githubusercontent.com/26482193/179881706-bf445861-a05e-4e7f-aef6-7cc712849579.jpg)

**Comment by dengyushuai** [comment]
视觉上感觉滚动条没有真正的到底，只是数值到底了
因为使用鼠标按住滚动条向下拖拽时，滚动条还是可以向下移动一点

**Comment by dengyushuai** [comment]
我们是内网，提供不了在线访问的连接

**Comment by dengyushuai** [comment]
> 你好@dengyushuai，请提供一个可以在线链接，或者使用[codesandbox](https://codesandbox.io/s/29zle)提供详细说明复现步骤（[查看更多](https://www.yuque.com/antv/vo4vyz/bam4vz)示例），15 个未完成的示例访问示例自动关闭。
> 
> 你好，@dengyushuai，请提供可访问的链接或使用[代码框](https://codesandbox.io/s/29zle)来描述复制步骤（[更多模板](https://www.yuque.com/antv/vo4vyz/bam4vz)）。该问题将在 15 天内关闭且不进行任何重播。

我们是内网，提供不了连接，这照片都是用手机拍摄的

**Comment by dengyushuai** [comment]
> 你这个 `scroll` 函数在哪里监听的, 你的业务场景是? 不是让你提供内网链接, 是让你用 `codesandbox` 搭一个 demo, 不然不好排查, 谢谢

我先自己研究一下，如果不行，我就用codesandbox 打一个demo. 谢谢

**Comment by lijinke666** [comment]
恩, 好的, 源码在: https://github.com/antvis/S2/blob/99b859392c7151d5700bf1c505a02f795b9a3f80/packages/s2-core/src/facet/base-facet.ts#L770-L779

**Comment by dengyushuai** [comment]
> 恩, 好的, 源码在:
> 
> https://github.com/antvis/S2/blob/99b859392c7151d5700bf1c505a02f795b9a3f80/packages/s2-core/src/facet/base-facet.ts#L770-L779

谢谢
