### ISSUE TITLE
🙏 透视表能够支持冻结行(有个需求希望总计能够固定在底部）

### ISSUE THREAD

**Issue by Hzhxi9** [antvis/S2#1589]
### 🖋 Description

透视表能够跟明细表一样支持 frozenTrailingRowCount 这些配置

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by devchen13** [comment]
遇到同样的问题，等待解决

**Comment by donglegend** [comment]
+1

**Comment by donglegend** [comment]
透视表为什么不能支持  冻结列呢？ 不想要行维度 直接被分离，有时候 有很多行维度，但是只想 冻结第一列 ，固定在左侧

**Comment by donglegend** [comment]
透视表为什么不能支持  冻结列呢？ 不想要行维度 直接被分离，有时候 有很多行维度，但是只想 冻结第一列 ，固定在左侧

**Comment by shuangxunian** [comment]
> 透视表为什么不能支持 冻结列呢？ 不想要行维度 直接被分离，有时候 有很多行维度，但是只想 冻结第一列 ，固定在左侧

佬找到解决方案了吗，我们现在也有这个需求 需要冻结列头，但是现在没找到合适的解决方法

**Comment by llifangyin** [comment]
+1 该功能很常见呀，明细表有透视表没有 有点说不过去， 😢

**Comment by llifangyin** [comment]
🙏 大佬们排期开始了吗，如果没有我明天再过来问

**Comment by wjgogogo** [comment]
ref: https://github.com/antvis/S2/pull/2416

**Comment by xulingling0** [comment]
+1

**Comment by xulingling0** [comment]
> ref: #2416

这个也解决不了总计能够固定在底部的问题吧？

**Comment by wozien** [comment]
> > ref: #2416
> 
> 这个也解决不了总计能够固定在底部的问题吧？

看起来只能固定在顶部

**Comment by wjgogogo** [comment]
duplicate of #2573
