### ISSUE TITLE
🤔自定义icon是否可以实现类似ant-table排序的icon点击的时候高亮

### ISSUE THREAD

**Issue by cdx111** [antvis/S2#1595]
### 😊 预期

<img width="342" alt="WX20220722-112544@2x" src="https://user-images.githubusercontent.com/39432333/180356293-a45ef860-8ebe-4c85-9326-fbd25f8ed0fd.png">

### 😅 当前

<img width="209" alt="WX20220722-112658@2x" src="https://user-images.githubusercontent.com/39432333/180356358-af1c2b8f-a39b-4c0b-a878-1dd1f198b3e0.png">

**Comment by lijinke666** [comment]
使用的 `headerActionIcons` 自定义吗? 目前只能通过自定义列头单元格实现, 可以考虑让`headerActionIcons.iconName` 支持回调

**Comment by cdx111** [comment]
使用自定义icon，每次点击icon后通过setOptions然后使用render可以实现了
