### ISSUE TITLE
🐛S2-React不支持umi4(react-18)

### ISSUE THREAD

**Issue by hch859** [antvis/S2#1598]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      √    |
| @antv/s2-react |     √     |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

最新的umi4-max，导入s2-react后做过简单的表格，运行后点击表格里的单元格报错：

index.js:1 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by qiaogaolong** [comment]
预计要多久支持呢哇？

**Comment by lijinke666** [comment]
resolved https://github.com/antvis/S2/pull/2373
