### ISSUE TITLE
🐛 build fail

### ISSUE THREAD

**Issue by zhou7rui** [antvis/S2#1600]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |  1.23.0        |
| @antv/s2-react |   1.21.0       |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [x] StrategySheet

### 🖋 Description
TS2416: Property 'getIconStyle' in type 'DataCell' is not assignable to the same property in base type 'BaseCell<ViewMeta>'.

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/31248715/180412060-62041ea5-6f5e-4a52-829f-f6f5b3957152.png">

### 🤔 Steps to Reproduce
build fail

### 😊 Expected Behavior
build success
### 😅 Current Behavior
yarn run v1.22.15
$ tsc && vite build
node_modules/@antv/s2/esm/index.d.ts:1113:5 - error TS2416: Property 'getIconStyle' in type 'DataCell' is not assignable to the same property in base type 'BaseCell<ViewMeta>'.
  Type '() => IconCfg | undefined' is not assignable to type '() => IconTheme'.
    Type 'IconCfg | undefined' is not assignable to type 'IconTheme'.
      Type 'undefined' is not assignable to type 'IconTheme'.

1113     getIconStyle(): IconCfg | undefined;
         ~~~~~~~~~~~~

node_modules/@antv/s2/esm/index.d.ts:2730:9 - error TS2411: Property 'red' of type 'string | undefined' is not assignable to 'string' index type 'string'.

2730         red?: string;
             ~~~

node_modules/@antv/s2/esm/index.d.ts:2731:9 - error TS2411: Property 'green' of type 'string | undefined' is not assignable to 'string' index type 'string'.

2731         green?: string;
             ~~~~~

node_modules/@antv/s2/esm/index.d.ts:2732:9 - error TS2411: Property 'yellow' of type 'string | undefined' is not assignable to 'string' index type 'string'.

2732         yellow?: string;
             ~~~~~~


Found 4 errors in the same file, starting at: node_modules/@antv/s2/esm/index.d.ts:1113

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
### 💻 System information
yarn vite react typescipt
<!-- eg: chrome: v91.0, window 🙅🏻‍♀️🚫 `latest`, `1.x` -->

**Comment by lijinke666** [comment]
贴下你的 `tsconfig.json`, 请检查是不是开启了 `strictNullChecks: true`, 请关闭后再次尝试打包看是否正常

**Comment by zhou7rui** [comment]
``` json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by zhou7rui** [comment]
strictNullChecks: false 可以build了
