### ISSUE TITLE
使用 antd tab 组件，切换 tab 的时候，表格会消失

### ISSUE THREAD

**Issue by promise6512** [antvis/S2#1602]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |    ^1.17.0      |
| @antv/s2-react |    17.x      |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### ⌨️ Code Snapshots
![image](https://user-images.githubusercontent.com/86681329/180428489-c7055be4-8226-46f3-8868-d921ef5c529a.png)

### 🔗 Reproduce Link
https://codesandbox.io/s/black-currying-1yqlch?file=/src/App.tsx

### 🤔 Steps to Reproduce
使用了 antd 的 tab 组件，切换 tab 的时候，表格会消失

### 😊 Expected Behavior
切换 tab 的时候，表格不会消失，仍能自适用父容器尺寸
Chrome：版本 103.0.5060.114（正式版本） (arm64)
操作系统：
![image](https://user-images.githubusercontent.com/86681329/180427700-f243162b-5923-4db7-99af-e0db2f8835b7.png)

**Comment by wangwufan** [comment]
我遇到了同样的问题，不知道是不是bug

**Comment by wangwufan** [comment]
切换 tab 的时候，表格会消失

**Comment by lijinke666** [comment]
这里 第二个 tab forceRender 的原因是? 
![image](https://user-images.githubusercontent.com/21015895/182284034-3e2a1f08-78cd-4d86-b70d-180dd2f9bfa4.png)

**Comment by lijinke666** [comment]
1. 表格消失的原因是因为你配置了 `forceRender` 让第二个 tab 强制渲染, 从而渲染了表格
2. 由于你这里是选项卡, 第二个 tab 是默认隐藏的 `display: none`, 导致子元素里面的表格渲染获取不到宽度

![image](https://user-images.githubusercontent.com/21015895/182287418-92b8efcd-9778-4a90-b471-8c3f9edb7eee.png)

3. 不太清楚你这里的设置 `forceRender` 的目的是啥, 目前的解法是将 `forceRender` 设为 `false`

**Comment by promise6512** [comment]
感谢您的回答，设置 `forceRender` 是为了能用 ref 拿到第二个表格的实例
![image](https://user-images.githubusercontent.com/86681329/182288141-e0ebe487-a4a4-4e1b-b2a2-af285a7aef0b.png)

**Comment by lijinke666** [comment]
> 为了能用 ref 拿到第二个表格的实例

针对你这种场景, 建议你使用 `getSpreadSheet` 来获取实例 

https://s2.antv.vision/zh/docs/manual/advanced/get-instance#getspreadsheet-%E6%96%B9%E5%BC%8F

```ts
  <TabPane tab="tab2" key="tab2">
    <SheetComponent
      getSpreadSheet={(spreadsheet) => {
        ref2.current = spreadsheet;
      }}
    />
  </TabPane>
```

**Comment by promise6512** [comment]
> > 为了能用 ref 拿到第二个表格的实例
> 
> 针对你这种场景, 建议你使用 `getSpreadSheet` 来获取实例
> 
> https://s2.antv.vision/zh/docs/manual/advanced/get-instance#getspreadsheet-%E6%96%B9%E5%BC%8F
> 
> ```ts
>   <TabPane tab="tab2" key="tab2">
>     <SheetComponent
>       getSpreadSheet={(spreadsheet) => {
>         ref2.current = spreadsheet;
>       }}
>     />
>   </TabPane>
> ```

刚刚测了一下，貌似没用
![image](https://user-images.githubusercontent.com/86681329/182309242-388c9f90-dc31-4a72-a89e-02298e7fe5f5.png)
![image](https://user-images.githubusercontent.com/86681329/182309277-ca47893f-76ff-44ca-abcb-5e592f2c32ad.png)

**Comment by lijinke666** [comment]
你的 ref2 在哪里 console 的, 请确保在 React.useEffect 中使用

**Comment by promise6512** [comment]
> 你的 ref2 在哪里 console 的, 请确保在 React.useEffect 中使用

是在 useEffect 里面打印的

**Comment by lijinke666** [comment]
哦, 我是在 forceRender 的场景测试下的, forceRender: false 情况下肯定是拿不到的, tab 都没有切换

我觉得两种方案吧

1. tab 开启 forceRender, 关闭 s2 提供的自适应, 自行在 onTabChange 后 设置表格宽高, 获取实例还是使用 useRef
2. tab 关闭 forceRender, 开启 s2 提供的自适应, 逻辑写在 `getSpreadSheet` 里, 不需要保存实例

```ts
        <TabPane tab="tab2" key="tab2">
          <SheetComponent
            getSpreadSheet={(s2) => {
              console.log('s2', s2)
              // 处理你的业务逻辑
            }}
            sheetType="table"
            dataCfg={s2DataConfig}
            adaptive={{
              width: true,
              height: true,
              getContainer: () => document.getElementById('container')!,
            }}
          />
        </TabPane>
```

然后想让 `getSpreadSheet` 在每次切换 tab 都执行, 请开启 `Tabs` 的 destroyInactiveTabPane 属性

**Comment by promise6512** [comment]
感谢大佬！按照您提供的方法，解决了需求了

**Comment by wangwufan** [comment]
后来我看了看css的状态，确认是s2表格组件外围的div的高度变成0了，是在切换tab时突然变的，具体原因不知道，我只好在容器div的style里绑定了s2表格的高度，才实现了正常显示

**Comment by wangwufan** [comment]
后来我看了看css的状态，确认是s2表格组件外围的div的高度变成0了，是在切换tab时突然变的，具体原因不知道，我只好在容器div的style里绑定了s2表格的高度，才实现了正常显示
