### ISSUE TITLE
🤔关于隐藏列头功能问题

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1603]
### 🖋 Description
设置一个button按钮，用来控制显示隐藏列头，此时点击按钮可以控制列头的显示隐藏
![1658545480629](https://user-images.githubusercontent.com/26482193/180588332-e0ff2813-2ac4-4ec2-9087-057cee681988.jpg)

问题：
当列头存在时，先使用鼠标拖拽一下列头（使用鼠标拖拽改变一下列头高度），之后再去点击显示隐藏列头按钮时（也就是设置列头height：0）,设置高度无效。
![1658545595765](https://user-images.githubusercontent.com/26482193/180588353-f6fe020c-d8a7-48cb-89d5-27c2be1fcd47.jpg)

codesandbox: https://el8wue.csb.app/

**Comment by lijinke666** [comment]
表格的宽高有三种, 优先级依次为:  用户拖拽后的 > 用户设置的 > 表格自动计算的

第二次拖拽后, 产生了一条拖拽信息, 所以在表格重新渲染的时候, 会优先读取它

```ts
// a. 你配置的 

{
  "colCfg": {
    "height": 0
  }
}

// b. 拖拽后生成的
{
  "colCfg": {
    "heightByField": {
      "province": 62
    }
  }
}
```

所以:

1. 关闭列头拖拽
2. 或者替换你的配置写法 a => b

```ts
{
  "colCfg": {
    "heightByField": {
      // 明细表列头高度都一样, 任取一个 field
      [任意列头 field]: 0
    }
  }
}
```

https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-size#%E8%B0%83%E6%95%B4%E8%A1%8C%E5%A4%B4%E5%8D%95%E5%85%83%E6%A0%BC%E5%AE%BD%E9%AB%98

**Comment by dengyushuai** [comment]
> 表格的宽高有三种, 优先级依次为: 用户拖拽后的 > 用户设置的 > 表格自动计算的
> 
> 第二次拖拽后, 产生了一条拖拽信息, 所以在表格重新渲染的时候, 会优先读取它
> 
> ```ts
> // a. 你配置的 
> 
> {
>   "colCfg": {
>     "height": 0
>   }
> }
> 
> // b. 拖拽后生成的
> {
>   "colCfg": {
>     "heightByField": {
>       "province": 62
>     }
>   }
> }
> ```
> 
> 所以:
> 
> 1. 关闭列头拖拽
> 2. 或者替换你的配置写法 a => b
> 
> ```ts
> {
>   "colCfg": {
>     "heightByField": {
>       // 明细表列头高度都一样, 任取一个 field
>       [任意列头 field]: 0
>     }
>   }
> }
> ```
> 
> https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-size#%E8%B0%83%E6%95%B4%E8%A1%8C%E5%A4%B4%E5%8D%95%E5%85%83%E6%A0%BC%E5%AE%BD%E9%AB%98

按照您的配置写法，出现两个问题？下图
![1658804147481](https://user-images.githubusercontent.com/26482193/180913424-6351c8d9-df56-4d00-99a8-f035b8ca402e.jpg)
第一个问题：头部不能拖拽了
第二个问题：当我把头部设置为0时，头部还是显示着
codesandbox: https://ndzp6j.csb.app/

**Comment by lijinke666** [comment]
> 第二个问题：当我把头部设置为0时，头部还是显示着。

看了下, 这是一个 bug, 内部会忽略为 0 的情况

https://github.com/antvis/S2/blob/a4efc490efb41683616b12149cc7c101a28fb2ea/packages/s2-core/src/facet/pivot-facet.ts#L356

> 第一个问题：头部拖拽功能失效了。

既然你都要隐藏列头, 拖拽列头的意义是? 为什么不直接把拖拽功能禁用? 或者我们表格内部 在高度为0 时应该做这个处理

**Comment by dengyushuai** [comment]
> > 第二个问题：当我把头部设置为0时，头部还是显示着。
> 
> >看了下, 这是一个 bug, 内部会忽略为 0 的情况
> 好的，谢谢。
> https://github.com/antvis/S2/blob/a4efc490efb41683616b12149cc7c101a28fb2ea/packages/s2-core/src/facet/pivot-facet.ts#L356
> 
> > 第一个问题：头部拖拽功能失效了。
> 
> >既然你都要隐藏列头, 拖拽列头的意义是? 为什么不直接把拖拽功能禁用? 或者我们表格内部 在高度为0 时应该做这个处理
> 不是要隐藏列头，需求是通过按钮控制显示隐藏列头，显示时还要能拖拽？

**Comment by dengyushuai** [comment]
> > > 第二个问题：当我把头部设置为0时，头部还是显示着。
> > 
> > 
> > > 看了下, 这是一个 bug, 内部会忽略为 0 的情况
>>
> > > 好的，谢谢。
> > > https://github.com/antvis/S2/blob/a4efc490efb41683616b12149cc7c101a28fb2ea/packages/s2-core/src/facet/pivot-facet.ts#L356
> > 
> > 
> > > 第一个问题：头部拖拽功能失效了。
> > 
> > 
> > > 既然你都要隐藏列头, 拖拽列头的意义是? 为什么不直接把拖拽功能禁用? 或者我们表格内部 在高度为0 时应该做这个处理
>>
> > > 不是要隐藏列头，需求是通过按钮控制显示隐藏列头，显示时还要能拖拽？

**Comment by lijinke666** [comment]
所谓的禁用拖拽, 就是隐藏拖拽热区, 隐藏列头隐藏热区, 显示列头再显示热区不就好了?
https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E8%A1%8C%E5%88%97%E5%AE%BD%E9%AB%98%E8%B0%83%E6%95%B4

**Comment by dengyushuai** [comment]
> 所谓的禁用拖拽, 就是隐藏拖拽热区, 隐藏列头隐藏热区, 显示列头再显示热区不就好了? https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E8%A1%8C%E5%88%97%E5%AE%BD%E9%AB%98%E8%B0%83%E6%95%B4

您说的有道理，现在这个需求确实不太好

**Comment by lijinke666** [comment]
>  或者我们表格内部 在高度为0 时应该做这个处理

感谢你为我们提供了一种场景吧, 我觉得对于高度为0的场景, 表格内部就不应该允许拖拽

**Comment by dengyushuai** [comment]
> > 或者我们表格内部 在高度为0 时应该做这个处理
> 
> 感谢你为我们提供了一种场景吧, 我觉得对于高度为0的场景, 表格内部就不应该允许拖拽

不要客气，我也是第一次使用这个表格，我还会有问题问的。感谢你们团队为我们提供这么方便的工具

**Comment by hurricane1998** [comment]
@lijinke666 您好，我遇到了另外一个关于隐藏列头的问题，使用style里的colCfg的hideMesureColumn属性没有变化，设置colCfg的height为0后，第一行的上方会没有边框，我的猜测是因为这个边框是使用了列头的边框，但是此时列头高度没有了，所以第一行也没有边框了
