### ISSUE TITLE
🤔表头排序功能与tootip冲突

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1605]
### 🖋 Description
当S2Options设置tooltip: { col: { showTooltip: false} }时，表头排序功功能也隐藏了

### 😊 Expected Behavior
设置showTootip为false时，表头排序功能不应该隐藏，只隐藏鼠标经过或按下提示即可

### 😅 Current Behavior
设置showTooltip:false时，表头排序功功能也隐藏了，也就是自带排序功能消失了

**Comment by lijinke666** [comment]
排序菜单是通过 Tooltip 承载的, 你又把 tooltip 关闭了, 又要显示排序菜单, 何来冲突这一说?

**Comment by dengyushuai** [comment]
> 排序菜单是通过 Tooltip 承载的, 你又把 tooltip 关闭了, 又要显示排序菜单, 何来冲突这一说?

也就是说，如果不想要Tooltip提示功能，还想要排序功能，是不可能的了。

**Comment by lijinke666** [comment]
排序的api表格是提供的, 只是排序/隐藏列头/多选 这些操作 UI 是通过 tooltip 呈现, 你不想要 tooltip, 又要排序, 那么你就需要自己写一个排序菜单或者怎么样, 然后调用这些排序 api 即可

**Comment by dengyushuai** [comment]
> 排序的api表格是提供的, 只是排序/隐藏列头/多选 这些操作 UI 是通过 tooltip 呈现, 你不想要 tooltip, 又要排序, 那么你就需要自己写一个排序菜单或者怎么样, 然后调用这些排序 api 即可

懂了，谢谢
