### ISSUE TITLE
🙏 行头单元格支持设置奇数背景颜色

### ISSUE THREAD

**Issue by Hzhxi9** [antvis/S2#1609]
### 🖋 Description

目前只有数值单元格支持奇数背景颜色

有需求想要整行颜色统一

希望能支持设置奇数背景颜色

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by lijinke666** [comment]
直接来个 PR 吧, 那么对于根节点 [省份], 他应该显示什么颜色呢?

![image](https://user-images.githubusercontent.com/21015895/180957515-1740af81-b7bb-4b83-ae10-5b58afafc71e.png)
