### ISSUE TITLE
1.请问明细表支持这种列头么，像excel那样的26个英文字母A、B ；    2、序号怎么更改文案呢🙏

### ISSUE THREAD

**Issue by carolCross** [antvis/S2#1614]
<img width="1105" alt="1" src="https://user-images.githubusercontent.com/24600605/180976068-354875fe-7a65-49ac-a250-fefe2d270481.png">

1、明细表支持这种列头么 2、序号支持变更文案么

**Comment by guizhichao** [comment]
<img width="1105" alt="1" src="https://user-images.githubusercontent.com/24600605/180975969-1f3dab67-46ce-4403-b78c-712f7551b0c3.png">

**Comment by lijinke666** [comment]
1. 不支持, 建议你把数据洗成 {type: 'A', name: '省份', {type: 'B', name: '第一季度'} 这种格式, 使用交叉表来渲染
2. 不支持, 可以开放一个 api 来做配置, 或者可以通过自定义 cornerCell 角头单元格实现

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/en/manual/migration-v2

https://s2.antv.antgroup.com/examples/custom/custom-cell/#series-number-cell
