### ISSUE TITLE
🤔S2Event.GLOBAL_SCROLL绑定如何触发执行

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1617]
### 🖋 Description

绑定了事件之后并不生效
<img width="602" alt="image" src="https://user-images.githubusercontent.com/17949045/180991488-bdecf004-33ed-411d-a4e3-8cad193756c0.png">

**Comment by yangxiaoguai132** [comment]
> globalScroll 是表格滚动会触发, ScrollInteraction 有注册吗? 建议来个可复现 demo 吗?

注册了
<img width="509" alt="image" src="https://user-images.githubusercontent.com/17949045/181026776-f314ba4f-98a6-449f-b1a0-01ad589ecca6.png">

**Comment by lijinke666** [comment]
麻烦用 [codesandbox](https://codesandbox.io/) 搭一个吧
