### ISSUE TITLE
🤔图中可拖拽透视表hover状态如何指定颜色

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1619]
### 🖋 Description
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/17949045/181203571-328aa805-14a9-40d3-9f15-646f9039334e.png">

**Comment by lijinke666** [comment]
什么叫 [可拖拽透视表hover状态] ???

如果你说的是拖拽参考线的话, 请配置主题 https://s2.antv.vision/zh/docs/api/general/S2Theme#resizearea
