### ISSUE TITLE
🤔	关于DataCell: 自定义单元格 cell的问题

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1621]
### 🖋 Description
设置单元格背景色后出现了两个问题
第一个问题（我不确定是不是bug）：s2options: 配置dataCell，序号列拖拽行高功能消失了；不配置dataCell，序号列拖拽行高功能可用
第二个问题：s2options: 配置dataCell，此时点击**不同的**单元格比较卡顿。（我测试卡顿原因好像是因为我写判断之后卡顿的，如果不写判断就不卡顿；我不确定真正卡顿原因是不是因为判断；下图）
![1658972708328](https://user-images.githubusercontent.com/26482193/181402343-2033d72e-dfa2-4d9e-975c-8ca312d01c34.jpg)

codesandbox：https://codesandbox.io/s/gai-bian-dan-yuan-ge-yan-se-hou-chu-xian-de-wen-ti-yfyu7q?file=/src/index.js

**Comment by xiaochong44** [comment]
第一个问题，判断是序号列就用TableSeriesCell，其它列再用CustomDataCell

**Comment by dengyushuai** [comment]
> 第一个问题，判断是序号列就用TableSeriesCell，其它列再用CustomDataCell

谢谢

**Comment by lijinke666** [comment]
第二个问题, 因为你复写了 DataCell 的 `drawBackgroundShape` 方法, 但是又加了 if 分支, 要在 else 分支 调用 父类的 `drawBackgroundShape`

```
if(xxx) {

} else {
  return super.drawBackgroundShape();
}
```

![image](https://user-images.githubusercontent.com/21015895/181690664-a6e63553-981e-4653-b9a5-5ff0702b70fa.png)

**Comment by dengyushuai** [comment]
> return super.drawBackgroundShape();

谢谢
