### ISSUE TITLE
🐛 选中态的描边样式问题

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#1624]
### 🖋 Description

![image](https://user-images.githubusercontent.com/10885578/181693528-edaaa68a-6741-48c7-ae11-55ca4cb7bdaf.png)

选中数据单元格的描边的粗细不一致，而且看起来变细了

**Comment by wjgogogo** [comment]
@xingwanying 看起来还是那个`GridGroup`层把部分的 cell border遮住了
