### ISSUE TITLE
🤔 rowCfg不执行

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1625]
### 🖋 Description
https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-size#%E8%B0%83%E6%95%B4%E8%A1%8C%E5%A4%B4%E5%8D%95%E5%85%83%E6%A0%BC%E5%AE%BD%E9%AB%98

<img width="458" alt="image" src="https://user-images.githubusercontent.com/17949045/181693815-02326b7d-b324-48d7-9254-5b2fb87a62dc.png">

透视表中按照这个方式配置，这个函数并不执行

**Comment by lijinke666** [comment]
这个是 [https://github.com/antvis/S2/releases/tag/%40antv%2Fs2-v1.24.0](1.24.0) 版本新增的特性, 请检查一下使用的版本, 后面我们会备注一下, 抱歉

**Comment by yangxiaoguai132** [comment]
使用的版本是没有错的

**Comment by yangxiaoguai132** [comment]
> 这个是 [1.24.0](https://github.com/antvis/S2/releases/tag/%40antv%2Fs2-v1.24.0) 版本新增的特性, 请检查一下使用的版本, 后面我们会备注一下, 抱歉

使用的是最新版，也不执行

**Comment by lijinke666** [comment]
那麻烦来个可复现 demo
