### ISSUE TITLE
🤔 角头文字居中失效

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1626]
### 🖋 Description
<img width="476" alt="image" src="https://user-images.githubusercontent.com/17949045/181728658-bc29ed9c-bdab-4420-9743-1421b727e096.png">

配置如下不生效，文字还是靠右对齐了

想要实现角头文字居中显示
<img width="504" alt="image" src="https://user-images.githubusercontent.com/17949045/181729927-b74a4f4a-9adc-43bf-a4d7-c420f4fb404f.png">

**Comment by lijinke666** [comment]
本地未复现, 请给一个在线 demo
![image](https://user-images.githubusercontent.com/21015895/182090977-c76b7696-e19a-4693-93fa-0aeb9fe612d1.png)
![image](https://user-images.githubusercontent.com/21015895/182091005-13819757-7c62-4689-85b1-e23a0a7fa35e.png)
