### ISSUE TITLE
🤔如何关闭圈选表格数据功能

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1628]
### 🖋 Description
<img width="637" alt="image" src="https://user-images.githubusercontent.com/17949045/182280214-a4aa728d-f34b-447a-a166-ba05814fd06e.png">

不想要实现圈选效果

**Comment by lijinke666** [comment]
请先看文档再提问 
https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E5%9C%88%E9%80%89%E9%AB%98%E4%BA%AE
