### ISSUE TITLE
🤔 mergedCellsInfo的showText如何使用更改merge的单元格的样式

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1630]
### 🖋 Description
<img width="901" alt="image" src="https://user-images.githubusercontent.com/17949045/182303542-74190af8-4d5d-43e1-8684-62bf66f0843f.png">

需要实现merge单元格内部的文字居中，但是不知如何实现，上述文档中的内容没有看懂是什么意思，应该如何使用这个showText，设置完true或者false之后，只看到数据从右上角展示变成了右下角展示

非常困惑这个属性的作用

**Comment by stone-lyl** [comment]
文档写的不太好😂，我后面优化一下。可以看看下面的截图，是否解决了你的疑惑哈。

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/20497176/182382855-5bd406cb-90cc-4262-a08a-35b2ced673e2.png">

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/20497176/182382925-ec58c048-3711-4913-8358-cb40994ded62.png">

**Comment by yangxiaoguai132** [comment]
请问偶数格子的垂直居中如何通过showText实现呢

**Comment by stone-lyl** [comment]
> 

这个功能暂不支持

**Comment by stone-lyl** [comment]
如果需要，可以给我们提一个 issue
