### ISSUE TITLE
列头操作图标替换问题

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1635]
### 🖋 Description
想把列头的**操作图标**替换成**html标签**（例如：span、p、div），可以吗？
我知道可以替换svg。
![image](https://user-images.githubusercontent.com/26482193/182504566-91df4f04-c904-49a5-be36-6398e2e0a271.png)

**Comment by stone-lyl** [comment]
暂时不支持的

**Comment by dengyushuai** [comment]
> 暂时不支持的

哦，谢谢。

**Comment by stone-lyl** [comment]
如果需要这个功能，可以给我们提 `feature  issue` , 这个issue 我先关闭了

**Comment by dengyushuai** [comment]
> 如果需要这个功能，可以给我们提 `feature issue` , 这个issue 我先关闭了

好的，谢谢
