### ISSUE TITLE
🤔getAllCells()获取数据问题

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1636]
### 🖋 Description
getAllCells()只能获取可视区域的全部数据，并不是获取所有表格数据。设计就是这样吗？

如果是设计如此，感觉文档不应该写获取所有单元格。
![image](https://user-images.githubusercontent.com/26482193/182509680-36be1391-534b-4f09-8126-37d900b96368.png)

**Comment by stone-lyl** [comment]
是的，`getAllCells()` 为可视区域的数据。全量数据你可以通过自身传入的 `dataCfg`  获取啊

**Comment by dengyushuai** [comment]
> 是的，`getAllCells()` 为可视区域的数据。全量数据你可以通过自身传入的 `dataCfg` 获取啊

谢谢，我知道怎么获取，只是文档写的是获取所有单元格，容易误解

**Comment by dengyushuai** [comment]
> 你好 @dengyushuai，请提供一个可以在线访问的链接, 或者使用 [codesandbox](https://codesandbox.io/s/29zle) 提供示例并详细说明复现步骤 ([查看更多模板](https://www.yuque.com/antv/vo4vyz/bam4vz)), 15 天内未回复issue自动关闭。
> 
> Hello, @dengyushuai, please provide an accessible link or usage [codesandbox](https://codesandbox.io/s/29zle) to describe the reproduction steps ([more template](https://www.yuque.com/antv/vo4vyz/bam4vz)). The issue will be closed without any replay within 15 days.

这个问题你在文档任何一个带滚动条的demo里都能测试。我只是问一下。如果必须出codesandbox示例才能解释的话，那就不用了，谢谢

**Comment by stone-lyl** [comment]
> > 你好 @dengyushuai，请提供一个可以在线访问的链接, 或者使用 [codesandbox](https://codesandbox.io/s/29zle) 提供示例并详细说明复现步骤 ([查看更多模板](https://www.yuque.com/antv/vo4vyz/bam4vz)), 15 天内未回复issue自动关闭。
> > Hello, @dengyushuai, please provide an accessible link or usage [codesandbox](https://codesandbox.io/s/29zle) to describe the reproduction steps ([more template](https://www.yuque.com/antv/vo4vyz/bam4vz)). The issue will be closed without any replay within 15 days.
> 
> 这个问题你在文档任何一个带滚动条的demo里都能测试。我只是问一下。如果必须出codesandbox示例才能解释的话，那就不用了，谢谢

回复时误加了 [🤔 need reproduce](https://github.com/antvis/S2/labels/%F0%9F%A4%94%20need%20reproduce) 的  `label`， 进行的自动回复。后面已经移除了。文档问题，我后期统一修复一下。感谢你提出的问题。

**Comment by dengyushuai** [comment]
> 



> > > 你好 @dengyushuai，请提供一个可以在线访问的链接, 或者使用 [codesandbox](https://codesandbox.io/s/29zle) 提供示例并详细说明复现步骤 ([查看更多模板](https://www.yuque.com/antv/vo4vyz/bam4vz)), 15 天内未回复issue自动关闭。
> > > Hello, @dengyushuai, please provide an accessible link or usage [codesandbox](https://codesandbox.io/s/29zle) to describe the reproduction steps ([more template](https://www.yuque.com/antv/vo4vyz/bam4vz)). The issue will be closed without any replay within 15 days.
> > 
> > 
> > 这个问题你在文档任何一个带滚动条的demo里都能测试。我只是问一下。如果必须出codesandbox示例才能解释的话，那就不用了，谢谢
> 
> 回复时误加了 [🤔 need reproduce](https://github.com/antvis/S2/labels/%F0%9F%A4%94%20need%20reproduce) 的 `label`， 进行的自动回复。后面已经移除了。文档问题，我后期统一修复一下。感谢你提出的问题。

没关系的。谢谢您

**Comment by lijinke666** [comment]
欢迎来个 PR 修改文档

**Comment by dengyushuai** [comment]
> 欢迎来个 PR 修改文档

这个就不太了解了
