### ISSUE TITLE
🙏明细表不使用序号，拖拽行高

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1637]
### 🖋 Description
明细表，不显示序号列（showSeriesNumber: false）情况下，可以设置列表第一列的每一行  可拖拽数据单元格行高吗？（不知道是否叙述清楚了）
现在是明细表如果不显示序号，就不能拖拽**数据单元格**的行高。
![image](https://user-images.githubusercontent.com/26482193/182514056-d8be9864-f9cf-4c9e-9f72-6c653b68a8c6.png)

**Comment by dengyushuai** [comment]
> 你好 @dengyushuai，经过我们的反复讨论, 你的需求现已被采纳, 我们会排期开发, 请关注后续发布日志。
> 
> Hello, @dengyushuai, your feature request has been accepted after our repeated discussion. We will schedule the development, please pay attention to the follow-up release logs.

好的，谢谢

**Comment by dengyushuai** [comment]
辛苦了，非常感谢。
这个是可以用了吗？
如果可以了，是不是我直接更新一下v1.25.0版本就行吧？

**Comment by wjgogogo** [comment]
请关注本周五的发版信息，然后更新版本即可

**Comment by dengyushuai** [comment]
> 请关注本周五的发版信息，然后更新版本即可
非常感谢，谢谢各位了

**Comment by dengyushuai** [comment]
> 🎉 This issue has been resolved in version @antv/s2-v1.26.0-alpha.1 🎉
> 
> The release is available on:
> 
> * [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.26.0-alpha.1)
> * [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.26.0-alpha.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

辛苦

**Comment by dengyushuai** [comment]
> > 🎉 This issue has been resolved in version @antv/s2-v1.26.0-alpha.1 🎉
> > The release is available on:
> > 
> > * [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.26.0-alpha.1)
> > * [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.26.0-alpha.1)
> > 
> > Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀
> 
> 辛苦

稳定版大概什么时候可以用？

**Comment by dengyushuai** [comment]
> 🎉 This issue has been resolved in version @antv/s2-v1.26.0-alpha.1 🎉
> 
> The release is available on:
> 
> * [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.26.0-alpha.1)
> * [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.26.0-alpha.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

稳定版大概什么时候可以用？
