### ISSUE TITLE
🙏透视表增加占比计算功能

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#1648]
### 🖋 Description
现在透视表的功能已经非常强大了，但缺少了一个重要的功能，就是值的占比显示
### 🏞 What problem does this feature solve
![image](https://user-images.githubusercontent.com/25057951/182985401-1f49f321-3ec9-406d-ad51-ffb450612053.png)
类似EXCEL透视表的这种，各强自助BI分析工具也有这种功能，这种占比比数据源去处理比较困难，反正表格有这样功能的话，
使用体检会增强很多
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
https://s2.antv.vision/zh/docs/manual/basic/totals#2-%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%B9%E6%B3%95
建议使用自定义聚合函数的方式实现自定义汇总。

展示格式设置可以通过 `S2DataConfig.meta.formatter` 进行配置

https://s2.antv.vision/zh/docs/api/general/S2DataConfig#meta
