### ISSUE TITLE
🤔 How to copy selected rows (Vue 3)?

### ISSUE THREAD

**Issue by doraemonxxx** [antvis/S2#1651]
### 🖋 Description
Are there any docs to set up copy functionalities using **S2 vue 3**?
Currently, this is the docs about the copy function 
> https://s2.antv.vision/zh/docs/common/export/#%E5%8E%9F%E5%A7%8B%E5%AF%BC%E5%87%BA%E6%96%B9%E6%B3%95

### 😊 Expected Behavior
Select rows -> click CTRL + C /render a button to copy row/right click & copy select rows -> copy the data in CSV, xlsx, or json format.

### 😅 Current Behavior
I can't find any other relative docs or examples about the copy function

**Comment by lijinke666** [comment]
Currently, S2 does not support copying row/column headers, which will be supported in the future. ref https://github.com/antvis/S2/issues/1527
