### ISSUE TITLE
🤔 交叉表的行 横向滚动条如何去掉

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1658]
### 🖋 Description
![image](https://user-images.githubusercontent.com/46083022/183550878-387f7692-e7c9-4aa9-9b36-12291a228c15.png)
如何去掉行头的滚动条呢

**Comment by wjgogogo** [comment]
设置 `options`中的`frozenRowHeader`为`false`，参考[API文档](https://s2.antv.vision/zh/docs/api/general/S2Options)

**Comment by feEden** [comment]
> 设置 `options`中的`frozenRowHeader`为`false`，参考[API文档](https://s2.antv.vision/zh/docs/api/general/S2Options)
可是我需要 冻结行头啊 ，只是不需要滚动条。这里可以配置行头的最大宽度么
