### ISSUE TITLE
🤔drawRectBorder这个函数如何覆盖

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1662]
### 🖋 Description
想要重写表头表格的右边框颜色，如何处理

**Comment by lijinke666** [comment]
1. 建议通过配置 [主题](https://antv-s2.gitee.io/zh/docs/api/general/S2Theme#celltheme) 修改边框颜色
2. 如果非要自定义单元格, 需要你对源码有一定的了解, 且熟悉 Canvas 和 AntV/G

https://github.com/antvis/S2/blob/a07f3fb2b9ffbb4527132bb43389377550cd7081/packages/s2-core/src/cell/row-cell.ts#L225

```ts
import { RowCell } from '@antv/s2'

class CustomCell extends RowCell {
  drawRectBorder(){
    ...
    // 你自己的处理
  }
}

```

https://s2.antv.vision/zh/examples/gallery#category-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E5%85%83%E6%A0%BC

**Comment by yangxiaoguai132** [comment]
> 1. 建议通过配置 [主题](https://antv-s2.gitee.io/zh/docs/api/general/S2Theme#celltheme) 修改边框颜色
> 2. 如果非要自定义单元格, 需要你对源码有一定的了解, 且熟悉 Canvas 和 AntV/G
> 
> https://github.com/antvis/S2/blob/a07f3fb2b9ffbb4527132bb43389377550cd7081/packages/s2-core/src/cell/row-cell.ts#L225
> 
> ```ts
> import { RowCell } from '@antv/s2'
> 
> class CustomCell extends RowCell {
>   drawRectBorder(){
>     ...
>     // 你自己的处理
>   }
> }
> ```
> 
> https://s2.antv.vision/zh/examples/gallery#category-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E5%85%83%E6%A0%BC

这个例子中并没有drawRectBorder的例子
