### ISSUE TITLE
🤔 交叉表的行头横行滚动条，如何设置 能保持 在固定列的情况下，不出现滚动条

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1663]
### 🖋 Description
设置frozenRowHeader： false，没法固定行头，可不可以配置滚动条出现的最大宽度呢，或者有个开关，配置是否需要行头的横向滚动条

**Comment by wjgogogo** [comment]
@feEden 在固定行头时，如果行头的宽度超过了表格整体宽度的50%，才会出现滚动条，你可以减少行头的宽度，或者提供一个复现demo

**Comment by feEden** [comment]
> @feEden 在固定行头时，如果行头的宽度超过了表格整体宽度的50%，才会出现滚动条，所以你可以减少行头的宽度，通过拖拽或者行头宽度配置实现。

行头宽度配置 指的是配置这个50% 比例么？

**Comment by wjgogogo** [comment]
提供一个你的demo吧，我们根据你的demo给你一个调试结果

**Comment by feEden** [comment]
> 提供一个你的demo吧，我们根据你的demo给你一个调试结果

https://codesandbox.io/s/strange-silence-9dhxwg?file=/index.tsx
我想配置出的结果是，行头没有滚动条，然后锁定行头，另外，现在这种情况行头的滚动条 无法通过手势滑动，只能使用滚动条

**Comment by lijinke666** [comment]
> 现在这种情况行头的滚动条 无法通过手势滑动，只能使用滚动条

这是一个bug, 正在修复中 https://github.com/antvis/S2/pull/1664

> 行头没有滚动条，然后锁定行头

你可以通过配置滚动条的 [主题](https://antv-s2.gitee.io/zh/docs/api/general/S2Theme#scrollbartheme) 将滚动条的 size 设置为 `0`

```ts
const theme = {
    scrollBar: {
      size: 0,
      hoverSize: 0,
    },
}
```

![image](https://user-images.githubusercontent.com/21015895/183641798-c969eecb-fb1b-460c-b68b-a4c57eb15954.png)


这个是行头和数值的滚动条都会生效, 如果是只想对行头生效, 目前没有相关配置, 后续考虑支持, **或者欢迎 PR**
