### ISSUE TITLE
🤔 drawRectBorder 这个函数如何覆盖使用

### ISSUE THREAD

**Issue by yangxiaoguai132** [antvis/S2#1665]
### 🖋 Description
想要实现自定义的行头的单元格的样式，针对特定单元格处理，不是批量处理
找到了drawRectBorder这个函数，但是不会覆盖使用，文档中没有找到例子

**Comment by lijinke666** [comment]
参考 https://s2.antv.antgroup.com/examples/custom/custom-cell/#custom-specified-cell

继承 rowCell 基类, 复写 drawRectBorder 即可
