### ISSUE TITLE
🐛透视表总计列，叶子节点列宽无法手动调整

### ISSUE THREAD

**Issue by ab291478089** [antvis/S2#1668]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by ab291478089** [comment]
https://antv-s2.gitee.io/zh/examples/analysis/totals#multiple-values 就是多维度值的时候，总计的列宽无法手动调整

**Comment by lijinke666** [comment]
对于列头, 只有**叶子节点**可以调整宽度, 你发的这个示例, 总计列是根节点, 所以不存在什么 [总计的列宽无法手动调整] 的说法

![image](https://user-images.githubusercontent.com/21015895/184091278-fad36d25-cda9-46c1-be0a-bb30c7bc0071.png)

![image](https://user-images.githubusercontent.com/21015895/184091769-d5a7d02e-1b5f-49db-928d-c9d9d00b190b.png)


另外, 提交 issue 的时候请按照模板填写, 谢谢

**Comment by ab291478089** [comment]
我说的是叶子节点，图中的价格和成本的宽度是无法调整的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/S2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月11日(星期四) 下午4:16
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/S2] 🐛透视表总计列，列宽无法手动调整 (Issue #1668)





 
对于列头, 只有叶子节点可以调整宽度, 你发的这个示例, 总计列是根节点, 所以不存在什么 [总计的列宽无法手动调整] 的说法
 

 

 
另外, 提交 issue 的时候请按照模板填写, 谢谢

**Comment by lijinke666** [comment]
> 🐛透视表总计列，列宽无法手动调整

> 就是多维度值的时候，总计的列宽无法手动调整

哦, 那确实有问题, 那为什么不能一次性说清楚呢...
