### ISSUE TITLE
🤔替换列头排序svg图标问题, 代码不执行？帮忙看一下呗

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1670]
### 🖋 Description
这行代码为什么不执行呢？
codesandbox地址：https://codesandbox.io/s/antv-tou-bu-pai-xu-zxz5jf?file=/src/index.js
![1660189291056](https://user-images.githubusercontent.com/26482193/184061400-d551cb5c-c8e1-4b02-a454-f3119150bc1e.jpg)

**Comment by lijinke666** [comment]
headerActionIcons 是一个**数组**, 不是一个**对象**

```ts
  headerActionIcons: [
    {
      iconNames: ['customKingIcon'],
      belongsCell: 'colCell',
    },
  ],
```

![image](https://user-images.githubusercontent.com/21015895/184090370-7e8e2e60-c8fc-4bb6-b366-a79e9b950e5d.png)


文档已经写的很清楚了

![image](https://user-images.githubusercontent.com/21015895/184090529-c63db843-5662-4df4-b687-285688f90ed8.png)

建议使用 ts, 有类型提示, 避免这种低级错误

**Comment by dengyushuai** [comment]
> headerActionIcons 是一个**数组**, 不是一个**对象**
> 
> ```ts
>   headerActionIcons: [
>     {
>       iconNames: ['customKingIcon'],
>       belongsCell: 'colCell',
>     },
>   ],
> ```
> 
> ![image](https://user-images.githubusercontent.com/21015895/184090370-7e8e2e60-c8fc-4bb6-b366-a79e9b950e5d.png)
> 
> 文档已经写的很清楚了
> 
> ![image](https://user-images.githubusercontent.com/21015895/184090529-c63db843-5662-4df4-b687-285688f90ed8.png)
> 
> 建议使用 ts, 有类型提示, 避免这种低级错误

确实是低级错误啊，我找了好久，都没找到，感谢
