### ISSUE TITLE
🤔 vue3 sheetComponent 头部icon和说明文字不在同一行

### ISSUE THREAD

**Issue by LJKOJBK** [antvis/S2#1674]
### 🖋 Description
<img width="295" alt="image" src="https://user-images.githubusercontent.com/39849103/184084138-c83ca14c-aa94-458b-af92-1befc9d82778.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/39849103/184084181-6059bc70-9d76-4642-a95f-c3cec5dc9576.png">
![image](https://user-images.githubusercontent.com/39849103/184084249-84bbb486-85d3-4cda-bdda-4d1cce648c88.png)

package version
"@antv/s2": "^1.25.0",
"@antv/s2-vue": "^1.2.1",
"ant-design-vue": "^3.2.10"

### 😅 Current Behavior

头部tooltip的icon和文字换行显示了，vue3的一个项目，不知道是不是我全局样式冲突了，如果是的话能告诉我怎么调整s2这块的样式到同一行吗

**Comment by LJKOJBK** [comment]
第三张图没出来，就是只引入了@antv/s2-vue/dist/style.min.css，其他没写任何样式，就改了主题，其余的都是默认样式

**Comment by lijinke666** [comment]
> 不知道是不是我全局样式冲突了，如果是的话能告诉我怎么调整s2这块的样式到同一行吗

你自己审查一下元素不就好了?

**Comment by LJKOJBK** [comment]
> > 不知道是不是我全局样式冲突了，如果是的话能告诉我怎么调整s2这块的样式到同一行吗
> 
> 你自己审查一下元素不就好了?

哦哦，确实是样式冲突了，还以为这个tooltip也是绘制到canvas里的

**Comment by LJKOJBK** [comment]
感谢！
