### ISSUE TITLE
🐛明细表，conditions icon 里给字段有配置，但是该字段每条数据返回的icon为空，最后文字渲染异常

### ISSUE THREAD

**Issue by hu-zhangping** [antvis/S2#1681]
![1660276122018_A94378D2-B32D-4b8f-958D-7A0AF5E9D35C](https://user-images.githubusercontent.com/57650567/184287630-fd200eab-5a34-4774-bd14-025d8bc65bc0.png)

![image](https://user-images.githubusercontent.com/57650567/184287706-d6d52239-7a21-4783-b011-f770440af113.png)

**Comment by hu-zhangping** [comment]
![1660280369401_AEF539D3-ED93-484e-B745-2E3E42745661](https://user-images.githubusercontent.com/57650567/184287849-dc2180a3-b786-4947-9f0b-5f3913313658.png)

**Comment by wjgogogo** [comment]
@hu-zhangping 你的`cellData`是什么?

**Comment by hu-zhangping** [comment]
cellData就是每条数据对应的一些额外的配置

**Comment by wjgogogo** [comment]
@hu-zhangping 麻烦提供一下复现demo链接
