### ISSUE TITLE
Copying cells not working in firefox and cannot copy row headers🐛

### ISSUE THREAD

**Issue by ThamaluM** [antvis/S2#1690]
### 🏷 Version 1.26.0

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.26.0    |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

1. I cannot copy cell values in the Firefox browser. (Selecting the cells with mouse and Cntrl+C)
2. I cannot copy row/column headers in the Chrome browser (I can copy cell values).
3. The columns are copied without newline characters.
4. When I right-click after selecting cells, there is no copy option in the pop-up menu.

Note: 
Above 1: ```Uncaught ReferenceError: ClipboardItem is not defined``` 
It looks like Firefox and several other browsers do not support ClipboardItem object by default (https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem).

It may be helpful to you to mention that I used ```navigator.clipboard.writeText(S2.copyData(datasheet,'\t',true))```  instead of ```S2.copyToClipboard(data)``` to implement the copy button.

### ⌨️ Code Snapshots

```
   const segment_s2Options = {
        width: screen.width*10/12,
        height: screen.height*0.3,
        style: {
            layoutWidthType: 'colAdaptive'
        },
        interaction: {
            enableCopy: true,
            selectedCellsSpotlight: false,
            hoverHighlight: false,
            selectedCellHighlight: true
        }
}
```

**Comment by lijinke666** [comment]
The latest version has been fixed, use **sync** copy when `ClipboardItem` is not supported
