### ISSUE TITLE
🐛容器transform: rotate(90deg)旋转90度之后，表格滚动方向错误

### ISSUE THREAD

**Issue by Forever8** [antvis/S2#1695]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |   1.26.0   |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

容器css transform: rotate(90deg)旋转90度之后，滚动方向没有跟着旋转。

1，没有旋转之前，上下滑动，表格显示正常上下滚动。
2，旋转90度之后，上下滑动，表格显示左右滚动。

期望：旋转90之后，上下滑动，表格也上下滚动。

### ⌨️ Code Snapshots
<div id="app" style="transform: rotate(90deg)"></div>

const container = document.getElementById('app');
const s2 = new TableSheet(container, s2DataConfig, s2Options);
s2.render();

**Comment by lijinke666** [comment]
好奇旋转90°的场景是?

**Comment by Forever8** [comment]
> 好奇旋转90°的场景是?

比如在手机屏幕上横屏放大显示表格 : )

**Comment by lijinke666** [comment]
通过 css 来旋转目前表格是识别不到的, 不支持
