### ISSUE TITLE
🙏希望单元格具有图表表现能力

### ISSUE THREAD

**Issue by li379395535** [antvis/S2#1696]
### 🖋 Description
希望单元格具有图表表现能力，甚至能打通G2，在单元格上通过canvas.drawImage或者是么方式绘制图表
### 🏞 What problem does this feature solve
让图表显示更加多元化
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  chartType  |  string  |  -  |  表格类型  |
| data | Object[] | - | 表格数据 |

**Comment by wjgogogo** [comment]
ref: https://github.com/antvis/S2/pull/2437

**Comment by lijinke666** [comment]
目前 `1.x` 版本支持简单的 [mini 图绘制](https://s2.antv.antgroup.com/examples/custom/custom-cell/#mini-chart), `2.0` 版本支持[直接渲染 G2 图表](https://github.com/antvis/S2/pull/2437)
