### ISSUE TITLE
🐛【性能问题】官方示例 - 排序按钮越点越卡

### ISSUE THREAD

**Issue by Miantang** [antvis/S2#1713]
### 🖋 Description

官方示例
https://s2.antv.vision/zh/examples/analysis/sort#table-sort

“内置排序按钮”在多次点击之后，越来越卡，后续再也点击不动，最后直接crash

<img width="654" alt="image" src="https://user-images.githubusercontent.com/3156907/187118822-51c3d91a-0b83-430f-a549-3ad37944d6c0.png">

### 💻 System information

chrome 104
Mac Apple M1 Pro 12.3.1

**Comment by wjgogogo** [comment]
@Miantang 官网已经重新部署，你的问题应该已经解决

**Comment by serializedowen** [comment]
这个应该是上周的bug   合并下alpha就可以了
