### ISSUE TITLE
🐛透视表列头隐藏错误，当value多个时

### ISSUE THREAD

**Issue by Miantang** [antvis/S2#1721]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |    1.28   |
| @antv/s2-react |     1.28     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

使用列头隐藏时，隐藏某一个value列，所有value列都会被隐藏，并且没有了<img width="51" alt="image" src="https://user-images.githubusercontent.com/3156907/187619179-08caece2-b3b6-4a8b-a597-1e60e5e82bd6.png">按钮

<img width="637" alt="image" src="https://user-images.githubusercontent.com/3156907/187618717-6a35ee5e-7590-49f4-9ce7-6ecdf7fc5871.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/3156907/187619001-e815f56d-4caf-4711-b308-d8781f7f5261.png">

### 🔗 Reproduce Link
https://codesandbox.io/s/suspicious-wood-4py200?file=/index.tsx

### 😊 Expected Behavior

正常隐藏对应列

**Comment by 2256184693** [comment]
any solutions?

**Comment by Miantang** [comment]
@lijinke666 这个bug有修复预期不

**Comment by lijinke666** [comment]
已排期, 近期会修复
