### ISSUE TITLE
🐛表格在自动滚动状态下，如果被销毁，会报错

### ISSUE THREAD

**Issue by xuanxiaoxiao** [antvis/S2#1728]
官方【循环滚动】示例：https://s2.antv.vision/zh/examples/interaction/advanced#scroll-loop
（稍微改动一下，在示例代码中增加一个可以销毁表格的按钮）
当开启滚动状态时，如果销毁组件，会报一个死循环错误
![image](https://user-images.githubusercontent.com/57079772/188117577-1f15ba37-4fae-47a8-9d7c-d1ecedbb3767.png)

**Comment by xuanxiaoxiao** [comment]
正常情况下，在React单页应用程序内，如果页面中含有s2表格，并开启了自动滚动，那么切换到别的页面，即可发生报错

**Comment by lijinke666** [comment]
你应该在手动销毁或者路由改变时, 清除 clearInterval 计时器, 这是你业务逻辑应该做的处理, 和表格无关

```ts
React.useEffect(() => {
  return () => {
    clearInterval(yourScrollTimer)
  }
},[])
```
