### ISSUE TITLE
🙏 总计小计功能，期望支持不同指标设置不同的聚合方式

### ISSUE THREAD

**Issue by elephantme** [antvis/S2#1730]
### 🖋 Description
总计小计功能，期望支持不同指标设置不同的聚合方式

### 🏞 What problem does this feature solve
目前如果设置了总计小计的sum聚合方式，所有指标都是统一都是sum，期望可以不同指标设置不同的聚合方式。

### 🧐 Suggest the API

CalcTotals
|  name  |  type  | default  | description |
|----|----|----|----|
|  aggregationByField  |  Record<string, AggregationType>  |  -  |  其中record种的key就为field的唯一标识，该map可以为不同指标指定不同的聚合函数  |

另外，如果要自定义实现总计小计功能，目前的`calcFunc `，也是所有指标都共用该方法，其实也可以实现为根据字段来设置

CalcTotals
|  name  |  type  | default  | description |
|----|----|----|----|
|  aggregationByField  |  Record<string, calcFunc >  |  -  |  其中record种的key就为field的唯一标识，该map可以为不同指标指定不同的自定义的函数来处理  |

另外`calcFunc `的回调函数的参数，期望可以把行列交叉之后的数据结构返回（树形结构），这样自定义函数处理会方便好多。

**Comment by stone-lyl** [comment]
我理解你通过 “配置自定义方法”： https://s2.antv.vision/zh/docs/manual/basic/totals#1-%E9%85%8D%E7%BD%AE%E8%81%9A%E5%90%88%E6%96%B9%E5%BC%8F 
就可以实现

**Comment by xiaochong44** [comment]
@stone-lyl 这样使用不太友好，能类似ag-grid这样最好
columnDefs: [
        { field: 'country', rowGroup: true, hide: true },
        { field: 'year', rowGroup: true, hide: true }, 
        { field: 'gold', aggFunc: 'sum' },
        { field: 'silver', aggFunc: 'max' },
        { field: 'bronze', aggFunc: 'avg' },
    ],

**Comment by elephantme** [comment]
@xiaochong44 我的意思和你说的一样的，只需要把现在接口扩展为map结构就可以，底层的逻辑其实都已经实现了。 @stone-lyl  自定义方法我调研了，回调函数拿到的是最原始的二维表数据，难道自己再去做一次复杂的行、列交叉逻辑吗？这个也是我建议的回调函数期望可以返回交叉之后的树形结构数据

**Comment by elephantme** [comment]
总计小计功能在多维表格里使用频率也是很高的，现在不能给不同指标设置不同的聚合方式，使用起来确实很不方便。 @stone-lyl 期望再三斟酌一下~

**Comment by xiaochong44** [comment]
@elephantme 还有我提的行列占比功能，透视中很常用的操作，现在搞起来都非常复杂
