### ISSUE TITLE
react SheetComponent 导出界面异常🐛

### ISSUE THREAD

**Issue by lichia9527** [antvis/S2#1736]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |        1.29.0  |
| @antv/s2-react |      1.26.0    |
| @antv/s2-vue   |          |

### Sheet Type

- [ -] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
<SheetComponent
                  loading={loading}
                  adaptive={{ width: true, height: true }}
                  themeCfg={{ name: 'gray' }}
                  sheetType="pivot"
                  header={{
                    exportCfg: {
                      open: true,
                    },
                  }}
                />
如上，配置导出复制生效时，界面异常，菜单项一直存在无法关闭
![20220907145359](https://user-images.githubusercontent.com/17775060/188809438-e208a797-2386-407f-b944-c750b2145252.jpg)

**Comment by lijinke666** [comment]
antd 新版本 visible 属性变成了 `open`, 和 s2 的 `open` 重名了, 导致透传下去无法关闭
