### ISSUE TITLE
明细表使用总计和合计的配置没有效果，请问是不是只有透视表才能配置总计和合计？

### ISSUE THREAD

**Issue by sli-work** [antvis/S2#1737]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by lijinke666** [comment]
是的
