### ISSUE TITLE
🐛 透视表格使用空数据值初始化，再使用 setDataCfg 动态更新，数据显示不正确

### ISSUE THREAD

**Issue by iamdhj** [antvis/S2#1744]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.29.0     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

透视表格使用空数组 `values` 初始化后，再使用 setDataCfg 动态更新数据，表格数值显示不正确

### ⌨️ Code Snapshots

```
import { PivotSheet } from "@antv/s2";

const rootElement = document.getElementById("root");
const s2 = new PivotSheet(
  rootElement,
  {
    fields: { rows: [], columns: [], values: [] },
    data: []
  },
  { width: 800, height: 600 }
);
s2.render();

document.getElementById("value").addEventListener("click", () => {
  console.log("set values");
  s2.setDataCfg({
    fields: { rows: ["city"], values: ["price"], columns: [] },
    data: [{ city: "杭州", price: "1" }]
  });
  s2.render(true);
});
```

### 🔗 Reproduce Link

[重现地址](https://codesandbox.io/s/pivot-sheet-update-data-problem-jc71oi?file=/src/index.js)

### 🤔 Steps to Reproduce

1.点击 `set values` 按钮动态更新数据
2.发现表格渲染不正确

### 😊 Expected Behavior
使用 `setDataCfg` 动态更新数据，表格渲染和带数据初始化一致
![image](https://user-images.githubusercontent.com/6936831/189107563-315e8dbd-049e-4c77-973a-44d3281f8039.png)

### 😅 Current Behavior
![image](https://user-images.githubusercontent.com/6936831/189107402-7336eaa1-4c5f-4313-916a-76352afb1dad.png)

### 💻 System information
edge v105， windows 10

**Comment by lcx-seima** [comment]
使用 new 初始化时，你 values 是空，所以值被置于行头了 `valueInCols=false`
后面 setDataCfg 时，valueInCols 保持了原配置值。
所以，setDataCfg 的时候，显示设置一下即可 
```
s2.setDataCfg({
  fields: {
    rows: ["city"],
    values: ["price"],
    columns: [],
    valueInCols: true
  },
  data: [{ city: "杭州", price: "1" }],
});
```
