### ISSUE TITLE
🐛斑马纹 奇数行背景色 crossBackgroundColor 透视表正常明细表失效

### ISSUE THREAD

**Issue by zjs307065909** [antvis/S2#1748]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      ^1.25.0    |
| @antv/s2-react |     ^1.23.0     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
明细表奇数行背景色 crossBackgroundColor 不生效

**Comment by zjs307065909** [comment]
https://codesandbox.io/embed/solitary-bush-kkihqh?fontsize=14&hidenavigation=1&theme=dark

**Comment by YardWill** [comment]
这个目前仅支持透视表模式，急着用的话可以提PR参与共建。
