### ISSUE TITLE
🐛明细表当我自定义dataCell后，无法选中整行

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1758]
### 🏷 Version
 "@antv/s2": "1.29.1",
 "@antv/s2-react": "^1.18.0",

https://github.com/antvis/S2/discussions/1756

测试了下，明细表会出现这个问题

**Comment by Chasen-Zhang** [comment]
复现： https://codesandbox.io/s/happy-hooks-z0blij?file=/index.ts:864-881

**Comment by YardWill** [comment]
第一列需要extends TableSeriesCell，这里可以写个判断 index === 0 的时候 使用自定义的序列头 其他使用自定义dataCell

**Comment by Chasen-Zhang** [comment]
谢谢！
