### ISSUE TITLE
怎么能统一设置行高rowCfg

### ISSUE THREAD

**Issue by LMLGM** [antvis/S2#1760]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by LMLGM** [comment]
![image](https://user-images.githubusercontent.com/58587791/190956689-5eba7f1d-87df-40c7-a0b8-45185f4f960b.png)
是否支持统一设置行高，想给每一行设置相同的高度

**Comment by lijinke666** [comment]
![image](https://user-images.githubusercontent.com/21015895/192682100-528933ce-0e4b-4473-9961-13e294783d35.png)

https://s2.antv.vision/zh/docs/manual/advanced/custom/cell-size#%E8%B0%83%E6%95%B4%E6%95%B0%E5%80%BC%E5%8D%95%E5%85%83%E6%A0%BC%E5%AE%BD%E9%AB%98
