### ISSUE TITLE
🐛表格内有滚动条时，点击滚动条空白区域，表格内变为空白

### ISSUE THREAD

**Issue by flyfly6** [antvis/S2#1764]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.30.0     |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

表格内有滚动条时，点击滚动条空白区域，表格内变为空白，数据无法展示

### ⌨️ Code Snapshots

任意官网示例都可以复现该问题

### 🔗 Reproduce Link

https://s2.antv.vision/zh/examples/case/performance-compare#table

![bug](https://user-images.githubusercontent.com/2952657/190846933-847e6c03-3944-4de9-8359-27068bc5f732.gif)

### 🤔 Steps to Reproduce

表格内有滚动条时，点击滚动条空白区域，表格内变为空白，数据无法展示

### 😊 Expected Behavior

表格内有滚动条时，点击滚动条空白区域，表格滚动到对应位置

### 😅 Current Behavior

表格内变为空白，数据无法展示

### 💻 System information

Microsoft Edge
版本 105.0.1343.42 (正式版本) (arm64)
macOS  12.6

**Comment by flyfly6** [comment]
https://github.com/antvis/S2/blob/97e512404bd5d171c581a53c92d130ef15e9e907/packages/s2-core/src/ui/scrollbar/index.ts#L362-L370
看起来是这个点击滑道的事件回调中，offset 计算的不对，event 参数是个 GraphEvent，没有 offsetX 和 offsetY

**Comment by tobemaster56** [comment]
这个问题，非常影响体验，而且比较容易发生，希望能尽快修复

**Comment by Chasen-Zhang** [comment]
太影响体验了

**Comment by Fnxxxxo** [comment]
目前这个问题有修复计划么？非常容易发生，并且损坏当前页面的展示

**Comment by lijinke666** [comment]
ref #1780

**Comment by lijinke666** [comment]
这周修复
