### ISSUE TITLE
🐛点击明细表边缘处会使表格消失，必现

### ISSUE THREAD

**Issue by Chasen-Zhang** [antvis/S2#1780]
### 🏷 Version
点击红色区域，大概滚动条位置点击会使表格消失。点击滚动条不会
| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.30.0     |
| @antv/s2-react |     ^1.18.0     |

![image](https://user-images.githubusercontent.com/15354455/191184268-bb120f9a-1eb3-4b8b-a1bc-b4d538428826.png)

复现地址：https://s2.antv.vision/zh/examples/case/kpi-strategy#covid-trend

**Comment by tobemaster56** [comment]
重复的issue  #1764

**Comment by lijinke666** [comment]
ref https://github.com/antvis/S2/issues/1764

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/1785

**Comment by Chasen-Zhang** [comment]
@lijinke666 我们要生哪个版本呢，好像还没打tag

**Comment by lijinke666** [comment]
还没发布, 预计本周5.

**Comment by Chasen-Zhang** [comment]
> 还没发布, 预计本周5.

@lijinke666 大概什么时候发呢
