### ISSUE TITLE
🤔平铺模式小计不显示

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#1789]
### 🏷  S2-vue 1.3.0

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |  1.30.0        |
| @antv/s2-vue   |   1.3.0       |

### Sheet Type 

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

设置平铺模式后小计不显示，不知道什么原因，不知道如何下手去查，我看官网的例 子是正常的，我的配置如下
![image](https://user-images.githubusercontent.com/25057951/192673790-96298273-c37a-4b64-95ab-50a586d8f0f2.png)
![image](https://user-images.githubusercontent.com/25057951/192674034-21882ce4-9dfc-4f2e-8b8e-afdb01de7b57.png)
![image](https://user-images.githubusercontent.com/25057951/192674186-0f16f495-8d55-4105-8918-b2f4db567275.png)
![image](https://user-images.githubusercontent.com/25057951/192674285-94142558-bc52-4f1f-bd03-852aa5a75cef.png)

**Comment by wjgogogo** [comment]
![image](https://user-images.githubusercontent.com/17964556/205602986-875278d9-f059-4a54-b323-9e4e5ef5508e.png)
还需要配置`subTotalDimensions`
