### ISSUE TITLE
极简Data数据如何直接渲染表格🤔

### ISSUE THREAD

**Issue by GoldSubmarine** [antvis/S2#1806]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     latest     |
| @antv/s2-react |     x     |
| @antv/s2-vue   |    x      |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

[https://s2.antv.vision/zh/docs/api/general/S2DataConfig#data](https://s2.antv.vision/zh/docs/api/general/S2DataConfig#data)

我想要一个简单的详情表，但是数据量很大，如果后端返回

```json
[
  {
    "area": "东北",
    "province": "吉林",
    "city": "白山",
    "type": "办公用品",
    "subType": "纸张",
    "cost": "2",
  }
]
```

那传输的体积就会非常大，为了减小通信的体积，所以后端返回如下的格式

```json
[
  ["东北", "吉林", "白山", "办公用品", "纸张", "2"]
]
```

我注意到文档中接收的 Data 是第一种格式，有没有办法直接使用第二种格式的数据进行渲染呢？如果手动在前端将第二种格式转换成第一种，感觉开销还是挺大的。

**Comment by lijinke666** [comment]
不支持
