### ISSUE TITLE
过滤无法过滤 空字符串🐛

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/S2#1807]
### 🏷 Version
1.18.0

| Package      | Version |
| -------------- | --------- |
| @antv/s2-react |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🔗 Reproduce Link
S2Event.RANGE_FILTER

![image](https://user-images.githubusercontent.com/34603922/194694107-6be8a17a-ba2c-45bb-a73a-8552b8a84bcd.png)

**Comment by serializedowen** [comment]
可以先用customFilter来绕过。 待修复
