### ISSUE TITLE
🙏编辑表格支持拖拽填充值

### ISSUE THREAD

**Issue by serializedowen** [antvis/S2#1811]
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by serializedowen** [comment]
https://github.com/antvis/S2/tree/master/packages/s2-react/src/components/sheets/editable-sheet

**Comment by lcx-seima** [comment]
fixed #1858
