### ISSUE TITLE
🙏 序号列，不合并单元格

### ISSUE THREAD

**Issue by tobemaster56** [antvis/S2#1815]
### 🖋 Description
现在的序号列开启后，会出现单元格合并的情况
![image](https://user-images.githubusercontent.com/8998761/195326985-01bc78aa-f0c6-4647-a0ef-626fc6a9410e.png)

### 🏞 What problem does this feature solve
序号列不合并单元格，类似下图中的一样
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/8998761/195327221-99583195-d914-426f-bba9-b210328afeaa.png">

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by JayceXS** [comment]
请问下，你这个Big_region 这一列的单元格是怎么合并的 ？

**Comment by tobemaster56** [comment]
> 请问下，你这个Big_region 这一列的单元格是怎么合并的 ？

这个s2，透视表默认合并的单元格，没做啥配置

**Comment by wjgogogo** [comment]
ref: https://github.com/antvis/S2/pull/1966
