### ISSUE TITLE
🐛框选的时候如果滚动选中，超出一屏选中的数据不完整，onDataCellBrushSelection

### ISSUE THREAD

**Issue by shalalasha** [antvis/S2#1817]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.31.0    |
| @antv/s2-react |     1.24.0     |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
表格有30行数据，一屏显示10行数据，框选从第一行开始，往下滚动框选到20行，刷选api回调数据只有10行

**Comment by lijinke666** [comment]
确实有问题, 单元格是按需加载的, 移出可视范围后销毁了, 导致拿不到完整数据, 我们看看怎么处理
