### ISSUE TITLE
🐛透视表，列布局是 adaptive 时，开启 showSeriesNumber 后，空间足够的情况下，显示了滚动条

### ISSUE THREAD

**Issue by tobemaster56** [antvis/S2#1821]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     latest     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
透视表，列布局是 adaptive 时，开启 showSeriesNumber 后，空间足够的情况下，显示了滚动条

### 🔗 Reproduce Link
https://codesandbox.io/s/strange-currying-pn654x?file=/index.ts

### 😊 Expected Behavior
空间足够的情况下，不需要显示滚动条

**Comment by lijinke666** [comment]
> 空间足够的情况下，显示了滚动条

空间足够是如何定义的呢? 我看你的 demo 宽度 1000, 显示不下确实应该显示滚动条啊

![image](https://user-images.githubusercontent.com/21015895/196656444-b10097ac-d4de-439b-b8f8-9ced527ff601.png)

**Comment by tobemaster56** [comment]
>adaptive 应该减去序号列, 再进行自适应宽度计算, 始终在一屏展示，

我是这个意思
