### ISSUE TITLE
🐛 添加事件监听函数不生效

### ISSUE THREAD

**Issue by Claiyre** [antvis/S2#1823]
### 🏷 1.31.1

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |    1.31.1      |
| @antv/s2-react |  1.28.0        |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
拿到表格实例，添加事件（如下），点击若干单元格，没有任何反应

### ⌨️ Code Snapshots

![image](https://user-images.githubusercontent.com/18069718/195806881-d5df2e5d-e904-41c4-93b9-a4c4d2f545f4.png)

**Comment by lijinke666** [comment]
props 形式的也不生效? 

```tsx
<SheetComponent onGlobalClick={}/>
```

**Comment by lijinke666** [comment]
官网的文档有误, 抱歉, 后面会更新, SheetComponent 由于层层 forwardRef 的原因, 在 useEffect 时还拿不到实例 

s2-react 已经对 S2Event 进行了封装, 直接使用 props 即可 

https://s2.antv.vision/zh/docs/api/components/sheet-component#spreadsheetprops

```tsx
<SheetComponent onClick={} onActionIconClick={} />
```
