### ISSUE TITLE
🤔怎么让容器中表格的高度自适应

### ISSUE THREAD

**Issue by longchuxiong** [antvis/S2#1824]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.31.0     |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by longchuxiong** [comment]
`
const tableContainerRef = ref(null)
const s2Instance = ref(null)
const s2DataCfg = ref(null)
const s2Options = ref({
  width: 1200,
  height: 600
})

// 获取模拟数据
const getMockData = async () => {
  const data = await fetch('https://gw.alipayobjects.com/os/bmw-prod/2a5dbbc8-d0a7-4d02-b7c9-34f6ca63cff6.json')
  return await data.json()
}

// 表格自适应
const debounceRender = debounce((width, height) => {
  s2Instance.value.changeSheetSize(width, height)
  s2Instance.value.render(false) // 不重新加载数据
}, 50)
const resizeObserver = new ResizeObserver(([entry] = []) => {
  const [size] = entry.borderBoxSize || []
  debounceRender(size.inlineSize, size.blockSize)
})

onMounted(async () => {
  s2DataCfg.value = await getMockData()
  s2Instance.value = new PivotSheet(tableContainerRef.value, s2DataCfg.value, s2Options.value)
  s2Instance.value.render()
  // 通过监听 来实现监听窗口大小变化
  resizeObserver.observe(tableContainerRef.value)
})
`

![Snipaste_2022-10-17_09-24-26](https://user-images.githubusercontent.com/46107383/196070126-0977bf81-c15d-4b18-bdae-6084aae4ff1c.png)

**Comment by lijinke666** [comment]
替换成你容器的高度即可

```diff
- debounceRender(size.inlineSize, size.blockSize)
+ debounceRender(tableContainerRef.value.clientWidth, tableContainerRef.value.clientHeight)
```

可参考 s2-react 的实现方式
https://github.com/antvis/S2/blob/80cbf2060ac530e0edeae1f7adef7a56303f8723/packages/s2-shared/src/utils/resize.ts#L46-L55
