### ISSUE TITLE
🙏希望增加setDisplayDataSet方法，只针对显示的数据集进行设置

### ISSUE THREAD

**Issue by XDEcat-Geek** [antvis/S2#1826]
### 🖋 Description
目前在文档中只发现了getDisplayDataSet，获取显示数据集的方法，并没有设置数据集的方法。当我想要重新设置数据配置的时候，只能通过setDataCfg方法进行改变，但是我仅仅想要是改变数据部分，使用setDataCfg改变了其它部分，不是我所预期的。
### 🧐 Suggest the API
setDisplayDataSet
|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by wjgogogo** [comment]
`setOptions`中已经可以实现自定义`dataSet`了，参考：https://s2.antv.vision/zh/docs/api/general/S2Options中dataSet属性
