### ISSUE TITLE
🐛 文档中 SplitLine 透明度参数默认值错误

### ISSUE THREAD

**Issue by ONES-Liuzhang** [antvis/S2#1836]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.31.0     |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

文档中 `SplitLine.horizontalBorderColorOpacity` 和 `SplitLine.verticalBorderColorOpacity` 参数给出的默认值错误。

### ⌨️ Code Snapshots

`packages/s2-core/src/theme/index.ts`
![image](https://user-images.githubusercontent.com/18098458/196853990-f05725d4-c1b6-4311-87f2-acfe9add0120.png)

`s2-site/docs/api/general/S2Theme.zh.md`
![image](https://user-images.githubusercontent.com/18098458/196854059-aa03f269-d197-4830-8f0c-efc83a7cf786.png)

**Comment by lijinke666** [comment]
直接来个PR?

**Comment by ONES-Liuzhang** [comment]
> 
okk 👌
