### ISSUE TITLE
🐛趋势表格树级结构显示不了

### ISSUE THREAD

**Issue by shalalasha** [antvis/S2#1838]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |    1.32.0      |
| @antv/s2-react |  1 .24.0       |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
antv从1.29.0更新到1.32.0，原来的树级结构更新版本后显示不了，且通过api获取的子级的customtCell对象缺少txetShape，导致attr设置失败

**Comment by shalalasha** [comment]
利用react使用的gridAnalysis类型表格；该模板没找到

**Comment by xingwanying** [comment]
`gridAnalysis` 表格 demo https://s2.antv.vision/zh/examples/case/proportion#group-drill-down
`strategy` 趋势分析表格 https://s2.antv.vision/zh/examples/react-component/sheet#strategy

**Comment by xingwanying** [comment]
有无更详细的报错截图或者复现demo可以提供下么？

**Comment by shalalasha** [comment]
抱歉，涉及项目内容，暂无法提供，我可以试试demo编写

**Comment by shalalasha** [comment]
import React, { useState } from 'react';
import { SheetComponent } from '@antv/s2-react';
import '@antv/s2-react/dist/style.min.css';

class App extends React.Component{
  constructor(props){
    super(props);
    this.state = {
      s2DataConfig:{
        fields: {
          rows: ["row1", "row2"],
          columns: ["column1", "column2"],
          values: ["value"]
        },
        data: [
          {
            row1: 1,
            column1: "kk",
            column2: "kk2",
            value: 12
          },
          {
            row1: 1,
            column1: "高收入",
            column2: "高收入1",
            value: 11
          },
          {
            row1: 1,
            row2: 2,
            column1: "kk",
            column2: "kk2",
            value: 12
          },
          {
            row1: 1,
            row2: 2,
            column1: "高收入",
            column2: "高收入1",
            value: 11
          },
        ]
      }
    };
  }
  s2Options = {
    width: 800,
    height: 600,
    hierarchyType:'tree',
    conditions: {
    },
  };
  componentDidMount(){

  }

  render(){
    // console.log(this.state.s2DataConfig);
    // console.log(this.s2Options);
    return <SheetComponent
              dataCfg={this.state.s2DataConfig}
              options={this.s2Options}
              sheetType="gridAnalysis"
            />
  }
}
export default App;

备注：antv/s2 1.29.0和1.31.0表现不一样；getPanelGroupAllDataCells没测试

**Comment by lijinke666** [comment]
![image](https://user-images.githubusercontent.com/21015895/198178461-dc8def5f-3a83-4b80-bdcf-79cb2e2f9c9c.png)

没懂你要干什么
