### ISSUE TITLE
🐛 明细表 自定义行头 textAlign, 文字出现错位

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1851]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.33.0     |
| @antv/s2-react |     1.30.0     |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [-] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

```
class CustomTextColCell extends ColCell {
  getTextStyle() {
    const textStyle = super.getTextStyle();
    const { text } = super.getStyle();

    const { meta } = this.spreadsheet.dataCfg;
    // @ts-ignore
    const { align } = meta.find(({ field }) => field === this.meta.field) ?? {};

    text.textAlign = "right";

    return textStyle;
  }
}
```
自定义行头，文字错位，如图所示
![image](https://user-images.githubusercontent.com/46083022/197974713-2c2c9ff2-9c47-4d04-8200-6b81e2d9f7df.png)

### ⌨️ Code Snapshots
https://codesandbox.io/s/competent-wescoff-zpod3h?file=/index.ts

**Comment by GaoFuhong** [comment]
这儿是列头居左、居右存在问题，我们排期修一下。

**Comment by GaoFuhong** [comment]
列头文本位置是在 getStyle 中设置哈，你这儿 ```return text``` 就好了。
