### ISSUE TITLE
🐛table形态下字段标记会对colcell也生效

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#1855]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.33.0    |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
![image](https://user-images.githubusercontent.com/15276351/198234765-4d114bd7-f050-474f-977d-3300155870d6.png)

应该是 #1809 ，但table和pivot下colcell 的field不一样导致的

![image](https://user-images.githubusercontent.com/15276351/198234514-cf6c7c79-3b3b-4aed-aeb1-ed123a3563ad.png)

**Comment by xingwanying** [comment]
condition hook mapping函数里， 根据 col id 把colCell 过滤即可

**Comment by xingwanying** [comment]
类似这个demo 
https://s2.antv.vision/zh/examples/analysis/conditions#text

```ts
          {
            field: 'type',
            mapping(field) {
              if (field === '类别') {
                return {
                  fill: '#327039',
                };
              }
            },
          },
```
