### ISSUE TITLE
🐛 多维度下对列总计下的字段排序，排序结果错误

### ISSUE THREAD

**Issue by feEden** [antvis/S2#1857]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |     1.33.0     |
| @antv/s2-react |     1.30.0     |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
![image](https://user-images.githubusercontent.com/46083022/198245858-ccd7d0ac-1158-4c71-b363-440d3cb870a7.png)
如图所示，对总计下的子类别进行排序，结果数量的值出现在了子类别下，对数量就行排序不会有这个问题

### ⌨️ Code Snapshots
https://codesandbox.io/s/pensive-kare-e39mnu?file=/index.tsx

**Comment by stone-lyl** [comment]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/20497176/199417611-acd62648-c860-4543-aa84-b93fad123e11.png">
还有，我记得总计，小计是没有支持排序的啊 😂

**Comment by stone-lyl** [comment]
这个问题在 next 版本中已被修复，但现在 next 尚不稳定
