### ISSUE TITLE
🐛 style.colCfg.hideMeasureColumn 开启后，当有多个值的时候，值只显示了一个

### ISSUE THREAD

**Issue by tobemaster56** [antvis/S2#1864]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |       latest   |

### Sheet Type

- [x] PivotSheet

### 🖋 Description
当列有多个值的时候，style.colCfg.hideMeasureColumn 不开启的时候

![image](https://user-images.githubusercontent.com/8998761/199379662-019515bb-ed95-433a-a17d-9ce32dcac5fd.png)

style.colCfg.hideMeasureColumn 开启之后，只显示了第一个值
![image](https://user-images.githubusercontent.com/8998761/199379769-2922e20d-181b-4acd-b9b8-b085477734cc.png)

### 🔗 Reproduce Link
https://codesandbox.io/s/rough-leaf-0f3mr1

**Comment by lijinke666** [comment]
`hideMeasureColumn` 只适用于单数值的场景, 并不是 bug, 设计如此, 这里文档需要完善一下.

多数值会有多列, 而父级节点又只有一个, 就像你发的图一样, 隐藏后已经没有多余的空间展示其他列了, 对于你这种场景, 更适合用 [隐藏列头](https://s2.antv.vision/manual/advanced/interaction/hide-columns#2-%E9%80%8F%E8%A7%86%E8%A1%A8)
