### ISSUE TITLE
可否让透视表支持实现一个配置，使行维度呈现不分组状态（类似明细表）

### ISSUE THREAD

**Issue by C-Echo** [antvis/S2#1866]
现在的透视表行维度下，会自动将维度分组，像树一样，能否支持增加一个配置，开启的时候，让行维度显示状态呈现成一条一条的，目的是：有需求是需要将指标全排序，而非普通的组内排序或按最值排序

**Comment by qiaogaolong** [comment]
这个问题有解决了么，比如省市，浙江 杭州和浙江 舟山 默认不合并

**Comment by LeeSSHH** [comment]
我们也是有这个需求，求实现

**Comment by jack484** [comment]
我也有这个需求 求实现呀

**Comment by xuanxiaoxiao** [comment]
这个需求我已经实现了，具体代码就不给了，关键是一个思路。
合并单元格的核心逻辑，是值相同，比如 浙江-杭州 和 浙江-宁波，俩浙江是相同的，自然就合并了。想让他不合并，那你叫不一样的就好了，比如 浙江1-杭州，浙江2-宁波。这就不会合并了，也是这个需求的核心思路。
当然，用户是不能看到 浙江1和浙江2的，所以这里需要一些小技巧：让后端做一个唯一的只有前端知道的字符串，然后在前端渲染时给他去掉

**Comment by lijinke666** [comment]
解决思路可以参考: https://github.com/antvis/S2/issues/2767#issuecomment-2164209195
