### ISSUE TITLE
🐛version 1.33.0 版本详情表 鼠标滚动 报错，望尽快修复

### ISSUE THREAD

**Issue by guizhichao** [antvis/S2#1868]
🏷 Version 1.33.0

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/24600605/199431178-37335609-a2bc-4862-8052-389b601d30a8.png">

**1.33.0版本有问题，详情表报错，望尽快修复。。**

1.31.0 版本没这个问题

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by serializedowen** [comment]
辛苦提供一下复现途径

**Comment by guizhichao** [comment]
> 辛苦提供一下复现途径

https://codesandbox.io/s/jolly-goodall-9hsw1q?file=/src/index.js

**Comment by stone-lyl** [comment]
> https://codesandbox.io/s/jolly-goodall-9hsw1q?file=/src/index.js

无法复现，麻烦提供一下复现步骤

![image](https://user-images.githubusercontent.com/20497176/199638389-f43093ec-d866-4862-9143-8229fc8fb72a.png)

**Comment by guizhichao** [comment]
>  不好意思，我提了两个，链接被覆盖了，现在好了

https://codesandbox.io/s/priceless-pateu-5nrwmx?file=/src/index.js

**Comment by guizhichao** [comment]
> 
再试下呢，1.33.0 版本 详情表格鼠标滚动的时候会报错

**Comment by guizhichao** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/24600605/199656571-674079d1-236c-4b99-bbc7-0869837c7685.png">

**Comment by stone-lyl** [comment]
你多包了一层数组，导致的报错了。你的配置太混乱了，也很容易导致其他问题
<img width="401" alt="image" src="https://user-images.githubusercontent.com/20497176/199663266-dac3a2cc-1371-41a3-8741-027ec8118f7d.png">

**Comment by guizhichao** [comment]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/24600605/199664738-3875e25f-cb66-43cf-8947-10653225f82c.png">



> 
不是这个导致的啊，为啥1.32.0版本好的啊，到1.33.0就不行了呢。而且我们也是参考你们官方文档做的呀，是个二维数组

**Comment by guizhichao** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/24600605/199665372-44b09e4b-c3cd-4f4d-83a1-fdb99253bdea.png">

**Comment by stone-lyl** [comment]
> 不是这个导致的啊，为啥1.32.0版本好的啊，到1.33.0就不行了呢。而且我们也是参考你们官方文档做的呀，是个二维数组

我这边弄错了，以为是mergeCells 的格式问题。
是因为主题没有适配 mergeCells ，你使用 1.33.0 版本，可以先把 mergedCellInfo 的相关的配置去掉。
下个版本中会修复这个问题。

**Comment by guizhichao** [comment]
> > 不是这个导致的啊，为啥1.32.0版本好的啊，到1.33.0就不行了呢。而且我们也是参考你们官方文档做的呀，是个二维数组
> 
> 我这边弄错了，以为是mergeCells 的格式问题。 是因为主题没有适配 mergeCells ，你使用 1.33.0 版本，可以先把 mergedCellInfo 的相关的配置去掉。 下个版本中会修复这个问题。
好的，感谢🙏，我本地回滚到1.32.0版本了
