### ISSUE TITLE
🤔矩阵式报表：1.  总计、小计  开启序号时，最后一行边框样式问题     2. 边框为啥不对齐,错位（行与表格主体样式不对齐）

### ISSUE THREAD

**Issue by guizhichao** [antvis/S2#1869]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/24600605/199449551-05eb6728-7a59-4a0c-a499-511d36d70ebd.png">

**在线地址：** https://codesandbox.io/s/jolly-goodall-9hsw1q?file=/src/index.js

### 🏷 Version 1.33.0

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |  1.33.0         |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

**Comment by guizhichao** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/24600605/199450653-8b696aa4-8a1c-4588-962c-5e653d834771.png">

**Comment by wjgogogo** [comment]
ref: https://github.com/antvis/S2/pull/1854
