### ISSUE TITLE
🙏 希望透视表列头在垂直滚动时可以配置阴影

### ISSUE THREAD

**Issue by ONES-Liuzhang** [antvis/S2#1870]
### 🖋 Description

希望透视表列头在垂直滚动时可以支持配置阴影

不太理解为啥 Frame 类绘制了行头阴影并支持配置，但是在垂直滚动时没有阴影，也不支持配置，是否有什么冲突的场景？
文件位置：packages/s2-core/src/facet/header/frame.ts
![image](https://user-images.githubusercontent.com/18098458/199638544-c161edcf-bb88-492a-8ad2-60a545319bc7.png)

目前调用时的实现方式是继承了 Frame 类，重写了 layout：
![image](https://user-images.githubusercontent.com/18098458/199638947-33f2eaa4-1007-4537-8d15-d71b86201548.png)

效果如下：
<img width="606" alt="image" src="https://user-images.githubusercontent.com/18098458/199639039-b659ffcc-5483-4d5a-aa8d-6cf121efaa71.png">

### 🏞 What problem does this feature solve
透视表在垂直滚动时有需要列头固定底部展示 shadow 的需求，这应该算是常见需求，但目前没有提供配置方式，在实现时需要阅读源码，有一定的心智负担，希望可以提供配置

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by lcx-seima** [comment]
后续在 next 版本中添加

**Comment by lcx-seima** [comment]
hi：
不好意思，经过与设计师商讨，并参考了 ant-design [table 设计](https://ant.design/components/table-cn#components-table-demo-fixed-columns-header)，S2 决定保留当前的阴影模式，不会添加上下的阴影。
另外欢迎贡献你的自定义代码，到文档 demo 区域，以帮助更多的人。
