### ISSUE TITLE
🙏 透视表多指标数值时隐藏列头的能力

### ISSUE THREAD

**Issue by godblesscwp** [antvis/S2#1872]
### 🖋 Description

透视表多指标数值时隐藏列头的能力 
e.g. 
![image](https://user-images.githubusercontent.com/33439817/199673762-1d0e5f43-bec2-4b5f-b2ea-8b582696d706.png)

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by lijinke666** [comment]
现已支持
![image](https://user-images.githubusercontent.com/21015895/216563692-8e75545e-8bb0-433f-866e-f50284e9b8fc.png)
