### ISSUE TITLE
🐛我在drawTextShape中使用两次addShape添加了两个文案，但是输出this发现this里只能取到其中一个文案的信息

### ISSUE THREAD

**Issue by p-al-ace** [antvis/S2#1873]
"@antv/s2": "^1.18.0"

详细复现步骤联系：qq2192798424

**Comment by stone-lyl** [comment]
亲，需要提供在线demo。我们才能基于帮助哦，如果涉及敏感数据，可以mock 数据，提供最小复现demo

**Comment by lvisei** [comment]
> "@antv/s2": "^1.18.0"
> 
> 详细复现步骤联系：qq2192798424

https://juejin.cn/pin/7157723705555189790
