### ISSUE TITLE
数据单元格自定义渲染问题

### ISSUE THREAD

**Issue by HuYong66** [antvis/S2#1875]
s2-react 
我想在数据单元格加一个按钮，怎么自定义渲染啊？文档里只看到一个背景色的示例

**Comment by HuYong66** [comment]
具体

> 目前是不支持 react node的渲染的，如果想增加按钮，需要用 g 绘制 UI，监听事件的方式来实现。 g 的使用可以参考 https://g.antv.vision/zh/docs/guide/introduce

具体实现还是继承DataCell ，重写方法吗？

**Comment by xingwanying** [comment]
> 具体
> 
> > 目前是不支持 react node的渲染的，如果想增加按钮，需要用 g 绘制 UI，监听事件的方式来实现。 g 的使用可以参考 https://g.antv.vision/zh/docs/guide/introduce
> 
> 具体实现还是继承DataCell ，重写方法吗？

对的，可以继承initCell方法，增加一个drawButton 方法，调用下，类似👇

```ts
 protected initCell() {
    super.initCell();
    this.drawButton();
  }

protected drawButton() {
  xxx
}
```
