### ISSUE TITLE
🤔树级配置问题

### ISSUE THREAD

**Issue by shalalasha** [antvis/S2#1879]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |          |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
<img width="611" alt="image" src="https://user-images.githubusercontent.com/31689651/200218304-aa102780-5a55-4f93-a940-74c1f2a6875a.png">
我想在途中画红线部分显示数据，该怎么配置？

**Comment by lcx-seima** [comment]
该部分数据对应行小计
请多参阅官方 demo 
https://s2.antv.vision/zh/examples/analysis/totals#tree

**Comment by shalalasha** [comment]
如果我的数据不是数值，是字符串，该怎么做？
