### ISSUE TITLE
🤔 使用 Conditions 时，interval类型支持修改柱状图高度吗

### ISSUE THREAD

**Issue by simpleAndElegant** [antvis/S2#1894]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/41931905/200818628-d4ed8bbd-126b-4af5-bc6e-d912bc0f4729.png">

**Comment by xingwanying** [comment]
https://s2.antv.vision/en/docs/api/general/S2Theme#celltheme

![image](https://user-images.githubusercontent.com/10885578/201016044-50862080-1b94-4bb0-a47a-bf9f21e758bc.png)
