### ISSUE TITLE
🐛  字段标记自定义svg无法修改颜色

### ISSUE THREAD

**Issue by jzb1205** [antvis/S2#1898]
### 🏷 Version

| Package      | Version |
| -------------- | --------- [|](url)
| @antv/s2       |   1.3.1    | 
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
自定义svg无法修改颜色
![img_v2_a1805c5d-dae1-4c80-93c8-c2568770aabg](https://user-images.githubusercontent.com/25791239/201294110-757412b8-f643-48d6-9a3a-2053e19b6192.jpg)

### 🤔 Steps to Reproduce

         import { PivotSheet, Node } from '@antv/s2';
        
        fetch(
          'https://gw.alipayobjects.com/os/bmw-prod/cd9814d0-6dfa-42a6-8455-5a6bd0ff93ca.json',
        )
          .then((res) => res.json())
          .then((res) => {
            const container = document.getElementById('container');
            const s2DataConfig = {
              fields: {
                rows: ['province', 'city'],
                columns: ['type', 'sub_type'],
                values: ['number'],
              },
              meta: res.meta,
              data: res.data,
            };
            const s2Options = {
              width: 600,
              height: 480,
              customSVGIcons: [
                {
                  name: 'customKingIcon',
                  svg: 'https://gw.alipayobjects.com/zos/bmw-prod/f44eb1f5-7cea-45df-875e-76e825a6e0ab.svg',
                },
              ],
              // 使用刚定义的 icon
              conditions: {
                icon: [
                  {
                    field: 'number',
                    position: 'right',
                    mapping(value) {
                      return {
                        icon: 'customKingIcon',
                        fill: '#2498D1'
                      }
                    }
                  }
                ]
              }
            };
            const s2 = new PivotSheet(container, s2DataConfig, s2Options);
        
            // 使用
            s2.render();
          });

**Comment by ab291478089** [comment]
这个bug还没有修复嘛

**Comment by ab291478089** [comment]
我在codesandbox试着和本地都不行呢 https://codesandbox.io/s/7ndckq

> This feature is effective in codesandbox and local environment but not work in S2 Site online example editor.
> 
> upd: even I run yarn site:start and latest deployment of pr, it works, too!
> 
> cc @lijinke666 @lcx-seima
> 
> Maybe this issue can be closed

**Comment by tyr1dev** [comment]
> 我在codesandbox试着和本地都不行呢 [codesandbox.io/s/7ndckq](https://codesandbox.io/s/7ndckq)
> 
> > This feature is effective in codesandbox and local environment but not work in S2 Site online example editor.
> > upd: even I run yarn site:start and latest deployment of pr, it works, too!
> > cc @lijinke666 @lcx-seima
> > Maybe this issue can be closed

你用的 SVG 的 fill 不能写死，需要是 currentColor，这是 SVG 基础。
示例中的 SVG 中的 fill 是写死数值的🥲

**Comment by tyr1dev** [comment]
![localhost_3000_](https://github.com/antvis/S2/assets/56076317/56ef693a-c907-4ddc-9a24-92827499b5dc)

**Comment by ab291478089** [comment]
> > 我在codesandbox试着和本地都不行呢 [codesandbox.io/s/7ndckq](https://codesandbox.io/s/7ndckq)
> > > This feature is effective in codesandbox and local environment but not work in S2 Site online example editor.
> > > upd: even I run yarn site:start and latest deployment of pr, it works, too!
> > > cc @lijinke666 @lcx-seima
> > > Maybe this issue can be closed
> 
> 你用的 SVG 的 fill 不能写死，需要是 currentColor，这是 SVG 基础。 示例中的 SVG 中的 fill 是写死数值的🥲

 你的意思就是在svg中写死的fill就不做处理了呗  那你告诉我conditions那里icon的fill配置的意义何在？

**Comment by lijinke666** [comment]
颜色动态修改只对字符串和本地文件有效, 在线链接不支持
