### ISSUE TITLE
🤔透视表和明细表默认开启分页组件

### ISSUE THREAD

**Issue by ab291478089** [antvis/S2#1912]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.26及以上      |
| @antv/s2-react |   1.24及以上      |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
1.26版本及以上透视表和明细表分页组件会默认开启，即使没有配置，亲测1.25版本是正常的。

### 🔗 Reproduce Link
https://codesandbox.io/s/lucid-morning-pwixyp?file=/index.tsx

**Comment by lijinke666** [comment]
你不是自己打开了这个配置吗? 不是很明白

![image](https://user-images.githubusercontent.com/21015895/203959163-1fc64cd2-5e04-4d86-add5-bd4c4a4d4763.png)

**Comment by lijinke666** [comment]
![image](https://user-images.githubusercontent.com/21015895/204069727-03bac4f4-4352-40e5-9ef0-8140eeca1577.png)
