### ISSUE TITLE
🤔 树状模式透视表的选择复制功能有提上日程吗？

### ISSUE THREAD

**Issue by mmmml-zhao** [antvis/S2#1941]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.34.1    |
| @antv/s2-react |    1.31.0     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在使用树状模式透视表时，选择单元格复制，发现并没有内容，查看源码发现复制功能在树状模式透视表下没有实现，通过注释639到642行，在树状模式透视表下是可以正常复制的（测试了选择行/列/框选单元格三种复制），所以现在在树状模式透视表下复制功能是有什么隐性的bug吗？只有这一种情况不能复制，感觉很奇怪啊。
![image](https://user-images.githubusercontent.com/25151442/203518890-97f060ff-6327-4216-995c-7a98be7358fa.png)

### 🔗 Reproduce Link

https://github.com/antvis/S2/blob/838d2d3ce614975e15472b97161ab8b7c7c89ffc/packages/s2-core/src/utils/export/copy.ts#L639

### 😊 Expected Behavior
树状模式透视表可以选择复制。
### 😅 Current Behavior
树状模式透视表选择后无法复制内容。

**Comment by lijinke666** [comment]
@stone-lyl 看看是不是可以放开限制了

**Comment by stone-lyl** [comment]
> @stone-lyl 看看是不是可以放开限制了

这个我最近评估一下
