### ISSUE TITLE
🙏表格，详情表没数据显示一行空数据，希望支持加入图标么比如像antd table 的暂无数据

### ISSUE THREAD

**Issue by guizhichao** [antvis/S2#1946]
### 🖋 Description
希望支持加入图标么比如像antd table 的暂无数据，否则现在感觉很奇怪
_链接如下：_  https://codesandbox.io/s/magical-diffie-4hif7t?file=/index.ts

<img width="679" alt="image" src="https://user-images.githubusercontent.com/24600605/203787240-f8c5f9f9-b314-4e92-abfa-cd014bb0885c.png">

### 🏞 What problem does this feature solve
类似于这种  https://codesandbox.io/s/4rzw9l?file=/demo.tsx
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/24600605/203788031-f5c5a1c1-9a11-4a4b-943a-fcb3ed707a00.png">

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by guizhichao** [comment]
要不然没法区分到底是1条空数据，还是没有数据

**Comment by lijinke666** [comment]
欢迎 PR
