### ISSUE TITLE
🐛配置自定义主题时，调整列高度与预期不符合

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/S2#1949]
### 🏷 Version
https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-schema
官方地址，最新版本
配置自定义主题之后，调整列高度有问题
详情可以点击操作一下即可

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.34.0     |
| @antv/s2-react |   1.32.0      |
| @antv/s2-vue   |         |

### Sheet Type

明细表

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

调整除表头的列高度，调整的高度与表格最终列的高度不一致，有明显的UI错误
https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-schema
![image](https://user-images.githubusercontent.com/34603922/203945765-8033e96a-1d82-4f9c-9964-56d4308ebc8a.png)

### ⌨️ Code Snapshots

https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-schema

### 🔗 Reproduce Link

https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-schema
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
> 详情可以点击操作一下即可

怎么操作? 你代码怎么写的? 预期是什么? 你贴一个官网链接没什么意义, 配置的 cellCfg 和实际的渲染不同?

**Comment by fanyongchao01** [comment]
麻烦 仔细阅读issue内容并仔细操作一下官网示例，我并没有改动什么代码

**Comment by xingwanying** [comment]
![Kapture 2022-11-28 at 11 19 10](https://user-images.githubusercontent.com/10885578/204184809-4d484856-9264-449f-9605-2aaadf8291d6.gif)

如图，在明细表格配置过自定义主题后，高度拉高为单元格两倍，但是实际生效高度不足原始两倍
