### ISSUE TITLE
🐛enableCopy bug

### ISSUE THREAD

**Issue by Malcn** [antvis/S2#1955]
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.34.0      |

### Sheet Type

- [ ] PivotSheet
### ⌨️ Code Snapshots
            interaction: {
                selectedCellsSpotlight: true,
                hoverHighlight: false,
                enableCopy: true
            },
           style: {
                colCfg: {
                    hideMeasureColumn: true
                }
            }
### 🔗 Reproduce Link

https://codesandbox.io/s/goofy-goldstine-brwhki?file=/index.ts

**Comment by lijinke666** [comment]
所以具体是什么问题呢？亲亲麻烦说清楚一点

**Comment by Malcn** [comment]
复现步骤：
1. enableCopy开启
2.设置hideMeasureColumn为true
3.刷选数据操作，ctrl+c 数据没有到粘贴板，并且有时报错
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/20159170/205000980-12c9be1f-2d58-4abc-8797-5bf79a287321.png">
