### ISSUE TITLE
🐛Windows下Shift+滚动横向滚动失效（Mac下正常）

### ISSUE THREAD

**Issue by haoqi0818** [antvis/S2#1958]
### 🏷 Version

1.33.0

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.33.0      |
| @antv/s2-react |  1.30.0       |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

Windows下Shift+滚动，无法实现横向滚动（在Mac下正常）

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     windows 10    |
| Browser |     chrome   |

**Comment by lijinke666** [comment]
fixed: https://github.com/antvis/S2/pull/1956
