### ISSUE TITLE
🐛列分组调整表头高度bug

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#1987]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 1.35.1        |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
表头分组调整表头高度存在bug,无法按鼠标移动的距离自动调整高度
![GIF 2022-12-9 13-32-05](https://user-images.githubusercontent.com/25057951/206631584-ba055608-a535-4d5e-a08d-90f6271e38f2.gif)

**Comment by lijinke666** [comment]
2.0 版本已修复
