### ISSUE TITLE
🤔折叠图标不显示；报出：GuiIcon Minus load error；（我的项目是内网）

### ISSUE THREAD

**Issue by dengyushuai** [antvis/S2#1991]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 1.36.0    |
| @antv/s2-react | 1.33.0        |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [X] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

我的项目是内网，无法访问外网；表格数据都没有问题，但是我使用了树结构(两个配置项为：hierarchyType: ‘tree’; sheeType: ‘gridAnalysis’;)，树结构的折叠图标不显示，报出：GuiIcon Minus load error。不知道这样描述您能不能理解，能不能告诉我该怎么解决？谢谢

### 🔗 Reproduce Link

内网提供不了连接，谢谢

**Comment by dengyushuai** [comment]
是不是我缺少什么依赖呢？

**Comment by dengyushuai** [comment]
> 你好@dengyushuai，很挽回给你带来了不好的体验，我们会尽快排查问题并修复，请关注后续发布日志。
> 
> 你好，@dengyushuai, 给您带来不好的体验，我们深表歉意。我们将尽快排除故障并解决问题。请关注后续变更日志。

谢谢。但是我感觉应该不是你们的问题，应该是我缺少什么东西吧

**Comment by wjgogogo** [comment]
如果可以，还是需要尽量提供复现链接，或者截图之类的

**Comment by dengyushuai** [comment]
> 如果可以，还是需要尽量提供复现链接，或者截图之类的

链接可能是提供不了了，到时候我看看能不能拍照吧。（正常单位是不让拍照的）

**Comment by dengyushuai** [comment]
> > 如果可以，还是需要尽量提供复现链接，或者截图之类的
> 
> 链接可能是提供不了了，到时候我看看能不能拍照吧。（正常单位是不让拍照的）

**Comment by wjgogogo** [comment]
并非是要你拍真实的数据，你可以将数据层面全部用假数据mock, 配置保持不变。就可以在codesandbox这样的平台测试了

**Comment by dengyushuai** [comment]
> 并非是的的数据一样的问题，那么就说明确实是s2的问题，否则需要你排查自己的平台代码是不是有什么影响

好的，谢谢了

**Comment by astragier** [comment]
@dengyushuai how did you solve your error please? I encounter the same one.
