### ISSUE TITLE
点击行（actvie状态）能不触发背景色改变吗🤔

### ISSUE THREAD

**Issue by alanPan931215** [antvis/S2#1999]
点击行（actvie状态）能不触发背景色改变吗
![feedback](https://user-images.githubusercontent.com/33088096/207799530-ded53795-88b8-445f-8b5d-a84c11c53f67.png)

**Comment by alanPan931215** [comment]
点击行头的时候那一行会加透明样式，是否有参数控制不添加，会与我选中背景色变化有冲突

**Comment by stone-lyl** [comment]
你可以使用 theme 配置单元格选中时的颜色。
demo 调试： https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-manual-palette
文档：https://s2.antv.antgroup.com/manual/basic/theme
