### ISSUE TITLE
next 版本中，icon 随缘出现？🐛

### ISSUE THREAD

**Issue by stone-lyl** [antvis/S2#2014]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.3   |
| @antv/s2-react |   2.0.0-next.3    |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
![bug-随缘出现的icon](https://user-images.githubusercontent.com/20497176/209105505-0e7a4047-3994-414d-9168-91d356afc8b1.gif)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by Create-Peace** [comment]
这个问题解决了吗？透视表树结构折叠展开按钮也是遇到这个问题了

**Comment by lijinke666** [comment]
> 这个问题解决了吗？透视表树结构折叠展开按钮也是遇到这个问题了

已知问题, 是底层渲染引擎 G 的问题, 之前修复过, 现在又能复现了, 跟进处理中.

**Comment by lijinke666** [comment]
https://github.com/antvis/G/pull/1637
