### ISSUE TITLE
🐛有内容的单元格多时，交叉表copyData速度很慢，可能导致浏览器崩溃

### ISSUE THREAD

**Issue by Bernicechl** [antvis/S2#2031]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  官网版本  |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

有内容的单元格多时，交叉表copyData速度很慢，可能导致浏览器崩溃。
如数据呈现对角线分布，则copyData很快，但如果是散落在各处或者内容较多时，速度大幅下降。

通过测试，发现有内容的单元格数较多时
| 单元格数        | copyData执行时间 |
| -------------- | ------- |
| 1万       |  3.23s  |
| -------------- | ------- |
| 3万       |  17.029s  |
| -------------- | ------- |
| 8万       |  67.085s  |
| -------------- | ------- |
| 32万       |  422.164s  |
| -------------- | ------- |
### 🤔 Steps to Reproduce

调用copyData，传入实例，计算耗时
### 😊 Expected Behavior

希望
1.提升速度，如果短期内无法提升速度，那还请尽快帮忙排查下原因，便于我们做下一步安排，感谢～
2.将此部分内容转移到web worker中操作，避免页面卡死

### 😅 Current Behavior
速度过慢，可能导致浏览器无响应或直接崩溃

**Comment by Bernicechl** [comment]
您发给我的信件已经收到。

**Comment by stone-lyl** [comment]
`copyData` 过慢，是因为行列数据过多，在 copy 过程中会嵌套遍历行头、列头。
需要优化代码，后续会在 `next` 分支中进行优化，欢迎持续关注。
如果想规避这个问题，可以考虑自己进行数据转换，实现复制。

**Comment by stone-lyl** [comment]
在这个PR 中，已经对交叉表模式的导出做了性能优化：https://github.com/antvis/S2/pull/2152
<img width="537" alt="image" src="https://user-images.githubusercontent.com/20497176/232979256-ed5d61fd-a96b-4d1e-b44e-7222b3f824e8.png">

web work 的改进将会在后续的 PR中改进

**Comment by Bernicechl** [comment]
您发给我的信件已经收到。
