### ISSUE TITLE
🙏 行头固定占比 50% 希望可以调整

### ISSUE THREAD

**Issue by zjs307065909** [antvis/S2#2042]
### 🖋 Description

![5c5a46c294ba8eb42784478ed7af0ced](https://user-images.githubusercontent.com/113426325/211710161-d05b75e1-2371-4367-85f5-c37eb99ff10a.png)
这个占比最大50%希望可以进行调整
### 🏞 What problem does this feature solve

希望可以进行调整占比
### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
欢迎 PR

**Comment by lijinke666** [comment]
ref #2142
