### ISSUE TITLE
🐛 开启指标行列转换valueInCols: false 后，当有两个指标，且列上有两个维度的时候，开启列总计，列总计行高异常

### ISSUE THREAD

**Issue by liran19960215** [antvis/S2#2049]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |  1.5.0   |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
开启指标行列转换valueInCols: false 后，当有两个指标，且列上有两个维度的时候，开启列总计，列总计行高异常
![image](https://user-images.githubusercontent.com/65275407/212260886-b90a132f-f351-461a-9a9d-4fe2d788c179.png)

### ⌨️ Code Snapshots
```javascript
import { PivotSheet } from '@antv/s2';

fetch(
  'https://gw.alipayobjects.com/os/bmw-prod/6eede6eb-8021-4da8-bb12-67891a5705b7.json',
)
  .then((res) => res.json())
  .then((data) => {
    const container = document.getElementById('container');
    const s2DataConfig = {
      fields: {
        rows: ['province'],
        columns: ['city','type'],
        values: ["price", "cost"],
        valueInCols: false,
      },
      meta: [
        {
          field: 'province',
          name: '省份',
        },
        {
          field: 'city',
          name: '城市',
        },
        {
          field: 'type',
          name: '商品类别',
        },
        {
          field: 'price',
          name: '价格',
        },
        {
          field: 'cost',
          name: '成本',
        },
      ],
      data,
    };

    const s2Options = {
      width: 600,
      height: 480,
      selectedCellsSpotlight: true,
      hoverHighlight: true,
      tooltip: {
        showTooltip: true,
      },
      interaction: {
        enableCopy: true,
      },
      // 配置小计总计显示
      totals: {
        row: {
          showGrandTotals: true,
          showSubTotals: true,
          reverseLayout: true,
          reverseSubLayout: true,
          subTotalsDimensions: ['province'],
        },
        col: {
          showGrandTotals: true,
          showSubTotals: true,
          reverseLayout: true,
          reverseSubLayout: true,
          subTotalsDimensions: ['type'],
        },
      },
      style: {
        colCfg: {
          hideMeasureColumn: false,
          widthByFieldValue: {},
        }
  },
    };
    const s2 = new PivotSheet(container, s2DataConfig, s2Options);

    s2.render();
  });
```

### 🤔 Steps to Reproduce
1、打开官网网页 [https://antv-s2.gitee.io/zh/examples/analysis/totals#multiple-values](https://antv-s2.gitee.io/zh/examples/analysis/totals#multiple-values)
2、使用上述代码替换链接页面代码即可复现：
![image](https://user-images.githubusercontent.com/65275407/212260531-4ffbc472-fec1-4482-8e91-971f427499b3.png)

### 😊 Expected Behavior
开启指标行列转换valueInCols: false 后，当有两个指标，且列上有两个维度的时候，列总计高度应该是两行的高度

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lcx-seima** [comment]
感谢反馈。试了下，确实有 bug，我们会排期修复。

另外可以试用 https://s2.antv.antgroup.com/ 来访问新官网

**Comment by lijinke666** [comment]
这个我在处理了, 和 #1715 是同一个问题
