### ISSUE TITLE
🤔透视表渲染10万行数据、5个维度行的case，渲染很慢，要十几秒

### ISSUE THREAD

**Issue by tyang-dev** [antvis/S2#2050]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.29.0    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

透视表渲染10万行，5个维度行的case，渲染很慢几乎要十几秒，而且表格处于卡顿不可用状态。

### 🔗 Reproduce Link

https://s2.antv.antgroup.com/examples/case/performance-compare#pivot

**复制下方代码到上面链接即可**

`import { PivotSheet } from '@antv/s2';

const s2Options = {
  width: 600,
  height: 480,
  pagination: {
    pageSize: 100,
    current:1
    },
};

let fiveNum = 0

function getNum(n) {
    return Math.floor(Math.random() * n) 
}

export function generateRawData(row, col) {
  const res = [];
  const rowKeys = Object.keys(row);
  const colKeys = Object.keys(col);

  for (let i = 0; i < row[rowKeys[0]]; i++) {
    for (let j = 0; j < row[rowKeys[1]]; j++) {
      for (let m = 0; m < col[colKeys[0]]; m++) {
        for (let n = 0; n < col[colKeys[1]]; n++) {
          res.push({
            province: `p${i}`,
            city: `c${j}`,
            type: `type${getNum(200)}`,
            subType: `subType${n}`,
            thirdType: `thirdType${getNum(50)}`,
            fourType: `fourType${getNum(39)}`,
            fiveType: `fiveType${(fiveNum++)%110}`,
            number: i * n,
          });
        }
      }
    }
  }

  return res;
}

const s2DataConfig = {
  fields: {
    rows: ['type', 'subType', 'thirdType', 'fourType', 'fiveType'],
    columns: ['province', 'city'],
    values: ['number'],
  },
  data: generateRawData(
    { province: 10, city: 30 },
    { type: 10, sub_type: 30 },
  ),
};
const container = document.getElementById('container');

const s2 = new PivotSheet(container, s2DataConfig, s2Options);

const start = Date.now()

s2.render();

console.log({
    time: Math.floor(( Date.now() -  start) / 1000),
    leng: s2.getRowLeafNodes().length
});`

### 😊 Expected Behavior

请问这种case还能优化吗

**Comment by lcx-seima** [comment]
维度多了确实有慢的问题，主要是内部那部分排序花的时间，目前 master 版本短时间比较难解。
我们会在 next 分支的版本上来重构解决。
