### ISSUE TITLE
🤔 请问如何让列头文字换行

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#2059]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.19.0      |
| @antv/s2-react |    1.17.0     |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

<img width="304" alt="截屏2023-01-28 12 37 51" src="https://user-images.githubusercontent.com/37238/215242335-b149a203-83a3-48e3-a389-f8f6cab2cea7.png">

如上图所示，列头文字比较多，在移动端的话，显示不了几个字。
想以多行显示，请问如何做到？

### 😊 Expected Behavior

列头能多行显示文本

**Comment by wangwufan** [comment]
我也有这个诉求

**Comment by lijinke666** [comment]
目前不支持换行, 新版在开发中, 会内置换行能力

如急需换行, 需要分词, 自行计算文字宽度和坐标, 进行文字的绘制, 可参考 corner cell 的逻辑
https://github.com/antvis/S2/blob/f3945ba317bacf126793f408c4c14adb3a8038c8/packages/s2-core/src/cell/corner-cell.ts#L145

**Comment by KuduroJS** [comment]
> 

可以透露一下大概的新版时间吗

**Comment by KuduroJS** [comment]
> 目前不支持换行, 新版在开发中, 会内置换行能力
> 
> 如急需换行, 需要分词, 自行计算文字宽度和坐标, 进行文字的绘制, 可参考 corner cell 的逻辑
> 
> https://github.com/antvis/S2/blob/f3945ba317bacf126793f408c4c14adb3a8038c8/packages/s2-core/src/cell/corner-cell.ts#L145

可以透露一下大概的新版时间吗

**Comment by ArleneShine** [comment]
> > 目前不支持换行, 新版在开发中, 会内置换行能力
> > 如急需换行, 需要分词, 自行计算文字宽度和坐标, 进行文字的绘制, 可参考 corner cell 的逻辑
> > https://github.com/antvis/S2/blob/f3945ba317bacf126793f408c4c14adb3a8038c8/packages/s2-core/src/cell/corner-cell.ts#L145
> 
> 可以透露一下大概的新版时间吗

同问新版发布时间

**Comment by lijinke666** [comment]
多行文本 2.0 版本支持 https://github.com/antvis/S2/pull/2383, 发布时间待定, 预计年底

**Comment by lijinke666** [comment]
resolved #2383
