### ISSUE TITLE
🙏数据透视表在只有行头或者列头的时候显示具体的表格数据

### ISSUE THREAD

**Issue by WeilinerL** [antvis/S2#2060]
### 🖋 Description

**数据透视表**在只有行头或者列头的时候不显示具体的表格数据：
![image](https://user-images.githubusercontent.com/52592562/215397445-c7678d61-7404-40aa-8f97-3fb3fb20a65c.png)

而对于**数据明细表**来说，则可以正常显示：
![image](https://user-images.githubusercontent.com/52592562/215397528-4a892aa6-9db9-4e34-b5ff-38cdcf46e4a3.png)

### 🏞 What problem does this feature solve

希望在**透视表**只有行头或者列头的时候也显示相应的数据（类似**明细表**）

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
> 希望在透视表只有行头或者列头的时候也显示相应的数据（类似明细表）

透视表的设计就是必须要数值, 你这个是错误的用法
