### ISSUE TITLE
🐛官网使用文档主题配置中预置主题色板对照表对应 schema 的 key不对

### ISSUE THREAD

**Issue by quitelxd** [antvis/S2#2068]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.41.0  |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在官网使用文档中->基础教程->主题配置->预置主题色板对照表中的 "对应 schema 的 key" 列，

"数据单元格鼠标选中态背景填充色" 对应 schema 的 key "dataCell.interactionState.selected.backgroundColor"
实际应为 "dataCell.cell.interactionState.selected.backgroundColor"。
不止一处由此问题，例如 "数据单元格鼠标悬停聚焦态背景填充色" 等。
![image](https://user-images.githubusercontent.com/23647844/217449170-cf4e62e5-fabd-4db7-b217-6eeab5b1f49e.png)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
感谢反馈, 直接来一个 PR ?
