### ISSUE TITLE
🐛文档链接失效

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/S2#2070]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

 [FAQ](https://s2.antv.vision/manual/faq#s2-%E6%9C%89%E5%AF%B9%E5%BA%94%E7%9A%84-vue-%E6%88%96%E8%80%85-angular-%E7%89%88%E6%9C%AC%E5%90%97)中的『分析组件』链接指向404

![图片](https://user-images.githubusercontent.com/30228406/217742353-02d0d5c7-bc96-4371-96e3-dbe1fedae6b0.png)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
直接来一波 PR ?
