### ISSUE TITLE
🤔请问如何知道单元格编辑完成？

### ISSUE THREAD

**Issue by one-god** [antvis/S2#2071]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |       1.41.0  |
| @antv/s2-react |     1.36.0    |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
![image](https://user-images.githubusercontent.com/25094341/218401264-1fc6be44-4fd8-4a46-a3e4-981164dd26b3.png)

我该怎么知道单元格是否编辑完成，我想编辑完成后，更改其他数据比如：统计这一列的数据和
### 🔗 Reproduce Link

https://s2.antv.antgroup.com/examples/case/data-preview/#excel

**Comment by one-god** [comment]
有人知道吗？

**Comment by serializedowen** [comment]
是希望透出一个类似edit success的事件吗？

**Comment by serializedowen** [comment]
> 有人知道吗？

是希望透出一个类似edit success的事件吗？

**Comment by one-god** [comment]
> > 有人知道吗？
> 
> 是希望透出一个类似edit success的事件吗？
是的

**Comment by one-god** [comment]
> > 有人知道吗？
> 
> 是希望透出一个类似edit success的事件吗？

@serializedowen 你知道怎么操作吗？我查看文档好久，没有找到
