### ISSUE TITLE
🙏 支持配置单元格合并后的样式

### ISSUE THREAD

**Issue by helianthuswhite** [antvis/S2#2077]
### 🖋 Description
目前S2提供的单元格合并配置只有单元格的行列及meta信息，无法修改合并后单元格的样式。从源码上看目前合并的单元格也是直接使用的dataCell的配置。

我的需求是在单元格合并之后取第一个单元格的样式，如下图斑马线样式中合并后背景色应该是深色的。

![image](https://user-images.githubusercontent.com/12878076/219533157-79582d5b-84af-41f1-b27a-acbf123d5d17.png)

### 🏞 What problem does this feature solve
使单元格合并后的样式更加灵活，满足更多样式上的定制化需求。

### 🧐 Suggest the API
可以在`dataCell.cell`配置中新增`mergedBackgroundColor`、`mergedBorderColor`等与`cellTheme`类似的配置。这样可以支持到整个表格的合并单元格样式可定制且统一。

个人感觉不需要将改配置支持到具体的某一个合并单元格中，如果有人有这样的需求，可以将配置项加入到`mergedCellInfo`中，取`mergedCellInfo[]`中的第一项的配置为合并后的样式。

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
感觉你已经有思路了, 尝试直接来一个 PR?

**Comment by helianthuswhite** [comment]
PR可以的，不过在想有没有更好的解决方式。
我们的场景是使用S2来实现BI平台中的透视表，需要能够将表格的样式配置细化到每一个单元格，目前看S2的主要配置只能对corner、row、column以及data等块级内容统一设置样式。
另外看到可以使用Conditions来细化具体单元格的样式，不知道能否满足我们的业务需求，需要尝试一下。

如果Conditions也无法满足设置单一单元格样式的话，那可能就得考虑是否要重新设计S2的样式配置，比如通过以下方式来指定具体行列样式：
```js
s2.setTheme({
    //  若只有行，则设置一整行的样式，只有列为设置整列样式，行列都有时为指定单元格的样式
    colIndex: 1,
    rowIndex: 2,
    ...
})
```

这可是个非常大的改动了:neutral_face:

**Comment by stone-lyl** [comment]
合并后的单元格，我们使用 `MergedCell` 代表的： packages/s2-core/src/cell/merged-cell.ts
现在 mergedCell 的样式配置，是和 DataCell 共用的同一套主题，你可以新增一些配置，将他们分离。
![image](https://user-images.githubusercontent.com/20497176/221848042-93f2358e-de09-4f8f-95dc-ea8f5a30635f.png)

**Comment by GaoFuhong** [comment]
建议自定义合并单元格。

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/examples/custom/custom-cell/#custom-merged-cell
