### ISSUE TITLE
🐛vue版本大数据时卡顿

### ISSUE THREAD

**Issue by hbyhby** [antvis/S2#2078]
vue版本大数据时卡顿

### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.41.0      |
| @antv/s2-react |    1.36.0     |
| @antv/s2-vue   |    1.5.0     |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
vue版本大数据情况卡顿

1.vue版本中，数据过多时，页面更新延迟。 hooks-> useResize. s2Ref 的 deep watch 导致
2. hooks 对应地址 antvis/S2/packages/s2-vue/src/hooks/useResize.ts
### ⌨️ Code Snapshots

```
 watch(
    [s2Ref, () => props.adaptive],
    ([s2, adaptive], _, onCleanup) => {
      if (!s2) {
        return;
      }
      unobserve.value = createResizeObserver({
        s2,
        adaptive,
        wrapper: dom.wrapperRef.value!,
        container: dom.containerRef.value!,
      });

      onCleanup(() => {
        unobserve.value?.();
      });
    },
    { deep: true },
  );
```

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by hbyhby** [comment]
不好意思没有外部链接，但是感觉这块是不合理的对SpreadSheet实例做 deep watch。vue3 deep watch 在其他属性改变时会对监控数据为数组的监控做递归遍历，导致之后的其他属性改动都会因为这个数据量过大而导致延迟 --粗略看了下。

**Comment by lcx-seima** [comment]
这个地方应该不影响(s2外层是shallowref)，如果频繁变动 useResize 里应该会执行多次吧。目前我本地看没发现这样的现象。

**Comment by hbyhby** [comment]
你好，我这边看不是deep会多次执行，是deep引起的数组递归扫描。



因为deep的数据是个数组，所以会递归扫描去做watch。只要页面有其他ref或reactive变更就回引发递归扫描。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/S2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/S2] 🐛vue版本大数据时卡顿 (Issue #2078)





 
这个地方应该不影响(s2外层是shallowref)，如果频繁变动 useResize 里应该会执行多次吧。目前我本地看没发现这样的现象。

**Comment by hbyhby** [comment]
我加下文件名称：
vue 的runtime-core。中&nbsp;doWatch方法。
用的是github下的开发版，&nbsp;vue:playground&nbsp; &nbsp; &nbsp;&nbsp;http://localhost:5050/ 测试。


traverse 代码







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hby"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上7:35
***@***.***&gt;;

主题:&nbsp;回复： [antvis/S2] 🐛vue版本大数据时卡顿 (Issue #2078)



你好，我这边看不是deep会多次执行，是deep引起的数组递归扫描。



因为deep的数据是个数组，所以会递归扫描去做watch。只要页面有其他ref或reactive变更就回引发递归扫描。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "antvis/S2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/S2] 🐛vue版本大数据时卡顿 (Issue #2078)





 
这个地方应该不影响(s2外层是shallowref)，如果频繁变动 useResize 里应该会执行多次吧。目前我本地看没发现这样的现象。
