### ISSUE TITLE
🤔 请问有办法只根据数据区域的行列索引 获取到对应的单元格数据/信息吗

### ISSUE THREAD

**Issue by liran19960215** [antvis/S2#2079]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.41.0  |
| @antv/s2-react |         |
| @antv/s2-vue   |  1.5.0  |

### Sheet Type

&#9745; PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![image](https://user-images.githubusercontent.com/65275407/219541070-d0def23a-7cde-4e84-991a-ebe8793a5d42.png)
点击图中1.5这个单元格时，可以通过提供的dataCellClick方法获取到单元格的meta信息（如下图所示），里面包含其行列索引值rowIndex、colIndex.
![image](https://user-images.githubusercontent.com/65275407/219541296-c250e2f7-d8d7-4122-ba0c-4e4a8bb76e0b.png)
那么请问现在支持仅仅根据行列索引值rowIndex、colIndex反推得到其对应单元格的meta或者data信息吗？
例如现在仅仅知道rowIndex=3、colIndex=3，可以定位到图中1.5对应的单元格吗？有相关的api提供吗？

感谢！

### 😊 Expected Behavior
希望可以仅通过行列索引值直接得到对应的单元格meta/数据信息

**Comment by lijinke666** [comment]
支持的, 文档有一点缺失, 后续完善一下

```ts
s2.facet.layoutResult.getCellMeta(rowIndex, colIndex)
```

https://s2.antv.antgroup.com/manual/advanced/get-cell-data#%E8%8E%B7%E5%8F%96%E6%8C%87%E5%AE%9A%E5%8C%BA%E5%9F%9F%E5%8D%95%E5%85%83%E6%A0%BC

![image](https://user-images.githubusercontent.com/21015895/219563045-ec3de609-3aa6-4cc7-b76b-b55687e725ad.png)

**Comment by liran19960215** [comment]
> 支持的, 文档有一点缺失, 后续完善一下
> 
> ```ts
> s2.facet.layoutResult.getCellMeta(rowIndex, colIndex)
> ```
> 
> https://s2.antv.antgroup.com/manual/advanced/get-cell-data#%E8%8E%B7%E5%8F%96%E6%8C%87%E5%AE%9A%E5%8C%BA%E5%9F%9F%E5%8D%95%E5%85%83%E6%A0%BC
> 
> ![image](https://user-images.githubusercontent.com/21015895/219563045-ec3de609-3aa6-4cc7-b76b-b55687e725ad.png)

收到 感谢！

**Comment by liran19960215** [comment]
收到 感谢！
