### ISSUE TITLE
🤔 请问有什么办法可以获取到某一列/行的所有数据单元格的meta信息吗

### ISSUE THREAD

**Issue by liran19960215** [antvis/S2#2080]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.41.0  |
| @antv/s2-react |         |
| @antv/s2-vue   | 1.5.0  |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![image](https://user-images.githubusercontent.com/65275407/219584695-9dc847c1-0619-46dc-bc1b-fee007e8e6e4.png)
如官网文档所示，提供了如何获取行列单元格的数据，但是目前我想获取的是单元格的元数据meta信息。
后续想做的操作是从meta中取到colIndx、rowIndex，从而可以得到某一个单元格相邻或者间隔的单元格信息，进行计算。

所以想请问下，能不能根据某种query 返回所有的数据单元格meta 而非data信息，求相关的API
感谢！

### 😊 Expected Behavior
获取某一行/列的所有数据单元格的meta元信息。

**Comment by lijinke666** [comment]
使用问题建议提交到讨论区 https://github.com/antvis/S2/discussions

这些 api 还不够吗? 里面都有 rowIndex  colIndex , 你自己去过滤一次应该就好了吧, 建议看完文档先多尝试一下再提问

![image](https://user-images.githubusercontent.com/21015895/219614666-af2d57f2-0991-4f83-802f-f6d1373e2bbf.png)

**Comment by liran19960215** [comment]
官方的api文档我肯定是看了的 第二个红框里的问题是没有办法获取到非可视区域的数据单元格 行列交互获取到的是该行/列的所有的单元格数据信息（不管是不是在可视区域） 而非meta信息 所以目前没有办法获取到该行/该列的所有meta信息  包括getAllCells获取的也是可视区域的

**Comment by liran19960215** [comment]
首先抱歉问题提问错了地方 官方的api文档我肯定是看了的 第二个红框里的问题是没有办法获取到非可视区域的数据单元格 而时s2.dataSet.getMultiData行列交互获取到的是该行/列的所有的单元格数据信息（不管是不是在可视区域） 而非meta信息 所以目前没有办法获取到该行/该列的所有meta信息  包括s2.interaction.getAllCells获取的也是可视区域的

**Comment by lijinke666** [comment]
> 第二个红框里的问题是没有办法获取到非可视区域的数据单元格

每个单元格对应一个 `DataCell` 实例, 由于表格是虚拟滚动, 所以只会渲染可视区域的单元格, 非可视区域的单元格都没有渲染, 所以肯定是取不到的, 但行头和列头是全量已渲染的, 即 `rowNodes`, `colNodes`, 通过行列头对应的索引反推到数值单元格的索引, 然后就能拿到非可视区域的单元格

> 是从meta中取到colIndx、rowIndex，从而可以得到某一个单元格相邻或者间隔的单元格信息

也许你可以考虑先用可视范围的 `dataCell` , 先找到它所对应的行头和列头的索引, 然后你可以参考下, 结合滚动刷选这里的代码, 通过已知的 rowIndex 和 colIndex, 去动态的实例化一下 `DataCell`

```ts
import { DataCell } from '@antv/s2'

const viewMeta = s2.facet.layoutResult.getCellMeta(rowIndex, colIndex);
const cell =  new DataCell(viewMeta, this.spreadsheet);
```

https://github.com/antvis/S2/blob/c912294ba36b2133be9228178c0b9e25bf918d69/packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts#L134-L151
