### ISSUE TITLE
@antv/s2-react  SheetComponent 数据内容复制有误

### ISSUE THREAD

**Issue by ldlnovel** [antvis/S2#2091]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     ^1.41.0    |
| @antv/s2-react |     ^1.36.0    |

### Sheet Type

- [x] SheetComponent

### 🖋 Description
```
import { SheetComponent } from '@antv/s2-react';
<SheetComponent
dataCfg={
  fields:[{'key1', 'key2'}],
  meta:[{field:'key1', name:'a'},field:'key2', name:'a'}],
 data:[{'key1':1,'key2':2}]
}
options={{
 interaction: {
     enableCopy: true,
     copyWithHeader: true,
}}
/>
```
![image](https://user-images.githubusercontent.com/28532288/220577001-6b20e73c-c272-4eaf-bd12-ca23b675edcc.png)
使用鼠标左键选中复制的时候只能复制出第一列
![image](https://user-images.githubusercontent.com/28532288/220577309-0fd2be2d-221e-4b76-95f1-4c1314237a1f.png)
通过选中表头也只能复制出第一列数据

**Comment by ldlnovel** [comment]
SheetComponent 表头有两列名称一样（field不一样），复制两列数据，只复制出了第一列，这个有办法解决吗

**Comment by stone-lyl** [comment]
你使用 Ctrl + C 和右键复制一样都只有一列数据？
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/20497176/221846340-c71b2bec-586c-48a7-afc3-de6f2b7654fc.png">
我使用 官方的demo 进行复制，没有你这个问题，建议给复现demo

**Comment by ldlnovel** [comment]
![image](https://user-images.githubusercontent.com/28532288/222026623-4530f0aa-3f2b-405d-a954-2d6ad21afc7d.png)

```
import React from 'react';
import ReactDOM from 'react-dom';
import { SheetComponent } from '@antv/s2-react';
import '@antv/s2-react/dist/style.min.css';

fetch('https://assets.antv.antgroup.com/s2/basic-table-mode.json')
  .then((res) => res.json())
  .then((res) => {
    const s2Options = {
      width: 600,
      height: 480,
      interaction: {
      enableCopy: true,
      copyWithHeader: true,
      }
    };

    const s2DataConfig = {
      fields: {
        columns: ['key1', 'key2'],
      },
      meta: [
        {
          field: 'key1',
          name: 'a',
        },
        {
          field: 'key2',
          name: 'a',
        },
      ],
      data: [
      {'key1':1,'key2':2}
      ],
    };

    ReactDOM.render(
      <SheetComponent
        dataCfg={s2DataConfig}
        options={s2Options}
        sheetType="table"
       
      />,
      document.getElementById('container'),
    );
  });
```

麻烦帮忙看一下

**Comment by stone-lyl** [comment]
> 

复制这块会在 2.0.0 next 中进行重构，会同时处理这个问题。
现在 1.XX.X 的问题暂时 pending 了，如果比较着急，可能需要您进行共建了😂
