### ISSUE TITLE
🐛next鼠标移出交互效果还在

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#2115]
| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.5        |
| @antv/s2-react |  2.0.0-next.5       |
| @antv/s2-vue   |  2.0.0-next.5       |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

鼠标移动表格，交互效果没有消失
![GIF 2023-3-10 13-19-49](https://user-images.githubusercontent.com/25057951/224230268-1e115ca2-cf86-4239-9458-5e1fa753b111.gif)

**Comment by lcx-seima** [comment]
现在还有问题吗，我自己用鼠标、键盘好像都没有复现。你那个 tooltip 是怎么配置的。

**Comment by xiaochong44** [comment]
> 现在还有问题吗，我自己用鼠标、键盘好像都没有复现。你那个 tooltip 是怎么配置的。

我没有任何配置，就是直接启动的源码里的playground，我现在用next6试一下

**Comment by xiaochong44** [comment]
> 现在还有问题吗，我自己用鼠标、键盘好像都没有复现。你那个 tooltip 是怎么配置的。

问题依旧呀，奇怪我是在windows环境下运行的，总不会和mac有差异吧

**Comment by xiaochong44** [comment]
> 现在还有问题吗，我自己用鼠标、键盘好像都没有复现。你那个 tooltip 是怎么配置的。

https://codesandbox.io/s/nervous-sanderson-mzfqot?file=/src/App.vue
看这个例 子，鼠标从下方移出透视表，十字交叉的效果还在

**Comment by xiaochong44** [comment]
> 现在还有问题吗，我自己用鼠标、键盘好像都没有复现。你那个 tooltip 是怎么配置的。
![image](https://user-images.githubusercontent.com/25057951/233829078-e7bdc00a-34d6-4a2a-94df-3c4deb9dc4f9.png)

我有调试过上面那个地方一直是true

**Comment by lijinke666** [comment]
fixed #2181

**Comment by xiaochong44** [comment]
@lcx-seima 还有问题
https://codesandbox.io/s/brave-cerf-l11fob?file=/src/App.vue
