### ISSUE TITLE
🤔合并单元格, 无法自定义合并后单元格值

### ISSUE THREAD

**Issue by szjSmiling** [antvis/S2#2127]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.35.0     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
合并单元格后,希望展示的值是合并项的和(数值类型),目前好像只能选择展示某一个cell的值

**Comment by lijinke666** [comment]
[@antv/s2-v1.43.0](https://github.com/antvis/S2/releases/tag/%40antv%2Fs2-v1.43.0) 支持自定义合并单元格, 请参考 [demo](https://s2.antv.antgroup.com/zh/examples/custom/custom-cell/#custom-merged-cell)

![image](https://user-images.githubusercontent.com/21015895/227467730-ce219068-2313-4430-af02-950bfbf2ec71.png)

**Comment by szjSmiling** [comment]
多谢
