### ISSUE TITLE
🤔关于icon如何居右展示

### ISSUE THREAD

**Issue by shuangxunian** [antvis/S2#2129]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.41.1    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ x ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

我现在有一个需求，想要icon居右展示，然后我翻到了[这个](https://s2.antv.vision/examples/case/data-preview/#index)；但是这个有几个使用问题：
1. icon是后端传过来的，我应该怎么展示
2. 如果左侧的文字太长了，文字会和icon进行重叠
3. 我们对表格的数据做过切割等操作，通过回调函数操作后我原来的操作都无效了。

我现在想请教的是有没有什么方法对原来影响最小的方法去实现icon居右，最好只是实现icon居右，同时不影响之前对data的操作，以及icon的点击事件

### 🔗 Reproduce Link

[这里](https://s2.antv.vision/examples/case/data-preview/#index)

**Comment by shuangxunian** [comment]
劳烦在[这里](https://s2.antv.vision/examples/case/data-preview#index)将[此代码](https://pastebin.ubuntu.com/p/nVH5Jk72Tm/)粘贴，可发现列头的province11111111与icon重叠，除此之外我没有找到什么合适的方法，所以我感觉可以作为一个feature，万分感谢~

**Comment by wjgogogo** [comment]
目前来说，只能通过自定义cell的方式来处理，可以参考这些实例：https://s2.antv.vision/examples#custom-custom-cell
根据你的描述，我们提供一个demo 仅供参考：https://codesandbox.io/s/busy-dawn-79s4ww?file=/index.ts

**Comment by shuangxunian** [comment]
了解，确实是demo的方法应该就能解决了，那请问这个后续会开发嘛？

**Comment by wjgogogo** [comment]
这个是定制需求，不会落到库中，定制需求都是建议走自定义模式

**Comment by shuangxunian** [comment]
了解，谢谢~
