### ISSUE TITLE
🐛next透视表值在行时，值标题单元格文本样式调不了

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#2136]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.5  |
| @antv/s2-react | 2.0.0-next.5  |
| @antv/s2-vue   |2.0.0-next.5  |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
如下图，修改了行的文字颜色，数量的颜色不会改变，只是排序图标的颜色改变了
![d319c81442cac06c83c1dc704d5ad6c1](https://user-images.githubusercontent.com/25057951/228159642-17fcee51-cbbf-4bc3-9315-9bd616a480fe.png)

**Comment by xiaochong44** [comment]
https://codesandbox.io/s/vibrant-noether-vm3j21?file=/src/App.vue

**Comment by wjgogogo** [comment]
![Image](https://user-images.githubusercontent.com/17964556/230880764-f37edbce-12dd-4a2a-94d3-a2be1f2ab77f.png)


因为这里是指标，所以应该用measureText:
![Image](https://user-images.githubusercontent.com/17964556/230880841-9edf248f-d8c3-4b79-b9c1-3eeef764b205.png)

不过 icon color没有遵从这个规则，有点问题，我们会后续修复

**Comment by wjgogogo** [comment]
ref: #2167
