### ISSUE TITLE
🤔点击明细表单元格能获取到当前行的所有数据吗？

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/S2#2141]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^1.12.1     |

### Sheet Type

使用的是  TableSheet
- [ ] PivotSheet
- [ x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

点击明细表上的单元格，通过getMeta()方法获取的data为当前单元格的数据

![image](https://user-images.githubusercontent.com/50241817/228776288-72f620e2-388e-409a-b21f-20baf81f8fbf.png)

### 😊 Expected Behavior
期望结果：点击单元格获取到一整行的数据

**Comment by lbf911531** [comment]
可以通过cell.getMeta().rowIndex 去取

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/manual/advanced/get-cell-data

```ts
s2.dataSet.getCellData({ query: { rowIndex: meta.rowIndex } });

// {province: '浙江', city: '杭州', type: '笔', price: 1}
```
