### ISSUE TITLE
请问是否能设置透视表行头滚动区域的最大宽度

### ISSUE THREAD

**Issue by lbf911531** [antvis/S2#2142]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |       ^1.41.1   |
| @antv/s2-react |     ^1.36.0    |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
如下图：透视表的dataConfig.fields.rows成员过多时，即便出现滚动条，但所占区域仍旧过大；
请问是否能配置行头滚动区域最大宽度，以确保dataCell可视区域大一点？
![image](https://user-images.githubusercontent.com/41470095/228807397-90ad063b-2498-4326-a3cd-19e671650762.png)

**Comment by lijinke666** [comment]
这个目前已经支持了, 不过是还在开发中的新版本的一个特性 https://github.com/antvis/S2/pull/2069

看是否加到 1.x 版本中 @wjgogogo

**Comment by lbf911531** [comment]
> 这个目前已经支持了, 不过是还在开发中的新版本的一个特性 #2069
> 
> 看是否加到 1.x 版本中 @wjgogogo

好的，谢谢

**Comment by lijinke666** [comment]
2.0 版本已支持 https://s2.antv.antgroup.com/manual/basic/sheet-type/pivot-mode#%E5%86%BB%E7%BB%93%E8%A1%8C%E5%A4%B4

**Comment by lbf911531** [comment]
> 2.0 版本已支持 https://s2.antv.antgroup.com/manual/basic/sheet-type/pivot-mode#%E5%86%BB%E7%BB%93%E8%A1%8C%E5%A4%B4

thank you
