### ISSUE TITLE
🐛tooltip挂载节点只在首次渲染时更新，延时修改挂载节点无效

### ISSUE THREAD

**Issue by Bernicechl** [antvis/S2#2146]
### 🏷 Version

官网版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |        官网版本 |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet

### 🖋 Description
场景：表格在全屏、非全屏状态下切换时，需要挂载在不同的DOM节点上才可正常显示。
复现代码现状：
1.首次渲染时tooltip内容为‘hhh’，默认挂在body上
2.延时10s修改tooltip内容为‘aaa’,并修改getContainer容器为'#container'(canvas的父容器)
3.点击单元格，tooltip显示为'hhh'，挂在body上
4.10s后点击单元格，tooltip显示为‘aaa’,仍然挂在body而非container上。此处需要挂在container上

### 🔗 Reproduce Link
复现链接：https://codesandbox.io/s/zealous-ardinghelli-vptd6s?file=/index.ts:0-2329 此处看不到tooltip内容，可将代码拷到demo中查看
### 🤔 Steps to Reproduce
复现链接看不到tooltip内容，可将代码拷到官网demo中查看

### 😊 Expected Behavior
挂载节点似乎只在首次渲染时更新，希望达到10s后点击单元格，tooltip显示为‘aaa’,此处需要挂在container上。

### 😅 Current Behavior
挂载节点未更新，10s后点击单元格，tooltip显示为‘aaa’,仍然挂在body而非container上

**Comment by lcx-seima** [comment]
改变之前，[卸载](https://github.com/antvis/S2/blob/master/packages/s2-core/src/ui/tooltip/index.ts#L95) 之前的 tooltip 就行了

```diff
+ s2.tooltip.destroy();

  s2Options.tooltip = {
    showTooltip: true,
    content: () => {
      return "aaa";
    },
    getContainer: () => {
      console.log("getContainer2");
      return document.querySelector("#container");
    }
  };
  s2.setOptions(s2Options);
  s2.render();
```

**Comment by wangwufan** [comment]
> 改变之前，[卸载](https://github.com/antvis/S2/blob/master/packages/s2-core/src/ui/tooltip/index.ts#L95) 之前的 tooltip 就行了
> 
> ```diff
> + s2.tooltip.destroy();
> 
>   s2Options.tooltip = {
>     showTooltip: true,
>     content: () => {
>       return "aaa";
>     },
>     getContainer: () => {
>       console.log("getContainer2");
>       return document.querySelector("#container");
>     }
>   };
>   s2.setOptions(s2Options);
>   s2.render();
> ```

我在使用全屏效果时也发现这个问题，直接改tooltip没用，现在知道原来还有这操作，destory之后确实好用了

**Comment by Bernicechl** [comment]
您发给我的信件已经收到。
