### ISSUE TITLE
🫡 S2 2.0 版本 roadmap 

### ISSUE THREAD

**Issue by lcx-seima** [antvis/S2#2153]
去年 11 月发布 2.0-alpha（next） 版本后，收获了不少社区的关注。
也有信赖 S2 的同学已经在生产环境部署了 next 版本（😅 功能待稳定，暂不推荐）。
为方便大家了解进度，经过内部盘点，确定了未来几个月正式版的投入事项和 roadmap。

> 抢先试用, API 可能会随时变动, 不建议用于生产环境, [查看更多](https://github.com/antvis/S2/discussions/1933)

```ts
yarn add @antv/s2@next
yarn add @antv/s2-react@next
yarn add @antv/s2-vue@next
```

<img width="548" alt="CleanShot 2023-04-04 at 11 48 34@2x" src="https://user-images.githubusercontent.com/6716092/229682466-a8fd742a-03ba-4daf-acda-289e3bfdb8e9.png">

如有疑问，可回复讨论。再次感谢大家的关注和支持 🫡

**Comment by xiaochong44** [comment]
太好了，终于有了盼头了

**Comment by Gacent** [comment]
> 太好了，终于有了盼头了

请问老铁现在用的是什么表格？移动端表格库有什么推荐的吗？

**Comment by wozien** [comment]
mark

**Comment by lijinke666** [comment]
close https://github.com/antvis/S2/issues/2454
