### ISSUE TITLE
🐛next高级排序不正确

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#2166]
| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.4        |
| @antv/s2-react |2.0.0-next.4         |
| @antv/s2-vue   | 2.0.0-next.4        |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
按度量值排序时，排序的结果有些会不正确，
![image](https://user-images.githubusercontent.com/25057951/232657037-86b41979-31eb-4cd5-9e50-d2ac5cd8385b.png)

### 🔗 Reproduce Link

https://codesandbox.io/s/nervous-sanderson-mzfqot?file=/src/App.vue

**Comment by lcx-seima** [comment]
参考 https://github.com/antvis/S2/pull/1550 配置排序参数

![CleanShot 2023-05-06 at 17 18 01@2x](https://user-images.githubusercontent.com/6716092/236615316-684e462d-faa8-4edb-8ab2-f7bb2a63326e.png)
