### ISSUE TITLE
🐛自定义tooltip只针对dataCell开启，点击tooltip中的内容时，tooltip会立即关闭

### ISSUE THREAD

**Issue by zzcypc** [antvis/S2#2170]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.43.0     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### ⌨️ Code Snapshots
![image](https://user-images.githubusercontent.com/18070429/233324107-a71a327c-c0ea-4214-a413-cf184292c04b.png)

### 🔗 Reproduce Link
https://codesandbox.io/s/exciting-mountain-33v8h7?file=/index.tsx

### 🤔 Steps to Reproduce
点击dataCell，再点击tooltip中的内容

### 😊 Expected Behavior
点击tooltip中的内容时，不关闭tooltip，点击tooltip之外的其它元素时，才关闭tooltip。

### 😅 Current Behavior
自定义tooltip只针对dataCell开启，点击tooltip中的内容时，tooltip会立即关闭，用户无法在tooltip中进行其它操作。

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS     |
| Browser |   chrome      |

**Comment by lijinke666** [comment]
> https://codesandbox.io/s/exciting-mountain-33v8h7?file=/index.tsx

本地未复现, 你这个 demo 也无法正常使用

你这个 demo 用的是 React 18, 为什么还在用 `ReactDOM.render` 和 `ReactDOM.unmountComponentAtNode` ?

自定义内容自己使用 `s2Options.tooltip.content` 就好了 https://s2.antv.antgroup.com/manual/basic/tooltip#%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by lijinke666** [comment]
试了下, 只开启 `dataCell` 的 tooltip, 确实会有问题, 和自定义 tooltip 无关, 内置的也有

**Comment by lijinke666** [comment]
@zzcypc 先这样配置解决

```ts
    const s2Options = {
      width: 600,
      height: 480,
      tooltip: {
        renderTooltip: (spreadsheet) => new CustomTooltip(spreadsheet),
        row: {
          showTooltip: false,
        },
        col: {
          showTooltip: false,
        },
        data: {
          showTooltip: true,
        }
      },
    };
```
