### ISSUE TITLE
🙏希望增加js代码版本

### ISSUE THREAD

**Issue by UpDownLeftRig** [antvis/S2#2184]
### 🖋 Description
我们有些项目是js版本，需要js版本的代码框架

### 🏞 What problem does this feature solve

解决原生js就是使用问题

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| - Ant_S2 | - object| - {}| - 图表类，里面有各种图表函数，也有data,configure,等细节配置对象|

**Comment by wjgogogo** [comment]
什么叫js代码版本， @antv/s2 不就是吗，你所说的原生js使用问题又是啥

**Comment by UpDownLeftRig** [comment]
不是react和vue框架，原生JavaScript代码，不用node.js下载和编译的。

**Comment by lijinke666** [comment]
使用 UMD 版本的 CDN 即可 https://s2.antv.antgroup.com/manual/getting-started#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5%E4%B8%8D%E6%8E%A8%E8%8D%90
