### ISSUE TITLE
🤔设置了tooltip的operation的trend和hiddenColumns为true,但是没出现官网demo出现的样式

### ISSUE THREAD

**Issue by Cref-t** [antvis/S2#2188]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.45.0     |
| @antv/s2-react |    1.39.0     |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

设置了trend和hiddenColumns为true，但是demo没有出现想要的效果
![image](https://user-images.githubusercontent.com/40594548/236400605-1edfb28c-702d-4b0d-8c90-c22d501fa6e2.png)
![image](https://user-images.githubusercontent.com/40594548/236400680-dad25f29-ef70-4bce-b19c-b5964140aa36.png)
![image](https://user-images.githubusercontent.com/40594548/236400799-a4551fd9-9432-4f6c-a4b3-6562c3d7ec9d.png)
官网是这样的
![image](https://user-images.githubusercontent.com/40594548/236401096-77605225-ee94-4bc2-a580-fc67dc9402ea.png)

**Comment by lcx-seima** [comment]
官网链接麻烦发下？
你应该是直接用的 s2-core，相关 tooltip 组件在 s2-react 包里，需使用 s2-react 里的表组件
https://s2.antv.antgroup.com/zh/examples/react-component/tooltip/#basic

**Comment by lijinke666** [comment]
请确保用法和官网一致, 用的同一个组件, 如果一致还是有问题, 请提供复现 demo
