### ISSUE TITLE
🤔请问mappingFunction如何获取对应的行信息获取其他列信息？

### ISSUE THREAD

**Issue by yida2017** [antvis/S2#2192]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by yida2017** [comment]
请问mappingFunction如何获取对应的行信息获取其他列信息？

**Comment by yida2017** [comment]
![111](https://user-images.githubusercontent.com/35675639/236719103-f3d44d9a-7193-4f70-84c9-b4a1f1ffdc03.png)


创建S2 表格TableSheet，需要设置多列的数据一起作为过滤条件，例如：若满足A条件 设置红色 、若满足B条件 设置蓝色 等方案。然后在设置mapping的时候获取不到对应其他列的数据值、行数据、行号等信息？

**Comment by lcx-seima** [comment]
目前 mapping 方法两个参数，第一个是当前格的值，第一个是所在行的数据对象
确实没有你想要的其他数据。

可参考源码 `packages/s2-core/src/cell/data-cell.ts` 复写 mappingValue 方法，使用自定义 [数据单元格](https://s2.antv.antgroup.com/zh/examples/custom/custom-cell/#data-cell) 达成你的目的，因为你使用的是明细表，需要自定义 TableDataCell，这个例子是交叉表的 DataCell
