### ISSUE TITLE
🤔请问行头、列头能够实现合并单元格效果？

### ISSUE THREAD

**Issue by Cref-t** [antvis/S2#2193]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.45       |
| @antv/s2-react |  1.39       |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

如题所示，透视表中，现在的合并单元格只能针对数据单元格，请问行头、列头、角头能否实现合并单元格效果

**Comment by lcx-seima** [comment]
没有对应合并功能

**Comment by Cref-t** [comment]
> 没有对应合并功能

请问后续有开发这个功能的计划吗

**Comment by weiguanglai** [comment]
工作中确实有这样的需求
