### ISSUE TITLE
🐛若字段的code中含有方括号，则无法通过拖拽调整该字段所在列的宽度

### ISSUE THREAD

**Issue by zzcypc** [antvis/S2#2195]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.45.1     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
若字段的code中含有`[[]]`，则无法通过拖拽调整该字段所在列的宽度

### ⌨️ Code Snapshots
![image](https://github.com/antvis/S2/assets/18070429/9169ba47-f013-4db8-a749-bcaab5c9a48a)

### 🔗 Reproduce Link
https://codesandbox.io/s/zealous-swartz-zhon31?file=/index.ts

### 🤔 Steps to Reproduce
打开Reproduce Link，用鼠标拖拽调整“商品类别”所在列的宽度
![image](https://github.com/antvis/S2/assets/18070429/f561aac1-1ad4-462d-a684-578a26326403)

### 😊 Expected Behavior
列宽可以正常拖拽调整

### 😅 Current Behavior
拖拽后列宽没有变化

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS     |
| Browser |    Chrome     |

**Comment by tyr1dev** [comment]
这个其实是因为字段代码中有方括号，无法使用 `xxxByField` 配置调整该字段的布局
