### ISSUE TITLE
🤔 明细表有能实现某些列根据当前列的内容值过滤么？

### ISSUE THREAD

**Issue by ilovejcm** [antvis/S2#2196]
### 🏷 Version

@antv/s2-react: 1.42.0
@antv/s2-react: 1.37.0

### Sheet Type

TableSheet

### 🖋 Description

明细表有能实现某些列根据当前列的内容值过滤么？
类似这样的：
![image](https://github.com/antvis/S2/assets/7704777/3b8ca8ee-7e64-4d34-a6bc-7433bad5a972)

找了一圈没有找到

**Comment by serializedowen** [comment]
参考  https://github.com/antvis/S2/blob/5610433123c0623eb0e10b460596f296dff1e018/s2-site/examples/case/data-preview/demo/index.tsx#L561   手动触发RANGE_FILTER事件

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/examples/case/data-preview/#index

**Comment by ilovejcm** [comment]
感谢回复，但我想是不是能有和排序放一起的那种筛选框，或者分开的筛选框，类似我截图的那种形式 @lijinke666

**Comment by lijinke666** [comment]
DEMO 不就是在一起吗? 
![image](https://github.com/antvis/S2/assets/21015895/b509a598-115e-4eed-9978-28490e1609f6)

S2 只提供底层的排序和筛选能力, 你想要长得像 Excel 的筛选器, 或要什么样的 UI 请你自己实现

**Comment by RJM1996** [comment]
> DEMO 不就是在一起吗? ![image](https://private-user-images.githubusercontent.com/21015895/239173348-b509a598-115e-4eed-9978-28490e1609f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDM0MjIsIm5iZiI6MTcxMTEwMzEyMiwicGF0aCI6Ii8yMTAxNTg5NS8yMzkxNzMzNDgtYjUwOWE1OTgtMTE1ZS00ZWVkLTk5NzgtMjg0OTBlMTYwOWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTJlMjRjNzRlNGVhZWFhZDU3YzdkZWI1YTI3NWRkZDAwNWQ3YmVkYTM2NWE4ZmVlNjIxYWIwNjI2YzUyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2J-Fppl8U_a3NA9ZuOJoE3sPgMLJn2XCXuqz8ykInQk)
> 
> S2 只提供底层的排序和筛选能力, 你想要长得像 Excel 的筛选器, 或要什么样的 UI 请你自己实现

请问下想要重置筛选该怎么做呢？
