### ISSUE TITLE
🐛在macOS系统，Chrome浏览器中，使用外接鼠标，按住shift键并滚动鼠标滚轮时，表格无法横向滚动

### ISSUE THREAD

**Issue by zzcypc** [antvis/S2#2198]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.45.1      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在macOS系统，Chrome浏览器中，使用外接鼠标，按住shift键并滚动鼠标滚轮时，表格无法横向滚动。

问题出在计算offsetX逻辑中：
![image](https://github.com/antvis/S2/assets/18070429/41e42e8c-00d2-47d8-8671-4cbd1a1b7a18)

使用外接鼠标时，deltaY的值始终为0：
![image](https://github.com/antvis/S2/assets/18070429/aae8f798-b6c4-456e-9f02-cc280779ad8f)

这应该是一个浏览器兼容性问题，需要根据不同情况，获取不同的delta值：
![image](https://github.com/antvis/S2/assets/18070429/52f0cd64-72e4-4166-a445-4a214f29fdbc)

或许这个js文件可以为你们提供一些可用的参考信息：
https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js

### ⌨️ Code Snapshots
无

### 🔗 Reproduce Link
https://s2.antv.antgroup.com/examples/case/kpi-strategy/#covid-trend

### 🤔 Steps to Reproduce
在macOS电脑上，使用外接鼠标，在表格组件上，按住shift键并滚动鼠标滚轮

### 😊 Expected Behavior
表格可以横向滚动

### 😅 Current Behavior
表格无法横向滚动

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS     |
| Browser |    Chrome     |

**Comment by lijinke666** [comment]
macOS 默认就有 按住 Shift 横向滚动的行为, 我记得这段代码当时是兼容 window 场景, 看起来反而把 macOS 的行为破坏了 @serializedowen 

![image](https://github.com/antvis/S2/assets/21015895/5bff2ec1-af20-4841-a373-0e5671b292d3)

@zzcypc 可以尝试直接来个 PR, 只在 windows 环境执行这段代码, 应该就能解决问题

**Comment by zzcypc** [comment]
> macOS 默认就有 按住 Shift 横向滚动的行为, 我记得这段代码当时是兼容 windows 场景, 看起来反而把 macOS 的行为破坏了 @serializedowen
> 
> ![image](https://user-images.githubusercontent.com/21015895/237566018-5bff2ec1-af20-4841-a373-0e5671b292d3.png)
> 
> @zzcypc 可以尝试直接来个 PR, 只在 windows 环境执行这段代码, 应该就能解决问题

@lijinke666 macOS在使用触控板的时候，按住shift键滚动是正常的，但使用外接鼠标就会遇到这个问题。这应该是关于wheel事件的浏览器/设备兼容性问题。PR的话，昨天原本以为处理起来比较简单，后来发现需要考虑和测试的case比较多，就先提issue了。近期事项较多，暂时无力提供PR。等后续如有闲暇时间，我会愿意尝试提交一些力所能及的代码。

**Comment by lijinke666** [comment]
我的意思是 macOS 就算是外接鼠标, 去掉这段 shifrt 的特殊逻辑, 也是可以正常横向滚动的
