### ISSUE TITLE
🤔如何自定义修改具体某一行的数据的样式

### ISSUE THREAD

**Issue by Cref-t** [antvis/S2#2202]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.45      |
| @antv/s2-react |  1.39        |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

如下图所示在交叉表中，我想单独修改LTI合计金额这单独一行的样式，现有配置可以支持吗？
![image](https://github.com/antvis/S2/assets/40594548/b0d527d3-5d2b-417a-8278-c445241cdbb1)

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/examples/custom/custom-cell/#custom-specified-cell
