### ISSUE TITLE
🐛selectedCellHighlight不生效

### ISSUE THREAD

**Issue by AALiujiajun** [antvis/S2#2203]
### 🏷 Version

@antv/s2 1.44.0

-->

### Sheet Type

 PivotSheet
 TableSheet

### 🖋 Description

interaction.selectedCellHighlight:true 不生效

### ⌨️ Code Snapshots

import { PivotSheet, S2Options } from '@antv/s2';

fetch(
  'https://gw.alipayobjects.com/os/bmw-prod/2a5dbbc8-d0a7-4d02-b7c9-34f6ca63cff6.json',
)
  .then((res) => res.json())
  .then((dataCfg) => {
    const container = document.getElementById('container');

    const s2Options: S2Options = {
      width: 600,
      height: 480,
      interaction: {
        // 悬停高亮
        hoverHighlight: true,
        selectedCellHighlight: true // 这一行
      },
      tooltip: {
        showTooltip: true,
      },
    };
    const s2 = new PivotSheet(container, dataCfg, s2Options);

    s2.render();
  });

### 🔗 Reproduce Link

![1683797115662](https://github.com/antvis/S2/assets/38196267/00773f32-a271-4fb5-9ae4-b2975253ac14)

### 🤔 Steps to Reproduce

行列联动高亮 官方实例上添加selectedCellHighlight: true 点击后未出现整行整列高亮

### 😊 Expected Behavior

所在单元格行列应高亮

### 😅 Current Behavior

没有执行高亮

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by tyr1dev** [comment]
```ts
selectedCellHighlight: true

// 等价于

selectedCellHighlight: {
  rowHeader: true, // 高亮行头
  colHeader: true, // 高亮列头
  currentRow: false, // 高亮选中单元格所在行
  currentCol: false, // 高亮选中单元格所在列
}

//如果想要高亮行列，应当手动设置下一级的属性

selectedCellHighlight: {
  rowHeader: false, // 高亮行头
  colHeader: false, // 高亮列头
  currentRow: true, // 高亮选中单元格所在行
  currentCol: true, // 高亮选中单元格所在列
}
```

[文档](https://s2.antv.antgroup.com/api/basic-class/interaction#interaction) 中的属性不对

同时目前是无法高亮行列头，确实存在其它问题
