### ISSUE TITLE
在交叉表S2中，数据可以按照列一列列展示吗？

### ISSUE THREAD

**Issue by yuanAIhan** [antvis/S2#2215]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   ^1.44.0      |
| @antv/s2-react |   ^1.38.0      |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet
- [-] SheetComponent

### 🖋 Description
我使用的是SheetComponent组件，目前的数据是一行一行进行展示，请问我如何将数据实现一列一列的进行展示呢？

目前我发现该表格支持行列切换，但是其中行列只是针对维度而言的，如果我想针对其中的数据指标进行行列转换的话。请问我应该如何实现呢？现在交叉表支持这个功能吗？
https://s2.antv.antgroup.com/zh/examples/react-component/switcher#pivot-header
比如官网上的列子，如果在列头中添加type、province、city等字段放在列头里面，会将对应的数据按照行的方式展示，但是放在行头里面就会按照一行一行的方式展示。对于这种切换方式，如果我想对后面的price和cost两个指标也实现相同的功能，请问可以实现吗？

**Comment by yuanAIhan** [comment]
即将数据按照下面的方式展示：
![image](https://github.com/antvis/S2/assets/80769611/be9ce5a5-513e-41e6-b189-b66c5f202af7)

或者类似于上面这样子
![image](https://github.com/antvis/S2/assets/80769611/d0dcc5d6-822e-4515-a8c9-06b98df52a84)
![image](https://github.com/antvis/S2/assets/80769611/18bd1a49-e5d8-4707-829a-64428be97244)

第二个图是我想要展示的数据显示效果，但是将其放表列头的时候，虽然显示出来了，但是下面的指标里面还是有很多空余的值。

**Comment by lcx-seima** [comment]
- 看得不是很明白，你大概是想把 price 当成维度，这是可以的
- 建议再看看交叉表的基础概念
- 如果仅仅是按行展示，请用明细表模式
