### ISSUE TITLE
🤔antd/s2-react 可以实现自主操作合并单元格吗？

### ISSUE THREAD

**Issue by Cref-t** [antvis/S2#2217]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.45      |
| @antv/s2-react |    1.39     |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![image](https://github.com/antvis/S2/assets/40594548/70d95eff-472f-402c-9ca8-fb10ccf7692b)
请问这种自主操作合并单元格在 antd/s2-react组件中可以实现吗？ 具体是怎么实现呢？

**Comment by lijinke666** [comment]
两者没有区别, 你用 `@antv/s2-react` 的话, 获取到 表格的实例即可, 剩下的参考文档中的代码即可

1. 获取实例 https://s2.antv.antgroup.com/manual/advanced/get-instance
2. 自定义 tooltip 内容, 添加对应的按钮
3. 调用对应方法

```ts
s2.interaction.mergeCells()
```


> 另外, 是 `antv/s2-react` 不是 `antd/s2-react` :)

**Comment by Cref-t** [comment]
> 两者没有区别, 你用 `@antv/s2-react` 的话, 获取到 表格的实例即可, 剩下的参考文档中的代码即可
> 
> 1. 获取实例 https://s2.antv.antgroup.com/manual/advanced/get-instance
> 2. 自定义 tooltip 内容, 添加对应的按钮
> 3. 调用对应方法
> 
> ```ts
> s2.interaction.mergeCells()
> ```
> 
> > 另外, 是 `antv/s2-react` 不是 `antd/s2-react` :)

但是demo里面，s2实例中的tooltip里的show方法在 antv/s2-react实例中的tooltip中并没有相对应的方法
