### ISSUE TITLE
S2支持自定义Action吗？🤔

### ISSUE THREAD

**Issue by yuanAIhan** [antvis/S2#2218]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.44.0      |
| @antv/s2-react |   1.38.0      |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet
- [-] SheetComponent

### 🖋 Description

S2中支持在每一行数据里面自定义Action操作吗？类似于antd design 中 Table里面的Action操作？
如下图的Action操作
![image](https://github.com/antvis/S2/assets/80769611/39db6f5c-79bf-4aa9-8499-0d4d4a053fd5)

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/discussions/1473#discussioncomment-3000664
