### ISSUE TITLE
🐛自定义tooltip位置错误

### ISSUE THREAD

**Issue by sl6-k** [antvis/S2#2220]
version -- v1.46.0
https://s2.antv.antgroup.com/zh/examples/custom/custom-cell/#custom-merged-cell 官网正常
https://codesandbox.io/s/focused-brown-cbq8c2?file=/index.ts codesandbox位置显示异常

**Comment by lcx-seima** [comment]
引入 core 层的 css
```diff
+ import '@antv/s2/dist/style.min.css';
```
