### ISSUE TITLE
🙏希望透视表数据实现可编辑功能

### ISSUE THREAD

**Issue by rrwang05** [antvis/S2#2243]
### 🖋 Description
当前是通过获取单元格的位置，定位一个div覆盖到该单元格上，目前是遇到了该单元格的x轴位移获取总是往左偏了一点，y轴是没问题的。效果大致如图：
![image](https://github.com/antvis/S2/assets/12505303/800dec84-05d5-41ba-9a79-9f08defaa866)

能否支持透视表也可实现编辑单元格的功能；
另： 如何能获取到单元格位置

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
透视表暂不考虑支持编辑功能, S2 透视表着重看数, 和目前的定位不太相符, 如果是你截图的场景, 单行头/单指标, 推荐使用明细表替代, 目前 `s2-react` 中明细表有编辑能力的封装, 可[直接使用](https://s2.antv.antgroup.com/manual/basic/analysis/editable-mode)

> 另： 如何能获取到单元格位置

如果目前要在透视表的基础上支持单元格编辑, 可参考 `s2-react` 中明细编辑表的做法

https://github.com/antvis/S2/blob/2845c11aff9768c61f0cb9d37614354729f4c1ed/packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx#L59-L75
