### ISSUE TITLE
🐛明细表数据为空会显示一行

### ISSUE THREAD

**Issue by wulie88** [antvis/S2#2255]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

<img width="1814" alt="image" src="https://github.com/antvis/S2/assets/783824/e4eb5f07-7cda-4cf9-bbd7-bb465fd1bdf0">

明细表数据为空会显示一行，期望显示数据为空的提示。

我们试过先拦截空数据直接显示空数据提示，不显示表格，但是因为空数据是在表头通过服务端筛选造成的，空数据不显示表格，会中断交互流程。希望能组件内部处理，并暴露空数据提示ReactNode供定制。

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by wulie88** [comment]
[https://github.com/antvis/S2/issues/1946](url)

**Comment by wulie88** [comment]
#1946

**Comment by wulie88** [comment]
#1946

**Comment by lijinke666** [comment]
> 希望能组件内部处理，并暴露空数据提示ReactNode供定制。

目前数据为空时推荐的做法是: 自行在表格上面觉得定位一个 div 蒙层显示提示

1. 明细表数据为空会显示一行是 bug, 近期修复

2. 内置的话改动成本较大, 在 2.0 版本我们会加上
