### ISSUE TITLE
🐛移动端表格边界滚动行为异常

### ISSUE THREAD

**Issue by LeeSSHH** [antvis/S2#2266]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |1.42.0|

### Sheet Type

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

移动端表格边界滚动行为异常

### ⌨️ Code Snapshots
```
const s2DataConfig = {
  fields: {
    columns: ["province", "city", "type", "price"]
  },
  data: [
    {
      province: "浙江",
      city: "杭州",
      type: "笔",
      price: "1"
    },
    {
      province: "浙江",
      city: "杭州",
      type: "纸张",
      price: "2"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "笔",
      price: "17"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "纸张",
      price: "0.5"
    },
    {
      province: "吉林",
      city: "丹东",
      type: "笔",
      price: "8"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    }
  ]
};

const s2options = {
  width: 600,
  height: 500,
  interaction: {
    overscrollBehavior: 'auto'
  }
};
```
报错信息
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

### 🔗 Reproduce Link
https://codesandbox.io/s/cocky-david-662ndr?file=/src/index.js

### 🤔 Steps to Reproduce
设备：移动端设备
涉及功能：滚动边界行为
前提条件：
- options.interaction.overscrollBehavior配置为'auto'
- 表格内容较多，出现滚动条

复现步骤：
- 触摸屏幕，拖动表格内容滚动至边界
- 继续滚动，控制台不断出现报错```[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.```
- 并且表格会出现轻微抖动，例如滚动条滚至底部，继续拖动屏幕往下滚动，正确效果应该是表格本身不懂，触发页面往下滚动，实际上是页面虽然是在往下滚动，但是这个过程中表格本身很容易发生抖动

### 😊 Expected Behavior
正确应该是表格滚动条到达边界之后继续滚动，只有外部容器会滚动，表格本身不应发生抖动

### 😅 Current Behavior
目前是表格滚动条到达边界之后继续滚动，外部容器会滚动，但是表格本身发生了抖动，并且出现控制台报错

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |windows11|
| Browser |Chrome 105.0.5195.102|

**Comment by lijinke666** [comment]
![image](https://github.com/antvis/S2/assets/21015895/c7b883cf-9b54-42d2-bc51-215de2f53a8b)

**Comment by lijinke666** [comment]
PR #2302 解决控制台报错, 抖动问题经排查是依赖的手势库 `@antv/g-gesture` 有 bug, 返回的 `deltaY` 和滚动方向不符, 向下滚动返回的 deltaY 是负数, 导致表格反方向滚动, 这个会在 2.0 版本解决
