### ISSUE TITLE
🐛React 18 is not supported for this S2 components

### ISSUE THREAD

**Issue by Sherlin007** [antvis/S2#2270]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^1.41.0     |
| @antv/s2-react |     ^1.41.0    |
| @antv/s2-vue   |         |

### Sheet Type

- [Y ] PivotSheet
- [ Y] TableSheet
- [Y ] GridAnalysisSheet
- [Y ] StrategySheet
- [Y ] EditableSheet

### 🖋 Description
The warning message you are seeing indicates that the ReactDOM.render method is no longer supported in React 18, please update it for supporting react 18+

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |
![image](https://github.com/antvis/S2/assets/137588651/c66ccb65-6deb-46f2-8809-96eccc232501)

**Comment by GaoFuhong** [comment]
目前保持现状，暂不投入修改。
