### ISSUE TITLE
🐛明细表点击行头的时候，meta获取的rowIndex错误

### ISSUE THREAD

**Issue by ahao430** [antvis/S2#2274]
### 🏷 Version
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.47.1  |
| @antv/s2-react |  1.40.0  |

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type
TableSheet
（s2react的SheetComponent，sheetType: 'table'）

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
在代码中重写了tooltip，发现点击列头时，读取到了错误的行数据进行渲染。
原因是meta返回了错误的rowIndex

### ⌨️ Code Snapshots
```js
      tooltip: {
        content: (cell, defaultTooltipShowOptions) => {
          if (cell) {
            // 单个
            const meta = cell.getMeta()
              const rowData = s2Ref.current.dataSet.getCellData({
                query: {
                  rowIndex: meta.rowIndex // 当点击列头时，返回了错误的rowIndex
                }
              }) || {}
              return (
                <div style={{padding: '10px'}}>
                  <p>广告位：{rowData.slotName}</p>
                  <p>数值：{cell.actualText}</p>
                </div>
              )
          } 
           return null
        },
      },
```

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by serializedowen** [comment]
<img width="907" alt="image" src="https://github.com/antvis/S2/assets/9219215/223ba5b7-bc4e-459f-9f24-d8161511ff06">
未复现
