### ISSUE TITLE
next版本存在内存泄露🐛

### ISSUE THREAD

**Issue by xiaochong44** [antvis/S2#2280]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.7        |
| @antv/s2-react | 2.0.0-next.6        |
| @antv/s2-vue   | 2.0.0-next.6        |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

来回拖动滚动条以后，内存飙升无法释放
使用源码里的示例测试如下
刚启动时
![652a82930259042adf04f02f46ed76ab](https://github.com/antvis/S2/assets/25057951/9e8643c3-f214-4e28-b73c-6a72fb65a58c)
来回拖动滚动条以后
![1689242198661_FA58A2F3-8515-4f07-8EAF-3E9C1118CEEE](https://github.com/antvis/S2/assets/25057951/a203134a-20aa-415e-9906-ae2a94d3dd6a)

### 🔗 Reproduce Link

使用源码里的vue或者react的例子就可以复现
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
Fixed in [@antv/s2-v2.0.0-next.8](https://github.com/antvis/S2/releases/tag/%40antv%2Fs2-v2.0.0-next.8)
