### ISSUE TITLE
🤔s2 怎么支持多种不同的字体

### ISSUE THREAD

**Issue by misswangkang** [antvis/S2#2292]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.47.1      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

s2 怎么支持多种不同的字体，我们用css 引入字体后，然后在主题里面给各个文本设置fontFamily
例如： theme.cornerCell.text.fontFamily='xxx',再调用s2.render(),鼠标悬浮上去才会生效，或者等待很久才生效
### 😊 Expected Behavior
像css一样能支持多种不同字体切换
### 😅 Current Behavior
设置好，悬浮才会生效，等待很久才生效

**Comment by misswangkang** [comment]
@lcx-seima 换种说法，我们需要s2支持更多不同的字体，应该怎么做

**Comment by zhangjinhao-work** [comment]
> @lcx-seima 换种说法，我们需要s2支持更多不同的字体，应该怎么做

我这里针对列头样式，修改colCell.bolderText.fontFamily去设置不同样式，
还有就是我针对全局使用的是获取canvas,然后去修改他的字体，
 // 全局更新字体
let cxt = container.children[0].getContext('2d');
cxt.fontFamily = 'fonts_883793'

<style id="font-face-style">
@font-face {
    font-family: 'fonts_883793';
    src: url('../assets/miaozizimuti-regular.ttf') format('truetype'), url('../assets/miaozizimuti-regular.ttf') format('woff'), url('../assets/miaozizimuti-regular.ttf') format('otf');
    font-weight: normal;
    font-style: normal;
}

.fonts_883793 {
    font-family: 'fonts_883793'
}
</style>

我都git中有这个写你可以参考下 https://gitee.com/zhangjinhao/antv-s2.git

**Comment by stone-lyl** [comment]
你在配置 theme 的时候就设置，就可以生效了
![image](https://github.com/antvis/S2/assets/20497176/efb4d596-52e4-4014-8bd5-b9bebb0e1b82)
