### ISSUE TITLE
🐛官方例子-表格交互-高级交互-合并单元格 在codesandbox打开 Tooltip 位置有问题

### ISSUE THREAD

**Issue by lujunpeng** [antvis/S2#2294]
### 🏷 Version 1.49.1

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.49.1   |
### Sheet Type

- [ ] PivotSheet

### ⌨️ Code Snapshots
使用s2.tooltip.show 弹出层位置错误

<img width="760" alt="屏幕截图 2023-07-25 194230" src="https://github.com/antvis/S2/assets/22834826/bbdba9fe-88e6-4575-b040-92a99802b052">

### 🔗 Reproduce Link
https://codesandbox.io/s/3phgzo

### 🤔 Steps to Reproduce

Tooltip 弹出层跑到表格最下面了，位置应该是鼠标点击位置，为何官方网站里面的示例显示正常，但是在codesandbox和本地运行项目时显示错误？

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     win11    |
| Browser |   chrome 114.0    |

**Comment by lijinke666** [comment]
因为你没有引入样式

```ts
import "@antv/s2/dist/style.min.css";
```

**Comment by lujunpeng** [comment]
解决了
