### ISSUE TITLE
🐛next版本，透视表的列头存在分组时导出CSV数据存在空缺

### ISSUE THREAD

**Issue by Ahui4518** [antvis/S2#2308]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.8     |
| @antv/s2-react |         |
| @antv/s2-vue   |    2.0.0-next.7     |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### ⌨️ 透视表在列头存在分组的情况下，使用asyncGetAllPlainData导出，开启格式化功能后，部分数据丢失。
![image](https://github.com/antvis/S2/assets/68359769/e7c32f7e-cb79-45c4-889a-863480f316cc)

### 🤔 Steps to Reproduce

![1692092675947](https://github.com/antvis/S2/assets/68359769/05974f49-720a-4fcf-9c28-786f6b0f3300)
这是字段的结构
在列头存在分组的透视表种，当asyncGetAllPlainData的格式化属性设置为true后

### 😊 Expected Behavior

asyncGetAllPlainData返回的数据应该与表格的数据能对上

### 😅 Current Behavior

导出的数据出现空缺
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
最新版本应该已经修复了, 如还有问题, 请提供最小复现示例
