### ISSUE TITLE
🤔透视图嵌入wujie微前端中，列拖动位置显示不正确

### ISSUE THREAD

**Issue by webLoginjun** [antvis/S2#2310]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |  
| @antv/s2       |     1.35.0    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视图中，如果是单独在系统中使用，在调整列宽时候可以按照鼠标拖动的方向，大小间距去调整；如果嵌入到wujie微前端中，在调整列宽，提示的位置和最终调整出来的位置，就不一致了
如何复现
给出详细的复现步骤
1、第一步
打开没有嵌入到wujie微前端的系统中进行透视表的列宽调整，可以进行正常的调整

https://github.com/antvis/S2/assets/22684780/83165367-2de6-4fb7-a737-f0fa4bb59037

2、 第二步
打开嵌入到wujie微前端系统中的透视图，然后调整列宽，可以看到调整时候列宽变的不一致

https://github.com/antvis/S2/assets/22684780/89ce7114-6a97-4957-bd91-9066804e9514

**Comment by stone-lyl** [comment]
首先可能需要明确你是通过什么方式进行微前端嵌入的？（web Component or iframe ...)
通过你上传视频的表现，我猜测是因为微前端嵌入导致 S2 中获取 resizeReferenceGroup 的位置，存在偏移导致的。 因为场景复现很困难，我们无法帮你debug。具体文件地址如下，你可以自己尝试debug 一下。https://github.com/antvis/S2/blob/807648180fe64f47e9f70df865890ab480b07603/packages/s2-core/src/interaction/row-column-resize.ts#L43
