### ISSUE TITLE
🐛 紧凑布局在部分metaname情况下会显示省略

### ISSUE THREAD

**Issue by helianthuswhite** [antvis/S2#2312]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      latest   |
| @antv/s2-react |   -      |
| @antv/s2-vue   |    -     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
在使用交叉表的紧凑模式时候，发现当存在多行，且第一列为分类时，在某些分类名称情况下紧凑模式仍然无法显示全分类名称。
这真的是一个非常非常奇怪的BUG！！

当我的名称这个位置加入一个字符 `I` 时，就会显示省略号
<img width="1051" alt="image" src="https://github.com/antvis/S2/assets/12878076/02aafa8e-e922-4003-abab-55b9303728ca">

但如果我把 `I` 去掉，或者在 `I` 后面再加一个其他字符的时候，就能显示全
<img width="1122" alt="image" src="https://github.com/antvis/S2/assets/12878076/5a99f17b-4e1e-488c-b8bf-c08d4c4c7d18">

### ⌨️ Code Snapshots
这里是fork的代码：https://codesandbox.io/s/suspicious-gagarin-d9zd5d?file=/index.ts

```ts
import { PivotSheet } from "@antv/s2";

const container = document.getElementById("container");

const dataCfg = {
  fields: {
    rows: [],
    columns: ["date_origin"],
    values: ["核心CPI环比_预期", "美国_ISM_制造业PMI_物价"],
    valueInCols: false
  },
  meta: [
    {
      field: "date_origin",
      name: "日期"
    },
    {
      field: "核心CPI环比_预期",
      name: "核心CPI测试一下很长的Is环比"
    },
    {
      field: "美国_ISM_制造业PMI_物价",
      name: "美国_ISM_制造业PMI_物价"
    }
  ],
  data: [
    {
      "2023": true,
      date_origin: "2023",
      核心CPI环比_预期: "2.3",
      美国_ISM_制造业PMI_物价: "326.8",
      "": true,
      source: {
        date_origin: 2023,
        核心CPI环比_预期: 2.3,
        美国_ISM_制造业PMI_物价: 326.8
      }
    },
    {
      "2022": true,
      date_origin: "2022",
      核心CPI环比_预期: "5.3",
      美国_ISM_制造业PMI_物价: "777.3",
      "": true,
      source: {
        date_origin: 2022,
        核心CPI环比_预期: 5.3,
        美国_ISM_制造业PMI_物价: 777.3
      }
    },
    {
      "2021": true,
      date_origin: "2021",
      核心CPI环比_预期: "4.1",
      美国_ISM_制造业PMI_物价: "1006",
      "": true,
      source: {
        date_origin: 2021,
        核心CPI环比_预期: 4.1,
        美国_ISM_制造业PMI_物价: 1006
      }
    },
    {
      "2020": true,
      date_origin: "2020",
      核心CPI环比_预期: "0.8",
      美国_ISM_制造业PMI_物价: "330.8",
      "": true,
      source: {
        date_origin: 2020,
        核心CPI环比_预期: 0.8,
        美国_ISM_制造业PMI_物价: 330.8
      }
    }
  ]
};

const s2Options = {
  width: 400,
  height: 480,
  style: {
    layoutWidthType: "compact"
  }
};
const s2 = new PivotSheet(container, dataCfg, s2Options);

s2.render();

```

### 🔗 Reproduce Link
https://codesandbox.io/s/suspicious-gagarin-d9zd5d?file=/index.ts

### 🤔 Steps to Reproduce
按照前面的描述操作就可以复现

### 😊 Expected Behavior
紧凑模式下都能显示全meta name

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
初步看下来是你的数据源导致的, 你的数值含有下划线 `_` 的情况下, 行头的节点宽度采样不精准

![image](https://github.com/antvis/S2/assets/21015895/9409cf99-71c7-4dad-b583-d77f5bee24c9)

**看起来 `_` 不是等宽字体导致的**

![image](https://github.com/antvis/S2/assets/21015895/749567e7-27b0-453d-946c-10f89f8272fe)

你可以配置[表格主题](https://s2.antv.antgroup.com/api/general/s2-theme#texttheme), 设置 fontFamily 为等宽字体, 比如 `JetBrains Mono`

![image](https://github.com/antvis/S2/assets/21015895/95923c07-f4dc-4849-8d4c-d3e14ca207f1)
