### ISSUE TITLE
🤔当某列某个指标无数据时，小计计算会错列计算求和

### ISSUE THREAD

**Issue by star-448** [antvis/S2#2313]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.43.0      |
| @antv/s2-react |      1.37.1   |
| @antv/s2-vue   |         |

### Sheet Type

- [ √] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![image](https://github.com/antvis/S2/assets/26704928/29f24bf4-2b5d-44c0-b743-bcc37b752bde)
如图所示，这里因为桌子的毛利率一列数据没有，导致计算毛利率列小计时，把椅子的毛利率和桌子的同期进行了相加，想知道目前这种特殊情况下是否有办法可以解决？

### 🔗 Reproduce Link

https://codesandbox.io/s/hardcore-brattain-3cl3lh?file=/mockData.json

**Comment by wjgogogo** [comment]
问题已修复，请使用最新的版本
