### ISSUE TITLE
🤔自定义单元格以后表格数据列中的宽度没有自适应？

### ISSUE THREAD

**Issue by yuanAIhan** [antvis/S2#2314]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.36.0    |
| @antv/s2-react |    1.33.0     |
| @antv/s2-vue   |         |

### Sheet Type

- [ -] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

我通过自定义单元格的方式，即继承了DataCell类，将当前明细表中的如果数据很长，会出现下面的情况，即重写后的表格不支持自适应。会出现下面的效果，请问应该如何修改呢？我并不想将宽度通过ColCfg中设置为一个固定的很大的宽度，这样会影响查看。但是宽度较小的时候，文案超出以后，当前的内容会溢出遮住其余单元格的内容。
![image](https://github.com/antvis/S2/assets/80769611/9b9cdf2a-25fe-43d8-ba6f-a743bac09f32)
![image](https://github.com/antvis/S2/assets/80769611/2146347c-5c2e-410e-9b15-0d83a75bb15e)

**Comment by lijinke666** [comment]
明细表对应的是 TableDataCell
