### ISSUE TITLE
🤔关于s2渲染性能监控的可行方案

### ISSUE THREAD

**Issue by sharpFD** [antvis/S2#2315]
### 🏷 Version
antv/s2-vue-v2.0.0-next.7

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |   v2.0.0-next.7      |

### Sheet Type

- [ ] PivotSheet
- [ ✓ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在大数据量的模式下，想对整体的s2进行性能渲染监控，有什么可行的方案吗，监听事件并不准确，因为数据量巨大的情况下线程会卡顿，影响了主线程渲染，不知道除了暴露的一些事件外还有什么可行的方案吗

**Comment by lijinke666** [comment]
对于 S2 这一层能做的只有尽可能抛出细粒度的 hook, 业务侧可以配合 [`requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) 和 [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) 去做.

**Comment by sharpFD** [comment]
> 对于 S2 这一层能做的只有尽可能抛出细粒度的 hook, 业务侧可以配合 [`requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) 和 [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) 去做.

感谢，已经通过requestIdleCallback完成性能监控
