### ISSUE TITLE
🤔交叉表-可以列表头拆分维度吗？

### ISSUE THREAD

**Issue by woshishade** [antvis/S2#2318]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.18    |
| @antv/s2-react |    1.18.0     |
| @antv/s2-vue   |         |

### Sheet Type
交叉表-可以列表头拆分维度吗？

### 🖋 Description
![image](https://github.com/antvis/S2/assets/10460238/d0d9b7c8-5bde-4e48-8eb6-2182b4142ce2)
像该图片框住的省份，可以分开一列列去显示吗？我没找到相应的api

**Comment by lijinke666** [comment]
> 交叉表-可以列表头拆分维度吗？

不支持, 交叉表的前提就是按相同维度进行聚合, 不然就是明细表了

> 像该图片框住的省份，可以分开一列列去显示吗

红框部分是 `行头`

> 我没找到相应的api

官网没写就是不支持, 谢谢


后续使用相关问题, 请在 https://github.com/antvis/S2/discussions 提问, 感谢

![image](https://github.com/antvis/S2/assets/21015895/abd1d690-4ea1-4f4c-8125-17d778cefe76)
