### ISSUE TITLE
🤔透视表-支持右键复制吗？

### ISSUE THREAD

**Issue by woshishade** [antvis/S2#2319]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.18     |
| @antv/s2-react |   1.18.0      |
| @antv/s2-vue   |         |

### Sheet Type

透视表-支持右键复制吗？包括表头和内容

### 🖋 Description
![image](https://github.com/antvis/S2/assets/10460238/024841c1-1671-42c0-8ee7-fb6c8ef94b1b)
目前该配置只支持，ctrl+c快捷键进行复制，可以通过右键弹出选择复制吗？

**Comment by lijinke666** [comment]
不支持
