### ISSUE TITLE
🐛 tableSheet 加载1w条数据并过滤大部分数据会卡顿

### ISSUE THREAD

**Issue by LUUUAN** [antvis/S2#2324]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.49.2     |
| @antv/s2-react |     1.42.1    |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
<img width="1526" alt="截屏2023-09-03 23 50 06" src="https://github.com/antvis/S2/assets/48037246/bbc9ac6c-2888-4cc8-a140-1cb1e2051d3a">
传入1w 条数据和一个 filterParams，其 filterdValues 长度约为4k，此时表格渲染需要1.4s

### ⌨️ Code Snapshots
耗时函数：
```
  handleDimensionValueFilter = () => {
    each(this.filterParams, ({ filterKey, filteredValues, customFilter }) => {
      const defaultFilterFunc = (row: DataType) =>
        !includes(filteredValues, row[filterKey]);
      this.displayData = [
        ...this.getStartRows(),
        ...filter(this.getMovableRows(), (row) => {
          if (customFilter) {
            return customFilter(row) && defaultFilterFunc(row);
          }
          return defaultFilterFunc(row);
        }),
        ...this.getEndRows(),
      ];
    });
  };
```

### 😊 Expected Behavior
对每个列进行过滤时，应为 O(n) 复杂度

### 😅 Current Behavior
当前 handleDimensionValueFilter 函数过滤复杂度为 O(n*len(filteredValues))

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
fixed #2325
