### ISSUE TITLE
🤔交叉表在树状结构下，如何通过JS调用，将指定行头单元格或者全部行头单元格展开

### ISSUE THREAD

**Issue by zzcypc** [antvis/S2#2326]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.49.2      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
我想要实现的一个功能是，在树状交叉表下，滚动到指定的单元格。如果用户折叠了行头单元格，则无法在s2.getRowLeafNodes()的返回值中，find到该单元格。于是我设想是否可以通过调用s2的方法将行头全部展开，然后再去find该单元格。

**Comment by zzcypc** [comment]
### 方法一
`s2.emit(S2Event.LAYOUT_TREE_ROWS_COLLAPSE_ALL, true)`

### 方法二
参考源码中handleTreeRowsCollapseAll的实现方式，先setOption设置hierarchyCollapse，再调用render
https://github.com/antvis/S2/blob/master/packages/s2-core/src/sheet-type/pivot-sheet.ts#L158

**Comment by lijinke666** [comment]
更新 s2Options.styles 即可
