### ISSUE TITLE
🤔透视表是否可以实现添加多列/多行统计值

### ISSUE THREAD

**Issue by zwh0711** [antvis/S2#2331]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.49.2  |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

想请问一下透视表是否可以实现添加多列/多行统计值？有一个需求是添加两行总计，一行计算求和一行计算平均。

**Comment by lijinke666** [comment]
目前不支持
