### ISSUE TITLE
🐛点击表头自定义icon，自定义tooltip无法显示

### ISSUE THREAD

**Issue by awaity** [antvis/S2#2336]
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.49.2      |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

🐛点击表头自定义icon，自定义tooltip无法显示，但是代码在官网react环境下可以正常显示

### ⌨️ Code Snapshots

![76463ef3c046f2e25903301b45d2aba](https://github.com/antvis/S2/assets/51053847/ae7aa5de-07b3-4507-b4e1-04359c2fa7e6)

### 😊 Expected Behavior

能够正常显示tooltip

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |      window 11    |
| Browser |   chrome: v91.0    |

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/manual/faq#%E4%B8%BA%E4%BB%80%E4%B9%88-tooltip-%E5%9C%A8-antvs2-%E4%B8%AD%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%9C%A8-antvs2-react-antvs2-vue-%E4%B8%AD%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA

**Comment by awaity** [comment]
好的，感谢

**Comment by awaity** [comment]
> 大佬请问下最后是如何解决的呢，我也遇到同样的需求，点击表头自定义Icon, 显示指定内容的tooltip。看文档的说明，没有找到怎样结合headerIcon 展示自定义tooltip~

![image](https://github.com/antvis/S2/assets/51053847/e8c129c5-4ad8-4de9-833e-eb2f05b1ce60)
