### ISSUE TITLE
🤔怎么禁止列头文字跟随滚动条移动

### ISSUE THREAD

**Issue by li-guanlong** [antvis/S2#2347]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [✔️ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

怎么禁止列头文字跟随滚动条移动
<img width="296" alt="image" src="https://github.com/antvis/S2/assets/54611134/67d01cee-02bf-4926-9b46-a8086d41c631">

**Comment by lijinke666** [comment]
ref: https://github.com/antvis/S2/issues/2223

**Comment by lijinke666** [comment]
文字滚动吸附是 S2 的一个特性, 可以自定义 ColCell, 复写 `getTextPosition` 自定义文字的 x 坐标

https://github.com/antvis/S2/blob/7751c4968b69752243928cbcd2c50333b06b2c66/packages/s2-core/src/cell/col-cell.ts#L176-L184

```ts
import { ColCell, getTextAndFollowingIconPosition } from '@antv/s2'

class CustomColCell extends ColCell {
  getTextPosition() {
    const defaultTextPosition = super.getTextPosition();
    const textStyle = this.getTextStyle();
    const contentBox = this.getContentArea();
    const iconStyle = this.getIconStyle();

    const { text } = getTextAndFollowingIconPosition(
      contentBox,
      textStyle,
      this.actualTextWidth,
      iconStyle,
      this.getActionIconsCount(),
    );

    return {
      ...defaultTextPosition,
      x: text.x,
    };
  }
}


const s2Options = {
  colCell: (...args) => new CustomColCell(...args),
}
```

![Kapture 2023-10-12 at 11 48 19](https://github.com/antvis/S2/assets/21015895/26c19a2a-07bd-448c-ab3d-4d7b24c28c2a)
