### ISSUE TITLE
🐛透视表数据按格式导出，格式显示错误

### ISSUE THREAD

**Issue by polikesen123** [antvis/S2#2349]
### 🏷 Version 

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.49.1      |
| @antv/s2-vue   |     1.5.0    |

### Sheet Type

-  PivotSheet

### 🖋 Description
透视表数据有用百分号(%)的格式化，使用getSheetData方法带格式导出后，保留一位小数的数据导出后加了一个0变成了两位小数。

### ⌨️ Code Snapshots
<img width="1034" alt="image" src="https://github.com/antvis/S2/assets/52644550/cc34896e-77e8-46fc-96c0-7b9dcec3305b">

`    const s2DataConfig = {
      fields: {
        rows: ['province', 'city'],
        columns: ['type', 'sub_type'],
        values: ['number'],
      },
      meta: res.meta.map(it=>{
        if(it.field === 'number'){
          it.formatter = (value)=>{
            return `${value / 10}%` ;
          }
        }
        return it;
      }),
      data: res.data,
    };`
### 🔗 Reproduce Link

https://codesandbox.io/s/qtx6kp?file=/index.tsx
### 🤔 Steps to Reproduce
meta中数值字段添加formatter，保留1位小数，并加上%，使用getSheetData方法按格式导出

### 😊 Expected Behavior

按格式导出数据不对，期待界面上显示的和导出后的的显示一模一样。
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS Ventura  Apple M1     |
| Browser |     chrome v116.0.5845.187    |

**Comment by lijinke666** [comment]
Excel 有配置过单元格格式吗?

**Comment by lijinke666** [comment]
和 Excel 的单元格格式有关系, S2 构建的数据是没问题的, Excel 默认是两位小数, 自行修改即可

![image](https://github.com/antvis/S2/assets/21015895/161b7991-bbd6-4e91-aa65-ff5fc638f85a)


![image](https://github.com/antvis/S2/assets/21015895/5a10a0d3-c67f-4ff6-9741-c39a239422d1)
