### ISSUE TITLE
🤔透视表部份表头样式无法修改，已经配置了theme所有表头样式

### ISSUE THREAD

**Issue by woshishade** [antvis/S2#2352]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.50.0     |
| @antv/s2-react |    1.43.0     |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表部份表头样式无法修改，已经配置了theme所有表头样式，但是部份表头单元格还是无法调整
![image](https://github.com/antvis/S2/assets/10460238/1d479679-7e30-416e-bc13-c5f57f70102d)
透视表红框表头的样式可以修改吗？我这边已经按照文档配置了，但是没效果

**Comment by lijinke666** [comment]
![image](https://github.com/antvis/S2/assets/21015895/a9b755df-6bb2-4a0e-a983-8a172aea5f23)

黄框/绿框部分属于加粗字体, 对应的主题配置是 `bolderText` 而不是 `text`
黑框部分属于 度量值文本样式, 对应的主题配置是 `measureText` 而不是 `text`


https://s2.antv.antgroup.com/api/general/s2-theme#s2theme

![image](https://github.com/antvis/S2/assets/21015895/6113774f-d728-4fef-a859-b0da8f79d2be)
