### ISSUE TITLE
明细表隐藏列头怎么操作

### ISSUE THREAD

**Issue by hurricane1998** [antvis/S2#2358]
看官方文档里S2options里的style可以控制列头是否显示，

![image](https://github.com/antvis/S2/assets/56187561/c213808b-07e8-460b-9739-9ede17356e73)

我不知道是不是这个hideMeasureColumn属性，我在官方文档里使用这个属性没啥效果

![image](https://github.com/antvis/S2/assets/56187561/fb3b7d5e-b56e-4fca-b168-15eb9ae15ddf)

修改colCfg的height属性为0的话可以隐藏列头，但是第一行的边框也没有了，这个是bug还是设计如此呢？

![image](https://github.com/antvis/S2/assets/56187561/a7efe7b7-786a-4f5b-a4bb-106a7c8e6869)

如果是设计如此，那么最上面一行的边框要如何加上呢？

**Comment by lijinke666** [comment]
> 但是第一行的边框也没有了，这个是bug还是设计如此呢？ 

设计如此

> 如果是设计如此，那么最上面一行的边框要如何加上呢？

可以自定义列头, 然后不绘制文本, 然后设置列头的高度比如 `3px`, 这样就可以显示边框了

```tsx
import { TableSheet, ColCell } from '@antv/s2';

class CustomColCell extends ColCell {
  drawTextShape() {
    return null
  }
}

const s2Options = {
  width: 600,
  height: 480,
  style: {
    colCfg: {
      height: 3,
    },
  },
  colCell: (...args) => new CustomColCell(...args)
};
```

![image](https://github.com/antvis/S2/assets/21015895/c3cedc53-8aa1-4977-b9de-f54cefb4a469)

**Comment by hurricane1998** [comment]
非常感谢您的回复，我刚才用您的代码在官网示例demo上试了一下，确实可以添加上列头，但是有一个小问题，不知道您遇到了没有，就是第一行和自定义的列头之间有一层很小的距离。像下面这样，不知道还有更好的方案能解决这个问题吗？
![image](https://github.com/antvis/S2/assets/56187561/1d50e7b3-ac4c-473b-ba3d-adeb1ae3028c)
