### ISSUE TITLE
🐛 getMultiData 函数，获取需要汇总的数据时，会混入非明细数据。

### ISSUE THREAD

**Issue by NoobNotN** [antvis/S2#2371]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.2.0  |
| @antv/s2-react |  1.3.3  |
| @antv/s2-vue   |   -     |

### Sheet Type

- [x] PivotSheet

### 🖋 Description
表现：用户数据中，提供了行汇总数据，再进行列汇总计算时，行数据被重复汇总（汇总数据被计算一次，明细数据又被计算一次）
在线demo：https://codesandbox.io/s/affectionate-lamarr-kmxfmr?file=/index.ts
预期：
![image](https://github.com/antvis/S2/assets/56724970/f294af3f-9535-43fb-92be-1cd9cd8d8f3d)
不符合预期：
![image](https://github.com/antvis/S2/assets/56724970/9c0aaf56-f8c9-46b3-a63f-9dbd0356c5d9)
【更加棘手的是，排序功能获取排序数据恰好依靠此bug特性运行。。。】

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by wjgogogo** [comment]
参数传错了
![image](https://github.com/antvis/S2/assets/17964556/046fa2fe-ab5c-4999-898b-69bd2eeff9b3)
