### ISSUE TITLE
🤔使用css rotate，加了supportCSSTransform:true，滚动方向还是反向的？

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/S2#2372]
### 🏷 Version
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.44.0    |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet

### 🖋 Description

业务需要在屏幕过小时或移动端浏览器中将图表强制横屏，使用css transform rotate属性将图表旋转了90度，在配置中添加了supportCSSTransform:true，点击交互都正常，但滚动方向还是翻转之前的方向。

### 😊 Expected Behavior
翻转后的图表滚动方向按照当前的方向正常滚动

**Comment by lijinke666** [comment]
`supportCSSTransform` 只是确保 transform 后拿到的坐标是正确的, 表格滚动是不受影响的, 不支持这种场景, 垂直滚动对应 `deltaY`, 水平滚动对应 `deltaX`, 你可以提一个 PR, 支持横屏模式, 互换下 `deltaX/deltaY` 的值, 或者 `onWheel` 的时候新增一个 hook, 可以自定义 `deltaX/deltaY`, 以满足你的诉求

https://github.com/antvis/S2/blob/bd09e3d0f16bcf714e3f031e17feeeb6471d3295/packages/s2-core/src/facet/base-facet.ts#L954-L959
