### ISSUE TITLE
🐛父元素存在transform，s2设置devicePixelRatio之后，鼠标交互对应不上

### ISSUE THREAD

**Issue by wind108369** [antvis/S2#2374]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.51.1  |
| @antv/s2-react |  1.44.0  |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
因为表格所在的页面存在transform，如果不设置devicePixelRatio，渲染会变得模糊，但是设置之后鼠标交互会对不上

### ⌨️ Code Snapshots

https://codesandbox.io/s/sleepy-brattain-gp3hzm?file=/index.ts

### 🔗 Reproduce Link

https://codesandbox.io/s/sleepy-brattain-gp3hzm?file=/index.ts

### 🤔 Steps to Reproduce

<img width="537" alt="image" src="https://github.com/antvis/S2/assets/1305983/0da090ed-9d5f-4197-9e7b-fae829a0f09c">

此时我的鼠标是放到最后一列的，但是hover是倒数第二列

### 😊 Expected Behavior

如题

### 😅 Current Behavior

如题

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by wind108369** [comment]
另外，交互部分的代码大概在什么位置，之后有时间可以学习一下，给你们提pr

**Comment by lijinke666** [comment]
请多看文档, 避免重复提问

https://s2.antv.antgroup.com/manual/faq#%E7%88%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E4%BD%BF%E7%94%A8%E4%BA%86-transform-scale-%E5%90%8E%E5%9B%BE%E8%A1%A8%E9%BC%A0%E6%A0%87%E5%9D%90%E6%A0%87%E5%93%8D%E5%BA%94%E4%B8%8D%E6%AD%A3%E7%A1%AE

```diff
  const s2Options = {
    width: 600,
    height: 480,
    showSeriesNumber: true,
    devicePixelRatio: 1.6,
+   supportCSSTransform: true
  };
```

![image](https://github.com/antvis/S2/assets/21015895/538e450f-e522-4a87-8b95-ef9c30ca0f98)
