### ISSUE TITLE
🐛单元格点击行高亮后 拖动横向滚动条会导致高亮消失

### ISSUE THREAD

**Issue by AALiujiajun** [antvis/S2#2376]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.13.1     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

用的TableSheet

### ⌨️ Code Snapshots

在官网示例的s2Options里加上点击单元格整行高亮的代码
interaction: {
  selectedCellHighlight: {
            rowHeader: false, // 高亮行头
            colHeader: false, // 高亮列头
            currentRow: true, // 高亮选中单元格所在行
            currentCol: false // 高亮选中单元格所在列
          }
}
### 🤔 Steps to Reproduce

在官网示例的s2Options里加上点击单元格整行高亮的代码 触发整行高亮后 调整网页窗口宽度 使其出现横向滚动条 用鼠标拖动横向滚动条则整行高亮特效消失

### 😊 Expected Behavior

应该不会消失高亮的效果

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
未复现, 你使用 `1.13.1` 版本很低, 请尝试升级到最新版本看还能复现不? 另外, 请确保你访问的官网是 https://s2.antv.antgroup.com/

> https://s2.antv.antgroup.com 未能复现, 不管是表格滚动条, 还是网页滚动条

![Kapture 2023-10-20 at 11 05 45](https://github.com/antvis/S2/assets/21015895/8a39dee5-4169-4c4b-9f94-592ed6851beb)

**Comment by AALiujiajun** [comment]
> 未复现, 你使用 `1.13.1` 版本很低, 请尝试升级到最新版本看还能复现不? 另外, 请确保你访问的官网是 https://s2.antv.antgroup.com/
> 
> > https://s2.antv.antgroup.com 未能复现, 不管是表格滚动条, 还是网页滚动条
> 
> ![Kapture 2023-10-20 at 11 05 45](https://user-images.githubusercontent.com/21015895/276807054-8a39dee5-4169-4c4b-9f94-592ed6851beb.gif) [ ![Kapture 2023-10-20 at 11 05 45](https://user-images.githubusercontent.com/21015895/276807054-8a39dee5-4169-4c4b-9f94-592ed6851beb.gif) ](https://user-images.githubusercontent.com/21015895/276807054-8a39dee5-4169-4c4b-9f94-592ed6851beb.gif) [ ](https://user-images.githubusercontent.com/21015895/276807054-8a39dee5-4169-4c4b-9f94-592ed6851beb.gif)


我更新到了 1.45.1 
代码在这个网页里了  https://codesandbox.io/s/young-pond-746xf2?file=/src/index.js 
复现的时候 请粘贴这段代码 
 interaction: {
    selectedCellHighlight: {
      rowHeader: false,
      colHeader: false,
      currentRow: true,
      currentCol: false
    }
  } 

因为在官网用自动生成的序号是可以的（但是实际工作中我多了几个配置也不行 不知道咋回事）

**Comment by lijinke666** [comment]
水平的滚动条在 表格外, 点击的时候触发了重置的逻辑, 关掉就可以了, 后续优化下这个场景, 感谢反馈

```diff
const s2options = {
  width: 200,
  height: 600,
  interaction: {
+   autoResetSheetStyle: false,
    selectedCellHighlight: {
      rowHeader: false,
      colHeader: false,
      currentRow: true,
      currentCol: false
    }
  }
};
```

**Comment by AALiujiajun** [comment]
> ```diff
> autoResetSheetStyle: false,
> ```

阔以啊 大佬nb
