### ISSUE TITLE
透视表列头 不支持滑动滚动表格

### ISSUE THREAD

**Issue by haihengit** [antvis/S2#2381]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.41.0    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [✅ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表 列头比较深，差不多在9行左右，现在是否有支持滑动列头，实现表格内容的滚动的方式

**Comment by lijinke666** [comment]
不支持, 欢迎 PR
