### ISSUE TITLE
S2  文本超出单元格，如何换行？

### ISSUE THREAD

**Issue by weibinhua** [antvis/S2#2382]
S2  文本超出单元格，如何换行？

**Comment by lijinke666** [comment]
目前不支持换行

文本换行功能开发中, 将在后续 2.0 版本中支持 https://github.com/antvis/S2/pull/2383 

> 使用问题, 请在 https://github.com/antvis/S2/discussions 提交

**Comment by XiChaoMing** [comment]
哈喽，2.0 版本预计啥时候上？非常需要这个换行功能~
