### ISSUE TITLE
🙏 透视表和明细表支持单元格虚线

### ISSUE THREAD

**Issue by aimerthyr** [antvis/S2#2400]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.51.2      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🏞 What problem does this feature solve

1. 透视表和明细表都支持单元格虚线
![image](https://github.com/antvis/S2/assets/44153856/7fd78f9f-3302-4c79-9bf6-4de008d835a3)
![image](https://github.com/antvis/S2/assets/44153856/9b6c01e1-be05-447f-a74e-70bb69e649ee)
2. 透视表和明细表都支持分割线虚线
![image](https://github.com/antvis/S2/assets/44153856/aa224c21-f398-4d52-9b3e-f3395f440ee9)

需求是对图表的边线进行自定义

**Comment by lolipop99** [comment]
@lijinke666 2.x版本无此功能，请重新合并此commit
