### ISSUE TITLE
🐛明细表超过5000列就会很卡

### ISSUE THREAD

**Issue by kkkisme** [antvis/S2#2402]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |    latest       |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

明细表超过5000列时（仅10行），拖动横向滚动条会很卡

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
5000 列的使用场景和意义分别是?

**Comment by kkkisme** [comment]
> 5000 列的使用场景和意义分别是?

https://github.com/antvis/S2/issues/2387

**Comment by xu-yi-hang** [comment]
s2提供了垂直的虚拟滚动，横向的，可以自己实现一下。

**Comment by NightRiderss** [comment]
https://s2-v1.antv.antgroup.com/examples/case/performance-compare/#pivot
https://s2.antv.antgroup.com/examples/case/performance-compare/#pivot
同样的100w数据 将宽高设置为2000缩放浏览器，尽可能的展示多点数据。
v1不卡，但是v2却卡的滚动不了
