### ISSUE TITLE
🙏 tree-shaking is not work

### ISSUE THREAD

**Issue by hemisu** [antvis/S2#2404]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

仅引用常量，打包的代码体积过大

见 [stackblitz](https://stackblitz.com/edit/github-psdsg2?file=src%2Findex.js)

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
目前打包的 `esm` 是单文件, 引用太复杂了, tree shaking 确实有问题, 2.0 版本会解决这个问题
