### ISSUE TITLE
图表绘制完成的监听事件有吗？

### ISSUE THREAD

**Issue by XiChaoMing** [antvis/S2#2409]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.30.0    |
| @antv/s2-react |    1.27.0    |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by XiChaoMing** [comment]
目前的场景需要做看板截图，但现在无法准确知道图表是否绘制完成，会出现截图在绘制完成前进行，导致截图出来不准确

**Comment by lijinke666** [comment]
文档都有写, 多看看文档再提问
文档都有写, 多看看文档再提问
文档都有写, 多看看文档再提问

感谢

> s2-core

https://s2.antv.antgroup.com/api/general/s2-event#%E5%B8%83%E5%B1%80

![image](https://github.com/antvis/S2/assets/21015895/c4620272-ee2d-468b-813b-ecee3363e9c1)

> s2-react

https://s2.antv.antgroup.com/api/components/sheet-component

![image](https://github.com/antvis/S2/assets/21015895/7889c6fb-aea4-4ecf-afac-f54372733b47)


> 使用问题, 请在讨论区提问, 谢谢 https://github.com/antvis/S2/discussions
