### ISSUE TITLE
🤔 当表格没有数据，怎么添加一个空状态，类似antd表格的empty状态

### ISSUE THREAD

**Issue by oliver34** [antvis/S2#2418]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by oliver34** [comment]
![image](https://github.com/antvis/S2/assets/12234456/c49b352a-0160-4ba1-8bba-ab8cd8f8ca53)
类似这种形式

**Comment by lijinke666** [comment]
目前不支持, 只能用一个 div 定位在 Canvas 表格的上面, 2.0 版本会内置这个特性
