### ISSUE TITLE
🤔明细表如何实现自定义单元格内容，例如说在单元格的数字里添加符号

### ISSUE THREAD

**Issue by 18211365467** [antvis/S2#2420]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by xu-yi-hang** [comment]
meta data

**Comment by lijinke666** [comment]
通过 `s2DataConfig.meta` 配置字段的格式化即可。请仔细阅读文档后再提问，感谢。 https://s2.antv.antgroup.com/api/general/s2-data-config#meta

```diff
  const s2DataConfig = {
    data,
    fields: {
      columns: ['province', 'city', 'type', 'price', 'cost'],
    },
+    meta: [
+      {
+        field: 'city',
+        name: '城市',
+        formatter: (value) => `${value}-@`
+      },
   ]
 };
```
