### ISSUE TITLE
🙏  链接跳转 - 透视表支持 colums

### ISSUE THREAD

**Issue by Jacleklm** [antvis/S2#2430]
### 🏷 Version
| Package        | Version |
| -------------- | ------- |
| @antv/s2-react | 1.44.2 |

### Sheet Type
- [x] PivotSheet

### 🖋 Description
希望透视表的链接跳转支持 colums, 当前不支持。[s2文档](https://s2.antv.vision/manual/advanced/interaction/link-jump#%E9%80%8F%E8%A7%86%E8%A1%A8)

**Comment by lijinke666** [comment]
来个 PR ?

**Comment by lijinke666** [comment]
2.0 支持
