### ISSUE TITLE
🎉  S2 2.0 版本开始内测啦 !!!

### ISSUE THREAD

**Issue by lijinke666** [antvis/S2#2454]
### Discussed in https://github.com/antvis/S2/discussions/1933

了解 2.0 版本新特性 - [S2 2.0 表格看数新纪元](https://www.yuque.com/antv/blog/1122_7_s2) 和 [roadmap](https://github.com/antvis/S2/issues/2153)

## 🏠 官网地址变化

原官网 <https://s2.antv.vision> 和 <https://antv-s2.gitee.io> 不再维护和使用，请使用最新的文档，确保您看到的不是过时的文档。

- 原 `v1` 官网迁移至 <https://s2-v1.antv.antgroup.com>.
- 原 <https://s2.antv.antgroup.com> 将作为 `v2` 默认官网。

## 🏷️ npm dist-tag 变化

> 什么是 [dist-tag](https://docs.npmjs.com/adding-dist-tags-to-packages/) ?

`S2 2.0` 版本目前处于**内测阶段**, 部分 API 可能会根据合理性随时改动。

`npm` 的 [`dist-tag`](https://docs.npmjs.com/cli/v10/commands/npm-dist-tag) 对应关系如下：

- `@antv/s2@next` 对应 `2.x` 版本
- `@antv/s2@latest` 对应 `1.x` 版本

## 📅 正式版本发布时间

目前 `next` 会持续内测一段时间，https://s2.antv.antgroup.com 会作为相应的文档网站。

在此期间，会持续根据用户的反馈进行 Bug fix 和代码调整，在 `@antv/s2@next` 版本稳定后，会发布正式版本, `latest` 将默认指向 `2.x` 版本，去除 `next` 标识。

## 🗓️ v1 版本维护期

目前 `v1` 版本会继续维护，针对 `BUG` 发布 `Patch` 版本修复，但不再接收新的 `Feature Request` 和 `Feature Pull Request`，欢迎 `Bug Fix Pull Request`, 截止日期为 `2024` 年年底。

## 📦 安装

| Package  | Version | Size   | Download     |
| - | - | - | - |
| [@antv/s2](https://github.com/antvis/S2/tree/next/packages/s2-core) |  ![next](https://img.shields.io/npm/v/@antv/s2/next.svg)  | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2@next/dist/index.min.js?label=gzip%20size&compression=gzip)       | ![download](https://img.shields.io/npm/dm/@antv/s2.svg)       |
| [@antv/s2-react](https://github.com/antvis/S2/tree/next/packages/s2-react) | ![next](https://img.shields.io/npm/v/@antv/s2-react/next.svg)| ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2-react@next/dist/index.min.js?label=gzip%20size&compression=gzip) | ![download](https://img.shields.io/npm/dm/@antv/s2-react.svg) |
| [@antv/s2-vue](https://github.com/antvis/S2/tree/next/packages/s2-vue) | ![next](https://img.shields.io/npm/v/@antv/s2-vue/next.svg) | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2-vue@next/dist/index.min.js?label=gzip%20size&compression=gzip)   | ![download](https://img.shields.io/npm/dm/@antv/s2-vue.svg)   |

```bash
# 基础版本
yarn add @antv/s2@next --save

# React 版本
yarn add @antv/s2-react@next antd @ant-design/icons --save

# Vue3 版本
yarn add @antv/s2-vue@next ant-design-vue@3.x --save
```

具体请查看 [2.0 升级指南](https://s2.antv.antgroup.com/manual/migration-v2)

欢迎尝鲜, 有任何问题欢迎在讨论区或 issue 区留言评论.

**Comment by xiaochong44** [comment]
@lijinke666 多行文本的能像字节的vtable一样，单元格高度也自适应吗？

**Comment by firmianaQ** [comment]
能支持单元格的拖拽事件吗

**Comment by lijinke666** [comment]
> @lijinke666 多行文本的能像字节的vtable一样，单元格高度也自适应吗？

是自适应的

**Comment by lijinke666** [comment]
> 能支持单元格的拖拽事件吗

如果指的是像 Excel 那样的行列拖拽的话, 在 2.0 后续的规划中

**Comment by happypayne** [comment]
明细表冻结列之后，无法合并单元格，新版本会支持吗

**Comment by firmianaQ** [comment]
能完全自定义单元格吗？就是单元格内的内容是使用@antv/g的图形绘制的

**Comment by cliens** [comment]
你好， 想了解一下2.0正式版本发布预测大概多久？

**Comment by lijinke666** [comment]
> 你好， 想了解一下2.0正式版本发布预测大概多久？

暂时没有一个明确的时间, 先收集社区和内部反馈进行调整, 稳定后发布正式版.

**Comment by firmianaQ** [comment]
> > 能完全自定义单元格吗？就是单元格内的内容是使用@antv/g的图形绘制的
> 
> 可以的, 你自己试试不就知道了? S2 的每一个单元格就是 `g` 的一个 [group](https://g.antv.antgroup.com/api/basic/group), 所以你可以任意绘制 g 的[图形](https://g.antv.antgroup.com/api/basic/circle), 甚至是任意基于 `g` 的上层图表库, 共享同一个图层, 比如[在单元格内绘制 G2](https://s2.antv.antgroup.com/manual/advanced/chart-in-cell)

😢我试了的，升级到2.x，改成g的图形，结果都不行了，可能改的有问题

**Comment by db-shuai** [comment]
透视表：布局方式使用 layoutWidthType: 'colAdaptive',
行头稍微长一点 就会展示 省略号，v1版本缺不会

https://codesandbox.io/p/sandbox/little-butterfly-fq9m6j?file=%2Fpackage.json%3A9%2C2

**Comment by db-shuai** [comment]
树状透视表： rowCellCollapseTreeRows 事件是否已废弃？
使用什么替代？

**Comment by lijinke666** [comment]
> 透视表：布局方式使用 layoutWidthType: 'colAdaptive', 行头稍微长一点 就会展示 省略号，v1版本缺不会
> 
> [codesandbox.io/p/sandbox/little-butterfly-fq9m6j?file=%2Fpackage.json%3A9%2C2](https://codesandbox.io/p/sandbox/little-butterfly-fq9m6j?file=%2Fpackage.json%3A9%2C2)

已修复

**Comment by cliens** [comment]
![2024-07-03 at 16 15](https://github.com/antvis/S2/assets/11920733/41a1df0e-c33b-4611-98d9-a1b7aeb12849)

react-dom@17.02

**Comment by cliens** [comment]
<img width="1420" alt="image" src="https://github.com/antvis/S2/assets/11920733/abb5be5d-2ee4-47e9-a8c5-573bd3d41e27">
react-dom@17.0.2

**Comment by lijinke666** [comment]
> <img alt="image" width="1420" src="https://private-user-images.githubusercontent.com/11920733/345343511-abb5be5d-2ee4-47e9-a8c5-573bd3d41e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTk2OTEsIm5iZiI6MTcxOTk5OTM5MSwicGF0aCI6Ii8xMTkyMDczMy8zNDUzNDM1MTEtYWJiNWJlNWQtMmVlNC00N2U5LWE4YzUtNTczYmQzZDQxZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Mjk4NTc0ZGVlOTgyMDAyOWE4YjJjYWFhZGM4MmE4MDk4MzRlM2FlZWEwOTY3ZWQ1ZGRkNzExZmE0Y2Q3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBRM_PqN2cHZDC93d3fTRvMUQZmIUdst3zao9mSJKBI"> react-dom@17.0.2

已知问题: https://github.com/antvis/S2/pull/2802

**Comment by elephantme** [comment]
总计小计，总计列数据不展示的问题：
数据配置：
```javascript
{
	"s2Config": {
		"fields": {
			"rows": [],
			"columns": ["date"],
			"values": ["204f5fb8-7591-4ede-9974-baa049c1ba20"],
			"valueInCols": false
		},
		"meta": [{
			"name": "日期",
			"field": "date"
		}, {
			"field": "204f5fb8-7591-4ede-9974-baa049c1ba20",
			"name": "Web 浏览页面的总次数"
		}],
		"sortParams": [{
			"sortFieldId": "date",
			"sortMethod": "DESC"
		}],
		"data": [{
			"date": "2024-07-08",
			"204f5fb8-7591-4ede-9974-baa049c1ba20": 14918
		}, {
			"204f5fb8-7591-4ede-9974-baa049c1ba20": 14918
		}]
	},
	"s2Options": {
		"height": 500,
		"tooltip": {},
		"interaction": {
			"linkFields": []
		},
		"totals": {
			"col": {
				"showGrandTotals": true,
				"showSubTotals": true,
				"reverseGrandTotalsLayout": true,
				"reverseSubTotalsLayout": true
			}
		},
		"style": {}
	}
}
```
实际结果：
![image](https://github.com/antvis/S2/assets/20337682/80f73c86-1b38-494c-a002-982e9b712b05)
期望结果：
![image](https://github.com/antvis/S2/assets/20337682/aa0a8a2e-897f-46d1-bedf-018b30473207)

**Comment by renruijun** [comment]
能否支持下横屏（全屏）场景？ 目前调用浏览器屏幕方向api受到一些限制，感觉这个场景在移动端上还是有很多需求的。

**Comment by caiyan1121** [comment]
2.X是否支持移动端的展示？

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/issues/2986
