### ISSUE TITLE
🐛 自定义目录树的tooltip显示和折叠的rowKey有问题

### ISSUE THREAD

**Issue by oliver34** [antvis/S2#2455]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.52.1  |
| @antv/s2-react |  1.44.3  |
| @antv/s2-vue   |         |

### Sheet Type

 ✅  PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

自定义目录树存在两个问题：
1. 如果两个树的父节点的`title`一样，那么一个折叠另一个也会折叠，而不是根据`key`来的
2. 默认tooltip展示的又是节点的`key`，而不是`title`

具体看截图，下面有codesandbox 链接
![image](https://github.com/antvis/S2/assets/12234456/776c025b-4492-4da2-9744-6f3273dc7b3e)
![image](https://github.com/antvis/S2/assets/12234456/a26bae84-7ca9-4a20-a5bc-676bf385c821)

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/old-currying-p3xz89?file=%2Findex.tsx
### 😊 Expected Behavior
希望折叠的根据`key`来做唯一标识，tooltip展示`title`

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
> 如果两个树的父节点的title一样，那么一个折叠另一个也会折叠，而不是根据key来的

问题1, 确实 1.x, 2.x 都有问题.

> 默认tooltip展示的又是节点的key，而不是title

问题 2, 在 2.0 版本中已修复

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/2551
