### ISSUE TITLE
🙏 希望主题设置中 「dataCell.cell.interactionState」可以支持配置各种状态（hover,selected) 下的文字颜色

### ISSUE THREAD

**Issue by xulingling0** [antvis/S2#2458]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.45.1     |
| @antv/s2-react |     1.31.0    |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

#### 我的需求：
   dataCell 单元格 在 hover, selected状态下，字体颜色变为对应状态颜色，而非默认色（dataCell.text.fill)

#### 现状：
 只支持设置以下属性（https://s2.antv.antgroup.com/api/general/s2-theme#interactionstatetheme）
<img width="943" alt="image" src="https://github.com/antvis/S2/assets/107020065/837857da-fa6d-4529-8d47-7ef02824b3b4">
  

### 🧐 Suggest the API

在 `InteractionStateTheme` 新增  `textColor`  属性
| name | type | default | description |
| ---- | ---- | ------- | ----------- |
|  textColor   | string | undefined     |       文字颜色   |

**Comment by lijinke666** [comment]
来个 pr?

**Comment by xulingling0** [comment]
希望官方支持，或者提供下替代的方案

**Comment by xulingling0** [comment]
> 来个 pr?

希望官方支持，或者提供下替代的方案
