### ISSUE TITLE
🤔antvS2表格中的icon如何调整大小

### ISSUE THREAD

**Issue by ctrl-c-bit** [antvis/S2#2464]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/discussions/2465
