### ISSUE TITLE
s2禁用选中高亮不生效🤔

### ISSUE THREAD

**Issue by p-al-ace** [antvis/S2#2468]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.52.1     |
| @antv/s2-react |     1.44.3    |

### Sheet Type

- [ ✅ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

 interaction: {
      selectedCellHighlight: {
        rowHeader: false,
        colHeader: false,
        currentRow: false,
        currentCol: false,
      },
      selectedCellsSpotlight: false,
    },
这样配置后，点击单元格时该单元格会高亮；点击行头时该行会高亮

**Comment by lijinke666** [comment]
正如文档所说, `selectedCellHighlight` 是配置选中数值单元格后对应的行列的联动, 和你期望的不是一回事

![image](https://github.com/antvis/S2/assets/21015895/48906456-f8f0-4604-a716-874159ec8b7a)

目前没有相关配置项, 如果你期望的是禁用数值单元格的选中高亮, 以及对应的行列多选, 可以参考[这个示例](https://s2.antv.antgroup.com/examples/interaction/basic/#state-theme)

```tsx

const stateTheme = {
  cell: {
    interactionState: {
      selected: {
        backgroundColor: 'transparent',
        borderColor: 'transparent',
      },
    },
  },
};
 
const s2ThemeConfig = {
  theme: {
    rowCell: stateTheme,
    colCell: stateTheme,
    dataCell: stateTheme,
  },
};


<SheetComponent themeCfg={s2ThemeConfig}/>
```

**Comment by lijinke666** [comment]
ref #2439

**Comment by p-al-ace** [comment]
> 正如文档所说, `selectedCellHighlight` 是配置选中数值单元格后对应的行列的联动, 和你期望的不是一回事
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/289768558-48906456-f8f0-4604-a716-874159ec8b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjk0OTQsIm5iZiI6MTcwMjM2OTE5NCwicGF0aCI6Ii8yMTAxNTg5NS8yODk3Njg1NTgtNDg5MDY0NTYtZjhmMC00NjA0LWE3MTYtODc0MTU5ZWM4YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4MTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MjM2MWQ2NzU3MGFmMWZmYmM3MTUxODlhMDBkZjc1ZTNhZTIzOWZmMTA3NzkwMzg2MjQ0NmIxMGEzMTYxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2kIYXyXT3oMO4b8Qnupz_DgcbGTXjyAwYQUJNFVIE2o)
> 
> 目前没有相关配置项, 后面会改进这块, 确实容易造成疑惑, 如果你期望的是禁用数值单元格的选中高亮, 以及对应的行列多选, 可以参考[这个示例](https://s2.antv.antgroup.com/examples/interaction/basic/#state-theme)
> 
> ```tsx
> const stateTheme = {
>   cell: {
>     interactionState: {
>       selected: {
>         backgroundColor: 'transparent',
>         borderColor: 'transparent',
>       },
>     },
>   },
> };
>  
> const s2ThemeConfig = {
>   theme: {
>     rowCell: stateTheme,
>     colCell: stateTheme,
>     dataCell: stateTheme,
>   },
> };
> 
> 
> <SheetComponent themeCfg={s2ThemeConfig}/>
> ```

解决了，非常感谢👍
