### ISSUE TITLE
🤔怎么在表头中设置带下标的文字

### ISSUE THREAD

**Issue by li-guanlong** [antvis/S2#2470]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^1.48.0     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [✔️ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

希望能够在表头的文字设置时，能够设置下标的单位展示
<img width="50" alt="image" src="https://github.com/antvis/S2/assets/54611134/492bd1c8-cb1f-45d3-91bc-f6c8498154a8">

**Comment by lijinke666** [comment]
可以定制单元格，然后在文字后面绘制一个下标，参考这个用户的做法

https://github.com/antvis/S2/issues/2471#issue-2036884806
