### ISSUE TITLE
🙏 透视表支持点击角头（列）字段时，选中相应行

### ISSUE THREAD

**Issue by ixuxinyue** [antvis/S2#2480]
### 🏷 Version
s2-react-v1.46.0-alpha.2

### Sheet Type
PivotSheet

### 希望透视表支持点击角头（列）字段时，选中相应行
<img width="649" alt="image" src="https://github.com/antvis/S2/assets/22525231/317148ad-ba2c-4d8f-a80c-d82cd983b03e">

**Comment by lijinke666** [comment]
resolved https://github.com/antvis/S2/pull/2571
