### ISSUE TITLE
🤔  master 丢失部分changeLog （@antv/s2-v1.53.0 正常),   会导致升级 s2 版本时影响范围不可控

### ISSUE THREAD

**Issue by xulingling0** [antvis/S2#2483]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.54.1      |
| @antv/s2-react |    1.46.0     |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

#### @antv/s2-v1.53.0([changeLog](https://github.com/antvis/S2/blob/%40antv/s2-v1.53.0/packages/s2-core/CHANGELOG.md))
  
  变更记录包含 v1.42.1-  v1.50.0 每个版本的变更记录
![image](https://github.com/antvis/S2/assets/107020065/f1c2cbf8-e57a-4e70-88b7-2e3bcc822e25)

####  master ([changeLog](https://github.com/antvis/S2/blob/master/packages/s2-core/CHANGELOG.md))
变更记录从 v1.42.1 直接跳到  @antv/s2-v1.50.0-alpha.1
<img width="855" alt="image" src="https://github.com/antvis/S2/assets/107020065/21169842-b2d7-495b-97ba-efa1be1cabcb">

 
### 😊 Expected Behavior
 `s2-core`,  `s2-react`  都存在changeLog 丢失问题
1.  ChangeLog 丢失是否故意为之？
2. 作为第三方开发者，升级 s2 依赖时，是否只需参考 master 分支的 ChangeLog？

**Comment by lijinke666** [comment]
> ChangeLog 丢失是否故意为之？

不是, 可能是之前 merge 到 master 有冲突, 合并掉了

> 作为第三方开发者，升级 s2 依赖时，是否只需参考 master 分支的 ChangeLog？

以 https://github.com/antvis/S2/releases 为准
