### ISSUE TITLE
🤔透视表隐藏列

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/S2#2486]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^1.44.0     |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

问题：怎么隐藏id这一列 
![image](https://github.com/antvis/S2/assets/50241817/9bab81e7-32f8-422c-8ed9-8a0f1b456681)

**Comment by wjgogogo** [comment]
`fields.rows` 不传，就不会渲染，行头没有交互时隐藏的能力
