### ISSUE TITLE
🐛排序 按汇总排序 结果错乱

### ISSUE THREAD

**Issue by shuangxunian** [antvis/S2#2487]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.54.1    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ x ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

1.54.1版本的按值排序出来的结果是乱的，当降到1.49.0时正常

### ⌨️ Code Snapshots

官网链接：
https://s2.antv.antgroup.com/zh/examples/analysis/sort/#custom-totals

代码链接：
https://pastebin.ubuntu.com/p/NHw3BFmcSw/

仅是s2DataConfig不同，其它相同。

### 🤔 Steps to Reproduce
将代码执行，可发现 sortParams[0] 下的 sortMethod 为 desc，即应为降序，但是对应的排在第一个的 count_1[&]origin 的值为1，5在1的后面。

### 😊 Expected Behavior
正确的结果：desc时5应该为第一个（1.49.0即这样），

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     macOS 12.3    |
| Browser |     chrome: v120.0    |

**Comment by wjgogogo** [comment]
`[&]`是内部使用的保留字段，不建议使用，可能会导致和内部的分隔符冲突，以前之前在排序场景下是ok的，在其他某些场景下也有问题，`count_1[&]origin`可以改为`count_1-origin`等形式

**Comment by shuangxunian** [comment]
> `[&]`是内部使用的保留字段，不建议使用，可能会导致和内部的分隔符冲突，以前之前在排序场景下是ok的，在其他某些场景下也有问题，`count_1[&]origin`可以改为`count_1-origin`等形式

-这个不太行，会和用户的数据冲突，那要是[xbb]这个呢？可以吗，我在代码里面没有搜到对应的关键字

**Comment by wjgogogo** [comment]
> > `[&]`是内部使用的保留字段，不建议使用，可能会导致和内部的分隔符冲突，以前之前在排序场景下是ok的，在其他某些场景下也有问题，`count_1[&]origin`可以改为`count_1-origin`等形式
> 
> -这个不太行，会和用户的数据冲突，那要是[xbb]这个呢？可以吗，我在代码里面没有搜到对应的关键字
可以的，也可以等 #2488 修复

**Comment by shuangxunian** [comment]
> > > `[&]`是内部使用的保留字段，不建议使用，可能会导致和内部的分隔符冲突，以前之前在排序场景下是ok的，在其他某些场景下也有问题，`count_1[&]origin`可以改为`count_1-origin`等形式
> > 
> > 
> > -这个不太行，会和用户的数据冲突，那要是[xbb]这个呢？可以吗，我在代码里面没有搜到对应的关键字
> 
> 可以的，也可以等 #2488 修复

万分感谢 也就是说我还是可以继续使用[&]这个字段吗，刚刚前后端共同查了一下，发现改动[&] => [xbb]的话代价有点大，也有风险。
