### ISSUE TITLE
🐛使用SpreadSheet：setOptions(options,true) 后 data部分tooltip展示空白。

### ISSUE THREAD

**Issue by db-shuai** [antvis/S2#2489]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 1.54.1  |
| @antv/s2-react |         |
| @antv/s2-vue   | 1.6.0   |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在VUE中使用 `SheetComponent` 初始化后`tooltip`展示正常,
但调用 `SpreadSheet：setOptions(options,true) ` 后，`data` 区域内的 `tooltip` 悬浮为空白块。

<img width="714" alt="image" src="https://github.com/antvis/S2/assets/40795095/bd51bbd6-a4f2-4661-b9c7-7106c9d67dc5">

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/cranky-mopsa-5mflpr?file=%2Fsrc%2FApp.vue%3A9%2C19

### 🤔 Steps to Reproduce

示例中点击 设置 按钮，
然后鼠标点击数据区域单元格 可看到展示出的tooltip为空白块。

### 😊 Expected Behavior

调用 `setOptions(options, true)` 后，data区域的`tooltip` 正常展示而非空白块。

### 😅 Current Behavior

调用 `setOptions(options, true)`后，data区域的`tooltip` 展示为空白块。

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  | MacOS Monterey M1 |
| Browser |chrome:  120.0.6099.62 |

**Comment by lijinke666** [comment]
`Vue` 的 tooltip 是通过 `renderTooltip` 自定义的 tooltip

![image](https://github.com/antvis/S2/assets/21015895/1f97dce5-04a0-4683-b752-906e16ba38a1)

你这里的 `s2Table` 拿到的是 `@antv/s2` 实例引用, 所以 `s2Table.setOptions(options, true)` 执行后 tooltip 配置被重置成了 `@antv/s2` 的默认配置, 所以变成了空白.

![image](https://github.com/antvis/S2/assets/21015895/164565bd-707a-45a3-b00b-21e9f6fb9c42)

你可以直接改 `const options = reactive(rawOptions)` 的值, 或者这样

```diff
- s2Table.setOptions(options, true);
+ s2Table.setOptions(
+  {
+    ...options,
+    tooltip: s2Table.options.tooltip,
+  },
+  true
);
```

![image](https://github.com/antvis/S2/assets/21015895/869c0038-296b-4e31-8b21-ca5465da16e0)
