### ISSUE TITLE
🐛明细表隐藏表头hiddenColumns更改，将部分字段取消隐藏，UI没有重新渲染

### ISSUE THREAD

**Issue by QJerryxjh** [antvis/S2#2495]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.54.2   |
| @antv/s2-react |  1.46.0  |
### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

明细表初始指明hiddenColumnFields部分字段，重新更改hiddenColumnFields此时隐藏列并非新制定的hiddenColumnFields内列，而是取了两次hiddenColumnFields的交集

### ⌨️ Code Snapshots

```typescript
const App = () => {
  const [data, setData] = useState([]);
  const [hiddenColumnFields, setHiddenCols] = useState(["city", "price"]);
  useEffect(() => {
    fetch("https://assets.antv.antgroup.com/s2/basic-table-mode.json").then(
      (res) =>
        res.json().then((res) => {
          setData(res);
        })
    );
  }, []);

  const s2DataConfig = useMemo(() => {
    return {
      fields: {
        columns: ["province", "city", "type", "price", "cost"],
      },
      meta: [
        {
          field: "province",
          name: "省份",
        },
        {
          field: "city",
          name: "城市",
        },
        {
          field: "type",
          name: "商品类别",
        },
        {
          field: "price",
          name: "价格",
        },
        {
          field: "cost",
          name: "成本",
        },
      ],
      data: data,
    };
  }, [data]);

  const s2Options = useMemo(() => {
    return {
      width: 600,
      height: 480,
      interaction: {
        hiddenColumnFields: hiddenColumnFields,
      },
    };
  }, [hiddenColumnFields]);

  console.log(s2Options);

  return (
    <div>
      <button
        onClick={() => {
          setHiddenCols(["city"]);
        }}
      >
        change to sub
      </button>
      <button
        onClick={() => {
          setHiddenCols(["type"]);
        }}
      >
        change to other fields
      </button>
      <SheetComponent
        dataCfg={s2DataConfig}
        options={s2Options}
        sheetType="table"
      />
    </div>
  );
};
```

### 🔗 Reproduce Link

[复现链接](https://codesandbox.io/p/sandbox/serene-chaum-3dyg8f?file=%2Findex.tsx%3A53%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxe9z6000063b6hcgvhv52v%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxe9z6000023b6hzppw1lb5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxe9z6000033b6hbyvuuudo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxe9z6000053b6hvevso94a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.48308583558236%252C48.51691416441764%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxe9z6000023b6hzppw1lb5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxe9z6000013b6ho6rkpxso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A53%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A53%252C%2522endColumn%2522%253A36%257D%255D%257D%255D%252C%2522id%2522%253A%2522clqxe9z6000023b6hzppw1lb5%2522%252C%2522activeTabId%2522%253A%2522clqxe9z6000013b6ho6rkpxso%2522%257D%252C%2522clqxe9z6000053b6hvevso94a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxe9z6000043b6hoz80tx0n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqxe9z6000053b6hvevso94a%2522%252C%2522activeTabId%2522%253A%2522clqxe9z6000043b6hoz80tx0n%2522%257D%252C%2522clqxe9z6000033b6hbyvuuudo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqxe9z6000033b6hbyvuuudo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 🤔 Steps to Reproduce

初始隐藏 `["city", "price"]`两个字段，点击 `change to sub` 按钮，此时UI没有变化
点击`change to other fields`改变hiddenColumnFields 为`['type']`,此时 `city`和`price`依然不可见

### 😊 Expected Behavior

预期根据最新指示的hiddenColumnFields控制隐藏列展示UI

### 😅 Current Behavior

取了几次指定options指定的hiddenColumnFields的交集

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS14.1.2     |
| Browser |    120.0.6099.129（正式版本） (arm64)     |

**Comment by lijinke666** [comment]
ref #2507
