### ISSUE TITLE
🐛 多列同名时，表格交互多处异常

### ISSUE THREAD

**Issue by LUUUAN** [antvis/S2#2502]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      1.54.2   |
| @antv/s2-react |      1.46.0 |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

当两列 name 相同时，会出现多种问题，如：
<img width="1384" alt="image" src="https://github.com/antvis/S2/assets/48037246/717fd44e-181a-45ef-81cc-01a02f786cf7">
测试发现隐藏列也不能正常使用。
看了下代码，似乎是因为`generateHeaderNodes`方法里将 fieldValue 拼接成为了列的 id，但是 fieldValue 可能重复
### 😊 Expected Behavior

field不同，但name相同时不应该影响使用

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
临时解决方案, 在其中一个同名字段后面加一个空格, 由于涉及到整体链路改动, 在2.0 版本优化改问题

```diff
  "meta": [
    {
      "field": "field-1",
      "name": "数量",
    },
    {
      "field": "field-2",
-      "name": "数量",
+      "name": "数量 ",
    },
  ]
```

**Comment by lijinke666** [comment]
#2510

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/2568
