### ISSUE TITLE
🐛复制内容时，列头名称包含 - 时，内容会被截断

### ISSUE THREAD

**Issue by LazyJoke** [antvis/S2#2504]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.54.2  |

### Sheet Type

- [ ] PivotSheet
- [*] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

复制内容时，列头名称包含 - 时，内容会被截断；比如 列头名称为 “商品-类别”，复制的内容则为 “商品”

### 🔗 Reproduce Link

[Demo](https://codesandbox.io/p/sandbox/bold-star-y4cw3n?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr63ncra0006356krtyck3bh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr63ncr90002356k7ul604dj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr63ncra0003356k3ijq9dml%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr63ncra0005356kpj2003zw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.29839810358451%252C43.70160189641549%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr63ncr90002356k7ul604dj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr63ncr90001356kmlmq6ulq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr63ncr90002356k7ul604dj%2522%252C%2522activeTabId%2522%253A%2522clr63ncr90001356kmlmq6ulq%2522%257D%252C%2522clr63ncra0005356kpj2003zw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr63ncra0004356k2nhohlnk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr63ncra0005356kpj2003zw%2522%252C%2522activeTabId%2522%253A%2522clr63ncra0004356k2nhohlnk%2522%257D%252C%2522clr63ncra0003356k3ijq9dml%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr63ncra0003356k3ijq9dml%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by lijinke666** [comment]
已知问题, 复制导出问题有点多, 会在 2.0 版本重构解决

![image](https://github.com/antvis/S2/assets/21015895/15c78969-6323-4fbd-981f-2ab19d39dd79)

**Comment by LazyJoke** [comment]
> 已知问题, 复制导出问题有点多, 会在 2.0 版本重构解决, 可以暂时替换成 `商品_类别` 或 `商品~类别` 解决.
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/296178049-772ff0ba-98f7-446e-9427-8631955bc3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTg2MDMsIm5iZiI6MTcwNTMxODMwMywicGF0aCI6Ii8yMTAxNTg5NS8yOTYxNzgwNDktNzcyZmYwYmEtOThmNy00NDZlLTk0MjctODYzMTk1NWJjM2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDExMzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODlhNmQ2OWVhZmM1N2Y1NjJjZWMzM2QzYTBiMjczZjE3ZmE3YWMzNjVhMzc4ZDZmM2ZlZmJhMGNhZGE4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LKJN75Z7OFjg3es-YIjsOifi95FA_WrCMr9f-b_uMow)

非常感谢
