### ISSUE TITLE
vue3 下钻功能Bug

### ISSUE THREAD

**Issue by machachong** [antvis/S2#2505]
### 🏷 Version 
@antv/s2-vue": "^1.6.0

### Sheet Type
基础表组件
SheetComponent

### 🖋 Description
在vue3中使用antv/s2-vue，下钻功能，import "ant-design-vue/dist/antd.css";引入报错，因为在ant-design-vue中的css文件只有reset.css,换成这个后成功运行，但是下钻功能失效

import { SheetComponent } from "@antv/s2-vue";
import { defineComponent, shallowRef, reactive } from "vue";
import { forEach, random } from "lodash";
import "@antv/s2-vue/dist/style.min.css";
import "ant-design-vue/dist/antd.css";

### 🔗 Reproduce Link
https://codesandbox.io/p/sandbox/cool-minsky-qr74nv
官方demo就是有问题的

### 🤔 Steps to Reproduce
1 运行demo， https://codesandbox.io/p/sandbox/cool-minsky-qr74nv
2 import "ant-design-vue/dist/antd.css";报错，修改为import 'ant-design-vue/dist/reset.css';, 下钻功能依然失效

**Comment by lijinke666** [comment]
> import "ant-design-vue/dist/antd.css";引入报错，因为在ant-design-vue中的css文件只有reset.css,换成这个后成功运行

这是因为目前 `ant-design-vue` 发布了 4.0 版本, 所以 demo 对应安装的 `ant-desigin-vue@latest`对应 `4.x`, 而 `4.x` 已经移除了 `"ant-design-vue/dist/antd.css"` 相关的样式文件了, 是一个[破坏性的改动](https://next.antdv.com/docs/vue/migration-v4-cn)

> 官方demo就是有问题的

`@antv/s2-vue` 依赖的是 `ant-design-vue` `3.x` 版本, 请确保你安装了正确的版本即可正常运行

![image](https://github.com/antvis/S2/assets/21015895/68246849-24a0-4d99-b8a1-b359f266cb72)

> 修改为import 'ant-design-vue/dist/reset.css';, 下钻功能依然失效

reset.css 是让你用来重置样式的, 和下钻功能失效没有半毛钱关系

**Comment by machachong** [comment]
那其实还是版本迭代导致的呀，如果用了新版本这个不就不行了嘛
