### ISSUE TITLE
🐛明细表隐藏列功能问题

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/S2#2507]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.46.0  |
| @antv/s2-vue   |   -     |

### Sheet Type

TableSheet（明细表）

### 🖋 Description

隐藏列功能有问题，具体见录屏

https://github.com/antvis/S2/assets/34603922/9b07b353-9513-4c8a-8de9-e147793ed3ec

### ⌨️ Code Snapshots
官网示例就可以复现 

### 🔗 Reproduce Link

https://s2.antv.vision/zh/examples/react-component/switcher/#table

| Environment | Info |
| ------- | ------- |
| System  |   mac      |
| Browser |    chrome： 120.0.6099.129     |

**Comment by lijinke666** [comment]
> [s2.antv.vision/zh/examples/react-component/switcher/#table](https://s2.antv.vision/zh/examples/react-component/switcher/#table)

请使用新的官网 https://s2.antv.antgroup.com/
