### ISSUE TITLE
相同name的列名，选中单元格时，会发生连带🐛

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/S2#2510]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.46.0  |
| @antv/s2-vue   |   -     |

### Sheet Type

TableSheet（明细表）

### 🖋 Description

相同name的列名，选中单元格时，会发生连带

https://riddle.alibaba-inc.com/riddles/eae92d8

| Environment | Info |
| ------- | ------- |
| System  |   mac      |
| Browser |    chrome： 120.0.6099.129     |

**Comment by wuhaiyang** [comment]
逻辑层面有这个问题，真实场景应该不会这么搞。下来我们思考下涉及到这块的逻辑要不要重构下

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/issues/2502#issuecomment-1888642061

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/2568
