### ISSUE TITLE
🐛 带有query的明细表排序结果出错

### ISSUE THREAD

**Issue by ixuxinyue** [antvis/S2#2511]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.53.0      |
| @antv/s2-react |    1.46.0     |

### Sheet Type

TableSheet

### 🖋 Description

带有query的明细表排序结果看着不对
![image](https://github.com/antvis/S2/assets/22525231/68e2f758-aa1e-4753-bb38-c364039fbdbf)

### 🔗 Reproduce Link

(https://s2.antv.antgroup.com/examples/analysis/sort/#table-sort)

### 🤔 Steps to Reproduce

官网demo

**Comment by wuhaiyang** [comment]
案例的 key 写的不对，下来我们修改下：

![image](https://github.com/antvis/S2/assets/8447716/956fc065-9424-48e4-93c2-b6da1cc770e9)

**Comment by lijinke666** [comment]
演示 Demo 问题, 后续更新官网
