### ISSUE TITLE
🐛自定义 icon 渲染会导致 canvas 无法正常导出图片

### ISSUE THREAD

**Issue by Micircle** [antvis/S2#2513]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.51.2    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

设置自定义 icon 后，如：
```javascript
{
    customSVGIcons: [
        { name: 'xxx', svg: 'https://xxx.svg' }
    ]
}
```
调用 canvas.toDataURL() 会报错
报错原因为：
https://github.com/antvis/S2/blob/c0376280ccc02405f6dbb137a777153d757d3c6c/packages/s2-core/src/common/icons/gui-icon.ts#L59

这里的 img 没有设置 `img.crossOrigin = 'Anonymous';` canvas toDataURL 会报错，希望可以修复一下，谢谢~。
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
直接来个 PR?
