### ISSUE TITLE
🤔透视表在开启首行冻结后行头和数据都会出现滚动条，请问有没有什么方法可以去除行头滚动条，保留数据滚动条？

### ISSUE THREAD

**Issue by Jasmine011** [antvis/S2#2514]
### 透视表在开启首行冻结后行头和数据都会出现滚动条，请问有没有什么方法可以去除行头滚动条，保留数据滚动条？

| Package        | Version |
| -------------- | ------- |
| @antv/s2 | ^1.54.2 |
| @antv/s2-vue | ^1.6.0 |

透视表在开启首行冻结后行头和数据都会出现横向的滚动条，请问有没有什么方法可以去除行头滚动条（或者设置超过一定宽度再显示滚动条），保留数据滚动条？

<img width="675" alt="image" src="https://github.com/antvis/S2/assets/96428529/c71cca6d-8e86-4ba4-a954-6e1660628c37">

**Comment by wuhaiyang** [comment]
先暂时这样设置下：![image](https://github.com/antvis/S2/assets/8447716/da198e03-fd9a-4a71-ae36-a5c7def1d567) ？

**Comment by lijinke666** [comment]
首先,您描述的不是冻结首行, 而是冻结行头

```diff
    const s2Options = {
      width: 600,
      height: 480,
// 方式1: 关闭冻结行头, 这样只有数值区域才会有滚动条
+     frozenRowHeader: false

// 方式2: 自定义树状模式下行头的宽度
+     treeRowsWidth: 300,
    };
```
