### ISSUE TITLE
🐛组内排序使用sortFunc会出现错误

### ISSUE THREAD

**Issue by tufaofu** [antvis/S2#2515]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.51.0     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
组内排序使用sortFunc，如果两个分组内部的数据相同，会按照一样的顺序排序，不会按照对应数值的大小进行排序
<img width="615" alt="image" src="https://github.com/antvis/S2/assets/74943736/dd9d006f-2ae6-4513-8434-bd8ab1b7f136">

### 🔗 Reproduce Link
https://codesandbox.io/p/sandbox/interesting-ride-r3sw4q?file=%2Fsrc%2Findex.js

### 😊 Expected Behavior
排序顺序不对，希望各个分组能按照对应值的大小进行排序

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    mac     |
| Browser |   120.0.6099.199      |

**Comment by wjgogogo** [comment]
这个是排序场景的不足，内部会最终针对返回值进行维度拼接，但是因为是同样的值，做拼接时就有有问题，你可以自行拼接完成的维度信息：https://codesandbox.io/p/sandbox/sharp-kalam-szlrc4?file=%2Fsrc%2Findex.js%3A58%2C6

**Comment by tufaofu** [comment]
这样是可以的，非常感谢
