### ISSUE TITLE
🐛 conditions 字段内配置的文本背景色和图标,对于表头也生效

### ISSUE THREAD

**Issue by cloudflypeng** [antvis/S2#2516]
### 🏷 Version

- [ ] PivotSheet
- [ . ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

自定义条件配置的conditions 内容对表头也生效了, 我认为这个应该只对单元格生效

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    mac     |
| Browser |      chrome   |

**Comment by wjgogogo** [comment]
字段标记的能力有增加，现在会对行列角头都生效，可以查看：https://s2.antv.antgroup.com/zh/examples/analysis/conditions/#text,  mapping接收到的参数，在行列角头会有不同，可以通过第二个，第三个参数做区分
