### ISSUE TITLE
🐛明细表的自定义序号标题属性无效

### ISSUE THREAD

**Issue by wisonic-s** [antvis/S2#2520]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.54.2    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

明细表的自定义序号标题属性无效。
### ⌨️ Code Snapshots

```
import { TableSheet } from '@antv/s2';

fetch('https://assets.antv.antgroup.com/s2/basic-table-mode.json')
  .then((res) => res.json())
  .then((data) => {
    const container = document.getElementById('container');
    const s2DataConfig = {
      fields: {
        columns: ['province', 'city', 'type', 'price', 'cost'],
      },
      meta: [
        {
          field: 'province',
          name: '省份',
        },
        {
          field: 'city',
          name: '城市',
        },
        {
          field: 'type',
          name: '商品类别',
        },
        {
          field: 'price',
          name: '价格',
        },
        {
          field: 'cost',
          name: '成本',
        },
      ],
      data,
    };

  const s2Options = {
    width: 600,
    height: 480,
    showSeriesNumber: true,
    seriesNumberText: '自定义序号标题',
  };

  const s2 = new TableSheet(container, s2DataConfig, s2Options);

  s2.render();
});
```
### 🔗 Reproduce Link
https://s2.antv.vision/zh/examples/basic/table/#table

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     Win11    |
| Browser |     Chrome 120.0.6099.224    |

**Comment by lijinke666** [comment]
抱歉, 是文档有误, `seriesNumberText` 是 2.0 版本新增的特性, 误更新到 1.x 的文档了, 目前 1.x 版本不支持该能力
