### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by QJerryxjh** [antvis/S2#2525]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.54.2    |
| @antv/s2-react |     1.46.0    |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

官网明细表隐藏表头示例，展示动图可以点击隐藏表头，在实例内showTooltip和hiddenColumns为true了，但是表头那没有出现，hiddenColumns是控制是否展示隐藏按钮的吗，还需要其他的设置吗
```javascript
tooltip: {
        showTooltip: true,
        operation: {
          // 开启手动隐藏
          hiddenColumns: true,
        },
      },
```

### 🔗 Reproduce Link
[s2官网示例](https://s2.antv.antgroup.com/examples/interaction/advanced/#table-hide-columns)

**Comment by lijinke666** [comment]
> 官网明细表隐藏表头示例，展示动图可以点击隐藏表头

- `s2Options.tooltip.operation.hiddenColumns` 控制是否允许手动点击隐藏 ( 列头 tooltip 中的小眼睛 icon)
- `s2Options.interaction.hiddenColumnFields` 控制默认隐藏的列头
 
`@antv/s2` 没有实现 tooltip 的 UI, 所以点击列头不会展示 tooltip, 官网这里有[说明](https://s2.antv.antgroup.com/manual/basic/tooltip#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

`@antv/s2-react` 是基于 `antd` 封装的 UI, 你反馈的这个 Demo 对应的 gif 有点问题, gif 录制的时候用的是 React 版本的, 代码示例又是用的 `@antv/s2`, 所以造成误解了, 后续我们更换一下 gif, 抱歉, 可以查看 [`React 版本的 demo`](https://s2.antv.antgroup.com/zh/examples/react-component/sheet/#table), 这个是正确的


> 还需要其他的设置吗

![image](https://github.com/antvis/S2/assets/21015895/fb1a2969-64a5-40f3-8237-8d7fc9fa432d)

你使用的 React 版本, 所以不会有这个问题, 只需要引入相应的样式即可, 可以这样理解:

`@antv/s2` 提供手动隐藏的能力和相应 API, 只支持控制默认隐藏的列头, 如果想手动点击列头隐藏, 需要自己实现 Tooltip 的 UI, 然后调用相应的 API

`@antv/s2-react` 是基于[上诉步骤封装的](https://github.com/antvis/S2/blob/c772c2a48e5e805f6def128d8c7ba07258246a29/packages/s2-react/src/components/tooltip/custom-tooltip.tsx#L12-L35), 所以可以直接使用.
