### ISSUE TITLE
🤔SheetComponent设置为可编辑时，meta里面设置了formatter，但是在编辑的时候拿到的还是原数据，如何在可编辑的时候拿到格式化后的数据，设置了showOriginalValue并不生效

### ISSUE THREAD

**Issue by jzm-123** [antvis/S2#2528]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
你到底表达的是, 你想 input 框里面的值是原始值, 然后你想拿到格式化的值

还是你指的是期望 input 框里面填充的是格式化后的值? `showOriginalValue` 和编辑表又有什么关系?

**Comment by jzm-123** [comment]
我期望 input 框里面填充的是格式化后的值
