### ISSUE TITLE
🙏 hope the vue component supports the export function

### ISSUE THREAD

**Issue by MaekBlack** [antvis/S2#2529]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.49.1     |
| @antv/s2-react |    --     |
| @antv/s2-vue   |     --     |

### Sheet Type

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🏞 What problem does this feature solve
vue component supports the export function

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
You can implement the UI yourself using the [basic export method](https://s2-v1.antv.antgroup.com/en/manual/basic/analysis/copy-export#original-export-method) provided by '@antv/s2'. 

Vue versions will not introduce new features.
