### ISSUE TITLE
🤔如何根据外部传入的配置动态修改表格指定列单元格对齐方式

### ISSUE THREAD

**Issue by lcmomo** [antvis/S2#2533]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.54.2    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [√ ] PivotSheet
- [ √] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
我想要实现根据外部传入配置来动态更改表格指定列的对齐方式，目前自定义单元格的示例中没有关于这一点的（就是设置样式的判断条件，需要从从外部传入，目前示例都是直接写死的）

参考过示例https://s2.antv.antgroup.com/zh/examples/custom/custom-cell/#custom-specified-cell
以及issue https://github.com/antvis/S2/issues/1448

我发现 重写 getTextStyle()方法中无法拿到外部传入的配置
请问是否还有其他方式，来实现指定列对齐需求。

```js
class CustomDataCell extends DataCell {
  public customCfg: any;
  
  
  constructor(viewData: ViewMeta, spreadsheet: SpreadSheet, cfg: any) {  
    super(viewData, spreadsheet);
    this.customCfg = cfg
  }

  override getTextStyle(): TextTheme {
    const subType = get(this.meta, 'data.sub_type', undefined);
    const selectedSeries = this.customCfg.selectedSeries;  // 这里根据cfg中的相关配置来计算指定列对齐方式，但是无法拿到customCfg, customCfg为undefined
    const textAlign =
     subType === selectedSeries? 'left' : 'right';  

    return {
      ...super.getTextStyle(),
      textAlign,
    };
  }
}

export function getSOptions(cfg) {
// 需要根据cfg变化来动态获取配置
  return {
    // // 其他配置... 
    dataCell: function (viewMeta) {
      return new CustomDataCell(viewMeta, viewMeta.spreadsheet, cfg)
    
    },
  }
}
```

**Comment by lijinke666** [comment]
直接放入 viewMeta 就行

```ts
new CustomDataCell({...viewMeta, customCfg: {...}}, viewMeta.spreadsheet)
```

```ts
getTextStyle() {
  this.meta.customCfg
}
```
