### ISSUE TITLE
🙏 Option to have line break on column names instead of ellipsis

### ISSUE THREAD

**Issue by fmo-dev** [antvis/S2#2534]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.45.0  |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

I'm using PivotSheet and TableSheet in my React application. I've encountered an issue with long column names: when I reduce the size of a column, the name is truncated with an ellipsis. However, for better readability and data presentation, I would prefer if the long names wrapped to multiple lines within the column header instead of being truncated. 

For example :
| Column Name     | 
| -------------------|
|                |
|                |

Can become :
| Column<br>Name  |
| ----------|
|                |
|                |

It would be very nice to have an option to choose the overflow style for column cell

### 🏞 What problem does this feature solve

This modification would allow users to view the full column names even in narrow columns, enhancing the user experience and data comprehension in scenarios with lengthy column headers.

**Comment by lijinke666** [comment]
see https://codesandbox.io/p/sandbox/s2-next-ban-ben-duo-xing-wen-ben-shi-li-mhdghm

![image](https://github.com/antvis/S2/assets/21015895/c5639239-ae34-4569-ad13-9cd427a1e783)

New English documentation in progress
