### ISSUE TITLE
不同数字的占位不同，导致相同位数的数字显示长度不一致🤔

### ISSUE THREAD

**Issue by tufaofu** [antvis/S2#2536]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.51.0     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
表格中显示的数字1和其他数字显示长度不一致，会导致位数一致的两个数字，数字1出现次数多的数字在显示上会短一点，效果如下图
<img width="735" alt="image" src="https://github.com/antvis/S2/assets/74943736/b8320624-82c6-4f30-8893-ffc8743d7ad6">
请问这个问题有什么解决办法吗？

### 🔗 Reproduce Link
[https://codesandbox.io/p/sandbox/blissful-cori-x96vz9?file=%2Fsrc%2Findex.js%3A24%2C20](https://codesandbox.io/p/sandbox/blissful-cori-x96vz9?file=%2Fsrc%2Findex.js%3A24%2C20)

**Comment by lijinke666** [comment]
使用等宽字体 https://github.com/antvis/S2/issues/2312#issuecomment-1700679491
