### ISSUE TITLE
官网右上角菜单偏上了

### ISSUE THREAD

**Issue by afc163** [antvis/S2#2538]
<img width="1782" alt="图片" src="https://github.com/antvis/S2/assets/507615/7662d05c-5819-4208-bc77-0c6b62f786ac">

**Comment by lijinke666** [comment]
收到, 我们看一下

**Comment by lijinke666** [comment]
已修复, 晚一点部署, 感谢反馈, 这下不 "偏" 了

![image](https://github.com/antvis/S2/assets/21015895/09f37e56-f4eb-4f5f-91cf-d08ea8aa6c2e)
