### ISSUE TITLE
🐛性能回退！1.31.1版本 1w列时候，横向滚动很丝滑，但是升级到 1.54.3时，掉帧严重

### ISSUE THREAD

**Issue by fanyongchao01** [antvis/S2#2548]
性能回退！1.31.1版本 1w列时候，横向滚动很丝滑，但是升级到 1.54.3时，掉帧严重

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  v1.54.3  |
| @antv/s2-react |  1.46.1  |

### Sheet Type

明细表

复现链接
https://riddle.alibaba-inc.com/riddles/a1072da9

**Comment by xiaopf** [comment]
> 性能回退！1.31.1版本 1w列时候，横向滚动很丝滑，但是升级到 1.54.3时，掉帧严重
> 
> Package	Version
> @antv/s2	v1.54.3
> @antv/s2-react	1.46.1
> ### Sheet Type
> 明细表
> 
> 复现链接 https://riddle.alibaba-inc.com/riddles/a1072da9

我看评论说 @antv/s2-v2.0.0-next.14 解决了这个问题，想请问一下有改善么，我个人感觉好像没有什么改善
