### ISSUE TITLE
🤔是否支持插入文件？

### ISSUE THREAD

**Issue by viz1997** [antvis/S2#2555]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     v2.0.0-next.12    |
| @antv/s2-react |     v2.0.0-next.11    |
| @antv/s2-vue   |     v2.0.0-next.10    |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ✔] EditableSheet

### 🖋 Description

是否支持插入文件？

**Comment by lijinke666** [comment]
不支持
