### ISSUE TITLE
🙏透视表树结构的小计希望能够使用传入的值

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2557]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表树结构小计需要接受传入的值，因为透视表的明细不能一次性加载完，小计是后端计算的，需要接受传入的值

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| useCurrentValue  | boolean   | false      | 设置为true时，接受当前计算好的值        |

**Comment by wjgogogo** [comment]
在 dataCfg 中传入总计小计的值即可，s2就不会使用计算的结果了，参考：https://s2.antv.antgroup.com/manual/basic/totals
