### ISSUE TITLE
透视表树结构展开按钮不能正确的渲染

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2563]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      next   |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
![s2_table_index](https://github.com/antvis/S2/assets/12973954/fe24efd3-2bc2-4d86-950c-8d14bb435cfb)
1. 使用自定义layoutSeriesNumberNodes自定义序号列, 折叠按钮跑到了 序号单元格，图中1。
2. 点击第一个折叠按钮，会触发所有行展开，图中2

**Comment by Create-Peace** [comment]
使用[官网树结构代码](https://s2.antv.antgroup.com/examples/basic/pivot/#tree),添加
```
seriesNumber: {
        enable: true
      }
```
显示序号列，折叠按钮显示在序号单元格
![树结构序号](https://github.com/antvis/S2/assets/12973954/e02af602-5a0b-4468-a6f9-01050b7908eb)

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/S2/pull/2571
