### ISSUE TITLE
交叉表希望能支持右侧和尾部列的冻结🙏

### ISSUE THREAD

**Issue by wenjingyuer** [antvis/S2#2573]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   v2.0.0-next.13      |

### Sheet Type

- [x] PivotSheet

### 🏞 What problem does this feature solve

交叉表希望能支持右侧和尾部列的冻结，右侧冻结列在表格中的一个常见场景是用于放置操作按钮或操作菜单，以便用户可以方便地对表格中的每一行进行操作。但是现在 S2 的交叉表不支持，
字节  [VTable](https://visactor.io/vtable/option/PivotChart#rightFrozenColCount)的交叉表是支持的。

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

Frozen.trailingColCount

Frozen.trailingRowCount

同时对交叉表和明细表都有效

**Comment by liao3320551** [comment]
现在支持了吗？很迫切需要。
