### ISSUE TITLE
🤔2.0版本的API文档中的getInitColLeafNodes方法在使用时报错

### ISSUE THREAD

**Issue by tufaofu** [antvis/S2#2576]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.13     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
s2. getInitColLeafNodes()方法不存在

<img width="1440" alt="image" src="https://github.com/antvis/S2/assets/74943736/26dbc5aa-8ffe-40b5-8c53-a5da34b27889">
<img width="1440" alt="image" src="https://github.com/antvis/S2/assets/74943736/033292cb-6592-46f5-935b-6b607dd97dba">
2.0版本的API文档中的getInitColLeafNodes方法在使用时报错

**Comment by lijinke666** [comment]
感谢反馈, 文档有误, 后续修改下.

节点获取相关 API 统一移动到了 `s2.facet` 命名空间下, 请查看 https://s2.antv.antgroup.com/api/basic-class/base-facet . 如果是想获取列头的话, 推荐使用

```ts
s2.facet.getColNodes()
s2.facet.getColLeafNodes()
```
