### ISSUE TITLE
如何实现点击单元格时，让单元格边框变蓝，再次点击点击时单元格边框恢复正常颜色

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2579]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

如何实现点击单元格时，让单元格边框变蓝，点击别的单元或者再次点击点击时单元格边框恢复正常颜色 ?

**Comment by lijinke666** [comment]
文档 [调整交互主题](https://s2.antv.antgroup.com/manual/advanced/interaction/basic#%E8%B0%83%E6%95%B4%E4%BA%A4%E4%BA%92%E4%B8%BB%E9%A2%98) 有写, 多看文档再提问, 谢谢.

![image](https://github.com/antvis/S2/assets/21015895/3541f809-01f4-45f9-b9e7-c0f79826f9f7)

> 点击别的单元或者再次点击点击时单元格边框恢复正常颜色 

监听单元格点击, 重置交互即可

```
s2.interaciton.reset()
```

另外使用问题请在 https://github.com/antvis/S2/discussions 提问, 谢谢配合.
