### ISSUE TITLE
如何给单元格右上角添加icon，icon不占文字的位置

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2583]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next   |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheetX
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

如何给单元格添加icon，icon固定再单元格的右上角，icon不影响文字的位置？

**Comment by lijinke666** [comment]
表格是 Canvas, 所以不存在什么 `icon不影响文字的位置`, 你想怎么画就怎么画, 可以参考字段标记绘制 icon 的实现, 后续官网增加一个示例

https://github.com/antvis/S2/blob/a82d571fdebf0be091694b947e969e90e125f833/packages/s2-core/src/cell/header-cell.ts#L290-L297

1. 方式1 - 自定义单元格, 在 `initCell` 的时候绘制

```ts
import { GuiIcon, RowCell } from '@antv/s2'

class CustomRowCell extends RowCell {
  initCell() {
    super.initCell()
    
    // 根据 meta 判断是否需要增加 icon
    console.log(this.meta)

    const size = 10
    const icon = new GuiIcon({
      x: this.meta.x + this.meta.width - size, 
      y: this.meta.y, 
      name: 'Plus', 
      width: size, 
      height: size, 
      fill: 'red', 
    });

    this.appendChild(icon);
  }
}
```

![image](https://github.com/antvis/S2/assets/21015895/2824dcec-8d76-469b-898c-70158f3f3894)


2. 方式2 - 获取单元格, 一个单元格对应一个 G 的 Group, 使用 `cell.appendChild(icon)` 添加 icon 到你自己指定的单元格图层内, 代码参考方式1
