### ISSUE TITLE
🐛明细表格-多层表头加列冻结情况下-表头宽度拖拽条位置出错

### ISSUE THREAD

**Issue by huci-lingmao** [antvis/S2#2588]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.42.0     |
| @antv/s2-react |    1.37.0     |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

明细表格-多层表头加列冻结情况下-表头宽度拖拽条位置出错

### ⌨️ Code Snapshots

```javascript
import { TableSheet } from '@antv/s2';

fetch('https://assets.antv.antgroup.com/s2/basic-table-mode.json')
  .then((res) => res.json())
  .then((data) => {
    const container = document.getElementById('container');
    const s2DataConfig = {
      fields: {
        columns: [
          'province',
          'type',
          {
            key:'分类',
            children: ['city', 'type',]
          },
          'price',
          'cost'
        ],
      },
      meta: [
        {
          field: 'province',
          name: '省份',
        },
        {
          field: 'city',
          name: '城市',
        },
        {
          field: 'type',
          name: '商品类别',
        },
        {
          field: 'price',
          name: '价格',
        },
        {
          field: 'cost',
          name: '成本',
        },
      ],
      data,
    };

    const s2Options = {
      width: 600,
      height: 480,
      showSeriesNumber: true,
      frozenColCount: 1
    };

    const s2 = new TableSheet(container, s2DataConfig, s2Options);

    s2.render();
  });

```

### 🔗 Reproduce Link

https://s2-v1.antv.antgroup.com/examples/basic/table/#table
打开上面链接，并将代码替换成上面Code Snapshots中的代码

### 🤔 Steps to Reproduce
1. 拖动一下横向滚动条；
2. 鼠标hover到列头分隔线上，无法选中分隔线；

bug原因：分割线向右偏移了，偏移的距离等于滚动的距离；
![image](https://github.com/antvis/S2/assets/142567585/35d548ab-b2fc-4bf8-8839-ac9da8af1bb9)

![image](https://github.com/antvis/S2/assets/142567585/cebd9543-1f13-4ae3-8631-80eaf1ab7eb5)

### 😊 Expected Behavior
1. 分隔线能正常hover选中

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
`2.x` 中问题已修复, `1.x` 问题代码问题都找到了, 直接来个 PR :) ?

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/en/manual/migration-v2
