### ISSUE TITLE
🐛明细表自定义列头时单元格内容显示为空

### ISSUE THREAD

**Issue by LanticGan** [antvis/S2#2589]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.54.6    |
| @antv/s2-react |   1.46.3      |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

使用@antv/s2-react明细表自定义列头时单元格内容渲染为空，只显示占位符“-”，官方提供的样例中也是如此。

![image](https://github.com/antvis/S2/assets/20263130/895117f8-dc83-47e1-96ae-128cc0881786)

### ⌨️ Code Snapshots

```javascript
import { CustomTreeNode, TableSheet, S2DataConfig, S2Options } from '@antv/s2';

export const tableSheetMultipleColumns: CustomTreeNode[] = [
  {
    field: 'area',
    title: '地区',
    children: [
      { field: 'province', title: '省份' },
      { field: 'city', title: '城市' },
    ],
  },
  {
    field: 'type',
    title: '类型',
  },
  {
    field: 'money',
    title: '金额',
    children: [
      { field: 'price', title: '价格', description: '价格描述' },
      { field: 'number', title: '数量' },
    ],
  },
];

fetch('https://assets.antv.antgroup.com/s2/basic-table-mode.json')
  .then((res) => res.json())
  .then(async (data) => {
    const container = document.getElementById('container');
    const s2DataConfig: S2DataConfig = {
      fields: {
        columns: tableSheetMultipleColumns,
      },
      data,
      // 自定义节点默认使用 `title` 作为展示名, 也可以通过 meta 来统一进行格式化
      meta: [
        {
          field: 'area',
          formatter: (value) => '当前节点自定义名称1',
        },
        {
          field: 'number',
          formatter: (value) => '1',
        },
      ],
    };

    const s2Options: S2Options = {
      width: 600,
      height: 480,
      seriesNumber: {
        enable: true
      }
    };

    const s2 = new TableSheet(container, s2DataConfig, s2Options);

    await s2.render();
  });
```

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/exciting-darwin-grmxwh?file=%2Findex.ts%3A5%2C19
### 🤔 Steps to Reproduce

正常渲染组件即可复现。

### 😊 Expected Behavior

正常显示单元格内容。

### 😅 Current Behavior

单元格内容展示为"-"。

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     window 10     |
| Browser |     chrome: v120    |

**Comment by lijinke666** [comment]
> 官方提供的样例中也是如此

你这个 codesandbox 链接是在哪里看到的? 这个 codesandbox 和你贴的代码是 `2.0` 版本的写法. 你使用 `1.x` 版本请参考官网的示例

https://s2-v1.antv.antgroup.com/examples/basic/table/#table-column-group

![image](https://github.com/antvis/S2/assets/21015895/3074f121-5586-46cc-b1c5-87e1a95bf884)
