### ISSUE TITLE
字段标记icon标记的position不能生效，一直现在文字的右侧

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2592]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   next      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

使用字段标记使用icon标记，icon的文字配置不生效，配置position: 'left',但是还是显示在右侧。
### ⌨️ Code Snapshots

```
conditions: {
        icon: [
          {
            field: 'province',
            mapping: (fieldValue, data) => {
              if (fieldValue === '浙江省') {
                return {
                  icon: 'SortDown',
                  fill: 'green',
                  position: 'left',
                };
              }
            },
          },
        ],
      },
```
### 🔗 Reproduce Link

[在线demo](https://stackblitz.com/edit/react-yrmfoe?file=src%2Findex.js)
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
`position` 和 `field` 是同级的, 不是在 `mapping` 里, 文档应该没有这样写吧?

https://s2.antv.antgroup.com/examples/analysis/conditions/#icon

![image](https://github.com/antvis/S2/assets/21015895/5af9efca-d3c8-4abc-91ba-851048de60ac)
