### ISSUE TITLE
dataCell单元格渲染多行文本无法自适应高度🐛

### ISSUE THREAD

**Issue by Gxyrious** [antvis/S2#2594]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.14 |
| @antv/s2-react |    -     |
| @antv/s2-vue   |    -     |

### Sheet Type

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

- 需求是让数据单元格(dataCell)能够自动换行，dataCell内容的长度是不确定的，希望能够在保持默认宽度下自适应cell的高度。虽然我希望dataCell能够自动换行并自适应高度，但行头也存在这种问题。

- 在next分支的仓库里找到了[相关的测试](https://github.com/antvis/S2/blob/a82d571fdebf0be091694b947e969e90e125f833/packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts#L199)，并且本地跑了一下，但是没通过，node版本是v21.2.0

![图片](https://github.com/antvis/S2/assets/83438334/19eee6ab-7a84-4c59-9f6b-92a14baecbbe)

- 在[G的文档](https://g.antv.antgroup.com/api/basic/text#maxlines)中看到了maxLines的默认值是'infinity'，这个值貌似是起作用的，虽然源码中maxLines类型是`number?`，但无论是'infinity'还是诸如4的数字，都会有无法自适应的情况。

### ⌨️ Code Snapshots

把官网示例的透视表改成了明细表：[https://s2.antv.antgroup.com/examples/layout/custom#multi-line-text](https://s2.antv.antgroup.com/examples/layout/custom#multi-line-text)，下面是改完的代码：

```tsx
import {
  CellTextWordWrapStyle,
  TableSheet,
  S2DataConfig,
  S2Options,
} from '@antv/s2';
import '@antv/s2/dist/style.min.css';

fetch('https://assets.antv.antgroup.com/s2/basic.json')
  .then((res) => res.json())
  .then(async (data) => {
    const container = document.getElementById('container');
    const s2DataConfig: S2DataConfig = {
      fields: {
        columns: ['province', 'city', 'type', 'price', 'cost'],
      },
      meta: [
        {
          field: 'province',
          name: '省份',
        },
        {
          field: 'city',
          name: '城市',
        },
        {
          field: 'type',
          name: '商品类别',
        },
        {
          field: 'price',
          name: '价格',
        },
        {
          field: 'cost',
          name: '成本',
        },
      ],
      data: [
        {
          province: '浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江',
          city: '杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州',
          type: '纸张纸张纸张纸张纸张纸张纸张纸张纸张纸张',
          price: '价格价格价格价格价格价格价格价格价格价格价格价格价格价格价格价格价格价格',
          cost: '花费花费花费花费花费花费',
        },
      ],
    };

    const cellTextWordWrapStyle: CellTextWordWrapStyle = {
      // 最大行数，文本超出后将被截断
      maxLines: 'infinity', // 如果是数字也会有问题
      // 文本是否换行
      wordWrap: true,
      // 可选项见：https://g.antv.antgroup.com/api/basic/text#textoverflow
      textOverflow: 'ellipsis',
    };

    const s2Options: S2Options = {
      width: 600,
      height: 480,
      style: {
        // 数值不建议换行, 容易产生歧义
        dataCell: cellTextWordWrapStyle,
      },
    };

    const s2 = new TableSheet(container, s2DataConfig, s2Options);

    await s2.render();
  });

```

![图片](https://github.com/antvis/S2/assets/83438334/3f00e765-eae5-416d-becc-f5db8b49c5ba)

### 🤔 Steps to Reproduce

借助官网上的这个示例可以直接体现：[https://s2.antv.antgroup.com/examples/layout/custom#multi-line-text](https://s2.antv.antgroup.com/examples/layout/custom#multi-line-text)
1. 将cellTextWordWrapStyle中原来的maxLines替换为4或上述的'infinity'
```ts
const cellTextWordWrapStyle: CellTextWordWrapStyle = {
  // 最大行数，文本超出后将被截断
  maxLines: 4,
  // 文本是否换行
  wordWrap: true,
  // 可选项见：https://g.antv.antgroup.com/api/basic/text#textoverflow
  textOverflow: 'ellipsis',
};
```

2. 把s2DataConfig.data里的province多增加一些：
```tsx
  data: [
    {
      province: '浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江浙江',
      city: '杭州杭州杭州杭州杭州杭州',
      type: '纸张纸张纸张纸张纸张',
      price: '2',
      cost: '20',
    },
    ...data,
  ],
```

这个行头单元格并没有高度自适应：
![图片](https://github.com/antvis/S2/assets/83438334/aedcde54-f3d5-498d-81d3-4e81b9800ff7)

比较神奇的是改这个杭州的city是可以自适应的：
```tsx
  data: [
    {
      province: '浙江浙江浙江浙江浙江浙江',
      city: '杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州杭州',
      type: '纸张纸张纸张纸张纸张',
      price: '2',
      cost: '20',
    },
    ...data,
  ],
```

![图片](https://github.com/antvis/S2/assets/83438334/dba00803-7f9c-4f7d-95ee-4eb1dd0ddc42)

### 😊 Expected Behavior

希望能够设置maxlines为'infinity'，使得无论内容多长都能够自动换行并高度自适应。

### 😅 Current Behavior

单元格虽然能够换行，但是高度无法自适应。

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  | Ubuntu 22.04.1 LTS |
| Browser | Chrome v119.0.6045.159(64位)，firefox122.0.1(64位) |

**Comment by lijinke666** [comment]
> 在next分支的仓库里找到了[相关的测试](https://github.com/antvis/S2/blob/a82d571fdebf0be091694b947e969e90e125f833/packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts#L199)，并且本地跑了一下，但是没通过，node版本是v21.2.0

这个应该和你是 Ubuntu 系统有关, 本地和 CI 的环境都是 macOS

![image](https://github.com/antvis/S2/assets/21015895/628d83d2-8ac0-4106-948b-2edebd2b5091)

> 比较神奇的是改这个杭州的city是可以自适应的

确实有问题, 看来单测覆盖的场景还不够全, 目前看起来当前行的高度以最后一个节点为准了, 空了我排查下

**Comment by lijinke666** [comment]
> 希望能够设置maxlines为'infinity'，使得无论内容多长都能够自动换行并高度自适应。

这个是 g 的文档有问题，是 Infinity https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by Gxyrious** [comment]
能设置个很大的数字实现类似自动换行的效果就可以 感谢修复

**Comment by lijinke666** [comment]
fixed #2598
