### ISSUE TITLE
透视表树结构自定义按钮渲染和展开逻辑有问题

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2607]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      next  |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheetX
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

1. 透视表树结构自动了展开折叠按钮后，发现按钮没有渲染完全，部分按钮没有渲染。点击第一个按钮展开收起后，后面的按钮可以正常渲染。
2.  透视表树结构点击第一个按钮展开，后面兄弟元素的也展开层级

### ⌨️ Code Snapshots

```
const s2Options = {
      width: 600,
      height: 480,
      hierarchyType: 'tree',

      customSVGIcons,
      style: {
        rowCell: {
          // 自定义树状模式下行头宽度
          // width: 80,

          // 折叠全部
          // collapseAll: true,

          // 折叠浙江省下面所有的城市
          collapseAll: true,
        },
      },
    };
```

### 🔗 Reproduce Link

1. 刚打开页面页面按钮渲染不全
![image](https://github.com/antvis/S2/assets/12973954/10b60877-0f2d-4298-8c64-5fd52858a42b)
2. 点击第一个按钮后后面兄弟层级也展开了
![image](https://github.com/antvis/S2/assets/12973954/d130973f-0811-48a9-ab75-980f70643729)

### 🤔 Steps to Reproduce
https://stackblitz.com/edit/react-ptkcrt

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by Jacleklm** [comment]
+1

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/issues/2014

**Comment by lijinke666** [comment]
icon 不展示是已知问题, 已修复 https://github.com/antvis/S2/pull/2606
