### ISSUE TITLE
🐛官方文档 tooltip 示例挂了

### ISSUE THREAD

**Issue by Jacleklm** [antvis/S2#2610]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
 官方文档 Tooltip悬停示例，打开正常，鼠标悬停上去后就挂了
  https://s2.antv.antgroup.com/zh/examples/react-component/tooltip/#custom-hover-show-tooltip
![image](https://github.com/antvis/S2/assets/50861119/b86d3f4b-0d29-4281-9aca-dfda6f43bca6)
![image](https://github.com/antvis/S2/assets/50861119/db3f892f-33a8-4945-95c6-48e6ae776b15)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
感谢反馈, 近期修复.
