### ISSUE TITLE
pnpm core:watch 经常卡顿

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2612]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

在S2原项目中执行pnpm core:watch，修改代码后保存，经常卡顿不能编译了，能优化一下吗 ？
- [X] PivotSheeXt
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    Windows10     |
| Browser |      Chrome   |

**Comment by lijinke666** [comment]
没太懂你用 `core:watch` 的用途? `watch` 本质上就是 `rollup` 的 watch, 你如果是本地单独调试 S2 请用 `react:playground`, 如果是在你的项目中调试 S2 请用 npm link 

https://s2.antv.antgroup.com/manual/contribution#%E8%B0%83%E8%AF%95%E5%8A%9F%E8%83%BD
