### ISSUE TITLE
🐛SheetComponent 在单元格内绘制 AntV/G 图形没有生效

### ISSUE THREAD

**Issue by Jacleklm** [antvis/S2#2614]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.15      |
| @antv/s2-react |    2.0.0-next.14      |

### Sheet Type

- [x] PivotSheet

### 🖋 Description
sandbox: https://codesandbox.io/p/sandbox/s2-debug-sandbox-84tdfg?file=%2Fsrc%2FS2Table.js
代码基本是copy[官方文档](https://s2.antv.antgroup.com/zh/examples/custom/custom-shape-and-chart/#custom-g-shape)，但改成 react SheetComponent，G的图形没有渲染出来
![image](https://github.com/antvis/S2/assets/50861119/3af7aec5-6b11-4c73-81f5-ee333b29e675)

sandbox好像有时也显示不出来页面... ，打开为单独tab就没问题
![image](https://github.com/antvis/S2/assets/50861119/2500a13d-0b97-4d30-b86b-8a42d2b6d966)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    Ubuntu 20.04     |
| Browser |   chrome: v116.0.5845.96     |

**Comment by Gxyrious** [comment]
sandbox的链接没权限or不存在

**Comment by Jacleklm** [comment]
> sandbox的链接没权限or不存在

开发权限了，辛苦再看下
