### ISSUE TITLE
🐛@antv/s2-vue 的 2.0 版本中 SheetComponent 组件的 dataCellClick 事件的回调函数的参数中的 target 和 viewMeta 的值为 undefined

### ISSUE THREAD

**Issue by wittyMouse** [antvis/S2#2615]
### 🏷 Version

| Package        | Version       |
| -------------- | ------------- |
| @antv/s2       | 2.0.0-next.15 |
| @antv/s2-react |               |
| @antv/s2-vue   | 2.0.0-next.11 |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在 @antv/s2-vue 的 2.0 版本中 SheetComponent 组件的 dataCellClick 事件的回调函数的参数中的 target 和 viewMeta 的值为 undefined，1.0 版本不存在这个问题

### ⌨️ Code Snapshots

```vue
<template>
  <SheetComponent
    sheetType="table"
    :dataCfg="dataCfg"
    :options="s2Options"
    @dataCellClick="handleDataCellClick"
  />
</template>

<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { SheetComponent } from '@antv/s2-vue'

import type { S2DataConfig, S2Options } from '@antv/s2'

const dataCfg = shallowRef<S2DataConfig>({
  fields: { columns: ['province', 'city'] },
  meta: [
    { field: 'province', name: '省份' },
    { field: 'city', name: '城市' }
  ],
  data: [
    { province: '浙江', city: '杭州' },
    { province: '吉林', city: '长春' }
  ]
})

const s2Options = ref<S2Options>({ width: 600, height: 480 })

const handleDataCellClick = (e) => {
  console.log('dataCellClick', e)
}
</script>
```

### 🔗 Reproduce Link

https://codesandbox.io/p/devbox/antv-s2-issue-demo-w74rk9?file=%2Fsrc%2FApp.vue%3A4%2C23

### 🤔 Steps to Reproduce

鼠标左键点击数值单元格

### 😊 Expected Behavior

![image](https://github.com/antvis/S2/assets/26075909/e6a35223-cf41-433f-8572-ccdda497a310)

![image](https://github.com/antvis/S2/assets/26075909/ad024a00-e97b-48a9-9513-a4b8b81b1580)

target 和 viewMeta 根据文档返回值

### 😅 Current Behavior

![image](https://github.com/antvis/S2/assets/26075909/4ffe7f44-89cb-4906-ba12-b7ff691a80ec)

target 和 viewMeta 的值为 undefined

### 💻 System information

| Environment | Info          |
| ----------- | ------------- |
| System      | macOS 12.5    |
| Browser     | chrome v122.0 |

**Comment by lijinke666** [comment]
已知问题, 感谢反馈 https://github.com/antvis/S2/issues/2610

**Comment by wittyMouse** [comment]
您好，这是自动回复。您发邮件我已经收到。谢谢。
