### ISSUE TITLE
🙏随时插入行、列，删除行列

### ISSUE THREAD

**Issue by 0obuwawao0** [antvis/S2#2624]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.54.7       |
| @antv/s2-react |  -        |
| @antv/s2-vue   |   -      |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
希望像excel一样，随时在数据中间插入行 和 列，删除某行 或 某列，插入后的行或列，都能参与新的编辑，比如 合并 插入图片 编辑等。

### 🏞 What problem does this feature solve
一个像excel一样的表格，用于排座位类的需求，需要灵活的添加行列。

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| insertRow(rowIndex/id)   | -   | -       |  传入当前行的index或id在当前行的下方插入新的空行          |
| insertCol(colIndex/id)   | -   | -       |  传入当前列的index或id在当前列的右方插入新的空列          |
| deleteCol(colIndex/id)   | -   | -       |  传入当前列的index或id在删除当前列         |

**Comment by wjgogogo** [comment]
s2 着重展示而非编辑，暂时不会提供对强编辑类诉求的支持
