### ISSUE TITLE
透视表列多时，使用触摸板左右快速滑动，会报栈溢出错误

### ISSUE THREAD

**Issue by Create-Peace** [antvis/S2#2627]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   next      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表列比较多，使用触摸板左右滑动快时会出现栈溢出错误, 看着像是@antv/g引擎报错了。
```
Uncaught RangeError: Maximum call stack size exceeded
    at @antv_s2.js?v=75bfa16a:39272:55
    at @antv_s2.js?v=75bfa16a:10425:18
    at Array.forEach (<anonymous>)
    at SyncHook2.call (@antv_s2.js?v=75bfa16a:10424:22)
    at RenderingService2.render (@antv_s2.js?v=75bfa16a:12154:29)
    at Canvas2.render (@antv_s2.js?v=75bfa16a:16213:24)
    at RootInteraction2.draw (@antv_s2.js?v=75bfa16a:43746:34)
    at RootInteraction2.clearState (@antv_s2.js?v=75bfa16a:43750:14)
    at RootInteraction2.changeState (@antv_s2.js?v=75bfa16a:43769:12)
    at PivotSheet2.<anonymous> (@antv_s2.js?v=75bfa16a:41177:21)
```

### ⌨️ Code Snapshots
官网demo向右滑动快的时候就能复现这个问题
https://s2.antv.antgroup.com/examples/case/performance-compare/#pivot

### 🔗 Reproduce Link

![image](https://github.com/antvis/S2/assets/12973954/b19fb875-3fe6-44df-89fb-25e1ff722635)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
未复现

**Comment by Create-Peace** [comment]
我使用的是Windows 10, 录了个视频。https://pan.baidu.com/s/141qet3k0MmyH2DeHVIp_wA 提取码: 3wir

**Comment by lijinke666** [comment]
没有 windows 电脑, 无法复现, 你可以尝试定位下问题, 来个 PR

**Comment by Create-Peace** [comment]
我尝试修复了，没有定位到问题，Mac 也能复现，向右滑动最后。

**Comment by EliazTray** [comment]
![image](https://github.com/antvis/S2/assets/16015431/a6dfdae4-b241-4cd8-9fdf-4febd5580515)
同样也是很多透视列，横向快速滚动时，会循环调用，导致栈溢出。

SpreadSheet 中 emit `GLOBAL_MOUSE_MOVE`
![image](https://github.com/antvis/S2/assets/16015431/2ae46de8-0e87-4595-ab94-67d50d7a6938)

**Comment by lijinke666** [comment]
下周发布

**Comment by FreeLiC** [comment]
升级到next.23版本 问题仍然存在 官网的例子即可复现

**Comment by DavisYao88** [comment]
> 升级到next.23版本 问题仍然存在 官网的例子即可复现

确定是23版本吗，拉取源码尝试，目前没复现。内存曲线也正常
![image](https://github.com/antvis/S2/assets/24189898/bcec03c6-c370-4456-a296-ba6113c042f7)

**Comment by FreeLiC** [comment]
@DavisYao88 

https://github.com/antvis/S2/assets/22054917/58931cb3-7839-4003-8927-07eb54cc9d45

这是官网示例的复现视频

**Comment by DavisYao88** [comment]
> @DavisYao88
> 
>  iShot_2024-06-11_15.35.19.mp4 
> 这是官网示例的复现视频

![image](https://github.com/antvis/S2/assets/24189898/73466a83-008e-4de7-9b8b-aa6b562184ad)
使用这个版本试试，

**Comment by xiaogang12131** [comment]
> 下周发布

hello，这个发布了，我下载最新的next，还是会栈溢出

**Comment by lijinke666** [comment]
见 https://github.com/antvis/S2/issues/2771#issuecomment-2208464399

> 请勿在已关闭的 issue 继续回复
