### ISSUE TITLE
@antv/s2-react未引用新版本@antv/s2

### ISSUE THREAD

**Issue by cweijan** [antvis/S2#2634]
@antv/s2-react版本: 2.0.0-next.15

目前@antv/s2-react的peerDependencies定义中, @antv/s2的版本是1.x, 但是代码调用却用了2.x的代码, 目前我通过npm i --force强制安装, 希望能尽快修复.

**Comment by cweijan** [comment]
@lijinke666 我想我已经说得很清楚了.

**Comment by lijinke666** [comment]
已知问题 https://github.com/antvis/S2/pull/2633

**Comment by cweijan** [comment]
Thanks~
