### ISSUE TITLE
透视表resize后怎么保存效果，刷新页面也能展示调整后的效果🤔

### ISSUE THREAD

**Issue by zcc19910728** [antvis/S2#2635]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.14    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ *] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表resize后怎么保存效果，刷新页面也能展示调整后的效果，比如resize后触发某个回调透出所有单元格宽高信息，然后我能保存到服务端，下次进入页面渲染的时候我能把这些信息直接导入表格里，就不需要手动去设置每个单元格
### 🔗 Reproduce Link

https://s2.antv.antgroup.com/api/general/s2-options#resizeinteractionoptions

**Comment by lijinke666** [comment]
1. 监听 [宽高拖拽调整](https://s2.antv.antgroup.com/api/general/s2-event#%E5%AE%BD%E9%AB%98%E6%8B%96%E6%8B%BD%E8%B0%83%E6%95%B4) 事件，自行进行存储
2. 然后配置 `s2Options.style` [自定义单元格宽高](https://s2.antv.antgroup.com/manual/advanced/custom/cell-size) 即可。

后续补充下相关文档示例。
