### ISSUE TITLE
🐛容器使用缩小的属性如transform-origin: 0px 0px; transform: scale(0.661111, 0.661111);出现鼠标焦点错位的情况

### ISSUE THREAD

**Issue by V-Max** [antvis/S2#2636]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.15    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [-] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

使用style = "transform-origin: 0px 0px; transform: scale(0.661111, 0.661111)" 设置在容器上，加载TableSheet后，鼠标焦点错乱。
### ⌨️ Code Snapshots

`
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { S2DataConfig, S2Options, TableSheet } from '@antv/s2';
import html2canvas from 'html2canvas';

@Component({
  selector: 'app-s2-table',
  templateUrl: './s2-table.component.html',
})
export class S2TableComponent implements OnInit {
  @ViewChild('container', { static: true }) container: ElementRef<any>;

  img : string = '';

  ngOnInit() {
    const data = [
      // 静态数据
      
        {
          "province": "浙江",
          "city": "杭州",
          "type": "笔",
          "price": 1
        },
        {
          "province": "浙江",
          "city": "杭州",
          "type": "纸张",
          "price": 2
        },
        {
          "province": "浙江",
          "city": "舟山",
          "type": "笔",
          "price": 17
        },
        {
          "province": "浙江",
          "city": "舟山",
          "type": "纸张",
          "price": 6
        },
        {
          "province": "吉林",
          "city": "长春",
          "type": "笔",
          "price": 8
        },
        {
          "province": "吉林",
          "city": "白山",
          "type": "笔",
          "price": 12
        },
        {
          "province": "吉林",
          "city": "长春",
          "type": "纸张",
          "price": 3
        },
        {
          "province": "吉林",
          "city": "白山",
          "type": "纸张",
          "price": 25
        },
        {
          "province": "浙江",
          "city": "杭州",
          "type": "笔",
          "price": 20
        },
        {
          "province": "浙江",
          "city": "杭州",
          "type": "纸张",
          "price": 10
        },
        {
          "province": "浙江",
          "city": "舟山",
          "type": "笔",
          "price": 15
        },
        {
          "province": "浙江",
          "city": "舟山",
          "type": "纸张",
          "price": 2
        },
        {
          "province": "吉林",
          "city": "长春",
          "type": "笔",
          "price": 15
        },
        {
          "province": "吉林",
          "city": "白山",
          "type": "笔",
          "price": 30
        },
        {
          "province": "吉林",
          "city": "长春",
          "type": "纸张",
          "price": 40
        },
        {
          "province": "吉林",
          "city": "白山",
          "type": "纸张",
          "price": 50
        }
      
    ];

    const s2DataConfig: S2DataConfig = {
      fields: {
        columns: ['province', 'city', 'type', 'price', 'cost'],
      },
      meta: [
        { field: 'province', name: '省份' },
        { field: 'city', name: '城市' },
        { field: 'type', name: '商品类别' },
        { field: 'price', name: '价格' },
        { field: 'cost', name: '成本' },
      ],
      data,
    };

    const s2Options: S2Options = {
      width: 800,
      height: 400,
      // seriesNumber: {
      //   enable: true,
      //   text: '序号',
      // },
      showSeriesNumber: true,
      pagination: {
        pageSize: 4,
        current: 1,
      },
      placeholder: () => '-',
    };

    const s2 = new TableSheet(this.container.nativeElement, s2DataConfig, s2Options);
    s2.render();

  }
}

`
html文件：<div #container style="width: 1920px; height: 1080px; transform-origin: 0px 0px; z-index: 5; transform: scale(0.661111, 0.661111);"></div>

### 🤔 Steps to Reproduce

就是在加载的容器或者直接在容器中设置style= "transform-origin: 0px 0px; transform: scale(0.661111, 0.661111);",会出现我电脑上点击的是第二韩给的单元格，但实际选中的是第一行的单元格的情况，鼠标焦点出问题了。
![image](https://github.com/antvis/S2/assets/52316109/7b7088dc-7d2b-4cff-bd98-8a2c98b5e65e)
![image](https://github.com/antvis/S2/assets/52316109/3e970e79-47f2-41d9-ba31-d4e31e3d8e32)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
```ts
const s2Options = {
  transformCanvasConfig() {
    return {
      supportsCSSTransform: true
    }
  }
}
```

https://s2.antv.antgroup.com/manual/faq#%E7%88%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E4%BD%BF%E7%94%A8%E4%BA%86-transform-scale-%E5%90%8E%E5%9B%BE%E8%A1%A8%E9%BC%A0%E6%A0%87%E5%9D%90%E6%A0%87%E5%93%8D%E5%BA%94%E4%B8%8D%E6%AD%A3%E7%A1%AE
