### ISSUE TITLE
🐛 react SheetComponent 单元格内渲染G失败

### ISSUE THREAD

**Issue by Jacleklm** [antvis/S2#2641]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   2.0.0-next.16      |
| @antv/s2-react |    2.0.0-next.15     |

### Sheet Type

- [x] PivotSheet

### 🖋 Description

 sandbox: https://codesandbox.io/p/sandbox/s2-debug-sandbox-v2-0-yl82f7?file=%2Fsrc%2FBaseDemo.tsx%3A1%2C10-1%2C24
 预期是 DataCell 能渲染出G绘制的图形和背景图
![image](https://github.com/antvis/S2/assets/50861119/141501a1-d222-4bec-9b1b-49911d3ae29b)

### 😊 Expected Behavior
期望在单元格内能渲染出G绘制的图形和背景图

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   window10      |
| Browser |     chrome    |

**Comment by lijinke666** [comment]
本地未复现

![image](https://github.com/antvis/S2/assets/21015895/ce399282-6e7c-484f-bce7-14834af991ed)
