### ISSUE TITLE
🤔 自定义目录的情况下还能自定义列头吗？

### ISSUE THREAD

**Issue by wozien** [antvis/S2#2646]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   next      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

自定义目录的情况下还能自定义列头吗？可以的话，数据data的格式是怎么样的？

**Comment by lijinke666** [comment]
不支持

**Comment by wozien** [comment]
> 不支持

感谢回复
