### ISSUE TITLE
s2-vue分页组件透传无效🤔

### ISSUE THREAD

**Issue by lixiaosaKk** [antvis/S2#2648]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |        latest |
| @antv/s2-react |         |
| @antv/s2-vue   |       latest  |

### Sheet Type

- [ ✅] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

s2-vue分页组件透传无效
<img width="1996" alt="image" src="https://github.com/antvis/S2/assets/84568102/bb12046d-56ae-471d-819c-28902e2167d3">@lijinke666

**Comment by lixiaosaKk** [comment]
<img width="1982" alt="image" src="https://github.com/antvis/S2/assets/84568102/6c830473-3f28-4f49-9620-e1c52e2e9447">
使用的zh这个demo加的参数

**Comment by lixiaosaKk** [comment]
<img width="476" alt="image" src="https://github.com/antvis/S2/assets/84568102/8ada9291-c23a-4457-8bc2-a98c29c45c4a">
我本地的@antv/s2-vue版本为1.6.1，分页透传参数也不生效

**Comment by lixiaosaKk** [comment]
<img width="1376" alt="image" src="https://github.com/antvis/S2/assets/84568102/4916e6ca-4422-4b54-8f22-7e4a2b7ea653">
s2-vue分页源码里size写死了small，而且并没有冗余的传参，也就是说它根本不接受传进去的其他分页参数

**Comment by lijinke666** [comment]
近期修复, 感兴趣的话可以直接 PR.
