### ISSUE TITLE
🤔[NEXT] 没法在 actionIcon中使用多色图标

### ISSUE THREAD

**Issue by Volankey** [antvis/S2#2654]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.17     |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

没法在 actionIcon中使用多色图标
1. 看目前源码逻辑，填写 fill 会全部替换颜色
2. 如果不写 fill 会使用 defaultText 的颜色

是否有好的解决方案？我可以提 pr

**Comment by lijinke666** [comment]
是指像字段标记一样支持 fill 改颜色，还是说 SVG 本身是彩色的？

**Comment by Volankey** [comment]
> 是指像字段标记一样支持 fill 改颜色，还是说 icon 本身是彩色的？

icon本身是彩色的，现有逻辑看起来没法保留原有的颜色

**Comment by lijinke666** [comment]
> 看目前源码逻辑，填写 fill 会全部替换颜色

这个主要用于字段标记替换颜色的场景, actionIcon 按理说不会替换 fill, svg 的 fill 应该是 'currentColor', 麻烦提供一个 demo, 看看你咋写的, 我看看如何优化

**Comment by Volankey** [comment]
https://codesandbox.io/p/sandbox/modern-brook-97c8fc?file=%2Fsrc%2Findex.js%3A27%2C17
如果没传的话使用了`defaultTextFill`
https://github.com/antvis/S2/blob/next/packages/s2-core/src/cell/header-cell.ts#L206

**Comment by lijinke666** [comment]
> [codesandbox.io/p/sandbox/modern-brook-97c8fc?file=%2Fsrc%2Findex.js%3A27%2C17](https://codesandbox.io/p/sandbox/modern-brook-97c8fc?file=%2Fsrc%2Findex.js%3A27%2C17) 如果没传的话使用了`defaultTextFill` [`next`/packages/s2-core/src/cell/header-cell.ts#L206](https://github.com/antvis/S2/blob/next/packages/s2-core/src/cell/header-cell.ts?rgh-link-date=2024-04-17T07%3A23%3A08Z#L206)

可以这样改, 不改变优先级规则, 同时可以避免使用兜底的 defaultTextFill

![image](https://github.com/antvis/S2/assets/21015895/9b22798c-5928-48f8-9ec0-53c48fa6f244)


```diff
headerActionIcons: [
  {
    icons: [
      {
        name: 'customKingIcon',
        position: 'right',
+       fill: '',
      },
    ],
    belongsCell: 'colCell',
  },
]
```

```diff
protected getActionIconStyle(
  options: Partial<HeaderActionIconOptions>,
): Partial<GuiIconCfg> {
  const { icon } = this.getStyle()!;
  const conditionStyle = this.getTextConditionMappingResult();
  const defaultTextFill = conditionStyle?.fill || this.getTextStyle().fill!;

  return {
    width: icon?.size,
    height: icon?.size,
    // 优先级: 单个 icon 颜色配置 > 全部 icon 颜色配置 > 主题 icon 颜色配置 > 文本默认颜色
-   fill: options?.fill || icon?.fill || defaultTextFill,
+   fill: options?.fill ?? icon?.fill ?? defaultTextFill,
    cursor: 'pointer',
  };
}
```

**Comment by Volankey** [comment]
> > [codesandbox.io/p/sandbox/modern-brook-97c8fc?file=%2Fsrc%2Findex.js%3A27%2C17](https://codesandbox.io/p/sandbox/modern-brook-97c8fc?file=%2Fsrc%2Findex.js%3A27%2C17) 如果没传的话使用了`defaultTextFill` [`next`/packages/s2-core/src/cell/header-cell.ts#L206](https://github.com/antvis/S2/blob/next/packages/s2-core/src/cell/header-cell.ts?rgh-link-date=2024-04-17T07%3A23%3A08Z#L206)
> 
> 可以这样改, 不改变优先级规则, 同时可以避免使用兜底的 defaultTextFill, 这样如果能满足你的诉求, 可以尝试来个 PR
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/323508797-9b22798c-5928-48f8-9ec0-53c48fa6f244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjYwODQsIm5iZiI6MTcxMzQyNTc4NCwicGF0aCI6Ii8yMTAxNTg5NS8zMjM1MDg3OTctOWIyMjc5OGMtNTkyOC00OGY4LTllYzAtNTNjNDhmYTZmMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NDBkNzc3YzcwODNlNzc2ZTg5ZDY3YmU4MWZjMDg5OGUxNGU4OTdkMWRkMGUxOGY3NDQyZGEyMjllMjVjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NX00vlGBDNSMhMu08OHi1aZjkldWnDxwIIAjOPTxtLM)
> 
> ```diff
> headerActionIcons: [
>   {
>     icons: [
>       {
>         name: 'customKingIcon',
>         position: 'right',
> +       fill: '',
>       },
>     ],
>     belongsCell: 'colCell',
>   },
> ]
> ```
> 
> ```diff
> protected getActionIconStyle(
>   options: Partial<HeaderActionIconOptions>,
> ): Partial<GuiIconCfg> {
>   const { icon } = this.getStyle()!;
>   const conditionStyle = this.getTextConditionMappingResult();
>   const defaultTextFill = conditionStyle?.fill || this.getTextStyle().fill!;
> 
>   return {
>     width: icon?.size,
>     height: icon?.size,
>     // 优先级: 单个 icon 颜色配置 > 全部 icon 颜色配置 > 主题 icon 颜色配置 > 文本默认颜色
> -   fill: options?.fill || icon?.fill || defaultTextFill,
> +   fill: options?.fill ?? icon?.fill ?? defaultTextFill,
>     cursor: 'pointer',
>   };
> }
> ```
fill 传 `null` 会不会表义更清楚一些？

**Comment by lijinke666** [comment]
传 `null` 不就和 `||` 一样的效果了吗?

**Comment by Volankey** [comment]
> 传 `null` 不就和 `||` 一样的效果了吗?

 fill: options?.fill ?? icon?.fill ?? defaultTextFill `null` 的话代码就不这么写了

**Comment by lijinke666** [comment]
恩, 确实 `null` 似乎更符合直觉一点, 期待你的 PR

**Comment by Volankey** [comment]
> 恩, 确实 `null` 似乎更符合直觉一点, 期待你的 PR

行，这周末我看看，提个pr

**Comment by lijinke666** [comment]
好的, 请确保 PR 尽量包含如下:

- 代码改动
- 相应的单测: packages/s2-core/__tests__/spreadsheet/header-action-icons-spec.ts
- 相应的示例完善: s2-site/examples/custom/custom-icon/demo
- 相应的 API 说明 (补充下功能描述):  s2-site/docs/common/custom/headerActionIcons.zh.md
![image](https://github.com/antvis/S2/assets/21015895/2f7aeb52-0319-4410-a711-a055f609ffec)

> 如何本地调试请参考 [贡献指南](https://s2.antv.antgroup.com/manual/contribution#%EF%B8%8F-%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91)
