### ISSUE TITLE
🐛s2 自定义单元格appendChild 绘制antv/g Rect坐标设置了无效一直在左上角 

### ISSUE THREAD

**Issue by wf335889056** [antvis/S2#2659]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  ^2.0.0-next.17       |
| @antv/s2-react |  ^2.0.0-next.16       |
| @antv/s2-vue   |         |

### Sheet Type

- [ 1] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![1713168659572](https://github.com/antvis/S2/assets/29749431/53de8605-f06c-4b6c-a78e-381b72bac176)
![image](https://github.com/antvis/S2/assets/29749431/16327671-31cc-4ba2-a0d5-35c3d129e651)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   window10      |
| Browser |   123.0.6312.107       |

**Comment by FuYanson** [comment]
问题解决了吗?

**Comment by lijinke666** [comment]
长时间未提供最小可复现示例, issue 关闭.
