### ISSUE TITLE
透视表是否能支持组合透视图🙏

### ISSUE THREAD

**Issue by tufaofu** [antvis/S2#2660]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.51.1     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
是否能支持类似Vtable的组合透视图的能力
<img width="1440" alt="image" src="https://github.com/antvis/S2/assets/74943736/ee2e082a-678f-4a5f-9fd4-6ea045f3b63c">

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
2.0 支持类似的组合图 https://s2.antv.antgroup.com/examples/custom/custom-shape-and-chart/#custom-g2-chart
