### ISSUE TITLE
🤔 S2 对比传统表格，其中传统表格上部分功能是否支持问题咨询------希望大佬帮忙解答一下

### ISSUE THREAD

**Issue by beezen** [antvis/S2#2670]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.55.0     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

1、是否可以支持自定义加载动画的能力？（面对请求服务返回数据场景，很有必要）
![image](https://github.com/antvis/S2/assets/13111739/5238dfc0-c0bc-42b1-8396-b4b1e2ae8642)

2、是否可以支持数据为空时，自定义显示 noData 的效果？
![image](https://github.com/antvis/S2/assets/13111739/bc36ec68-652e-47e9-b7bb-e8d190001bb3)

3、是否可以支持 checkbox 这类选择样式？（习惯了传统的这种选择交互，很有必要）
![image](https://github.com/antvis/S2/assets/13111739/a8c2696a-1f3a-4333-be98-d414f014eca1)

4、是否可以支持行数据向上或向下拖拽的功能？（主要是为了方便分析）
![image](https://github.com/antvis/S2/assets/13111739/758a2ac6-85c3-4de8-84dc-d420e3e5ff69)

**Comment by lijinke666** [comment]
1: 建议直接在表格上面绝对定位加一个 div 蒙层即可.
2: 在 2.0 版本后续的迭代计划中, 后面会加上.
3/4: 由于是 Canvas, 实现成本较高, 需要模拟一个 checkbox/radio 的 UI 和交互, 如果要加, 单选/多选都需要考虑, 人力有限, 和第四点一样, 纳入2.0 版本需求池, 不过优先级不高.

**Comment by beezen** [comment]
> 1: 建议直接在表格上面绝对定位加一个 div 蒙层即可. 2: 在 2.0 版本后续的迭代计划中, 后面会加上. 3/4: 由于是 Canvas, 实现成本较高, 需要模拟一个 checkbox/radio 的 UI 和交互, 如果要加, 单选/多选都需要考虑, 人力有限, 和第四点一样, 纳入2.0 版本需求池, 不过优先级不高.

上面的点都了解了，**在这里再问一个点**。
@lijinke666 
如果要实现最后一列添加（**编辑，删除**）这样的功能，我们自己在源码层面，调用 G6 引擎绘制到 S2 的最后一列节点上，这样的方案可行不，还是说有更好的方法。
![image](https://github.com/antvis/S2/assets/13111739/5b56357a-bfbd-4c0c-b967-1bd039b764dc)
