### ISSUE TITLE
🙏应属于同一类的资料，被取代了而不是加总显示。

### ISSUE THREAD

**Issue by FuJun-Tsai** [antvis/S2#2677]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @node | v14.15.1 |
| @antv/s2       |    ^1.55.1    |
| @antv/s2-react |         |
| @antv/s2-vue   |     ^1.7.1    |
| @vue   |     ^3.2.13    |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

a.有条件相符的数据被取代，显示与资料有所出入
b.能否显示符合的资料笔数(count)

### 🏞 What problem does this feature solve

![1713865589805](https://github.com/antvis/S2/assets/55325225/b9759ebc-9c06-4bad-b7e5-faab8cc2992f)
【图一】程式码截图
图一为所有资料，仅测试资料，无商业用途。

![1713865636701](https://github.com/antvis/S2/assets/55325225/a911ceed-87db-40d7-91fd-20cbddecbbd2)
【图二】网页结果
图二为网页结果，消费日期为2020/1/4 且 顾客等级为VVIP 且 顾客姓名为H 满足条件的资料有两笔（图一所示）。
但在图表中是以新资料取代旧资料的方式呈现，是否可以在数值型别时将其加总。

sandbox 程式码
https://codesandbox.io/p/sandbox/old-violet-xc98yq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvc6lvf60006356igyf9ldw4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvc6lvf60002356is9rt40cl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvc6lvf60003356ibj9wchlx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvc6lvf60005356i4stswxc8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvc6lvf60002356is9rt40cl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvc6lvf50001356ijknzefml%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A22%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvc6lvf60002356is9rt40cl%2522%252C%2522activeTabId%2522%253A%2522clvc6lvf50001356ijknzefml%2522%257D%252C%2522clvc6lvf60005356i4stswxc8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvc6lvf60004356ik9r5ebad%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvc6lvf60005356i4stswxc8%2522%252C%2522activeTabId%2522%253A%2522clvc6lvf60004356ik9r5ebad%2522%257D%252C%2522clvc6lvf60003356ibj9wchlx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvc6lvf60003356ibj9wchlx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

第一次于开源专案提问，感谢你们阅读我的建议，再麻烦各位了。
如果上述的建议已经有了，再麻烦你们拨冗告知我，很抱歉成为一个不好的典范。

**Comment by lijinke666** [comment]
你的配置有问题, `2020/1/4` 有两条数据, 但是属于不同的 `place`, 所以你的列头需要配置 `place` 才能正确展示.

![image](https://github.com/antvis/S2/assets/21015895/167ed77e-5404-4165-a2d2-d0277f5d0f8b)

如果你想表达的是希望展示两列, 但是不想展示 `place`, 可以将其隐藏

```ts
const s2options = {
  width: 800,
  height: 600,
  style: {
    colCfg: {
      heightByField: {
        place: 0
      }
    }
  }
};
```

![image](https://github.com/antvis/S2/assets/21015895/ef8a1f3a-f766-4b51-9031-204eaab9e9d0)

**Comment by FuJun-Tsai** [comment]
谢谢大大的回覆，感谢你拨冗回覆我的问题，已解决我的疑惑。
