### ISSUE TITLE
2.0 版本可以取消 antd 的强绑定么？ 🙏

### ISSUE THREAD

**Issue by XiChaoMing** [antvis/S2#2680]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0  |
| @antv/s2-react |  2.0.0  |
| @antv/s2-vue   |   -     |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🏞 What problem does this feature solve

- 长期维护项目使用的 antd 版本是 4.9.4
- 要使用 S2 的 2.0 版本，但是 2.0 版本需要 5.0 版本的 antd
- 升级 antd 到 5.0 版本的代价过高，会有很多 css 样式带来的问题 （升级原因仅仅是因为要使用 S2 的 2.0 版本......）
- 是否考虑取消对于 antd 的强绑定？

### 🧐 Suggest the API

是否考虑取消对于 antd 的强绑定？

**Comment by lijinke666** [comment]
暂时不会考虑, 大版本升级必然会带来很多不兼容的改动, 主要是为了长远考虑和以后得可维护性, 这边有两个建议:

- 2.0 版本的 `s2-react` 主要是 分页/下钻/Tooltip/高级排序/指标切换 等分析组件依赖 antd, antd 5 可以[多版本共存](https://ant-design.antgroup.com/docs/react/migration-v5-cn#%E5%A4%9A%E7%89%88%E6%9C%AC%E5%85%B1%E5%AD%98), 如果你对 `s2-react` 的这些分析组件有强诉求可以考虑多版本共存.
- 如果仅仅是使用了 `<SheetComponent />`, 只是希望在 React 中使用 S2, 那么完全可以只使用无任何额外依赖的 `@antv/s2`, 参考 [在 React 中使用 `@antv/s2`](https://s2.antv.antgroup.com/manual/basic/sheet-type/pivot-mode#%E4%BD%BF%E7%94%A8-antvs2)

**Comment by XiChaoMing** [comment]
好的，谢谢~
