### ISSUE TITLE
next版本自定义 DataCell，给数值单元格添加HTML内容, HTML会覆盖在冻结行列上方

### ISSUE THREAD

**Issue by FuYanson** [antvis/S2#2683]
🏷 Version
   node: v20.10.0
   npm: 9.5.0
    "@antv/g": "^6.0.2",
    "@antv/s2": "2.0.0-next.17",
    "@antv/s2-vue": "2.0.0-next.12",
    "vue": "^3.3.8",

```
export class CustomDataCell extends DataCell {
    // 重写数值单元格
    initCell () {
        super.initCell();
        // 绘制图形
        this.renderDrawGraph();
    }
    // 绘制图形
    renderDrawGraph () {
        let { x, y, width, height, data, valueField, rowIndex, colIndex, rowId, colId, spreadsheet, field, id } = this.meta;
        const cellMeta = spreadsheet.facet.getCellMeta(rowIndex, colIndex)
        const layoutResult = spreadsheet.facet?.getLayoutResult()
        const canvas = spreadsheet.getCanvas()
        let { customParams } = this.spreadsheet.options
        const params = customParams?.params
        let positionX = x;
        let positionY = y + height / 2;
        const currentData = data?.raw
        const innerHTML = `<div id="container" style="overflow: hidden;">
                <div></div>
                <div style="display:inline-block;">
                    <div style="background-color: #F1F2F6; border-radius: 6px;color: #aaaaab;">同比</div> 
                    <div>20%</div> 
                </div>
                <div style="display:inline-block;">
                    <div style="background-color: #F1F2F6; border-radius: 6px;color: #aaaaab;">上期</div> 
                    <div>200.00</div> 
                </div>
            <div>`
            const html = new HTML({
                style: {
                    x,
                    y,
                    width,
                    height,
                    innerHTML,
                    fontSize: '12px',
                    textAlign: 'center',
                    pointerEvents: 'none', // 让事件穿透它
                    // color: '#000',
                    // visibility: 'hidden',
                },
            })
            // canvas.appendChild(html);
            this.appendChild(html);
    }
```
<img width="1098" alt="image" src="https://github.com/antvis/S2/assets/41688233/4effc7be-dc63-471c-8b33-de9d2d917476">
<img width="1107" alt="image" src="https://github.com/antvis/S2/assets/41688233/d6fcfab1-1b20-40ef-8b63-5383a370fede">

[appendChild 绘制的图形 始终定位在一处, 未根据所设置的x、y轴坐标定位](https://github.com/antvis/S2/issues/2659)

**Comment by lijinke666** [comment]
你在 `initCell` 后渲染的 `HTML` 图层, 如 G 的[文档所示](https://g.antv.antgroup.com/api/basic/html),  `HTML` 的实现是在 `<canvas/>` 中添加一个 DOM 元素, 就好比所有元素都是绝对定位, 需要自行管理所有图层的坐标的裁剪.

![image](https://github.com/antvis/S2/assets/21015895/ffb9697f-e32a-45c2-8836-dff604ede988)

内部单元格已经适配了滚动后的裁剪:

https://github.com/antvis/S2/blob/6a71390795b40cfc4d42f5740349a25a14269524/packages/s2-core/src/facet/base-facet.ts#L1639-L1654

所以, 你虽然看似是添加在单元格内部, 但是其实元素变成了一个绝对定位的 dom, 而不是一个单元格内部的 Group 图层.

```ts
this.appendChild(html);
```

你光设置了 HTML 的 宽高左边和单元格一致, 但是还需考虑滚动的偏移/裁剪等问题, 比如在滚动裁剪溢出部分, 避免遮挡, 需要对源码和 AntV/G 有一定的了解, 上手成本有点高, 不建议这样使用.

https://github.com/antvis/S2/blob/6a71390795b40cfc4d42f5740349a25a14269524/packages/s2-core/src/facet/frozen-facet.ts#L718-L725

https://github.com/antvis/S2/blob/6a71390795b40cfc4d42f5740349a25a14269524/packages/s2-core/src/facet/header/row.ts#L134-L158
