### ISSUE TITLE
🤔列头分组后，数据进行格式化meta，导出表格的列头非字段名，而是格式化后的数据？

### ISSUE THREAD

**Issue by Zhaohanqi12** [antvis/S2#2688]
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |     next    |

- [ √ ] PivotSheet
- [ √ ] TableSheet

### 🖋 Description
列头分组后，数据进行格式化meta，导出表格的列头非字段名，为格式化后的数据

### 🔗 Reproduce Link

https://codesandbox.io/p/devbox/lt48gr?migrateFrom=z9zhfg&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvj986je0006356f8hhyckco%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvj986je0002356ftuh8gz6v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvj986je0004356foohjuhbm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvj986je0005356flih8t4nc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvj986je0002356ftuh8gz6v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvj986je0001356fxa8ljz1o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clvj986je0002356ftuh8gz6v%2522%252C%2522activeTabId%2522%253A%2522clvj986je0001356fxa8ljz1o%2522%257D%252C%2522clvj986je0005356flih8t4nc%2522%253A%257B%2522id%2522%253A%2522clvj986je0005356flih8t4nc%2522%252C%2522activeTabId%2522%253A%2522clvj98ou6009g356fsqpitps9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clvj98ou6009g356fsqpitps9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvj986je0004356foohjuhbm%2522%253A%257B%2522id%2522%253A%2522clvj986je0004356foohjuhbm%2522%252C%2522activeTabId%2522%253A%2522clvj98kuq007c356fap59bo13%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvj986je0003356fj0353btm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvj987mg000jdif8b7gjh2s1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clvj98kuq007c356fap59bo13%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Zhaohanqi12** [comment]
https://codesandbox.io/p/sandbox/flamboyant-greider-z9zhfg?file=%2Fsrc%2Findex.ts%3A52%2C30

**Comment by lijinke666** [comment]
![image](https://github.com/antvis/S2/assets/21015895/a9bf69dd-3e42-4a7e-874e-59bd80538e44)

你的 meta 只有数值的格式化, 又没有配置列头的格式化, 自定义列头的情况下, 列头都是按维值处理, 即导出默认是以 `title` 为准, 符合预期.

你的期望是 `formatHeader: false` 的情况下, 希望是用 `field` 而不是 `title` ?

**Comment by Zhaohanqi12** [comment]
当然希望用title了，但是导出的不符合预期，是meta格式的数据格式展示的列头，有示例https://codesandbox.io/p/sandbox/flamboyant-greider-z9zhfg?file=%2Fsrc%2Findex.ts%3A52%2C30，&nbsp;formatHeader: false好像不起作用，可以导出看一下。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinke ***@***.***&gt;; 
发送时间: 2024年4月29日(星期一) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/S2] 🤔列头分组后，数据进行格式化meta，导出表格的列头非字段名，而是格式化后的数据？ (Issue #2688)














 
image.png (view on web)
 
你的 meta 只有数值的格式化, 又没有配置列头的格式化, 自定义列头的情况下, 列头都是按维值处理, 即导出默认是以 title 为准, 符合预期.
 
你的期望是 formatHeader: false 的情况下, 希望是用 field 而不是 title ?

**Comment by lijinke666** [comment]
`formatHeader` 是控制使用 `field` 还是 `name`, 对于自定义场景, 是控制使用 `field` 还是 `title`

> 当然希望用title了

所以你应该使用 `formatHeader: true`, 而 meta 中的 formatter 只会对数值生效, 不应该作用于列头, 这个是 bug

**Comment by Zhaohanqi12** [comment]
希望能修复一下，谢谢

**Comment by Zhaohanqi12** [comment]
我的需求是以title定义的名字返回，而不是用field原始字段的返回。
