### ISSUE TITLE
data cell合并之后能自定义渲染吗？

### ISSUE THREAD

**Issue by czbczb** [antvis/S2#2702]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/examples/custom/custom-cell/#custom-merged-cell

https://s2.antv.antgroup.com/zh/examples/custom/custom-cell/#custom-specified-cell
