### ISSUE TITLE
透视表渲染10w+的单元格内存持续飙升（可能内存泄漏）浏览器崩溃

### ISSUE THREAD

**Issue by Azhi-ux** [antvis/S2#2710]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.19   |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

<img width="1020" alt="image" src="https://github.com/antvis/S2/assets/57614070/f51d6548-d06b-40e6-8dce-f4c131786c4b">
这里为什么要一下子处理所有单元格的宽高呢，在这里很容易直接内存oom；

![image](https://github.com/antvis/S2/assets/57614070/c4ebacaf-b6bd-4ee2-b592-63e51e608073)

而且拖拽列头依然会执行到这块方法；内存持续飙升；

![image](https://github.com/antvis/S2/assets/57614070/c457fb9f-e51a-4cac-91a8-e38b134a652a)

还有官网事例

### 😊 Expected Behavior
期望能关注内存占用的问题

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   Mac: 14.1     |
| Browser |    Chrome: 124.0.6367.92     |

**Comment by wyh888** [comment]
这里是因为每一次重新布局都会重新绘制文本，计算行头的高度，我这边临时的解决方案是覆写 `getRowNodeHeight` 方法，可以参考下：

```javascript
import { PivotFacet } from "@antv/s2";

export class PivotFacetSetter extends PivotFacet {
  constructor(spreadsheet) {
    super(spreadsheet);
  }

  // 自定义行头节点高度
  getRowNodeHeight() {
   // ...
    return this.spreadsheet.options.style?.rowCell?.height || 30;
  }
}
```

在 `options` 中：

```javascript
const options = {
  facet: sheetType === 'pivot' ? (spreadsheet) => new PivotFacetSetter(spreadsheet) : null,
}
```

**Comment by Azhi-ux** [comment]
> 这里是因为每一次重新布局都会重新绘制文本，计算行头的高度，我这边临时的解决方案是覆写 `getRowNodeHeight` 方法，可以参考下：
> 
> ```js
> import { PivotFacet } from "@antv/s2";
> 
> export class PivotFacetSetter extends PivotFacet {
>   constructor(spreadsheet) {
>     super(spreadsheet);
>   }
> 
>   // 自定义行头节点高度
>   getRowNodeHeight() {
>    // ...
>     return this.spreadsheet.options.style?.rowCell?.height || 30;
>   }
> }
> ```
> 
> 在 `options` 中：
> 
> ```js
> const options = {
>   facet: sheetType === 'pivot' ? (spreadsheet) => new PivotFacetSetter(spreadsheet) : null,
> }
> ```

好的，感谢大佬，我试试🙏
