### ISSUE TITLE
更新到2.x版本，明细表自定义排序，菜单点击无效果

### ISSUE THREAD

**Issue by RosyClousXun** [antvis/S2#2715]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.19     |
| @antv/s2-react |     未使用    |
| @antv/s2-vue   |    2.0.0-next.13     |
| vue   |    3.2.33    |
| ant-design-vue |    3.2.17    |

### Sheet Type   

- [x] TableSheet

### 🖋 Description

按照官网自定义排序操作了一遍，下拉菜单能正常点击出来，但是点击下拉菜单项没反应。
![image](https://github.com/antvis/S2/assets/22146752/47493a18-5bc4-4ff6-a48c-31a40c10d09c)
![image](https://github.com/antvis/S2/assets/22146752/42d528d5-abe9-4276-9812-6fa30eea91f9)
如图，红框里的click方法进不去，之前1.x版本是可以正常进去的。

**Comment by RosyClousXun** [comment]
https://s2.antv.antgroup.com/manual/advanced/custom/custom-order    官方文档描述有错误，应该将click方法放到menu选项中

**Comment by lijinke666** [comment]
> [s2.antv.antgroup.com/manual/advanced/custom/custom-order](https://s2.antv.antgroup.com/manual/advanced/custom/custom-order) 官方文档描述有错误，应该将click方法放到menu选项中

是的, 文档有误, 感谢反馈, 后续修复
