### ISSUE TITLE
🤔 官网示例 sandbox 打开报错

### ISSUE THREAD

**Issue by MaekBlack** [antvis/S2#2717]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🔗 Reproduce Link
sandbox 地址 https://codesandbox.io/p/sandbox/nice-forest-4mqz3l?file=%2Findex.ts

### 😊 Expected Behavior
![image](https://github.com/antvis/S2/assets/45852479/81f56c58-2f1f-47c3-a429-1dfd3a7e7fcb)

### 😅 Current Behavior
![image](https://github.com/antvis/S2/assets/45852479/41f806a9-9b80-4d80-a471-48a3d7eac244)

另：该示例直接打开失败
<img width="1469" alt="image" src="https://github.com/antvis/S2/assets/45852479/1bcaf2e5-41ba-4a49-b085-6f8eaa694b53">

**Comment by lijinke666** [comment]
> sandbox 地址 [codesandbox.io/p/sandbox/nice-forest-4mqz3l?file=%2Findex.ts](https://codesandbox.io/p/sandbox/nice-forest-4mqz3l?file=%2Findex.ts)

感谢反馈, 这个地址是从哪里复制的?
