### ISSUE TITLE
🤔导出功能中能否不对日期进行格式化

### ISSUE THREAD

**Issue by Zhaohanqi12** [antvis/S2#2723]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1x    |
| @antv/s2-react |    1x     |
| @antv/s2-vue   |         |

### Sheet Type

- [√ ] PivotSheet
- [√ ] TableSheet

### 🖋 Description

![image](https://github.com/antvis/S2/assets/166707652/1e5c21d7-1829-493e-9f03-2536d9cf55d9)

![image](https://github.com/antvis/S2/assets/166707652/a14d9a25-111e-4576-bebd-1ae03dfad779)

**Comment by lijinke666** [comment]
日期格式化不是 S2 做的, 是 Excel 对日期的默认行为, 可以自行更改单元格格式

![image](https://github.com/antvis/S2/assets/21015895/1812af2b-62d0-48a6-972a-98a97f03a87d)
