### ISSUE TITLE
透视表：布局方式使用 layoutWidthType: 'colAdaptive' 宽度足够的情况下表头有省略号出现？🤔

### ISSUE THREAD

**Issue by db-shuai** [antvis/S2#2726]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.20   |
| @antv/s2-react |    -     |
| @antv/s2-vue   |     -    |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

行头稍微长一点 就会展示出 省略号，v1版本却不会！

<img width="1113" alt="image" src="https://github.com/antvis/S2/assets/40795095/e9c6e884-1480-404b-9610-c19d867e8356">

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/little-butterfly-fq9m6j?file=%2Fpackage.json%3A9%2C2

### 😊 Expected Behavior
期望行头不出现省略号，文本正常展示！

**Comment by lijinke666** [comment]
Demo 打不开

**Comment by db-shuai** [comment]
https://codesandbox.io/p/sandbox/little-butterfly-fq9m6j?file=%2Findex.ts%3A300%2C13

不好意思 是角头 ， 链接开了一下权限 你看看

> Demo 打不开, 另外你截图的部分是角头, 不是行头

**Comment by lijinke666** [comment]
好的, 近期排期一下

**Comment by lijinke666** [comment]
2.0 的布局机制变了, 所以表现会有一点不一样, 对于 colAdaptive 还有点问题, 如果你想和 v1 一样, 先这样改

```ts
  cornerCell: {
    wordWrap: false,
  }
```

![image](https://github.com/antvis/S2/assets/21015895/45cfa5e3-7bde-416e-bea1-67bca6a3c35b)
