### ISSUE TITLE
🐛SheetComponent 里面设置的 cell 高度没有生效

### ISSUE THREAD

**Issue by egolink0** [antvis/S2#2736]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.21    |
| @antv/s2-react |      2.0.0-next.20   |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet(SheetComponent)
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### ⌨️ Code Snapshots

```
 const s2Options: S2Options = {
      width: 600,
      height: 480,
      style: {
        // 列头宽度始终和数值单元格一致
        dataCell: {
          width: 200,
          height: 50, // 高度没生效
        },
        colCell: {
          width: 200,
          height: 50,
          widthByField: {
            // 特定维度 (如: 城市)
            city: 100,
            // 特定维值 (明细表场景下等同于配置特定维度)
            "root[&]province": 80,
          },
        },
        rowCell: {
          // 设置行高
          height: 40,
          // 明细表每一行根据行索引单独设置 (从 0 开始)
          heightByField: {
            "0": 40,
            "1": 130,
            "3": 60,
            "10": 80,
            "15": 20,
          },
        },
      },
    };
```

### 🤔 Steps to Reproduce
[sandbox](https://codesandbox.io/p/sandbox/goofy-leavitt-mhs2tx?file=%2Findex.tsx%3A17%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwhkqbko00062v6g62f85mfk%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwhkqbko00022v6g1t2rdql6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwhkqbko00032v6gs895fi9n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwhkqbko00052v6gpolxd75w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwhkqbko00022v6g1t2rdql6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhkqbko00012v6g1pbgqlgs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwhkqp7u00022v6gjjgfird2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwhkqbko00022v6g1t2rdql6%2522%252C%2522activeTabId%2522%253A%2522clwhkqp7u00022v6gjjgfird2%2522%257D%252C%2522clwhkqbko00052v6gpolxd75w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhkqbko00042v6g4ncjvnwi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwhkqbko00052v6gpolxd75w%2522%252C%2522activeTabId%2522%253A%2522clwhkqbko00042v6g4ncjvnwi%2522%257D%252C%2522clwhkqbko00032v6gs895fi9n%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwhkqbko00032v6gs895fi9n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 😊 Expected Behavior

预期应该根据高度设置的值变化，但现在并没有变化
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    linux deepin     |
| Browser |      chrome  122   |

**Comment by lijinke666** [comment]
Demo 示例只是演示一下各种配置如何写, 优先级规则是 `rowCell.heightByField > rowCell.height > dataCell.height`

![image](https://github.com/antvis/S2/assets/21015895/a01a5381-de4e-42ef-8cdb-b4d249c3669e)

所以这里 `dataCell.height` 是不生效的, 你想设置明细表的行头, 直接使用 [`rowCell.height`](https://s2.antv.antgroup.com/manual/advanced/custom/cell-size#%E8%B0%83%E6%95%B4%E6%98%8E%E7%BB%86%E8%A1%A8%E8%A1%8C%E9%AB%98) 就行了
