### ISSUE TITLE
🙏透视表 没数据显示一行空数据，希望支持加入图标么比如像antd table 的暂无数据

### ISSUE THREAD

**Issue by donglegend** [antvis/S2#2742]
### 🏷 Version
"@antv/s2": "2.0.0-next.21",

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description
透视表 没数据显示一行空数据，希望支持加入图标么比如像antd table 的暂无数据

### 🏞 What problem does this feature solve
![image](https://github.com/antvis/S2/assets/13144324/c0b4563d-7bee-4b86-a8b3-3beb7021f599)

透视表不支持 全部都是空数据时候的 empty-placeholder
### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

**Comment by lijinke666** [comment]
透视表不支持, 明细表是支持像 antd 那样展示的: https://s2.antv.antgroup.com/examples/custom/custom-cell/#empty-placeholder

透视表有可能是行头有维值, 但是数值为空, 也有可能是行头维值和数值都为空, 不太适用于明细表的空数据占位符展示逻辑, 建议根据自己的业务场景, 在表格上面绝对定位一个 div, 自行展示占位符.

**Comment by donglegend** [comment]
> 透视表不支持, 明细表是支持像 antd 那样展示的: https://s2.antv.antgroup.com/examples/custom/custom-cell/#empty-placeholder
> 
> 透视表有可能是行头有维值, 但是数值为空, 也有可能是行头维值和数值都为空, 不太适用于明细表的空数据占位符展示逻辑, 建议根据自己的业务场景, 在表格上面绝对定位一个 div, 自行展示占位符.

好吧，业务需求催，那我先自己实现吧；主要表格都是一套的，得保持风格一直，透视表不行，明细表也就没用的意义了
