### ISSUE TITLE
🤔 透视表不支持导出序号吗？

### ISSUE THREAD

**Issue by wozien** [antvis/S2#2745]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.22        |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在开启序号的情况下，asyncGetAllPlainData方法导出，明细表导出包含序号列，但是交叉表不包含？这是正常的吗

### 😊 Expected Behavior
透视表可以导出序号列

**Comment by lijinke666** [comment]
不太符合预期, 听起来是 BUG, 近期看一看

**Comment by lijinke666** [comment]
不支持.

看了下, 因为透视表的序号其实是一对多, 复制/导出后, 默认由于无法合并单元格, 所以会长这样子, 意义不是很大, 故没有适配

![image](https://github.com/antvis/S2/assets/21015895/c0124fe6-0503-4b73-a97e-1c716d45b4c9)

**Comment by wozien** [comment]
能不能加个配置，有一个场景只有一个行维或者这个序号当前排名列那样子，这样导出就有意义了

**Comment by lijinke666** [comment]
可以考虑支持, 不过人力有限, 短期内可能没精力适配, 欢迎 PR.
