### ISSUE TITLE
🐛@antv/s2-react 2.0.0-next.21版本， React组件内置重渲染render仍为同步模式，频繁更新组件导致渲染重影异常

### ISSUE THREAD

**Issue by riverxs** [antvis/S2#2752]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      2.0.0-next.21    |
| @antv/s2-react |     2.0.0-next.21     |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

@antv/s2 与@antv/s2-react升级2.0版本后，s2的render改为异步渲染，而@antv/s2-react封装的代码内render调用方式仍为同步渲染方式，快速更新React组件导致渲染重影异常，是否应改为异步渲染（不确定）
<img width="411" alt="image" src="https://github.com/antvis/S2/assets/14970922/97e84fcc-66c5-4398-a130-97e01e7a59d8">

### ⌨️ Code Snapshots

官方@antv/s2-react代码
![image](https://github.com/antvis/S2/assets/14970922/67c0276f-cc43-418d-9682-6f39de9f3759)

修复建议：
```
   await s2Ref.current?.render({
      reloadData: renderOptions!.reloadData,
      reBuildDataSet: renderOptions!.reBuildDataSet,
    });
```

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
直接来个 PR ?

**Comment by lijinke666** [comment]
> 快速更新React组件导致渲染重影异常

快速更新具体是指? 最好提供一个 Demo
