### ISSUE TITLE
🐛frozen属性不起作用,官网的例子codeSandBox打开也是不生效的!!!

### ISSUE THREAD

**Issue by chenjiaxin11** [antvis/S2#2761]
### 🏷 版本信息

| Package  | Version              |
|----------|----------------------|
| @antv/s2 | ^2.0.0-next.13       |

### 📄 表类型

- [x] PivotSheet（透视表）
- [ ] TableSheet（平铺模式冻结）
- [ ] GridAnalysisSheet（网格分析表）
- [ ] StrategySheet（策略表）
- [ ] EditableSheet（可编辑表）

### 🖋 描述

设置frozen属性不生效，官网的示例中的CodeSandBox也无法生效。

### ⌨️ 代码快照

```javascript
const s2Options: S2Options = {
  width: 600,
  height: 300,
  frozen: {
    rowCount: 1,
    trailingRowCount: 1,
    colCount: 1,
    trailingColCount: 1,
  },
  totals: {
    row: {
      showGrandTotals: true,
      reverseGrandTotalsLayout: true,
    },
  },
  style: {
    colCell: {
      widthByField: {
        'root[&]家具[&]沙发[&]number': 200,
        'root[&]办公用品[&]笔[&]number': 200,
      },
    },
  },
};
```

### 🔗 Reproduce Link
官网的codeSandBox链接
https://codesandbox.io/p/sandbox/zen-kepler-x4l6lx?file=%2Findex.ts%3A10%2C1-33%2C7

### 🤔 Steps to Reproduce

打开上面的 CodeSandbox 链接。

### 😊 Expected Behavior
设置 frozen 属性后，行数据应被冻结，不应随滚动条滚动。

### 😅 Current Behavior
设置 frozen 属性后，行数据仍会随滚动条滚动，未达到预期效果。
官网例子中的  透视表 - 平铺模式冻结 是生效的,但是按照这个例子的写法是不生效的,并且这个例子的codeSandBox链接打开也是不生效

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     Windows 11    |
| Browser |   Chrome 125.0.6422.141      |

**Comment by wjgogogo** [comment]
这个codesandbox 对应的 s2 版本是 latest, 而不是 next。该特性在@antv/s2-v2.0.0-next.23 才包括
