### ISSUE TITLE
s2-react版本的导出组件在隐藏列头之后  导出来的数据列头和数据不对应   列头是隐藏后的,数

### ISSUE THREAD

**Issue by coco0426** [antvis/S2#2764]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
2.0 版本未复现, 请提供复现链接
