### ISSUE TITLE
🤔 rowCell和colCell中对数据String()处理后导致拿不到原始值

### ISSUE THREAD

**Issue by liqiuqiui** [antvis/S2#2766]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
rowCell和colCell中对数据String()处理后导致拿不到null的原始值，是否考虑增加originLabel和originValue的方式保留未经处理的原始值，以供开发者自行处理一些特殊的情况？
<img width="1410" alt="image" src="https://github.com/antvis/S2/assets/61131824/56f4f2b7-538f-41f5-b70a-9f65fc2d0262">

具体代码就是这一行 https://github.com/antvis/S2/blob/master/packages/s2-core/src/utils/dataset/pivot-data-set.ts#L66

**Comment by lijinke666** [comment]
麻烦 @wjgogogo 看看

**Comment by KzqKzq** [comment]
@lijinke666 请问下这个问题有计划修复吗，在使用的时候我也有这个获取colCell原始值的需求

**Comment by lijinke666** [comment]
> 是否考虑增加originLabel和originValue的方式保留未经处理的原始值，以供开发者自行处理一些特殊的情况？

近期看一下, 有一定改造成本, 如可行会在 2.x 中支持

**Comment by lijinke666** [comment]
> @lijinke666 请问下这个问题有计划修复吗，在使用的时候我也有这个获取colCell原始值的需求

你是什么场景? 也是维值为 null ?

**Comment by KzqKzq** [comment]
> > @lijinke666 请问下这个问题有计划修复吗，在使用的时候我也有这个获取colCell原始值的需求
> 
> 这个属于能力增强了, 不是 `修复`, 你是什么场景? 也是维值为 null ? 请详细描述你的诉求

目前就是对维度定义了一些格式化函数，然后这个函数里面包含了对维度为null值的一些处理，目前就是导出成的时候我需要将维度的null经过格式化处理之后的结果导出。
比如说下面这个表
![image](https://github.com/antvis/S2/assets/61263079/dc81c12a-62c8-4a83-a7b7-18e259d40aad)
通过
`
    const data = await asyncGetAllPlainData({
      sheetInstance: s2,
      split: '\t',
      formatOptions: true
    });
`
导出的结果为
![image](https://github.com/antvis/S2/assets/61263079/f2469b20-3c37-409c-8faf-784685803b82)
我希望的结果是上面的日期为空的维度值可以导出成我在formatter自定义的null为空值的结果，我的一个实现思路是通过这个colCell的单元格对应的原始值来判断，如果是null就在对应维度的formatter函数中进入自定义的null为空值的处理逻辑。但是由于维度值在s2中直接被转成字符串，就没有办法在formatter中进行正确的维值为null的格式处理再进行导出。
或者说，针对导出的这个问题，能否支持在asyncGetAllPlainData 中的formatOptions 加入一个配置开关类似 
`
export declare type FormatOptions = boolean | {
    formatHeader?: boolean;
    formatData?: boolean;
    placeholder?:boolean;
};
`
支持占位符的导出

**Comment by lijinke666** [comment]
> > > @lijinke666 请问下这个问题有计划修复吗，在使用的时候我也有这个获取colCell原始值的需求
> > 
> > 
> > 这个属于能力增强了, 不是 `修复`, 你是什么场景? 也是维值为 null ? 请详细描述你的诉求
> 
> 目前就是对维度定义了一些格式化函数，然后这个函数里面包含了对维度为null值的一些处理，目前就是导出成的时候我需要将维度的null经过格式化处理之后的结果导出。 比如说下面这个表 ![image](https://private-user-images.githubusercontent.com/61263079/345794417-dc81c12a-62c8-4a83-a7b7-18e259d40aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA1ODcsIm5iZiI6MTcyMDA5MDI4NywicGF0aCI6Ii82MTI2MzA3OS8zNDU3OTQ0MTctZGM4MWMxMmEtNjJjOC00YTgzLWE3YjctMThlMjU5ZDQwYWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNDEyZjMxY2UyZjFjYzY4YmEwNmQ4YjE4M2U4MzFlMWZkYmIwZDM1MmVkZTFlYTJjNDYzMGIxMDAxNDlmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.781CNaSKW2Ruel-ixb1yzsYt4pB7c3kb5BITdZEoljQ) 通过 `const data = await asyncGetAllPlainData({ sheetInstance: s2, split: '\t', formatOptions: true });` 导出的结果为 ![image](https://private-user-images.githubusercontent.com/61263079/345794923-f2469b20-3c37-409c-8faf-784685803b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA1ODcsIm5iZiI6MTcyMDA5MDI4NywicGF0aCI6Ii82MTI2MzA3OS8zNDU3OTQ5MjMtZjI0NjliMjAtM2MzNy00MDljLThmYWYtNzg0Njg1ODAzYjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzNlMTU3Yzk1NDJlZGMxMDNkNmNkZjVjZjQyYTVlOGNjODc1YzQxYTgzODc4MzBhNTQ0MDY0ZTJjYzkwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8xLW9rkuxlYYRMQjKnAE3xnLP_YZhjwqJ3NKp95UeOg) 我希望的结果是上面的日期为空的维度值可以导出成我在formatter自定义的null为空值的结果，我的一个实现思路是通过这个colCell的单元格对应的原始值来判断，如果是null就在对应维度的formatter函数中进入自定义的null为空值的处理逻辑。但是由于维度值在s2中直接被转成字符串，就没有办法在formatter中进行正确的维值为null的格式处理再进行导出。 或者说，针对导出的这个问题，能否支持在asyncGetAllPlainData 中的formatOptions 加入一个配置开关类似 `export declare type FormatOptions = boolean | { formatHeader?: boolean; formatData?: boolean; placeholder?:boolean; };` 支持占位符的导出

明白了, 这个请另外提个 issue (带上复现 demo), 你的场景和该 issue 没关系, 不要混在一起了.

看起来你配置了 `S2DataConfig.meta` 的格式化, 表格渲染的时候把 `null` 转成了 `-`, 但是导出的时候 `formatOptions: true` 预期应该是使用格式化后的值, 和表格长一样, 但是还是导出的还是 `null`, 初步看起来是 BUG, 需要排查一下.
