### ISSUE TITLE
透视表列头如何能不分组展示？🤔

### ISSUE THREAD

**Issue by Zhaohanqi12** [antvis/S2#2767]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |    next     |
| @antv/s2-vue   |         |

### Sheet Type

- [√ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
透视表是否可以开启列头不分组展示，name相同不自动合并？
before
![image](https://github.com/antvis/S2/assets/166707652/4159b597-e4fc-4688-af23-2ca5afc58158)
预期after，一样的列头不合并
![image](https://github.com/antvis/S2/assets/166707652/ad623e6a-3475-4d63-9ba7-d96cd266ba35)

**Comment by lijinke666** [comment]
暂不支持

**Comment by Zhaohanqi12** [comment]
> 暂不支持
> 
> > PS: 另外你说的是行头, 不是列头.

> 但是会出现同样的数据被合并，导致合计出现错误。
> 有三条数据，但是只展示两条，后面的数据覆盖了前面一条
> https://codesandbox.io/p/sandbox/flamboyant-greider-z9zhfg?file=%2Fsrc%2Findex.ts%3A71%2C6

**Comment by lijinke666** [comment]
> 但是会出现同样的数据被合并，导致合计出现错误。
> 有三条数据，但是只展示两条，后面的数据覆盖了前面一条
> https://codesandbox.io/p/sandbox/flamboyant-greider-z9zhfg?file=%2Fsrc%2Findex.ts%3A71%2C6
> 

好的，近期看一下咋回事

**Comment by lijinke666** [comment]
你两条数据都一样, 是会被覆盖的, 符合预期

![image](https://github.com/antvis/S2/assets/21015895/bf211bcd-6ed7-4450-8778-a282fef73b7d)

你可以预处理下数据, 遍历数据给相同的维值增加一个序号, 然后渲染时通过 `meta` 再格式化去除这个序号, 就能实现你想要的不分组展示

```ts
const customRowDataConfig: S2DataConfig = {
  fields: {
    rows: ["name", "title"],
    values: ["number"],
  },
  data: [
    {
      name: "張三-1",
      title: "被合并1",
      number: 1223,
    },
    {
      name: "張三-2",
      title: "被合并1",
      number: 555,
    },
    {
      name: "里斯",
      title: "123",
      number: 3344,
    },
  ],
  meta: [
    {
      field: 'name',
      formatter: (v) => v.split('-')[0] 
    }
  ]
};
```

![image](https://github.com/antvis/S2/assets/21015895/b83569cf-2f0d-4874-a766-5ee8c42c01ea)

**Comment by Zhaohanqi12** [comment]
> 你两条数据都一样, 是会被覆盖的, 符合预期
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/339181089-bf211bcd-6ed7-4450-8778-a282fef73b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzA3NTUsIm5iZiI6MTcxODMzMDQ1NSwicGF0aCI6Ii8yMTAxNTg5NS8zMzkxODEwODktYmYyMTFiY2QtNmVkNy00NDUwLTg3NzgtYTI4MmZlZjczYjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxY2FhZWI3OTZiM2Y1OWI0ZTg3NDU4MjY3MDkzZmI0MzdjYzI0MDM5MWIxM2U5ZjcwMzgxZGNkMzkyMzBjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_TkSSIUZ7INBBu-p3nShiifKQwS6XLcU4CkpG1EU98)
> 
> 你可以预处理下数据, 遍历数据给相同的维值增加一个序号, 然后渲染时通过 `meta` 再格式化去除这个序号, 就能实现你想要的不分组展示
> 
> ```ts
> const customRowDataConfig: S2DataConfig = {
>   fields: {
>     rows: ["name", "title"],
>     values: ["number"],
>   },
>   data: [
>     {
>       name: "張三-1",
>       title: "被合并1",
>       number: 1223,
>     },
>     {
>       name: "張三-2",
>       title: "被合并1",
>       number: 555,
>     },
>     {
>       name: "里斯",
>       title: "123",
>       number: 3344,
>     },
>   ],
>   meta: [
>     {
>       field: 'name',
>       formatter: (v) => v.split('-')[0] 
>     }
>   ]
> };
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/339181560-b83569cf-2f0d-4874-a766-5ee8c42c01ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzA3NTUsIm5iZiI6MTcxODMzMDQ1NSwicGF0aCI6Ii8yMTAxNTg5NS8zMzkxODE1NjAtYjgzNTY5Y2YtMmYwZC00ODc0LWE3NjYtNWVlOGM0MmMwMWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTRiODUzOTFmZGI4NWU5ZThlNjliMzg0MmVkNGZmNzM3NDVkMDZkMDhmNzI4NGFmODE1ZTViYWQ0ZTc2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ol6LKppRV9wtHWbSDKKs8PBqu0FhAk4aR0suL19ZZek)

谢谢提供方案

**Comment by liqiuqiui** [comment]
> 你两条数据都一样, 是会被覆盖的, 符合预期
> 
> ![image](https://github.com/antvis/S2/assets/21015895/bf211bcd-6ed7-4450-8778-a282fef73b7d)
> 
> 你可以预处理下数据, 遍历数据给相同的维值增加一个序号, 然后渲染时通过 `meta` 再格式化去除这个序号, 就能实现你想要的不分组展示
> 
> const customRowDataConfig: S2DataConfig = {
>   fields: {
>     rows: ["name", "title"],
>     values: ["number"],
>   },
>   data: [
>     {
>       name: "張三-1",
>       title: "被合并1",
>       number: 1223,
>     },
>     {
>       name: "張三-2",
>       title: "被合并1",
>       number: 555,
>     },
>     {
>       name: "里斯",
>       title: "123",
>       number: 3344,
>     },
>   ],
>   meta: [
>     {
>       field: 'name',
>       formatter: (v) => v.split('-')[0] 
>     }
>   ]
> };
> ![image](https://github.com/antvis/S2/assets/21015895/b83569cf-2f0d-4874-a766-5ee8c42c01ea)

有什么方案能让列头也不合并吗？
<img width="1810" height="704" alt="Image" src="https://github.com/user-attachments/assets/ece30146-f0a0-4315-a816-72cc31fb52ca" />
