### ISSUE TITLE
🤔S2透视多维表有没有后端类似的库，可以根据前端显示效果，导出一样的效果到Excel

### ISSUE THREAD

**Issue by junety** [antvis/S2#2768]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- ✅ PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

🤔S2有没有后端类似的库，可以根据前端显示效果，导出一样的效果到Excel

**Comment by lijinke666** [comment]
没有
