### ISSUE TITLE
🐛透视表数据较多时，频繁滚动会导致栈溢出错误

### ISSUE THREAD

**Issue by tufaofu** [antvis/S2#2771]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.23     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

当视表数据较多时，左右或者上下频繁滚动，会导致栈溢出错误。源码@antv/s2-v2.0.0-next.23分支，**100w 数据** 示例即可复现。
<img width="1436" alt="image" src="https://github.com/antvis/S2/assets/74943736/64483831-d9d9-4639-9392-12ec57d07b4d">

官网示例 **100w条数据性能表现-透视表** 也可复现。
<img width="1435" alt="image" src="https://github.com/antvis/S2/assets/74943736/239430ef-258e-4b77-b82e-51aad50a464e">
### 🔗 Reproduce Link
https://s2.antv.antgroup.com/examples/case/performance-compare#pivot

### 🤔 Steps to Reproduce
电脑配置如下：
<img width="280" alt="image" src="https://github.com/antvis/S2/assets/74943736/0c1f63b6-fb8b-460b-8769-08afcc055f66">

持续滚动60-120s左右就会报错

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
> 持续滚动60-120s左右就会报错

什么使用场景会一直滑动 1-2 分钟?

**Comment by tufaofu** [comment]
当图表数据量比较大，可能就会存在频繁滚动的情况

**Comment by lijinke666** [comment]
近期看一下这个问题

**Comment by lijinke666** [comment]
底层渲染引擎 G 的问题 https://github.com/antvis/G/issues/1712, 等待 G 修复

**Comment by db-shuai** [comment]
G 没人关注啊 这个好久了，有没有什么临时解决方案

**Comment by wangnannanziyu** [comment]
> G 没人关注啊 这个好久了，有没有什么临时解决方案

把官网例子拉下来，修改依赖包中的代码（g-lite），找到 Canvas.prototype.render，然后修改代码如下：

**Comment by wangnannanziyu** [comment]
> G 没人关注啊 这个好久了，有没有什么临时解决方案

把官方例子下下来，修改依赖中的g-lite包的源码，找到 Canvas.prototype.render，源代码如下：
Canvas.prototype.render = function (frame) {
        var _this = this;
        this.dispatchEvent(beforeRenderEvent);
        var renderingService = this.getRenderingService();
        renderingService.render(this.getConfig(), frame, function () {
            // trigger actual rerender event
            // @see https://github.com/antvis/G/issues/1268
            _this.dispatchEvent(rerenderEvent);
        });
        this.dispatchEvent(afterRenderEvent);
    };

修改后如下：
try {
           var _this = this;
        this.dispatchEvent(beforeRenderEvent);
        var renderingService = this.getRenderingService();
        renderingService.render(this.getConfig(), frame, function () {
            // trigger actual rerender event
            // @see https://github.com/antvis/G/issues/1268
            _this.dispatchEvent(rerenderEvent);
        });
        this.dispatchEvent(afterRenderEvent);
       } catch (error) {
           const renderer = this.getConfig().renderer
           this.getRenderingService().destroy();
           this.context.renderingService = new RenderingService(runtime, this.context);
           this.initRenderingService(renderer)
       }
修改完后，重新构建，项目中引用你自己构建后的资源。

解决思路：
catch 内存溢出的错误，然后销毁 render服务，重新生成一个。这样虽然还是会内存溢出，但是不影响使用。render这里的逻辑太长了，感觉底层设计有问题，这样可以临时解决

**Comment by dekexu** [comment]
大表左右滑动 栈溢出这个问题 G现在解决了么？  S2有没有比较好的workaround方式  ，可以暂时跳过这个的

**Comment by lijinke666** [comment]
一个临时解决方案, 开启 G 的 [视锥剔除](https://g.antv.antgroup.com/api/renderer/intro#enableculling)

```ts
const s2Options = {
  transformCanvasConfig(renderer) {
    renderer.setConfig({
      enableCulling: true,
    })
  },
}
```

**Comment by yukre** [comment]
> 一个临时解决方案, 升级 S2 到最新版本, 开启 G 的 [视锥剔除](https://g.antv.antgroup.com/api/renderer/intro#enableculling) (注意: 是否对 S2 其他场景有副作用还待验证, 请谨慎使用, 待稳定后在 2.0 正式版中默认开启)
> 
> ```ts
> const s2Options = {
>   transformCanvasConfig(renderer) {
>     renderer.setConfig({
>       enableCulling: true,
>     })
>   },
> }
> ```

你这个方案和G的issue中的方案刚好相反，https://github.com/antvis/G/issues/1712#issuecomment-2357614783，请教下是我理解错误了么

**Comment by lijinke666** [comment]
> 你这个方案和G的issue中的方案刚好相反

G 的 enableCulling 默认就是关闭的

---

G 最近优化了该问题, 最新版本经测试未复现 (无需修改 enableCulling )

如果你说的是在 S2 中遇到了, 那么可以试试升级到 @antv/s2@^2.0.0-next.30
如果你使用的只是 G, 那么升级 G 的相关依赖到最新版本即可

**Comment by wangjinqing111** [comment]
@antv/s2@^2.0.0-next.30

开启视锥剔除栈溢出问题没出现了，但是在行头非冻结，并且超长行头的情况下（行头宽度超过可视区域），多维表的数据区域和列头区域没渲染出来
![1730948106190_9EF75B44-C6C7-4401-97E2-1B039C37DB8D](https://github.com/user-attachments/assets/521d7e6d-8369-4f72-9f7a-40d22c8eb584)

**Comment by lijinke666** [comment]
> 开启视锥剔除栈溢出问题没出现了

最新版本的 G 解决了该问题, S2 这一层不用修改什么配置 (不需要开启视锥剔除),  可以关掉再试试, 应该也不会栈溢出.
