### ISSUE TITLE
合计行如何能不参与排序？🤔

### ISSUE THREAD

**Issue by Zhaohanqi12** [antvis/S2#2778]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     √    |
| @antv/s2-react |    √     |
| @antv/s2-vue   |         |

### Sheet Type

- [√ ] PivotSheet
- [√ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/flamboyant-greider-z9zhfg?file=%2Fsrc%2Findex.ts%3A71%2C6

**Comment by Zhaohanqi12** [comment]
S2明细表升级2X后自带的排序倒三角消失，添加上icon点击无效果。

**Comment by lijinke666** [comment]
你给的 demo 是透视表, 也没有任何的排序代码, 透视表总计就是不参与排序的呀, 没太懂你在说什么.

如果你说的是明细表, 总计是你自己的数据, 对于表格来说就是一条普通数据, 无法识别这是不是总计行, 除非你[自定义排序逻辑](https://s2.antv.antgroup.com/manual/basic/sort/basic#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%B9%E6%B3%95sortfunc).

> S2明细表升级2X后自带的排序倒三角消失，添加上icon点击无效果。

有没有一种可能, 你贴一下你的代码和截图, 而不是大家彼此交流全靠猜?

点击无效果是什么意思? 点击 icon 后出现的那个 Tooltip 排序菜单? 你提供的 demo 是用的 `@antv/s2`, 而不是 ` @antv/s2-react`, 排序菜单是 `@antv/s2-react` 封装的功能, [文档说的很清楚了](https://s2.antv.antgroup.com/manual/basic/tooltip#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9), `@antv/s2` 只提供[基础排序的能力](https://s2.antv.antgroup.com/manual/basic/sort/basic)


----------

> ![image](https://github.com/antvis/S2/assets/21015895/bc7080a7-1964-4d33-ba6c-4fffdb5d5bc2)

这是让你填写版本号, 不是让你打钩, 模版写的很清楚了.

**Comment by Zhaohanqi12** [comment]
首先对您表示很抱歉，没有按照要求提issue
我的意思用以下截图来表示，当固定总计行时，序号列会将总计带入，如果不想让总计行带入序号列，那么又没法将总计固定在第一行？
![image](https://github.com/antvis/S2/assets/166707652/c043cbc8-112f-45c1-ab0e-e0b49fe97888)

**Comment by Zhaohanqi12** [comment]
![image](https://github.com/antvis/S2/assets/166707652/c6a7d6d1-9d1c-4511-83ac-03fa62eca57b)

**Comment by Zhaohanqi12** [comment]
> 你给的 demo 是透视表, 也没有任何的排序代码, 透视表总计就是不参与排序的呀, 没太懂你在说什么.
> 
> 如果你说的是明细表, 总计是你自己的数据, 对于表格来说就是一条普通数据, 无法识别这是不是总计行, 除非你[自定义排序逻辑](https://s2.antv.antgroup.com/manual/basic/sort/basic#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%B9%E6%B3%95sortfunc).
> 
> > S2明细表升级2X后自带的排序倒三角消失，添加上icon点击无效果。
> 
> 有没有一种可能, 你贴一下你的代码和截图, 而不是大家彼此交流全靠猜?
> 
> 点击无效果是什么意思? 点击 icon 后出现的那个 Tooltip 排序菜单? 你提供的 demo 是用的 `@antv/s2`, 而不是 ` @antv/s2-react`, 排序菜单是 `@antv/s2-react` 封装的功能, [文档说的很清楚了](https://s2.antv.antgroup.com/manual/basic/tooltip#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9), `@antv/s2` 只提供[基础排序的能力](https://s2.antv.antgroup.com/manual/basic/sort/basic)
> 
> > ![image](https://private-user-images.githubusercontent.com/21015895/340266974-bc7080a7-1964-4d33-ba6c-4fffdb5d5bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTUxMDEsIm5iZiI6MTcxODc5NDgwMSwicGF0aCI6Ii8yMTAxNTg5NS8zNDAyNjY5NzQtYmM3MDgwYTctMTk2NC00ZDMzLWJhNmMtNGZmZmRiNWQ1YmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWJiNDZjOGRlZmYyMWNiYTIxMWExZDBhMDllZTI4NjNkMmIwODM1OGM0NmY2ZmYyNjRiMmZkNTQ1ZTg2YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EcpTtr8Ci31rvAxkEtwdr5GloFj7FB2YWGw0538raE)
> 
> 这是让你填写版本号, 不是让你打钩, 模版写的很清楚了.
首先表示很抱歉，没有按照要求提issue
我的意思可以用以下截图来表示，当固定总计行时，序号列会将总计带入，如果不想让总计行带入序号列，那么又没法将总计固定在第一行？
![image](https://github.com/antvis/S2/assets/166707652/6ec8cda1-44e6-4f1a-97e6-a69f7e9a2329)
![image](https://github.com/antvis/S2/assets/166707652/98ffcc74-42bc-4163-97b7-673789a18632)
