### ISSUE TITLE
🐛自定义表头样式，样式不生效

### ISSUE THREAD

**Issue by 12144** [antvis/S2#2781]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

![image](https://github.com/antvis/S2/assets/41766193/86367cf8-b315-4810-bc75-7ad6de6911ec)

在官方示例的基础上，只加了text的配置，表头有部分没有应用自定义的样式，https://s2.antv.antgroup.com/zh/examples/theme/custom/#custom-transparent-background， 这个页面添加图里text的配置即可复现

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
text 对应不加粗的文本, 这里文档容易让人迷惑, 后续优化.

你截图的分别对应 维值 (加粗文本 bolderText) 数值 (度量值 measureText)

![image](https://github.com/antvis/S2/assets/21015895/dbde750d-85be-47ac-b1ea-5a870d922e15)
