### ISSUE TITLE
S2在加载了新的row和colums后如何渲染到页面，更新页面数据

### ISSUE THREAD

**Issue by annisFromchina** [antvis/S2#2794]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | ^2.0.0-next.24  |
| @antv/s2-react | 未使用|
| @antv/s2-vue   |^1.0.11  |

### Sheet Type

- [√ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

你好，首先，我使用的是Vue2的框架，接下来是我的问题
  我目前想要实现这样的透视表：通过两个多选Select栏分别选择值，保存在 s2DataConfig.fields.rows 和 s2DataConfig.fields.columns里面，使rows 和columns做到自定义选择的功能。现在遇到的问题是：已经将新选择的rows 和columns赋值到s2DataConfig.fields里面，使用了const container = this.$refs.container
      this.s2= new PivotSheet(container, this.s2DataConfig, this.s2Options) 但是页面没有进行更新，数据没有发生改变，后面又测试使用了 this.pivotSheet.render(),页面数据也没有发生改变，我该使用什么语句才能使页面数据重新渲染呢？ 期待您的回复
### 🔗 Reproduce Link

 checkSerch() {
      // 直接将选中的值赋值给 s2DataConfig.fields.rows 和 s2DataConfig.fields.columns
      if (this.s2DataConfig.fields.rows != null) {
        this.s2DataConfig.fields.rows = this.selectedRows
      }
      if (this.s2DataConfig.fields.columns != null) {
        this.s2DataConfig.fields.columns = this.selectedColumns
      }
      console.log(this.s2DataConfig.fields)
      this.bootstrap()
    },
 async bootstrap() {
      const container = this.$refs.container
      this.pivotSheet = new PivotSheet(container, this.s2DataConfig, this.s2Options)
      this.pivotSheet.on(S2Event.DATA_CELL_CLICK, (event) => {
        this.pivotSheet.tooltip.show({
          position: { x: event.clientX, y: event.clientY },
          content: this.dataCellTooltip(),
        })
      })
      this.pivotSheet.on(S2Event.MERGED_CELLS_CLICK, (event) => {
        const cell = this.pivotSheet.getCell(event.target)
        this.pivotSheet.tooltip.show({
          position: { x: event.clientX, y: event.clientY },
          content: this.unmergeCell(cell),
        })
      })

      await this.pivotSheet.render() // 异步渲染
    },

**Comment by annisFromchina** [comment]
<template>
  <div ref="container" class="main">
    <a-select mode="multiple" v-model="selectedRows" style="width: 20.5%" placeholder="X轴">
      <a-select-option v-for="row in test.fields.rows" :key="row.id" :value="row.jia">
        {{ row.china }}
      </a-select-option>
    </a-select>

    <a-select mode="multiple" v-model="selectedColumns" style="width: 20.5%" placeholder="y轴">
      <a-select-option v-for="column in test.fields.columns" :key="column.id" :value="column.jia">
        {{ column.china }}
      </a-select-option>
    </a-select>

    <a-button type="dashed" shape="circle" icon="search" @click="checkSerch" />

    <div>
      <button v-if="mergeButton" class="merge-cells-button" @click="mergeCells">合并单元格</button>
      <button class="ant-btn ant-btn-default" @click="copyData(true)">复制全量数据</button>
      <button class="ant-btn ant-btn-default" @click="downloadData(true)">导出全量数据</button>
    </div>
  </div>
</template>  

  <script>
import {
  PivotSheet,
  S2DataConfig,
  Aggregation,
  CopyMIMEType,
  S2Event,
  S2Options,
  SpreadSheet,
  asyncGetAllPlainData,
  copyToClipboard,
  download,
} from '@antv/s2'
//这个是自适应窗口大小需要导入的组件
import { debounce } from 'lodash'
import { message } from 'antd'
export default {
  data() {
    return {
      split: '\t',
      fileName: 'test',
      selectedRows: [], // 用于存储X轴选中的值
      selectedColumns: [], // 用于存储Y轴选中的值
      row: String,
      column: String,
      test: {
        fields: {
          //定义了表格的行字段，这里是省份和城市
          rows: [
            { id: '1', jia: 'province', china: '省份' },
            { id: '2', jia: 'city', china: '城市' },
          ],
          //定义了表格的列字段，这里是商品类别
          columns: [{ id: '3', jia: 'type', china: '类型' }],
          //定义了用于聚合或显示的数值字段，这里是价格
          values: ['price'],
        },
      },
      mergeButton: false,
      cancelButton: false,
      button: document.createElement('button'),
      pivotSheet: null,
      s2DataConfig: {
        fields: {
          //定义了表格的行字段，这里是省份和城市
          rows: ['province', 'city'],
          //定义了表格的列字段，这里是商品类别
          columns: ['type'],
          //定义了用于聚合或显示的数值字段，这里是价格
          values: ['price'],
        },
        //字段用于定义每个字段的元数据，比如字段的显示名称等
        meta: [
          {
            field: 'province',
            name: '省份',
          },
          {
            field: 'city',
            name: '城市',
          },
          {
            field: 'type',
            name: '商品类别',
          },
          {
            field: 'price',
            name: '价格',
          },
        ],
        //字段是一个数组，包含了表格的实际数据
        data: [
          {
            province: '浙江',
            city: '杭州',
            type: '笔',
            price: '1',
            cost: '0.5',
          },
          {
            province: '浙江',
            city: '杭州',
            type: '纸张',
            price: '2',
            cost: '20',
          },
          {
            province: '浙江',
            city: '舟山',
            type: '笔',
            price: '17',
            cost: '1.7',
          },
          {
            province: '浙江',
            city: '舟山',
            type: '纸张',
            price: '6',
            cost: '0.12',
          },
          {
            province: '吉林',
            city: '长春',
            type: '笔',
            price: '8',
            cost: '10',
          },
          {
            province: '吉林',
            city: '白山',
            type: '笔',
            price: '12',
            cost: '9',
          },
          {
            province: '吉林',
            city: '长春',
            type: '纸张',
            price: '3',
            cost: '3',
          },
          {
            province: '吉林',
            city: '白山',
            type: '纸张',
            price: '25',
            cost: '1',
          },
        ],
      },
      //用于定制表格的外观和行为
      s2Options: {
        width: 600,
        height: 480,
        //设置表格的层级类型为树状结构。这通常意味着表格可能包含嵌套的层级数据，例如父子关系的数据
        hierarchyType: 'tree',
        //当鼠标悬停在表格的某个单元格上时，会显示一个包含该单元格详细信息的提示框。
        tooltip: {
          enable: true,
        },
        interaction: {
          copy: {
            // 允许复制
            enable: true,
            // 是否携带行列头数据
            withHeader: true,
            // 是否使用格式化数据
            withFormat: true,
          },
          brushSelection: {
            rowCell: true,
            colCell: true,
            dataCell: true,
          },
          // 多选
          multiSelection: true,
          // 高亮选中单元格
          selectedCellsSpotlight: true,
          // 悬停高亮
          hoverHighlight: true,
          // 透视表默认隐藏需要指定唯一列头 id
          // 可通过 `s2.facet.getColNodes()` 获取列头节点查看i d
          hiddenColumnFields: ['root[&]家具[&]沙发[&]number'],
        },
        //totals 字段用于控制表格中行（row）和列（col）的小计（subTotals）和总计（grandTotals）的显示
        mergedCellsInfo: [
          [
            { colIndex: 1, rowIndex: 6, showText: true },
            { colIndex: 1, rowIndex: 7 },
            { colIndex: 2, rowIndex: 6 },
            { colIndex: 2, rowIndex: 7 },
            { colIndex: 3, rowIndex: 6 },
            { colIndex: 3, rowIndex: 7 },
          ],
        ],

        totals: {
          row: {
            //是否显示行的总计
            showGrandTotals: true,
            // /是否显示行的小计
            showSubTotals: true,
            //是否反转行的总计布局（例如，将其显示在顶部而不是底部）
            reverseGrandTotalsLayout: true,
            //是否反转行的小计布局
            reverseSubTotalsLayout: true,
            //指定哪些维度（在这里是 'province'）用于计算行的小计
            subTotalsDimensions: ['province'],
            //定义如何计算行的总计
            calcGrandTotals: {
              aggregation: Aggregation.SUM,
            },
            //定义如何计算行的小计
            calcSubTotals: {
              aggregation: Aggregation.SUM,
            },
          },
          //与 row 类似，但控制列的小计和总计的显示
          col: {
            //是否显示列的总计
            showGrandTotals: true,
            //是否显示列的小计
            showSubTotals: true,
            //是否反转列的总计布局
            reverseGrandTotalsLayout: true,
            // /是否反转列的小计布局
            reverseSubTotalsLayout: true,
            //指定哪些维度（在这里是 'type'）用于计算列的小计
            subTotalsDimensions: ['type'],
            //calcGrandTotals: 和 calcSubTotals 同样定义了如何计算和显示总计和小计
            calcGrandTotals: {
              aggregation: Aggregation.SUM,
            },

            calcSubTotals: {
              aggregation: Aggregation.SUM,
            },
          },
        },
      },
    }
  },
  mounted() {
    this.bootstrap()
  },
  methods: {
    async bootstrap() {
      const container = this.$refs.container
      this.pivotSheet = new PivotSheet(container, this.s2DataConfig, this.s2Options)
      this.pivotSheet.on(S2Event.DATA_CELL_CLICK, (event) => {
        this.pivotSheet.tooltip.show({
          position: { x: event.clientX, y: event.clientY },
          content: this.dataCellTooltip(),
        })
      })
      this.pivotSheet.on(S2Event.MERGED_CELLS_CLICK, (event) => {
        const cell = this.pivotSheet.getCell(event.target)
        this.pivotSheet.tooltip.show({
          position: { x: event.clientX, y: event.clientY },
          content: this.unmergeCell(cell),
        })
      })

      await this.pivotSheet.render() // 异步渲染
    },
    dataCellTooltip() {
      this.mergeButton = true
    },
    mergeCells() {
      if (this.pivotSheet) {
        this.pivotSheet.interaction.mergeCells()
      }
    },
    unmergeCell(cell) {
      this.mergeButton = false
      if (this.pivotSheet) {
        this.pivotSheet.interaction.unmergeCell(cell)
      }
    },
    checkSerch() {
      // 直接将选中的值赋值给 s2DataConfig.fields.rows 和 s2DataConfig.fields.columns
      if (this.s2DataConfig.fields.rows != null) {
        this.s2DataConfig.fields.rows = this.selectedRows
      }
      if (this.s2DataConfig.fields.columns != null) {
        this.s2DataConfig.fields.columns = this.selectedColumns
      }
      console.log(this.s2DataConfig.fields)
      this.pivotSheet.resetOptions()
    },

    //做数据导出所需要的方法们
    // 全量复制
    async copyData(isFormat) {
      // 这里可以定义你的 customTransformer，如果需要的话
      const data = await asyncGetAllPlainData({
        sheetInstance: this.pivotSheet,
        split: this.split,
        formatOptions: isFormat,
      })

      copyToClipboard(data)
        .then(() => {
          console.log('data', data)
          // 假设你有一个全局的 message 方法，或者你可以使用 Vue 的通知系统
          this.$message.success('复制成功!')
        })
        .catch((error) => {
          console.log('copy failed: ', error)
          this.$message.error('复制失败!')
        })
    },
    async downloadData(isFormat) {
      // 使用 this 来访问组件的 data 和其他方法
      this.$message.loading('导出中...') // 假设您使用的是 Element UI 或类似的 UI 库
      try {
        // 假设 asyncGetAllPlainData 是一个全局函数或已经在其他地方导入
        const data = await asyncGetAllPlainData({
          sheetInstance: this.pivotSheet, // 使用组件的 data
          split: this.split, // 如果 split 是组件的 data 或 prop
          formatOptions: isFormat,
        })
        download(data, this.fileName)
        console.log('downloadData', data)
        this.$message.success('导出成功!')
      } catch (err) {
        this.$message.error('导出失败!')
      } finally {
        // 假设 $message.loading 返回了一个关闭加载提示的函数
        this.$message.destroy() // 销毁加载提示
      }
    },
  },
}
</script>
<style>
</style>

**Comment by lijinke666** [comment]
> 后面又测试使用了 this.pivotSheet.render()

数据更新后, 调用 `render()` 没问题, 且也只有这一个 API, 没必要每次都 `this.bootstrap()` 重新实例化, 未更新从你提供的代码看起来是 `this.s2DataConfig.rows` 只更新了引用, 这样 S2 内部是感知不到的, 这样写即可:

```ts
this.pivotSheet.setDataCfg({
  fields: {
     rows: this.selectedRows,
     columns: this. selectedColumns
  }
})

this.pivotSheet.render()
```
