### ISSUE TITLE
🐛 表格区域双击时会选择表格外的文本

### ISSUE THREAD

**Issue by iGarym** [antvis/S2#2798]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.22        |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在 Chrome 浏览器中双击表格内的任意区域，表格外的文本被选中。

### ⌨️ Code Snapshots

```ts
const s2DataConfig: S2DataConfig = {
  fields: {
    columns: ["id", "pt_date"]
  },
  meta: [],
  data: [
    {
      id: 20,
      pt_date: "2023-02-08"
    },
    {
      id: 8,
      pt_date: "2023-02-15"
    },
  ]
};

const s2Options: S2Options = {
  width: 600,
  height: 480,
  seriesNumber: {
    enable: false
  }
};
```

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/admiring-breeze-ftf64h

### 🤔 Steps to Reproduce

在 Chrome 浏览器中双击表格任意区域即可复现。

### 😊 Expected Behavior

双击表格时不要选中组件外的文本

### 😅 Current Behavior

双击表格时选中组件外的文本

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |  macOS@13.6.3       |
| Browser |  Chrome@126.0.6478.127 |

**Comment by lijinke666** [comment]
这个是浏览器的默认行为, 给 canvas 设置下 `user-select: none` 即可, 后面我们修改下, 初始化时默认加上

```css
canvas {
  user-select: none;
}
```
