### ISSUE TITLE
透视表树模式根节点没有后代也展示展开/收起图标

### ISSUE THREAD

**Issue by ggcfcmd** [antvis/S2#2804]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 1.54.7 |
| @antv/s2-react | 1.46.4 |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

当前使用s2-react透视表的树模式，一级节点（同时也是叶子节点）没有子节点的情况默认也显示了展开图标

### 🔗 Reproduce Link
![image](https://github.com/antvis/S2/assets/47233749/bfee55bc-1e6d-44b6-86b2-6b0f9417b111)

感觉现在一级节点的isLeaf字段并没有被维护，在不使用CustomRowCell自定义展开收起的情况下是否可以实现没有子节点的一级节点不展示图标
### 😊 Expected Behavior
没有子节点的一级节点不展示展开图标（图中蓝色）
### 😅 Current Behavior
没有子节点的一级节点也展示展开图标

**Comment by lijinke666** [comment]
> 一级节点（同时也是叶子节点）没有子节点的情况默认也显示了展开图标

一级节点同时也是叶子节点是什么意思, 是数据本身就没有子节点, 但是错误的展示了 icon ?

还是说有, 只是折叠后没有 children 了?

> 感觉现在一级节点的isLeaf字段并没有被维护

只有叶子节点才会写入 isLeaf 属性

官网能复现吗? 不能的话请使用 mock 数据, 用 codesandbox 提供一个最小可复现 demo 吧, 看代码才好理解你的意思

**Comment by ggcfcmd** [comment]
> > 一级节点（同时也是叶子节点）没有子节点的情况默认也显示了展开图标
> 
> 一级节点同时也是叶子节点是什么意思, 是数据本身就没有子节点, 但是错误的展示了 icon ?
> 
> 还是说有, 只是折叠后没有 children 了? 折叠后没有 children 符合预期.
> 
> > 感觉现在一级节点的isLeaf字段并没有被维护
> 
> 只有叶子节点才会写入 isLeaf 属性
> 
> > 是否可以实现没有子节点的一级节点不展示图标
> 
> 官网能复现吗? 没有子节点就是不展示 icon 呀, 是指这一组数据只有一条? 看你截图是当做明细表再用, 但是又需要树状功能? 不能的话请使用 mock 数据, 用 [codesandbox](https://codesandbox.io/) 提供一个最小可复现 demo 吧, 看代码才好理解你的意思

数据本身没有子节点 但是也展示了icon

**Comment by lijinke666** [comment]
> 在不使用CustomRowCell自定义展开收起的情况下是否可以实现没有子节点的一级节点不展示图标

算是一个 bug, 树状模式下一级节点同时还有**行小计**的含义, 数据虽然只有一条, 内部布局时会生成一条额外的虚拟小计节点, 所以才造成了 children 为空时 isLeaf 没有值

https://github.com/antvis/S2/blob/c8ebc98c1fad3d50c7ecf6a1d75205a5ef1395bc/packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts#L121-L124

1.x 历史包袱比较重, 可能会在 2.x 版本中修复, 你可以暂时先用 CustomRowCell 重写一下 `showTreeIcon`, 通过 `rowPivotMeta` 来判断是否有子节点.

```ts
import { TOTAL_VALUE } from '@antv/s2'

  protected showTreeIcon() {
    if (!this.spreadsheet.isHierarchyTreeType() || this.meta.isLeaf) {
      return false;
    }

    const pivotMetaValue = (
      this.spreadsheet.dataSet as PivotDataSet
    ).rowPivotMeta.get(this.meta.value);
    const children = [...(pivotMetaValue?.children?.keys() || [])].filter(
      (child) => child !== TOTAL_VALUE,
    );
    return children.length > 0;
  }
```

![image](https://github.com/antvis/S2/assets/21015895/f6f76047-9f78-4328-83bb-7906eea4cff4)

**Comment by ggcfcmd** [comment]
> rowPivotMeta
我试下 感谢回复🙏
