### ISSUE TITLE
透视表列头是否可以禁止拖拽行为

### ISSUE THREAD

**Issue by ggcfcmd** [antvis/S2#2807]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 1.54.7 |
| @antv/s2-react | 1.46.4  |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表树模式希望可以禁止列头拖拽宽度行为

### 🔗 Reproduce Link
![image](https://github.com/antvis/S2/assets/47233749/c3321e58-b99f-4f4c-ba44-eee4b1ddd060)

**Comment by lijinke666** [comment]
关闭相应区域的拖拽热区即可

https://s2-v1.antv.antgroup.com/manual/advanced/interaction/basic#%E8%A1%8C%E5%88%97%E5%AE%BD%E9%AB%98%E8%B0%83%E6%95%B4

https://s2-v1.antv.antgroup.com/examples/interaction/advanced#resize-active

**Comment by ggcfcmd** [comment]
> 关闭相应区域的拖拽热区即可
> 
> https://s2-v1.antv.antgroup.com/manual/advanced/interaction/basic#%E8%A1%8C%E5%88%97%E5%AE%BD%E9%AB%98%E8%B0%83%E6%95%B4
> 
> https://s2-v1.antv.antgroup.com/examples/interaction/advanced#resize-active

OK 感谢回复

**Comment by lijinke666** [comment]
**使用问题**请先仔细看下文档, 如果还是没找到解决方案请在 [讨论区]( https://github.com/antvis/S2/discussions/categories/q-a) 提问.
