### ISSUE TITLE
🐛使用 asyncGetAllPlainData 导出的数据与表格渲染结果不一致

### ISSUE THREAD

**Issue by KzqKzq** [antvis/S2#2808]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   2.0.0-next.24      |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

问题：需要对所有原始值为空的单元格进行自定义格式化，（包含对维度值为null的colCell 进行格式化）并且按照格式化的内容进行导出，为了实现这个功能发现了下面的问题：
1. 问题1列维度值中有null的情况下，默认的占位符函数不生效 （好像s2默认将维度值转换成了字符串，导致占位符不生效）
![image](https://github.com/antvis/S2/assets/61263079/ce7d46e3-af7f-48de-84c4-943374c3f601)
2. 问题2为了尝试解决问题1，配置了 S2DataConfig.meta 的格式化函数，发现列维度单元格无法获取对应的原始值；
3. 问题3 dataCell 在配置了占位符以及开启了`asyncGetAllPlainData` 的 `formatOptions: true` 情况下导出的结果占位符没有正常导出

### ⌨️ Code Snapshots
![image](https://github.com/antvis/S2/assets/61263079/a844fa1e-297c-4dad-be6a-4c9b78388806)
![image](https://github.com/antvis/S2/assets/61263079/1e05dd21-bbb8-464a-b1cf-1fdb9ecd48b6)

### 🔗 Reproduce Link
https://codesandbox.io/p/sandbox/pagination-forked-dsxzpp?file=%2Findex.html

### 😊 Expected Behavior
1. 问题1列维度值中有null的情况下，希望默认的占位符函数能够生效；
2. S2DataConfig.meta 的格式化函数，可以获取列维度单元格对应的原始值；
3. dataCell 在配置了占位符以及开启了`asyncGetAllPlainData` 的 `formatOptions: true` 情况下能够正确导出占位符；

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   window 10       |
| Browser |  chrome: 126.0.6478.127      |

**Comment by lijinke666** [comment]
ref https://github.com/antvis/S2/issues/2766
