### ISSUE TITLE
有什么方式可以拿到当前表格的 scrollTop 和 scrollLeft (scrollX， scrollY)值吗？🤔

### ISSUE THREAD

**Issue by liqiuqiui** [antvis/S2#2809]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
https://s2-v1.antv.antgroup.com/api/basic-class/base-facet

`s2.facet.getScrollOffset()`

使用问题请先仔细看下文档, 如果还是没找到解决方案请在 [讨论区](https://github.com/antvis/S2/discussions/categories/q-a) 提问.

**Comment by liqiuqiui** [comment]
> https://s2-v1.antv.antgroup.com/api/basic-class/base-facet
> 
> `s2.facet.getScrollOffset()`
> 
> 使用问题请先仔细看下文档, 如果还是没找到解决方案请在 [讨论区](https://github.com/antvis/S2/discussions/categories/q-a) 提问.

不好意思，刚找到相关api 准备来关闭issue
