### ISSUE TITLE
支持设置滚动条的粗细🙏

### ISSUE THREAD

**Issue by wind108369** [antvis/S2#2830]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.55.6  |
| @antv/s2-react |  1.47  |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

客户反馈在windows电脑上滚动条比较窄，点击交互不方便，希望能够有配置调整粗细

**Comment by lijinke666** [comment]
请先看/搜索文档后再提问谢谢.

https://s2-v1.antv.antgroup.com/api/general/s2-theme

![image](https://github.com/user-attachments/assets/8ec7f020-8397-48c9-9022-45b7866c43ee)
