### ISSUE TITLE
🤔 自定义单元格时遇到的问题 ViewMeta.data 和1.x数据不一致，文档描述也没变

### ISSUE THREAD

**Issue by firmianaQ** [antvis/S2#2845]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.25    |
| @antv/s2-react |         |
| @antv/s2-vue   |    2.0.0-next.15     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

自定义单元格时遇到的问题 
ViewMeta.data 和1.x数据不一致，原始数据在 ViewMeta.data.raw内，但是类型没暴露raw属性
```
1.x ViewMeta.data 的值
{
    "number": 352,
    "province": "四川省",
    "city": "乐山市",
    "type": "办公用品",
    "sub_type": "纸张",
    "$$extra$$": "number",
    "$$value$$": 352
}
```
```
2.x ViewMeta.data 的值
{
    "raw": {
        "number": 352,
        "province": "四川省",
        "city": "乐山市",
        "type": "办公用品",
        "sub_type": "纸张"
    },
    "extraField": "number"
}
```

**Comment by lijinke666** [comment]
> ViewMeta.data 和1.x数据不一致

数据结构有变动, 这块文档近期完善

> 但是类型没暴露raw属性

data 是联合类型, 只有透视表的数值单元格才会有 `raw`, 可以 as 一下

```ts
//  data: ViewMetaData | SimpleData | undefined

(this.meta.data as CellData).raw
```

另外 `raw` 和 `extraField` 是 private 属性, 所以没有类型提示, 可以访问 `data.$$origin$$`, 和 `data.raw` 等价

![image](https://github.com/user-attachments/assets/5520e42d-0021-495c-9d2c-96c8dece2d04)
