### ISSUE TITLE
设置cellTextWordWrapStyle 展示多行，点击表格td，只有第一横行点击会选中这个td，tooltip才会展示

### ISSUE THREAD

**Issue by striveDSG** [antvis/S2#2846]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by striveDSG** [comment]
![Untitled42](https://github.com/user-attachments/assets/6ed9eb8a-ed0d-4732-9194-d2e0525ee798)

上面的链接，代码如下

<img width="595" alt="image" src="https://github.com/user-attachments/assets/7224ee20-6f97-4744-b4ce-cb7de65b7f81">

问题1: 超出5行没有省略号。
问题2:
1.  鼠标悬浮会展示tooltip，鼠标碰到tooltip就消失了，没办法进入。
2. 想tooltip不消失就鼠标点击，但是目前发现只有点击第一横行有用，其他行点击tooltip没办法展示

**Comment by lijinke666** [comment]
请提供最小可复现 demo, 这样才能排查, 代码怎么写的都不知道, 光看一个动图谁能知道问题在哪?

> 问题1: 超出5行没有省略号。

实际文本有多少行?

> 想tooltip不消失就鼠标点击，但是目前发现只有点击第一横行有用，其他行点击tooltip没办法展示

什么叫第一横行?
