### ISSUE TITLE
🐛S2父级及以上的节点，添加了transform: scale(1.1)后，透视表分组排序按钮失效

### ISSUE THREAD

**Issue by Karl-Xu** [antvis/S2#2849]
### 🏷 Version 1.55.8
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.55.8  |
| @antv/s2-react |  1.47.0  |
| antd |  4.24.16  |
| react |  18.3.1  |
| react-dom |  18.3.1  |

### Sheet Type
- [x]  PivotSheet
- [ ]  TableSheet
- [ ]  GridAnalysisSheet
- [ ]  StrategySheet
- [ ]  EditableSheet

### 🖋 Description
在S2表格的父级及以上的任意结点，添加transform: scale(1.1)样式后，透视表的分组排序按钮失效；通过调试及源码解读，因是点击位置已经不在S2的原始设定范围内，导致无法正确获取canvas内部点击位置
![image](https://github.com/user-attachments/assets/267f2e91-180c-4370-b5d9-5843b5c51f83)
也曾尝试官网的高清适配方案，但是两种场景并不相同，changSheetSize后仍受控与父级scale css样式影响

### ⌨️ Code Snapshots
使用官网示例：https://s2-v1.antv.antgroup.com/examples/analysis/sort#group-sort
并修改示例项目中的index.html文件，内容更改为：<div id="container" style="transform: scale(1.1); transform-origin: 0px 0px;" />
![image](https://github.com/user-attachments/assets/154aa0d0-71cd-45c9-bcc4-1717e7df377d)

### 🔗 Reproduce Link
修改后的codeSandbox连接：https://codesandbox.io/s/silly-gould-v447zf?file=/index.html

### 🤔 Steps to Reproduce
放大前：
![image](https://github.com/user-attachments/assets/6631bd07-3331-474d-a6fb-20cb6ba036fe)
放大后：
![image](https://github.com/user-attachments/assets/033d2d57-3006-4b2e-9699-b16586359762)

### 😊 Expected Behavior
希望放大后组内排序按钮功能正常；另，我们尝试使用S2 2.x版本，发现存在这样的问题

### 😅 Current Behavior
父级配置scale放大后，组内排序按钮失效

### 💻 System information
| Environment |     Info  |
| ------- | ------------- |
| System  |   macOS Sonoma 14.5   |
| Browser | chrome: v127.0.6533.89 |

**Comment by lijinke666** [comment]
https://s2-v1.antv.antgroup.com/manual/faq#%E7%88%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E4%BD%BF%E7%94%A8%E4%BA%86-transform-scale-%E5%90%8E%E5%9B%BE%E8%A1%A8%E9%BC%A0%E6%A0%87%E5%9D%90%E6%A0%87%E5%93%8D%E5%BA%94%E4%B8%8D%E6%AD%A3%E7%A1%AE

```ts
const s2Options = {
  supportCSSTransform: true
}
```

**Comment by oz9876** [comment]
添加后依然无效
