### ISSUE TITLE
🐛移动端 图表滑动到边缘 页面滚动条无法滚动 

### ISSUE THREAD

**Issue by zjs307065909** [antvis/S2#2857]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

2.0版本 移动端 图表按住滑动到边缘 页面滚动条无法滚动  图表有无数据皆不能滚动页面
1.0版本 完全正常

### 🔗 Reproduce Link

2.0地址:
https://s2.antv.antgroup.com/zh/examples/case/performance-compare/#table
1.0地址:
https://s2-v1.antv.antgroup.com/examples/basic/table/#table

### 🤔 Steps to Reproduce

打开提供的链接 
F12 移动端模式下 修改canvas高度和可视区域高度 显示出网页滚动条后 鼠标滚轮 页面向下滚动一些 按住数据网上拖拽即可复现 无法滑动问题 
相同操作 1.0版本可以拖动   
### 😊 Expected Behavior

早日排期 尽快恢复 

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by sgf1205** [comment]
支持早日解决该问题，我暂时是将生成的canvas中的touch-action属性设置为auto解决的

canvas.style.touchAction = 'auto'

**Comment by zjs307065909** [comment]
这么改并不行 应该是虚拟滚动到边缘 再改变canvas的touchAction
直接去掉touchAction 导致虚拟滚动也不好用了  滚动了整个页面

**Comment by zjs307065909** [comment]
> 🎉问题已在版本 @antv/s2-v2.0.0-next.28 中得到解决 🎉
> 
> 此新闻稿可在以下网站获取：
> 
> * [npm 包（@next dist-tag）](https://www.npmjs.com/package/@antv/s2/v/2.0.0-next.28)
> * [GitHub 发布](https://github.com/antvis/S2/releases/tag/%40antv/s2-v2.0.0-next.28)
> 
> 您的**[报价发布](https://github.com/semantic-release/semantic-release)**机器人📦🚀

这么改不行 应该是虚拟滚动到边缘再改变canvas的touchAction
直接去掉touchAction 导致虚拟滚动也不好用了 滚动了整个页面

**Comment by lijinke666** [comment]
> > 🎉问题已在版本 @antv/s2-v2.0.0-next.28 中得到解决 🎉
> > 此新闻稿可在以下网站获取：
> > 
> > * [npm 包（@next dist-tag）](https://www.npmjs.com/package/@antv/s2/v/2.0.0-next.28)
> > * [GitHub 发布](https://github.com/antvis/S2/releases/tag/%40antv/s2-v2.0.0-next.28)
> > 
> > 您的**[报价发布](https://github.com/semantic-release/semantic-release)**机器人📦🚀
> 
> 这么改不行 应该是虚拟滚动到边缘再改变canvas的touchAction 直接去掉touchAction 导致虚拟滚动也不好用了 滚动了整个页面

@zjs307065909 直接来 PR 吧, 期待
