### ISSUE TITLE
S2明细表鼠标悬停每行上面，去掉下边框🤔

### ISSUE THREAD

**Issue by Shanks0724** [antvis/S2#2858]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

S2明细表鼠标悬停每行上面，去掉下边框🤔
![20240813-103334](https://github.com/user-attachments/assets/06c9a4ae-d821-4b80-b66c-dcfde77ca787)

**Comment by wjgogogo** [comment]
这个是宽高 resize 热区，请阅读文档，通过 `rowCellVertical：false` 关闭：https://s2.antv.antgroup.com/manual/advanced/interaction/resize#%E7%83%AD%E5%8C%BA%E6%8E%A7%E5%88%B6

**Comment by wjgogogo** [comment]
如果使用的是 1.x 版本，参考：https://s2-v1.antv.antgroup.com/manual/advanced/interaction/basic#%E8%A1%8C%E5%88%97%E5%AE%BD%E9%AB%98%E8%B0%83%E6%95%B4
