### ISSUE TITLE
antv s2@1.49.1 使用customTree 目录树时，想通过conditions配置表头的样式，使用后发现，插件内部生成的row【指标】这一格无法修改，利用什么属性可以修改

### ISSUE THREAD

**Issue by zj-93** [antvis/S2#2860]
| Package        | Version |
| @antv/s2       |   1.49.1   |

PivotSheet

### 🖋 Description

'![Snipaste_2024-08-14_10-36-29](https://github.com/user-attachments/assets/592d2c4d-554c-4f83-8ddf-b8148350dced)' 
使用hierarchyType: customTree 目录树时，想通过conditions配置表头的样式，使用后发现，插件内部生成的row【指标】这一格无法修改

### 🔗 Reproduce Link

https://s2-v1.antv.antgroup.com/zh/examples/custom/custom-tree/#custom-tree
const s2Options = {
      width: 600,
      height: 480,
      hierarchyType: 'customTree',
      conditions: {
        text: [
          {
            field: 'custom-node-1',
            mapping(value) {
              return {
                fill: 'red',
              };
            },
          },
        ],
        background: [
          {
            field: 'type',
            mapping(value) {
              return {
                fill: 'red',
              };
            },
          },
          {
            field: 'sub_type',
            mapping(value) {
              return {
                fill: 'red',
              };
            },
          },
          {
            field: 'measure-a',
            mapping(value) {
              return {
                fill: 'red',
              };
            },
          },
        ],
      },
    };

### 😊 Expected Behavior
如何可以修改row【指标】这一格样式

**Comment by lijinke666** [comment]
conditions 是用于字段标记的场景, 如果你只是想定制表头样式, 请考虑 [主题配置](https://s2-v1.antv.antgroup.com/manual/basic/theme) 或 [自定义单元格](https://s2-v1.antv.antgroup.com/examples/custom/custom-cell/#custom-specified-cell)

[指标] 对应的单元格类型为 角头 (CornerCell)

```ts
s2.setTheme({
  cornerCell: {
    cell: { ... },
    text: {...}
  }
})
```

```ts
class CustomCornerCell extends CornerCell {
  getBackgroundColor() {
    console.log(this.meta)
    return {
      backgroundColor: 'red',
      backgroundColorOpacity: 0.2,
    };
  }
}
```
