### ISSUE TITLE
🤔S2明细表在使用tooltip  对dataCell自定义时  抛出异常！

### ISSUE THREAD

**Issue by Shanks0724** [antvis/S2#2861]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2    |
| @antv/s2-react |    2     |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

S2明细表在使用tooltip  对dataCell自定义时  抛出异常！

![20240815-11243211qqqqqq](https://github.com/user-attachments/assets/5f339146-8e46-4c67-bb9e-e2d5cf04d5ef)

![20240815-112443wwwww](https://github.com/user-attachments/assets/f433ddc4-8c53-4ea3-85e1-bc26c0033470)

![20240815-112449eeeeee](https://github.com/user-attachments/assets/4709ab43-5a74-41ca-b4b6-f9bf8219669d)

**Comment by lijinke666** [comment]
亲亲, 你用的 react 为什么不返回一个 jsx , 要返回一个 dom?
且类型提示都告诉你, 需要一个 `ReactNode`

![image](https://github.com/user-attachments/assets/a5927770-adf1-4828-94c0-28fd00768074)
