### ISSUE TITLE
🤔透视表树模式只有叶子节点才展示数据

### ISSUE THREAD

**Issue by ggcfcmd** [antvis/S2#2867]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.54.7     |
| @antv/s2-react |    1.46.4     |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

使用透视表树模式，之前可以正常渲染，现在只有叶子节点才能渲染，前后代码未做改动。尝试使用在线模式复现正常的情况，未果。官网给的例子目前也是只展示叶子节点，下面是官网的链接。因为项目中维护的版本会自动获取依赖最新的补丁版本，所以无法排除之前正常运行的版本比目前填写的版本旧的可能性
### 🔗 Reproduce Link
https://s2-v1.antv.antgroup.com/examples/basic/pivot/#tree
![image](https://github.com/user-attachments/assets/09536dcd-98a1-4259-8c08-d75bb5264420)

### 😊 Expected Behavior
希望可以帮忙确定下是否为依赖版本问题 或者提供解决问题的思路

**Comment by DelMemory** [comment]
@ggcfcmd 

![image](https://github.com/user-attachments/assets/d85f7c48-f525-47ae-8b66-2083412858a0)

配置一下就可以正常展示了

**Comment by lijinke666** [comment]
在树状模式, 非叶子节点 = 行小计节点, 所以需要开启行小计

1. 开启 `showSubTotals`, 参考楼上回答
2. 确保数据源有传入小计数据, 或者开启了前端小计计算功能.

![image](https://github.com/user-attachments/assets/8366f4b4-18b5-4d59-a6bd-e03ad5353626)


> 使用透视表树模式，之前可以正常渲染

那看起来是很早以前的版本了, 后续有改动
