### ISSUE TITLE
🐛onListSort内做自定义排序无效

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#287]
### 🖋 Description
组件下：
onListSort不生效；
onListSort 属性更新时，事件绑定的函数并不会更新（只绑定第一次）；
外部覆盖 RANGE_SORT 也不work
### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/dfaebbc0
### 🖥 Steps to Reproduce
点击列头排序 只会生效一次 只打印一次 “123”

**Comment by sc-xx** [comment]
同样遇到了onListSort不生效问题 😂

**Comment by stone-lyl** [comment]
以前向外抛出的 onListSort（排序回调，用于做自定义排序） 事件没有生效，因为 [sortParams. sortFunc](https://s2.antv.vision/zh/docs/api/general/S2DataConfig#sortfuncparam) 具有相同功能，估不重复定义。现向外抛出 onSortChange（组内排序时触发回调事件） 事件，用户可拿到每次排序的规则。
