### ISSUE TITLE
🐛asyncGetAllPlainData 自定义导出类型 customTransformer 配置 text/html 无效

### ISSUE THREAD

**Issue by DelMemory** [antvis/S2#2873]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.25    |
| @antv/s2-react |    2.0.0-next.24     |
| @antv/s2-vue   |         |

### Sheet Type

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在进行自定义复制配置时发现该问题，无论如何修改，都无法改变复制后的结果

可直接使用官方实例复现

### 🔗 Reproduce Link

https://s2.antv.antgroup.com/api/components/export#exportcfgprops

该链接为提供的官网链接，未修改代码，仅作参考

![image](https://github.com/user-attachments/assets/aa6173c2-0e01-456e-8217-d607041a64b5)

请使用 CodeSandbox 查看，官网的dom无法展示按钮，需要修改一下

### 🤔 Steps to Reproduce

请使用上面的链接查看代码

install react react-dom 可展示页面

![image](https://github.com/user-attachments/assets/cdb27591-4475-45c3-b8d3-920c0e568d83)

修改版本，否则会报 asyncGetAllPlainData 不存在

![image](https://github.com/user-attachments/assets/dc4b92eb-1ede-4d6c-b61f-df27908a0818)

放开 customTransformer 的注释
点击全部复制按钮
在飞书、语雀等文档中粘贴，会输出文本，按文档描述，应该输出的是空表格

![image](https://github.com/user-attachments/assets/77ea5c56-1d73-4670-9559-0ee091c3ca16)

经过多轮测试，无论传入什么参数，都会输出一模一样的文本

### 😊 Expected Behavior

应该输出空表格

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     macOS Ventura 13.4.1    |
| Browser |     Chrome 127.0.6533.100（正式版本） (arm64)    |

**Comment by lijinke666** [comment]
text/html 还不支持全量导出场景, 文档有误导, https://github.com/antvis/S2/pull/2865

https://github.com/antvis/S2/issues/2828
