### ISSUE TITLE
🤔列头能换行吗？不要省略号

### ISSUE THREAD

**Issue by stone1314** [antvis/S2#2874]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.30.0      |
| @antv/s2-react |   1.27.0      |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ 1] StrategySheet
- [ ] EditableSheet

### 😅 Current Behavior
如题，列头的内容太多，想要直接展示，不想省略，有办法吗？

**Comment by stone1314** [comment]
![20240823-141753](https://github.com/user-attachments/assets/f6fd1068-be59-4da0-8f8c-1e0bda714a5f)

想让它换行显示，可以吗？或者 我在内容上加上特殊字符，重新，进行换行？谢谢！

**Comment by stone1314** [comment]
这个里面执行`colCell: (node, s2, headConfig) => {
      console.log(11);
      return new CustomColCell(node, s2, headConfig);
     
    },`log 是打印不出来的吗？也没效果

**Comment by lijinke666** [comment]
> 如题，列头的内容太多，想要直接展示，不想省略，有办法吗？

不支持

> @antv/s2-react 里面 s2Options添加方法colCell: (node, s2, headConfig) => {
console.log(11);
return new CustomColCell(node, s2, headConfig);
},log 是打印不出来的吗？也没效果

趋势分析表是一个特殊的场景表, 列头本身就已经是一个[自定义单元格](https://github.com/antvis/S2/blob/e5b16c55b0a090560673f2723659d74a063662df/packages/s2-react/src/components/sheets/strategy-sheet/index.tsx#L83-L87)了, 不能二次自定义, 所以不会调用

**Comment by stone1314** [comment]
可以用 \\n 实现换行
   "$$extra_column$$": "[\"111数\\n值111111111\",\"环比\",\"同比\"]"
