### ISSUE TITLE
🤔getContentHeight可以获取实际内容高度，那如何获取实际内容的宽度呀

### ISSUE THREAD

**Issue by machachong** [antvis/S2#2881]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

**Comment by lijinke666** [comment]
> https://github.com/antvis/S2/blob/7f13ab1e2fb5d17be3bf7036b316a78027878eaf/packages/s2-core/src/facet/base-facet.ts#L640-L644

目前没有开放 API, 你可以这样拿到实际宽度

```ts
  const { rowsHierarchy, colsHierarchy } = s2.facet.getLayoutResult();

  const width = rowsHierarchy.width + colsHierarchy.width;
```

提 issue 请严格按照模版填写, 后续不遵守直接关闭了, 如果是使用问题请在 https://github.com/antvis/S2/discussions 提问
