### ISSUE TITLE
🐛 导出方法 copyData 在有手动隐藏列的情况下，导出的数据中，对应隐藏列的数据依然被导出，导致与表头错位

### ISSUE THREAD

**Issue by Miantang** [antvis/S2#2885]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.55.8    |
| @antv/s2-react |    1.47.0     |
| @antv/s2-vue   |         |

### Sheet Type

明细表

- [] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

导出方法 copyData 在有手动隐藏列的情况下，导出的数据中，对应隐藏列的数据依然被导出

### 🔗 Reproduce Link

改写官网DEMO后，

https://codesandbox.io/p/sandbox/condescending-dewdney-cgc9v8?file=%2Findex.tsx%3A8%2C10

### 🤔 Steps to Reproduce
<img width="743" alt="image" src="https://github.com/user-attachments/assets/4eede3a3-977c-4bad-ba26-67a1ad0d68da">

当有手动隐藏列后的导出， 表头与数据列会错位

<img width="286" alt="image" src="https://github.com/user-attachments/assets/41b4ba63-559b-4b80-a933-dca9b5b6ce7c">

### 😊 Expected Behavior

能正确导出

### 💻 System information

| Environment |     Info  |
| ------- | ------------- |
| System  |   mac 14.6   |
| Browser | chrome: v128.0 |

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/en/manual/migration-v2
