### ISSUE TITLE
🐛透视表自定义列头分组

### ISSUE THREAD

**Issue by Ahui4518** [antvis/S2#2893]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |    -     |
| @antv/s2-vue   |    -    |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在使用透视表的列头分组后，总计和小计的自动聚合计算不出来值
### ⌨️ Code Snapshots

在官网示例的透视表列头分组的options加入totals: {
      row: {
        showGrandTotals: true,
        calcGrandTotals: {
          aggregation: 'SUM'
        }
      }
    }就可以复现
### 😊 Expected Behavior

使用自定义聚合时，回调的第二个参数应该返回小计或总计中需要计算的量值

### 😅 Current Behavior

透视表自定义列头后，自定义聚合回调的第二个参数为空数组

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     -    |
| Browser |    -     |

**Comment by lijinke666** [comment]
自定义行/列头的场景, 不支持总计/小计, 后续完善下文档

**Comment by lijinke666** [comment]
已适配, 本周发布

![image](https://github.com/user-attachments/assets/a6ef6b86-a7e2-464f-b7a3-4020e3a81838)
