### ISSUE TITLE
🐛透视表自定义表头时，导出的表头与表格不一致

### ISSUE THREAD

**Issue by Ahui4518** [antvis/S2#2894]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

透视表的表头使用自定义节点时，导出的表头标题与表格显示不一致
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
怎么个不一致法? 自定义表头时, 导出原始值时对应 field, 导出格式化值则对应 title

**Comment by Ahui4518** [comment]
@lijinke666 好的，使用格式化导出的时候表头值就和渲染时的表格对上了
