### ISSUE TITLE
🐛紧凑模式，手动拖拽减小列宽，字体直接溢出

### ISSUE THREAD

**Issue by Azhi-ux** [antvis/S2#2900]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     next27    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

![image](https://github.com/user-attachments/assets/e84d817e-bb8d-4d43-8162-ddbf121af4d4)

### 🔗 Reproduce Link

https://s2.antv.antgroup.com/examples/layout/basic/#compact

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |      mac   |
| Browser |       chrome  |

**Comment by Azhi-ux** [comment]
@lijinke666 大佬帮看下

**Comment by lijinke666** [comment]
可以尝试来个 PR, 精力有限, 近期没时间修复.

**Comment by lijinke666** [comment]
在 `@antv/s2^2.0.0-next.30` 中升级了 G 的底层依赖, 应该不会出现字体溢出的问题了, 可以试试更新到最新版本 (官网还未部署)

![image](https://github.com/user-attachments/assets/4a90a6d2-8c6d-4c98-87d5-9a1c89d25232)


另外调整了最小可调整宽高的默认值, 如有特殊需求, 可自定义, 避免单元格被调整到一个极小不合理的宽度

```tsx
const s2Options = {
  interaction: {
    resize: {
      minCellWidth: 40,
	  minCellHeight: 20
	}
  }
}
```
