### ISSUE TITLE
🤔 为什么2.0版本中的明细表去掉了自动分组功能

### ISSUE THREAD

**Issue by liqiuqiui** [antvis/S2#2926]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.28     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
为什么2.0版本中的明细表去掉了自动分组功能
**2.0**
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/08b89ce6-05ca-4abf-a7bc-64dfae6fb267">
**1.x**
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/2974cc05-1df7-4d38-ab28-4d6232c76a95">

**Comment by lijinke666** [comment]
没有去掉, 2.0 版本修改了内部实现和 API, 移动了 demo 的位置 https://s2.antv.antgroup.com/zh/examples/layout/custom-header-group/#custom-table-col-header

**Comment by liqiuqiui** [comment]
> 没有去掉, 2.0 版本修改了内部实现和 API, 移动了 demo 的位置 https://s2.antv.antgroup.com/zh/examples/layout/custom-header-group/#custom-table-col-header

嗯，我已经找到了，谢谢
