### ISSUE TITLE
🐛Hidden data are present when exported in CSV, but not the hidden headers

### ISSUE THREAD

**Issue by fmo-dev** [antvis/S2#2936]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.45.0  |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

If some columns have been hidden in a table and you use the copyData function to prepare a CSV to download from the spreadsheet object, it is generated with :
- The headers without the hidden headers
- The data with the hidden data

This results in an incorrect CSV, as there are more data columns than headers

### ⌨️ Code Snapshots

To export our table, we only use this code snipper

```
const data = copyData(spreadsheet, ";");
download(data, title)
```

### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/eager-pascal-rxkllp?file=%2Fsrc%2FApp.tsx%3A16%2C23

### 🤔 Steps to Reproduce

Hide one or many columns by clicking on a header and clicking on "Hide", then try to export the table by clicking on the button above

### 😊 Expected Behavior

No hidden data should be in the CSV

### 😅 Current Behavior

The hidden data are in the CSV, but not their header, so their corresponding header on the CSV is the wrong one, and this is the case for any column after that

For example if we have this table

| Header1 |  Header2  | Header3  |
| --------- | ----------- | ---------- |
| Data1     | Data2      | Data3        |

If I hide the second column the table will looks like this

| Header1 | Header3  |
| --------- | ---------- |
| Data1        | Data3        |

But if i use the function `copyData` it will returns this string 

```
"Header1", "Header3",
"Data1", "Data2", "Data3"
```

Which is incorrect, because converting it to csv would give something similar to the table below

| Header1 |  Header3|  |
| --------- | ----------- | ---------- |
| Data1     | Data2      | Data3        |

### 💻 System information

| Environment |     Info  |
| ------- | ------------- |
| System  |   Windows 11   |
| Browser | chrome: v130.0.6723.70 |

**Comment by astragier** [comment]
Hi!
We have this bug in production, exporting tables while having some columns hidden result in an **invalid CSV file**.
Can you please look at this bug??

**Comment by lijinke666** [comment]
This was a known issue because there were a lot of copy/export issues and incompatible changes in 1.x version, so we completely refactored this part of the logic in version 2.0, which is currently in private beta with a stable release expected next month.

**Comment by lijinke666** [comment]
Version 2.0 is currently under construction and has only Chinese documentation.

**Comment by lijinke666** [comment]
ref: https://github.com/antvis/S2/issues/2885

**Comment by astragier** [comment]
> This was a known issue because there were a lot of copy/export issues, because have break changes in 1.x version, so we completely refactored this part of the logic in version 2.0, which is currently in private beta with a stable release expected next month.
> 
> If your project cannot be upgraded to 2.0, you will need to wait for a fix to be released later, or help us build together, submit bugfix patch PR.

Ok we'll wait for the v2 but I hope it would be released next month as you expect. Indeed we are waiting for it since November 2023 when it was announced for end of the year 😅

**Comment by lijinke666** [comment]
2.0 stable version is published. see https://s2.antv.antgroup.com/en/manual/migration-v2, other english documentation is `WIP`.

**Comment by fmo-dev** [comment]
Excellent news ! Do you have an idea of when the full english documentation will be available ?
