### ISSUE TITLE
🐛 大数据性能表现栈溢出 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by liangyuqi** [antvis/S2#2938]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     @antv/s2-v2.0.0-next.27    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

官网“100w条数据性能表现-明细表” 示例，下滑过程中栈溢出，不到 1w条数据稳定复现  https://s2.antv.antgroup.com/zh/examples/case/performance-compare#table
<img width="1712" alt="截屏2024-10-23 18 13 54" src="https://github.com/user-attachments/assets/516b8d5e-b8a2-4a23-81a0-bd69dc33fcd8">
<img width="519" alt="截屏2024-10-23 18 24 06" src="https://github.com/user-attachments/assets/a3b71457-cfc3-444a-a0ff-a13f0005554d">

### 🔗 Reproduce Link
https://s2.antv.antgroup.com/zh/examples/case/performance-compare#table

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     macos 14.3   |
| Browser |    chrome  129.0.6668.101（正式版本） (arm64)     |

**Comment by lijinke666** [comment]
已知问题, 等待底层渲染引擎解决中 https://github.com/antvis/G/issues/1712

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/issues/2771
