### ISSUE TITLE
🐛内置dark主题不生效

### ISSUE THREAD

**Issue by xuefeibai** [antvis/S2#2943]
### 🏷 Version

官网示例中, 自定义主题https://s2.antv.antgroup.com/examples/theme/custom/#custom-generate-palette, 将代码中的colorful改为dark, 切换任何颜色, 整个表格都是白色. dark不生效

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    -     |
| @antv/s2-react |   -      |
| @antv/s2-vue   |    -     |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
暗黑主题下, 不支持自定义 palette 色板, 仅声明 name 即可.

![image](https://github.com/user-attachments/assets/8421a09c-3327-4bda-b097-b3c157715511)

```ts
   <SheetComponent
      dataCfg={dataCfg}
      options={s2Options}
      themeCfg={{ name: 'dark' }}
    />
```
