### ISSUE TITLE
🙏希望可以兼容antd v4，仅需一点小小的改动

### ISSUE THREAD

**Issue by GuoMouMo** [antvis/S2#2952]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.29  |
| @antv/s2-react |  2.0.0-next.28  |

### Sheet Type

- [ ] PivotSheet
- [✅ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

项目中使用的antd v4

从S2 v1版本升级到S2 v2时碰到了一个报错
```
Uncaught TypeError: Cannot read properties of null (reading 'darkAlgorithm')
```
经过排查是这个目录下S2-next/packages/s2-react/src/components/config-provider/index.tsx，消费了antd的theme
antd v5的theme是一个对象，但在v4版本是null值，希望可以增加可选链来做兼容。

目前已经通过webpack插件修改了这部分代码，项目可以正常使用了，但不是长久之计，希望可以修改一下这部分代码

### 🏞 What problem does this feature solve

这个改动可以使s2-react运行在使用了antd v4版本的环境

**Comment by lijinke666** [comment]
已知问题, 下个月会发布 2.0 的正式版, s2-react 会移除 antd 的耦合

https://github.com/antvis/S2/pull/2887
