### ISSUE TITLE
🤔希望这里的高度是单行文本的高度

### ISSUE THREAD

**Issue by wangjinqing111** [antvis/S2#2955]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
明细表-多级表头-长文本下
![image](https://github.com/user-attachments/assets/efb3cee3-eb03-40cd-8366-eabf3745c494)

**Comment by lijinke666** [comment]
看起来是父节点未超过 `maxLines` 时, 高度有点问题

![image](https://github.com/user-attachments/assets/19b2cc6c-e545-4f93-b5bf-002d5b6864c1)


![image](https://github.com/user-attachments/assets/1cac6978-2bc2-4e67-99f6-16ee72a7d54f)
