### ISSUE TITLE
🐛 `cornerCell` 的 `measureText.textBaseline` 和其它 cell 的 `measureText.textBaseline`默认值不一样

### ISSUE THREAD

**Issue by liqiuqiui** [antvis/S2#2957]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.30     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
角头虚拟数值字段文本在配置了cornerCell.measureText后不能垂直居中了

### ⌨️ Code Snapshots
未配置 `textBaseline` 时，`cornerCell.measureText`和其它单元格的 `measureText` 的默认值不一样

![image](https://github.com/user-attachments/assets/eea83905-ff4a-4bf6-a26f-39bc516f8525)

显示配置 `textBaseline: "middle"` 可居中

![image](https://github.com/user-attachments/assets/9eb723cf-c76a-40a0-a0b5-7c0f04c418c5)

### 🔗 Reproduce Link
[在线复现链接](https://codesandbox.io/p/sandbox/busy-gwen-vqyfj4?file=%2Findex.ts%3A70%2C35)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
感谢反馈, 看了下, cornerCell 的默认主题没有 `measureText` 的配置, 所以默认取成 `top` 了, 这种场景漏掉了, 预期应该都是 `textBaseline: 'middle'`
