### ISSUE TITLE
🤔想自定义列头加入 writing-mode: vertical-lr; 竖着显示有什么好方法吗

### ISSUE THREAD

**Issue by mtrucc** [antvis/S2#2959]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |     2.0.0    |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

<img width="990" alt="image" src="https://github.com/user-attachments/assets/5eee2440-6289-46af-a9bd-47f1ab1cb022">
我期望能自定义列头，这样显示

**Comment by lijinke666** [comment]
`writing-mode: vertical-lr` 是 CSS 的能力, 你要在 Canvas 中实现意味着你要模拟浏览器的排版实现, 很麻烦, 一切都要自己计算, 建议不要折磨自己, 提供几个可能的思路:

首先预设一个合适的列头宽高, 在自定义 ColCell 的基础上

1. 分词

```ts
const textList = "我是文本".split('')

textList.forEach((text) => {
  // 测量或写死每一个字的高度
  // 调用 G 的 API 绘制文本
})
```


2. 旋转绘制

```ts
ctx.save();
ctx.translate(this.meta.width / 2,this.meta.height / 2);
ctx.rotate(Math.PI / 2);
ctx.fillText('我是文本', 0, 0);
ctx.restore();
```

以上情况, 如果文本长度是动态的, 那还需要动态调整列头宽高, 实现自动撑高的效果


3. 利用 S2 自带的[多行文本](https://s2.antv.antgroup.com/manual/basic/multi-line-text)能力, 无需考虑文本分词和坐标计算, 单元格自动撑开等逻辑, 设置一个足够大的 `maxLines`, 然后设置一个只能放下一个字的列宽

```ts
const cellTextWordWrapStyle = {
  maxLines: 10,
  wordWrap: true,
  textOverflow: ''
};
```

![image](https://github.com/user-attachments/assets/5ea3bbe2-a1c1-4089-b17e-1fd7ca18c7bd)


以上方式如果都不行或者效果不佳, 直接用 DOM 表格吧...
