### ISSUE TITLE
🤔基础类不能设置高宽？

### ISSUE THREAD

**Issue by 4color** [antvis/S2#2962]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |      2.0.0-next.30    |
| @antv/s2-react |         |
| @antv/s2-vue   |    2.0.0-next.15     |

### Sheet Type

- [1 ] PivotSheet
- [1 ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

我直接用基础类来展示表格，但高宽不管怎么调都是默认值 600，400

  const s2 = new PivotSheet(container, s2DataConfig, s2Options);
要如何改才可以修改高宽

**Comment by lijinke666** [comment]
> 不管怎么调

怎么个调法? 代码怎么写的? 初始化还是动态更新? 什么有用信息都没有, 也没有最小复现链接, 没人能回答你

1. 初始化

```ts

const s2Options = {
  width: 300,
  height: 200
}

const s2 = new PivotSheet(container, s2DataConfig, s2Options);

await s2.render()
```

2. 更新

```ts
s2.changeSheetSize(300, 200)
await s2.render(false)

```

https://s2.antv.antgroup.com/manual/faq#%E6%89%8B%E5%8A%A8%E6%9B%B4%E6%96%B0%E8%A1%A8%E6%A0%BC%E5%AE%BD%E9%AB%98%E5%90%8E%E4%B8%BA%E4%BB%80%E4%B9%88%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8D%E6%98%BE%E7%A4%BA%E4%BA%86
