### ISSUE TITLE
🐛 透视表自定义icon初始化加载第一个单元格icon会消失的问题

### ISSUE THREAD

**Issue by liran19960215** [antvis/S2#2976]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.32     |
| @antv/s2-react |         |
| @antv/s2-vue   |   2.0.0-next.16      |

### Sheet Type

- [ √ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
当使用自定义icon功能时，发现初始化进入页面时 第一个单元格子的自定义icon都会消失不渲染 鼠标hover上去的时候才会显示
![image](https://github.com/user-attachments/assets/488fde37-58f0-478b-b4b2-5f0576ddda71)
![image](https://github.com/user-attachments/assets/6dd8d334-51ba-45da-b5a8-a59c6597fae9)
![image](https://github.com/user-attachments/assets/51ce4ed2-6a86-4167-a171-a6b973d28468)

### ⌨️ Code Snapshots
无

### 🔗 Reproduce Link
https://s2.antv.antgroup.com/zh/examples/custom/custom-icon/#custom-svg-icon
https://s2.antv.antgroup.com/zh/examples/custom/custom-icon/#custom-header-action-icon
https://s2.antv.antgroup.com/zh/examples/custom/custom-icon/#custom-data-cell-icon

### 🤔 Steps to Reproduce
打开对应官网链接即可复现

### 😊 Expected Behavior
所有符合要求的自定义icon都能主动显示

### 😅 Current Behavior
首个符合要求的自定义icon不会渲染

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
G 的问题, 升级到 `@antv/s2@2.0.0-next.33` 即可.
