### ISSUE TITLE
🤔树状透视表 子节点无数据时，展开折叠按钮不显示？

### ISSUE THREAD

**Issue by db-shuai** [antvis/S2#2981]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     2.0.0-next.32    |
| @antv/s2-react |         |
| @antv/s2-vue   |     2.0.0-next.16    |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

当我尝试将 S2 表格从 s2@2.0.0-next.23 升级至 s2@2.0.0-next.32、s2-vue@2.0.0-next.14升级至s2-vue@2.0.0-next.16
发现在树状模式下 hierarchyType:tree ，若子节点无数据父节点不展示 折叠与展开按钮了，因以前是通过点击折叠按钮获取子节点数据的。所以想咨询一下目前怎么配置可以使展开折叠按钮一直显示？
### 🔗 Reproduce Link

https://codesandbox.io/p/sandbox/async-leaf-fmt353

### 😊 Expected Behavior
<img width="150" alt="image" src="https://github.com/user-attachments/assets/9537c945-ae27-4219-bf51-d757af426c5b">

### 😅 Current Behavior
<img width="588" alt="image" src="https://github.com/user-attachments/assets/a153538b-4194-496e-b1d3-38637b0d8e28">

**Comment by lijinke666** [comment]
> 若子节点无数据父节点不展示 折叠与展开按钮了

之前的版本能展示是 bug

> 因以前是通过点击折叠按钮获取子节点数据的。所以想咨询一下目前怎么配置可以使展开折叠按钮一直显示？

可以[自定义 rowCell](https://s2.antv.antgroup.com/examples/custom/custom-cell/#custom-specified-cell), 重写 默认 icon 的展示规则, 比如第一层级始终展示

```ts
class CustomRowCell extends RowCell {
  showTreeIcon() {
    return (
      this.spreadsheet.isHierarchyTreeType() &&
      (!this.meta.isLeaf || this.meta.level === 0)
    );
  }
}

const s2Options = {
  rowCell: (node, spreadsheet, headerConfig) => {
    return new CustomRowCell(node, spreadsheet, headerConfig);
  }
}
```
