### ISSUE TITLE
🤔点击单元格中的icon，获取不到本行的数据，怎么可以点击图标获取当前行的数据

### ISSUE THREAD

**Issue by dyllike3892654** [antvis/S2#2985]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^2.0.0-next.26     |
| @antv/s2-react |    ^2.0.0-next.25     |
| @antv/s2-vue   |         |
 

### Sheet Type

使用的react中的透视表 SheetComponent 组件

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet
- [ √ ] SheetComponent

### 🖋 Description

我使用的是  @antv/s2-react 中的 SheetComponent 组件 ，给 表格 的 s2Options增加 配置 icon，使单元格的数据前增加一个icon图标，代码如下：
      **conditions: {
        icon: [
          // 配置数据单元格
          {
            field: 'number',
            position: 'left',
            mapping() {
              return {
                icon: 'CellUp',
                fill: '#2498D1',
              };
            },
          },
        ],
      },**
      
**出现的问题是：当我点击单元格的时候可以获取到数据，但是当我单击到图标上时就会显示 undefined ；**
![image](https://github.com/user-attachments/assets/76b03ab1-c7a0-47d4-a48b-bcae061e4561)

使用 headerActionIcons 这个属性只能在角头、列头、行头显示
![image](https://github.com/user-attachments/assets/3c866d15-16f8-4e2c-9b91-3edd26deb3f1)

**想达到的效果是：点击图标能获取当前行的数据**

**Comment by lijinke666** [comment]
可以先这样写, icon 是单元格的子节点, 所以没获取到 meta, 后续优化下

```ts
const meta = viewMeta || target?.parent?.meta
```
