### ISSUE TITLE
🎉 S2 2.0 正式版现已发布 !

### ISSUE THREAD

**Issue by lijinke666** [antvis/S2#2986]
## 🏠 官网地址变化

> [!WARNING] 
原官网 <https://s2.antv.vision> 和 <https://antv-s2.gitee.io> 不再维护和使用，请访问最新的网址，以确保您看到的不是过时的文档。

- 原 `v1` 官网迁移至 <https://s2-v1.antv.antgroup.com>.
- 原 <https://s2.antv.antgroup.com> 将作为 `v2` 默认官网。

## 🏷️ npm dist-tag 变化

> 什么是 [dist-tag](https://docs.npmjs.com/adding-dist-tags-to-packages/) ?

[`S2 2.0`](https://s2.antv.antgroup.com) 正式版已发布，现在 `npm` 的 [`latest` dist-tag](https://docs.npmjs.com/cli/v10/commands/npm-dist-tag) 默认对应 `2.x` 版本，即：

- ~~`@antv/s2@latest` => `@antv/s2@1.x.x`~~

- `@antv/s2@latest` => `@antv/s2@2.x.x`

> [!WARNING] 
**如通过此类未指定具体版本的方式安装，请注意不要意外安装到 `2.0` 新版本。**

## ⏰ 已停止维护的包和版本

- `1.x` 版本现已停止维护，不再继续更新，不再修复 bug，不再支持新特性。
- `@antv/s2-vue` 现已停止维护，由于精力投入有限，出于维护成本，包下载量等因素综合考虑，从 `2.0.0` 正式版后不再继续更新，请基于 `@antv/s2` 自行封装，或 fork 仓库进行二次开发社区版本。

请根据 [升级指南](https://s2.antv.antgroup.com/manual/migration-v2) 尽快升级到 `2.x` 版本。

## 🛺 从 2.0.0-next.x 到 2.0.0 正式版

如果你使用的是内测版本 `2.0.0-next.x`, 升级到 `2.0` 正式版时额外需要注意以下几点不兼容改动：

- [构建产物调整](#-构建产物调整)
- [移除 Ant Design 组件库依赖](#移除-ant-design-组件库依赖)
- [Tooltip 操作项默认菜单组件移除](#tooltip-操作项默认菜单组件移除)

具体请查看 [2.0 升级指南](https://s2.antv.antgroup.com/manual/migration-v2)

## 📦 安装

| 包名  | 稳定版  | 包大小  | 下载量    |
| -------- | ------ | --------- | ------ |
| [@antv/s2](https://github.com/antvis/S2/tree/next/packages/s2-core)        | ![latest](https://img.shields.io/npm/v/@antv/s2/latest.svg?logo=npm)  | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2@latest/dist/index.min.js?label=gzip%20size&compression=gzip)       | ![download](https://img.shields.io/npm/dm/@antv/s2.svg?logo=npm)       |
| [@antv/s2-react](https://github.com/antvis/S2/tree/next/packages/s2-react) | ![latest](https://img.shields.io/npm/v/@antv/s2-react/latest.svg?logo=npm) | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2-react@latest/dist/index.min.js?label=gzip%20size&compression=gzip) | ![download](https://img.shields.io/npm/dm/@antv/s2-react.svg?logo=npm) |
| [@antv/s2-react-components](https://github.com/antvis/S2/tree/next/packages/s2-react-components) | ![latest](https://img.shields.io/npm/v/@antv/s2-react-components/latest.svg?logo=npm) | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2-react-components@latest/dist/index.min.js?label=gzip%20size&compression=gzip) | ![download](https://img.shields.io/npm/dm/@antv/s2-react-components.svg?logo=npm) |
| [@antv/s2-vue](https://github.com/antvis/S2/tree/next/packages/s2-vue)（停止维护）| ![latest](https://img.shields.io/npm/v/@antv/s2-vue/latest.svg?logo=npm) | ![size](https://img.badgesize.io/https:/unpkg.com/@antv/s2-vue@latest/dist/index.min.js?label=gzip%20size&compression=gzip)   | ![download](https://img.shields.io/npm/dm/@antv/s2-vue.svg?logo=npm)   |

### 使用基础版本 <Badge>`@antv/s2`</Badge>

> 使用 npm 或 yarn 或 pnpm 安装

```bash
# npm
$ npm install @antv/s2 --save

# yarn
$ yarn add @antv/s2

# pnpm
$ pnpm add @antv/s2
```

### 使用 React 版本 <Badge>`@antv/s2-react`</Badge>

```bash
npm install @antv/s2 @antv/s2-react --save

```

### 使用 Vue3 版本 <Badge type="success">@antv/s2-vue</Badge> <Badge type="error">停止维护</Badge>

> [!WARNING] 
`@antv/s2-vue` 现已停止维护，由于精力投入有限，出于维护成本，包下载量等因素综合考虑，从 `2.0.0` 正式版后不再继续更新，请基于 `@antv/s2` 自行封装，或 fork 仓库进行二次开发社区版本。

```bash
npm install @antv/s2 @antv/s2-vue ant-design-vue@3.x --save
```

## ⭐ 新增功能

官网目录标记为 <Badge type="success">`New`</Badge> 和 <Badge>`Updated`</Badge> 则表示新增功能.

## 📦 构建产物调整

- `ESModule/CommonJS`

所有包的 `ESModule (esm)` 和 `CommonJS (lib)` 构建产物从 `Bundle` 调整为 `Bundless`, 其所依赖的子模块会被直接拷贝输出，不再做编译，以便于更好的支持代码 `tree shaking`, 减少包体积。

- `UMD`

所有包的 `UMD (dist)` 构建产物依然为 `Bundle` 单文件，**文件名**和**全局变量名**有所调整：

| 包名  | 文件名（修改前） | 文件名（修改后） |
| -------- | ------ | --------- |
| `@antv/s2` | `dist/index.min.js` `dist/style.min.css` | `dist/s2.min.css` `dist/s2.min.css` |
| `@antv/s2-react` | `dist/index.min.js` `dist/style.min.css` | `dist/s2-react.min.css` `dist/s2-react.min.css` |
| `@antv/s2-vue` | `dist/index.min.js` `dist/style.min.css` | `dist/s2-vue.min.css` `dist/s2-vue.min.css` |

| 包名  | 全局变量名（修改前） | 全局变量名（修改后） |
| -------- | ------ | --------- |
| `@antv/s2` | `S2` | `S2` |
| `@antv/s2-react` | `S2-React` | `S2React` |
| `@antv/s2-vue` | `S2-Vue` | `S2Vue` |

## 📣 不兼容的变化

请查看 [2.0 升级指南](https://s2.antv.antgroup.com/manual/migration-v2)

**Comment by afc163** [comment]
加油
