### ISSUE TITLE
🐛编译的时候黑暗主题的部分编译无法通过

### ISSUE THREAD

**Issue by sunchenjun** [antvis/S2#2989]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   2.0.0 |
| @antv/s2-react |  2.0.1   |
| @antv/s2-react-components |  2.0.1   |

### Sheet Type

- PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

组件源码 引入less文件的代码出错导致编译错误

### ⌨️ Code Snapshots

Uncaught SyntaxError: The requested module '/@fs/C:/Users/admin/Desktop/electron-tos/node_modules/@antv/s2/esm/styles/theme/dark.less' does not provide an export named 'default' (at chunk-YBHE4DD3.js?v=f504c188:34022:8)
### 🤔 Steps to Reproduce

安装了最新的正式版，编译时报错，溯源是
![image](https://github.com/user-attachments/assets/29288c0b-3a34-47c4-8f01-0b21356631ef)

正常编译通过

### 😅 Current Behavior

编译未通过

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |  window 11   |
| Browser |  chrome: v130.0.6723.117  |

**Comment by lijinke666** [comment]
已知问题, 升级到最新版本即可 (@antv/s2^2.0.1 @antv/s2-react^2.0.2)
