### ISSUE TITLE
🐛关于svg的导入错误导致编译不过去

### ISSUE THREAD

**Issue by sunchenjun** [antvis/S2#2990]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.1       |
| @antv/s2-react |   2.0.2      |
| @antv/s2-vue   |   2.0.1      |

### Sheet Type

- [x]  PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

编译时，svg作为react组件部分代码编译不过去
### ⌨️ Code Snapshots

编译时报错
Uncaught SyntaxError: The requested module '/@fs/C:/Users/admin/Desktop/electron-tos/node_modules/@antv/s2-react-components/esm/components/common/icons/svg/calendar-icon.svg?import' does not provide an export named 'ReactComponent' (at @antv_s2-react-components.js?v=7ab7ed45:4814:10)
![image](https://github.com/user-attachments/assets/61fbdd19-e12d-4037-ba21-4343fe0c0dda)

### 🤔 Steps to Reproduce

编译时报错, 认为这里没有这样的抛出
![image](https://github.com/user-attachments/assets/ab1d1c3e-7deb-40a1-9c62-8c921e82d018)

### 😊 Expected Behavior

编译过去
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |      |
| Browser |         |

**Comment by lijinke666** [comment]
近期看一下, 是用到了 `@antv/s2-react-components` 的什么组件?

**Comment by sunchenjun** [comment]
单纯是包编译不过去

**Comment by sunchenjun** [comment]
可以自己装一下使用一下，会发现编译不过去，和使用哪个组件无关

**Comment by sunchenjun** [comment]
具体可以使用一下Switcher
