### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by gb853940223** [antvis/S2#2996]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.33 |
| @antv/s2-react |2.0.0-next.30|

### Sheet Type

- [x ] PivotSheet

### 🖋 Description

本人提交了一个PR：https://github.com/antvis/S2/pull/2995
在review阶段报如下错误：
![image](https://github.com/user-attachments/assets/db7a5ab9-9638-40e0-87d0-507957c081fa)
但是当我点击“Details”想查看具体错误原因，并尝试修复此PR时，却跳转了404页面
![image](https://github.com/user-attachments/assets/2a537d8a-f631-4d03-9686-9a5a73b6d049)
因为无法知晓PR报错的具体原因，导致我无法将改动内容正常PR。

### 🔗 Reproduce Link

https://github.com/antvis/S2/pull/2995

**Comment by lijinke666** [comment]
https://github.com/antvis/S2/issues/3006#issuecomment-2515995666
