### ISSUE TITLE
🤔提交PR之后，Deployment has failed，却看不到任何详情信息

### ISSUE THREAD

**Issue by gb853940223** [antvis/S2#3006]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.33 |
| @antv/s2-react |2.0.0-next.30|

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

本人提交了一个PR:https://github.com/antvis/S2/pull/3005。却出现了如下错误：
![image](https://github.com/user-attachments/assets/6f7cea4a-e760-4304-a0e9-0eee578c06b3)
当尝试去点击”Details“查看具体的错误详情时，得到如下错误：
![image](https://github.com/user-attachments/assets/7b624663-176a-40f6-8c63-dbb09c70016f)

### 🔗 Reproduce Link

PR地址：https://github.com/antvis/S2/pull/3005

**Comment by lijinke666** [comment]
这个错误不用管, 一直是挂的
