### ISSUE TITLE
🐛  项目运行时，@antv/s2-react@2.1.2  内部报错

### ISSUE THREAD

**Issue by oliver34** [antvis/S2#3025]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.1.2     |
| @antv/s2-react |  2.1.2       |
| @antv/s2-vue   |         |

### Sheet Type

- [ ✅] PivotSheet
- [打钩 ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

项目环境：umi3.0 + React 17  
之前使用 1.0 版本，没有报错，最近想升级一下 2.0 版本，处理了一些兼容报错问题，但是项目运行后 @antv/s2-react 内部报错了，然后 尝试直接从 dist 引入也是一样报错，报错截图如下，是打包工具太老了需要升级吗
### 🔗 Reproduce Link

<img width="937" alt="image" src="https://github.com/user-attachments/assets/39d3300e-800c-4a48-88de-d3ff8b7067cc">

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by oliver34** [comment]
我在配置中将包引用强制指向了 cjs 构建产物
```
alias: {
    '@antv/s2-react': '@antv/s2-react/dist/s2-react.min.js', 
  },
```
报错少了，但是还是报了一个错
```
ERROR in ./node_modules/_@antv_s2-react@2.0.0@@antv/s2-react/dist/s2-react.min.js
Module not found: Error: Can't resolve '@antv/s2/extends' in '/Users/wangjunjie/Desktop/hmos/hmos-report-solution/node_modules/_@antv_s2-react@2.0.0@@antv/s2-react/dist'
 @ ./node_modules/_@antv_s2-react@2.0.0@@antv/s2-react/dist/s2-react.min.js 26:113-140
 @ ./src/index.ts
```
@lijinke666

**Comment by lijinke666** [comment]
> 我在配置中将包引用强制指向了 cjs 构建产物

你引的是 umd, 不要为了不报错乱搞...

---

esm 编译的 target 是 ESNext, 所以没处理 `??=` `??` 之类的语法, 你的打包工具应该是忽略了 node_modules, 所以没编译, 导致 webpack 不识别这个语法

这个我优化下, 把构建产物编译到 es2015 好了

**Comment by HdjPoppy** [comment]
![Image](https://github.com/user-attachments/assets/50d8806f-f7f7-4baa-9ce4-56fd196ffc51) 同样问题
