### ISSUE TITLE
透视表 单度量值的情况下可以隐藏度量列的名称或者合并吗

### ISSUE THREAD

**Issue by LiaoMinYu** [antvis/S2#3031]
### 🏷 Version 
| Package        | @antv/s2-vue 1.49.0 ||

### Sheet Type

- [ ] PivotSheet
### 🖋 Description

透视表 在单度量值的情况下可以隐藏度量列的名称或者合并吗

<img width="735" alt="image" src="https://github.com/user-attachments/assets/6c144e98-16c4-413a-9d99-3e9e63ebc311">

**Comment by lijinke666** [comment]
https://s2-v1.antv.antgroup.com/api/general/s2-options#colcfg

![image](https://github.com/user-attachments/assets/fe920a19-7cc5-4639-a1a9-f2b31266d4ff)
