### ISSUE TITLE
🐛合并单元格在滚动后出现异常

### ISSUE THREAD

**Issue by wyh888** [antvis/S2#3032]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  v2.0.0-next.33  |
| @antv/s2-react |  v2.0.0-next.31  |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

设置合并单元格生效后，滚动表格，再滚动回合并单元格的位置，发现合并的样式出现异常且不可预计
![file](https://github.com/user-attachments/assets/d4577022-2685-46dc-b816-d18aec637fa7)

### ⌨️ Code Snapshots

```
const s2Options: S2Options = {
      width: 600,
      height: 280,
      mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
    };
```

### 🔗 Reproduce Link

[https://s2.antv.antgroup.com/examples/basic/table/#table](https://s2.antv.antgroup.com/examples/basic/table/#table)

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

**Comment by lijinke666** [comment]
最新版本 (@antv/s2-v2.1.4) 未复现

![image](https://github.com/user-attachments/assets/770a2d53-81a0-48eb-86e1-f045ee222943)

**Comment by wyh888** [comment]
> 最新版本 (@antv/s2-v2.1.4) 未复现
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/396433396-770a2d53-81a0-48eb-86e1-f045ee222943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk0OTgsIm5iZiI6MTczNDQ0OTE5OCwicGF0aCI6Ii8yMTAxNTg5NS8zOTY0MzMzOTYtNzcwYTJkNTMtODFhMC00OGViLTg2ZTEtZjA0NWVlMjIyOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE1MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNzQ4NDgzNzIzNDU2OGI4NDA4ZDk3NTc2NTJhOGNjNmU0MGI2MDY2MjgwY2IxODBkNGMwYmIyNDg3MGE4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XyzsrKTAepw-pyCXMzRa-oQaQmba9RR6xYTOIh5zFAI)

@lijinke666 麻烦大佬再看一下，我拉取最新的代码v2.1.4依然是复现的，并且官网demo也是一样的bug，需要滚动可以复现

复现案例：
1. 官网地址：https://s2.antv.antgroup.com/examples/basic/table/#table，代码参考 issue 内容
2. 拉取最新代码本地运行，复现如图：

![1](https://github.com/user-attachments/assets/5efeb836-f5ae-4b0a-98b4-4bdb349359c3)

按照下述代码修改一下 100w 数据的demo，反复滚动可出现：

```
const s2Options: SheetComponentOptions = {
  height: 480,
  mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
  interaction: {
    scrollSpeedRatio: {
      vertical: 1,
      horizontal: 1,
    },
  },
  transformCanvasConfig(renderer) {
    renderer.setConfig({
      enableCulling: true,
    });
  },
};

const s2DataConfig: S2DataConfig = {
  fields: {
    // rows: [],
    columns: ['type', 'subType', 'province', 'city', 'number'],
    // values: ['number'],
  },
  data: generateRawData(
    { province: 1, city: 10 },
    { type: 10, subType: 10 },
  ),
};

// sheetType 也改成 table
```
