### ISSUE TITLE
🤔运行pnpm site:start报错

### ISSUE THREAD

**Issue by gb853940223** [antvis/S2#3034]
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

打算新增一个案例demo。按照官网的贡献指南，将代码clone之后，依次执行以下命令：

切换到 2.x 分支
git checkout next

安装依赖
pnpm install # 或者 pnpm bootstrap

打包
pnpm build

pnpm core:build-esm # 首次运行需要先执行一次

本地启动官网
pnpm site:start

报错如下图：
![image](https://github.com/user-attachments/assets/b6059d06-7f11-4e1a-8811-32c40b81893c)

**Comment by lijinke666** [comment]
pnpm 版本多少? 看起来是依赖没有安装成功, 包没有 link 到, 根目录 `pnpm i` 执行成功了吗? 检查下 `s2-site` 下的 node_modules

![image](https://github.com/user-attachments/assets/ea66e891-8dd5-4c8e-ac96-9dcbe2154430)

**Comment by gb853940223** [comment]
pnpm版本为：9.14.1
s2-site 下的 node_modules如下：
![image](https://github.com/user-attachments/assets/4c8f4b5d-47f6-4ea4-ab0f-d9ecc9b513f4)
s2-site 下的 node_modules下的s2如下
![image](https://github.com/user-attachments/assets/1d43ae16-99d8-41a4-a99f-6c03568b98da)
s2-site 下的 node_modules下的s2-react如下
![image](https://github.com/user-attachments/assets/fa886a2e-c037-488e-b1b6-4adcea77291e)
s2-site 下的 node_modules下的s2-react-components如下
![image](https://github.com/user-attachments/assets/3f38a103-7b78-40f0-baee-0e8410857a01)

**Comment by gb853940223** [comment]
![image](https://github.com/user-attachments/assets/9b2d70d4-6a1c-435c-b0d2-4e287538780a)

**Comment by lijinke666** [comment]
本地文档执行的是各子包下的 esm 的产物, 所以根目录 `pnpm build` 后再 `pnpm site:start`, 后面优化下文档
