### ISSUE TITLE
🐛字符串如果第一个字符为换行符会报错

### ISSUE THREAD

**Issue by ouzhou** [antvis/S2#3040]
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    |
| @antv/s2-react |    |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/5de2bb82-45e6-4636-a032-b6ae1a763c37)

测试数据
```
'\naaaa'
```

但是这种数据不报错
```
'aa\naa'
```

### ⌨️ Code Snapshots / 代码片段

```
'\naaaa'
```

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

随便哪个表格，搞一个这样的字符串作为数据就会报错
```
'\naaaa'
```

### 😊 Expected Behavior / 期望行为

不要直接崩溃

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by ouzhou** [comment]
@petercat-assistant
应该是代码中wordWrap函数在处理的时候 执行了appendEllipsis这个函数，const currentLineLength = lines[lineIndex].length;
但是lines为空数据，导致currentLineLength为undefined

**Comment by ouzhou** [comment]
这个是一个bug

**Comment by lijinke666** [comment]
fixed https://github.com/antvis/G/pull/1871
