### ISSUE TITLE
🐛明细表自定义列头分组时，隐藏列后列头显示错误

### ISSUE THREAD

**Issue by qianchengjie** [antvis/S2#3044]
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    |
| @antv/s2-react |    |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

明细表自定义列头分组时，隐藏列后列头显示错误，会有空白出现
<img width="712" alt="image" src="https://github.com/user-attachments/assets/5e20a120-26b4-4b34-92f6-ca6c9ba929f6" />

### ⌨️ Code Snapshots / 代码片段

https://codesandbox.io/p/sandbox/clever-orla-n7lqf4?workspaceId=ws_8oNxnxhUCJz2Dk1z7Gf7rk

### 🔗 Reproduction link / 复现链接

https://codesandbox.io/p/sandbox/clever-orla-n7lqf4?workspaceId=ws_8oNxnxhUCJz2Dk1z7Gf7rk

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

 隐藏分组的叶子节点的第一个节点

### 😊 Expected Behavior / 期望行为

不显示空白

### 😅 Current Behavior / 当前行为

会显示空白

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by lijinke666** [comment]
开启序号列导致的, 看起来是和多级列头有点兼容问题, 可以先临时关闭, 近期排查下, 感兴趣也可以 PR.

```ts
seriesNumber: {
  enable: false
}
```
