### ISSUE TITLE
透视表树模式自定义行头单元格是否支持自定义react组件

### ISSUE THREAD

**Issue by ggcfcmd** [antvis/S2#3045]
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    |
| @antv/s2-react |  1.54.7  |
| @antv/s2-react-components   |  1.46.4  |

### 💻 Sheet Type / 表格类型

- [X] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

你好 透视表树模式下如果在企业微信场景需要将部门名称做企微转译  通过企微接口获取转译后的数据不一定完全准确 所以想通过组件的方式渲染部门名称 目前组件对企微组件（<ww-open-data>）应该是不支持的 是否有其他可行方案？（可以排除是数据本身的问题）

### ⌨️ Code Snapshots / 代码片段

![image](https://github.com/user-attachments/assets/f0ac6224-a0ea-4284-a630-e31c38e650fc)

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

见代码片段截图

### 😊 Expected Behavior / 期望行为

希望在自定义行头中可以传递组件

### 💻 OS / 操作系统

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by lijinke666** [comment]
不支持自定义 react 组件, 没有什么可行方案.

这种场景更适合 DOM 表格, 而不是 Canvas, 唯一的可能就是在行头单元格上方绝对定位一个 div, 用于渲染 React 组件, 需要考虑滚动/折叠展开/拖拽 各种场景的 div 宽高坐标同步, 文本省略, 成本太高. 

类似于[编辑表格](https://github.com/antvis/S2/blob/9c259c52e413c3a89ec49011ea484aa3c4463713/packages/s2-react/src/components/sheets/editable-sheet/index.tsx#L7-L21)的处理

![image](https://github.com/user-attachments/assets/12202ebc-f056-4948-8ccd-b76cf16d9565)

**Comment by ggcfcmd** [comment]
> 不支持自定义 react 组件, 没有什么可行方案.
> 
> 这种场景更适合 DOM 表格, 而不是 Canvas, 唯一的可能就是在行头单元格上方绝对定位一个 div, 用于渲染 React 组件, 需要考虑滚动/折叠展开/拖拽 各种场景的 div 宽高坐标同步, 文本省略, 成本太高.
> 
> 类似于[编辑表格](https://github.com/antvis/S2/blob/9c259c52e413c3a89ec49011ea484aa3c4463713/packages/s2-react/src/components/sheets/editable-sheet/index.tsx#L7-L21)的处理
> 
> ![image](https://private-user-images.githubusercontent.com/21015895/397204998-12202ebc-f056-4948-8ccd-b76cf16d9565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1ODUyNTEsIm5iZiI6MTczNDU4NDk1MSwicGF0aCI6Ii8yMTAxNTg5NS8zOTcyMDQ5OTgtMTIyMDJlYmMtZjA1Ni00OTQ4LThjY2QtYjc2Y2YxNmQ5NTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA1MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNjAzODBlOGIxNTBlZDBhZDkyOGE5YTMyMmRiZjU4NDliOGUwN2Y5YmQwNzY4MDk0MGFhN2E4ZGI2ZWY4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uT1okIZ2JczvlF-2OzaMi_1Q6Qu8bmxBEMhEPxaGQiA)

了解 感谢回复
