### ISSUE TITLE
1.x版本明细表固定列之后合并单元格实效

### ISSUE THREAD

**Issue by sl6-k** [antvis/S2#3047]
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.x |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

固定列和合并单元格发生了冲突

### ⌨️ Code Snapshots / 代码片段

import { TableSheet } from "@antv/s2";

fetch("https://assets.antv.antgroup.com/s2/basic-table-mode.json")
  .then((res) => res.json())
  .then((data) => {
    const container = document.getElementById("container");
    const s2DataConfig = {
      fields: {
        columns: ["province", "city", "type", "price", "cost"],
      },
      meta: [
        {
          field: "province",
          name: "省份",
        },
        {
          field: "city",
          name: "城市",
        },
        {
          field: "type",
          name: "商品类别",
        },
        {
          field: "price",
          name: "价格",
        },
        {
          field: "cost",
          name: "成本",
        },
      ],
      data,
    };

    const s2Options = {
      width: 600,
      height: 480,
      showSeriesNumber: true,
      frozenColCount: 2,
      mergedCellsInfo: [
        [
          { colIndex: 1, rowIndex: 0, showText: true },
          { colIndex: 1, rowIndex: 1 },
          { colIndex: 1, rowIndex: 2 },
          { colIndex: 1, rowIndex: 3 },
        ],
      ],
    };

    const s2 = new TableSheet(container, s2DataConfig, s2Options);

    s2.render();
  });

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

![image](https://github.com/user-attachments/assets/38910700-80d8-4180-85ad-1628d7c334e8)
![image](https://github.com/user-attachments/assets/bf0d4a95-d4f2-4499-86d0-223ab72f37b0)

### 😊 Expected Behavior / 期望行为

希望在固定列的时候可以合并固定列的单元格

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by lijinke666** [comment]
不支持组合使用.
