### ISSUE TITLE
🐛合并单元格在滚动后出现异常（最新版本会复现）

### ISSUE THREAD

**Issue by wyh888** [antvis/S2#3048]
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  v2.1.4  |
| @antv/s2-react | v2.1.3    |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

设置合并单元格生效后，滚动表格，再滚动回合并单元格的位置，发现合并的样式出现异常且不可预计

可查看原 issue [https://github.com/antvis/S2/issues/3032](https://github.com/antvis/S2/issues/3032)

![file](https://github.com/user-attachments/assets/d4577022-2685-46dc-b816-d18aec637fa7)

### ⌨️ Code Snapshots / 代码片段

```
const s2Options: S2Options = {
      width: 600,
      height: 280,
      mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
    };
```

### 🔗 Reproduction link / 复现链接

https://s2.antv.antgroup.com/examples/basic/table/#table

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

拉取最新的代码v2.1.4依然是复现的，并且官网demo也是一样的bug，需要滚动可以复现

复现案例：
1. 官网地址：https://s2.antv.antgroup.com/examples/basic/table/#table，代码参考 issue 内容
2. 拉取最新代码本地运行，复现如图：

![1](https://github.com/user-attachments/assets/5efeb836-f5ae-4b0a-98b4-4bdb349359c3)

按照下述代码修改一下 100w 数据的demo，反复滚动可出现：

```
const s2Options: SheetComponentOptions = {
  height: 480,
  mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
  interaction: {
    scrollSpeedRatio: {
      vertical: 1,
      horizontal: 1,
    },
  },
  transformCanvasConfig(renderer) {
    renderer.setConfig({
      enableCulling: true,
    });
  },
};

const s2DataConfig: S2DataConfig = {
  fields: {
    // rows: [],
    columns: ['type', 'subType', 'province', 'city', 'number'],
    // values: ['number'],
  },
  data: generateRawData(
    { province: 1, city: 10 },
    { type: 10, subType: 10 },
  ),
};

// sheetType 也改成 table
```

### 😊 Expected Behavior / 期望行为

滚动后合并单元格显示正常

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by lijinke666** [comment]
将合并单元格滚动出可视范围后可以复现

**Comment by zjs307065909** [comment]
合并的单元格里面的内容 跟不合并的单元格内容 好像差了几个像素 对不齐
![微信截图_20241220135837](https://github.com/user-attachments/assets/75f49304-87dd-41c5-8515-1c643259c0ae)
