### ISSUE TITLE
💄 明细表行列头冻结样式优化

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#308]
### 🏷 Version
v 0.1.6
### 🖋 Description

明细表行列头冻结分割线可以增加类似透视表行头冻结外阴影
![image](https://user-images.githubusercontent.com/10885578/133760322-605d4107-6666-4de4-95cd-0d53493e60d4.png)

**Comment by zxc0328** [comment]
closeed by https://github.com/antvis/S2/pull/610
