### ISSUE TITLE
feat: ✨ 官网建设计划

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#311]
# 前言
目前官网的基础框架已经ready，等待大家的内容填充！～
文档和 demo 的编写说明详情见 https://github.com/antvis/S2/blob/master/s2-site/README.md
文档教程部分可以从原来的文档库语雀导出为 markdown 根据网站效果进行格式调整，多多参考 AntV 其他各站点官网文档。

注：文档相关负责人同时需要补齐对应代码注释。

参考格式：

```ts
/**
 * 简单功能描述
 * @param 
 * @return
 */

```

# 目录结构
> 大致层级结构如下，具体命名和分层粒度由内容作者自行决定

* 教程
  * 简介 
  * 快速上手 
  * 基础教程
    * 基本概念 
    * 表形态
      * 透视表
      * 明细表
    * 字段标记
    * 小计总计
    * 排序 
    * tooltip
    * 复制导出 
    * 维度下钻 
    * 主题设置 
    * 分析组件
  * 进阶教程
    * 数据处理
       * 透视表
       * 明细表
    * 布局
       * 透视表
       * 明细表
    * 自定义Hook（四种hook的实际使用案例）
    * 自定义单元格绘制
    * 自定义目录树
    * 交互
    * 性能介绍 

---------------------------------------------------------------------

* API
   * SpreadSheet (待定)
   * 通用配置项
     * S2DataConfig
     * S2Options
     * S2Theme 
   * 分析组件
     * SheetComponent
     * DimensionSwitchModal
     * DrillDown
     * Export
     * Header
   * [绘图属性](https://g2plot.antv.vision/zh/docs/api/graphic-style)

---------------------------------------------------------------------

* 图表示例
  * 基础透视表
    * 树状
    * 平铺
  * 基础明细表
  * 字段标记
    * 文本
    * 颜色条
    * 背景
    * 图标
  * tooltip
    * 基础 tooltip
    * 自定义 tooltip
  * 小计总计
  * 自定义排序
    * 透视表
    * 明细表
  * 交互
     * 基础交互
     * 自定义交互
     * 明细表行列头冻结
     * 单元格合并
  * 主题
    * 内置主题
    * 自定义主题  
  * 维度下钻 
  * 自定义Hook
  * 自定义目录树
  * 分析组件
    * 表组件
       * 透视表
       * 明细表
       * 网格分析表
    * 维度切换组件
    * 表头组件
    * 下钻组件
    * 导出组件

---------------------------------------------------------------------

# 任务分工

- 未开始：⚠️
- 进行中：♻️
- 待验收：🚀
- 完成验收：✨

> 负责人： @xingwanying 
状态：♻️

- [x] 教程-简介
- [x] 教程-快速上手
- [ ] 教程-基础教程-维度下钻
- [x] 教程-基础教程-主题设置
- [ ] 教程-基础教程-分析组件
- [x] API-通用配置项-S2DataConfig
- [x] API-通用配置项-S2Options
- [x] API-通用配置项-S2Theme
- [x] API-通用配置项-SheetComponent
- [x] API-分析组件- DrillDown
- [x] 图表示列-基础透视表-树状
- [x] 图表示列-基础透视表-平铺
- [x] 图表示列-主题-内置义主题
- [x] 图表示列-主题-自定义主题
- [x] 图表示列-分析组件-表组件-网格分析表
- [x] 图表示列-分析组件-表组件-表头组件
- [x] 图表示列- 维度下钻
- [x] 图表示列-分析组件-表组件-下钻组件

> 负责人： @qubaomingg  
状态：♻️

- [x] 教程-基础教程-基本概念
- [x] 教程-基础教程-表形态-透视表
- [x] 教程-进阶教程-数据流处理-透视表
- [ ] 教程-进阶教程-布局-透视表
- [ ] 教程-进阶教程-自定义Hook（四种hook的实际使用案例）                    
- [ ] 教程-进阶教程-自定义目录树
- [x] 教程-进阶教程-性能介绍
- [ ] 图表示列-自定义Hook
- [ ] 图表示列-自定义目录树

> 负责人： @lijinke666 
状态：♻️

- [x] 教程-进阶教程-交互
- [x] 图表示列-交互-基础交互
- [x] 图表示列-交互-自定义交互
- [x] 图表示列-分析组件-表组件-透视表

> 负责人： @wjgogogo 
状态：♻️

- [x] 教程-基础教程-字段标记
- [x] 教程-基础教程-分析组件
- [x] API-分析组件-DimensionSwitchModal
- [ ] 教程-进阶教程-自定义单元格绘制
- [x] 图表示列-字段标记-文本
- [x] 图表示列-字段标记-颜色条
- [x] 图表示列-字段标记-背景
- [x] 图表示列-字段标记-图标
- [x] 图表示列-分析组件-表组件-维度切换组件
- [x] 绘图属性

> 负责人： @yangzhanmei 
状态：♻️

- [x] 教程-基础教程-小计总计
- [x] 教程-基础教程-排序
- [x] 教程-基础教程-tooltip
- [x] 图表示列-tooltip-基础tooltip
- [x] 图表示列-tooltip-自定义tooltip
- [x] 图表示列-tooltip-小计总计
- [x] 图表示列-自定义排序-透视表

> 负责人： @zxc0328 
状态：⚠️

- [x] 教程-基础教程-表形态-明细表
- [ ] 教程-进阶教程-数据流处理-明细表
- [ ] 教程-进阶教程-布局-明细表
- [ ] 图表示列-基础明细表
- [ ] 图表示列-交互-明细表行列头冻结
- [ ] 图表示列-分析组件-表组件-明细表

> 负责人： @YardWill 
状态：⚠️

- [x] 教程-基础教程-复制导出
- [x] API-分析组件-Export
- [x] 图表示列-自定义排序-明细表
- [x] 图表示列-分析组件-表组件-导出组件

> 负责人：@stone-lyl
状态：⚠️

- [x] 官网首页
- [ ] 图表示列-交互-单元格合并
- [x] API-分析组件- Header

**Comment by lijinke666** [comment]
![image](https://user-images.githubusercontent.com/21015895/133928892-0a3451d8-5f05-427a-8023-83479c3e2cc4.png)
这个是不是艾特错人了

**Comment by yuzhanglong** [comment]
> ![image](https://user-images.githubusercontent.com/21015895/133928892-0a3451d8-5f05-427a-8023-83479c3e2cc4.png)
> 这个是不是艾特错人了

感觉是的，因为我根本没用过S2😄

**Comment by xingwanying** [comment]
> > ![image](https://user-images.githubusercontent.com/21015895/133928892-0a3451d8-5f05-427a-8023-83479c3e2cc4.png)
> > 这个是不是艾特错人了
> 
> 感觉是的，因为我根本没用过S2😄

dbq🧎‍♀️
