### ISSUE TITLE
🐛单元格点击事件响应行为不准确

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#315]
### 🖋 Description
1. 使用onColCellClick覆盖tooltip时 会经常出现原生tooltip，不是最后一列（？）的指标上容易出现
![image](https://user-images.githubusercontent.com/15276351/133881135-9084a10f-12f2-4ecd-92cb-56d378e695c7.png)

2. 单元格的刷选操作判定
正常点击还是比较容易触发刷选，出现合计tooltip，是否可以加个移动距离校验
![image](https://user-images.githubusercontent.com/15276351/133881320-c1ebfc26-163b-4d9e-a0ae-9bfa693004a7.png)

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/3ee3b8e8

**Comment by lijinke666** [comment]
> 单元格的刷选操作判定
正常点击还是比较容易触发刷选，出现合计tooltip，是否可以加个移动距离校验

可以加一个
