### ISSUE TITLE
🙏 角头宽度优化

### ISSUE THREAD

**Issue by BBSQQ** [antvis/S2#375]
### 🖋 Description
如下图，明明表格宽度默认那么宽，但是角却要换行

### 🏞 What problem does this feature solve
![image](https://user-images.githubusercontent.com/35586469/135012856-c969ddd8-f566-4432-9f89-531e8e0b31ef.png)

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
这个宽度是默认配置的，你们可以在 `options` 里修改 `treeRowsWidth` 调整

**Comment by xingwanying** [comment]
@wjgogogo 大佬看下这部分代码层面可有优化空间，没有就关掉保持现状好了

**Comment by BBSQQ** [comment]
> 这个宽度是默认配置的，你们可以在 `options` 里修改 `treeRowsWidth` 调整 @BBSQQ

就是，虽然开放配置，但是可以默认好看啊

**Comment by xingwanying** [comment]
> > 这个宽度是默认配置的，你们可以在 `options` 里修改 `treeRowsWidth` 调整 @BBSQQ
> 
> 就是，虽然开放配置，但是可以默认好看啊

等 @wjgogogo 大佬诊断看看
