### ISSUE TITLE
🐛大数据量表格形态切换明显卡顿

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#388]
### 🖋 Description
测试数据
![image](https://user-images.githubusercontent.com/15276351/135204922-2efb5e97-6b21-42a7-b1e5-74d8dc65702b.png)

s2切平铺/树形 buildRowTreeHierarchy  耗时
![image](https://user-images.githubusercontent.com/15276351/135204954-4215469e-1778-497a-a27d-70029eb32251.png)

旧版明细切树形耗时
![image](https://user-images.githubusercontent.com/15276351/135205061-abb753d2-0a30-48c5-a25c-a17fac08e6d1.png)

**Comment by qubaomingg** [comment]
不只是树状，所有涉及到 Node 结构的都会慢5倍。
