### ISSUE TITLE
🙏 明细表和透视表排序交互统一

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#393]
### 🖋 Description
目前透视表排序交互：

![image](https://user-images.githubusercontent.com/10885578/135379288-8b5fbc7a-74b2-46c9-b6ed-c0cf72234c3b.png)

明细表排序交互：

![image](https://user-images.githubusercontent.com/10885578/135379346-e87dca69-e57c-43a8-ace3-37507f3fc8b0.png)

### 🏞 What problem does this feature solve

1. 从一致性来说期望二者交互一致，都为点击icon出tooltip的方式进行排序
2. 明细表目前的排序交互无法取消排序

**Comment by zxc0328** [comment]
fixed in https://github.com/antvis/S2/pull/763
