### ISSUE TITLE
🐛子维度切换展开功能失效

### ISSUE THREAD

**Issue by ArranZeyuWang** [antvis/S2#419]
### 🖋 Description
官网[demo](https://s2-preview-pr-411.surge.sh/zh/examples/analysis/switcher#pivot-with-children)子维度展开功能失效，点击后数据不发生变化，再次打开自动恢复原样。
![image](https://user-images.githubusercontent.com/31071085/136693860-e84719e2-b6c4-4dc8-9a61-288efdf8baf4.png)
关闭⬆️
![image](https://user-images.githubusercontent.com/31071085/136693870-6a3f2363-74db-4ded-bf66-d12578e89ab4.png)
关闭后⬆️
![image](https://user-images.githubusercontent.com/31071085/136693875-92a8b6a3-a1ab-4eb3-979d-f102e376fe75.png)
再次打开⬆️

**Comment by wjgogogo** [comment]
@ArranZeyuWang 经确认，是理解上有所偏差，不是bug。感谢反馈😀
