### ISSUE TITLE
🐛  Cell 边框渲染遮挡问题

### ISSUE THREAD

**Issue by zxc0328** [antvis/S2#426]
### 🏷 Version

0.1.14

### 🖋 Description

Cell 的 Border 渲染出来粗细不一，lineWidth 设置为 2px 的时候就很明显了。

![image](https://user-images.githubusercontent.com/10339692/136751819-a8a8cf44-c9b9-4e8e-88b9-bac988a71b6f.png)

在把渲染线的位置减去 lineWidth / 2 之后这个现象就消失了。所以这里渲染粗细不一的原因应该是边框渲染在底部，有一半是在 Cell 的 Rect 外的。所以 Cell 直接会相互遮挡，导致边框粗细不一。解决办法就是把 Border 完全渲染在 Rect 内，同时在 Cell 的渲染时，计算可用高度时减去边框的 lineWidth，类似 CSS 盒子模型。

**Comment by serializedowen** [comment]
![image](https://user-images.githubusercontent.com/9219215/141958217-65e28a2e-4756-49f1-b49e-f2e564d436ab.png)
目前border仅渲染右侧和底部，导致靠近左侧和顶部的cell边框不完整

**Comment by xingwanying** [comment]
是否可以考虑针对dataCell区域，在frame层整体画网格？且能减少绘制描边次数。参考现在的横纵分割部分？

**Comment by wukai7777777** [comment]
https://github.com/antvis/S2/issues/1645
@xingwanying 这是不是类似问题？
