### ISSUE TITLE
🐛调用copyData报错

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#446]
### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/7bd85d05

**Comment by xingwanying** [comment]
![image](https://user-images.githubusercontent.com/10885578/137279276-edd2bedf-5f8a-4f14-b77b-8ebf51e8f046.png)
这个demo的shu数据有问题，新版本应该已经修复了，再check下呢？

**Comment by YardWill** [comment]
正在修复
