### ISSUE TITLE
🐛 树状表格没有 values 的空白策略

### ISSUE THREAD

**Issue by BBSQQ** [antvis/S2#451]
### 🏷 Version
^0.2.0

### 🖋 Description

原版效果
![image](https://user-images.githubusercontent.com/35586469/137236869-8f6215e9-8418-4b38-93c4-e9209b8b0526.png)

当前版本
![image](https://user-images.githubusercontent.com/35586469/137236917-4df1c0f2-34a1-4473-bd90-22e027f00e28.png)

**Comment by xingwanying** [comment]
如果连values都为空，显示不出来确实符合预期？显示出来了反而奇怪了是不是🤔
