### ISSUE TITLE
🐛 树状下钻之后取消下钻，下钻 icon hover 不出来

### ISSUE THREAD

**Issue by BBSQQ** [antvis/S2#452]
### 🖋 Description
如题
![image](https://user-images.githubusercontent.com/35586469/137253906-2cc39af4-dcad-4b77-be90-5095f96014ed.png)

**Comment by xingwanying** [comment]
> @xingwanying 可找我复现

当前为选中态，再点击下取消选中态可以出来，交互冲突了，需要优化下
