### ISSUE TITLE
🐛单指标单数据点不能正常展示

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#460]
### 🖋 Description
1. riddle上是显示空白

2. 项目中使用出现报错：
![image](https://user-images.githubusercontent.com/15276351/137425735-524709a0-6dbf-41f4-ab40-99d59d82330f.png)
位置是
![image](https://user-images.githubusercontent.com/15276351/137426080-fddd59e8-c9ee-4189-9b49-654b3d3b0676.png)

麻烦两种情况都看下～
### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/e739eb5a

**Comment by zxc0328** [comment]
明细表的列是放在 columns 中的吧

fields: {
      columns: ['D2021012600161505000001296968_sum'],
      rows: [],
      values: [],
      valuesInCols: true
},

这样就好了。

如果有需求需要 table 模式兼容 values 和 valuesInCols 的话，我们也可以加上。
