### ISSUE TITLE
🙏tooltip会跑出容器外

### ISSUE THREAD

**Issue by bigZhang131** [antvis/S2#487]
### 🖋 Description
![image](https://user-images.githubusercontent.com/87478398/137713393-6e51bcb9-365b-47fa-a85f-edee71f3b528.png)

这个高亮会超出表格，在底部时需要显示在top
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by Esorakouki** [comment]
或者鼠标移出表后 表本身应该去除高亮状态？
