### ISSUE TITLE
🐛 排序逻辑优化

### ISSUE THREAD

**Issue by xingwanying** [antvis/S2#544]
### 🏷 Version
v0.2.4
### 🖋 Description
![image](https://user-images.githubusercontent.com/10885578/138625612-877a5516-5f19-45df-9706-c0f4d14314b2.png)

这部分的逻辑使用Set直接add当前维值会导致不同层级下维值相同的情况下值被覆盖，例如当数据为如下结构时：
![image](https://user-images.githubusercontent.com/10885578/138625812-0f968d15-85c2-49a5-9b3a-9c1e717718e6.png)
sortedDimensionValues 为如下结构：
![image](https://user-images.githubusercontent.com/10885578/138625936-2c535a92-056d-45ec-bbc5-35538a5002d4.png)

缺失了'物美'下面的'张三'

修改建议： 需要存维值信息时存入层级信息保证唯一性，消费处需要对应进行解析。

**Comment by yangzhanmei** [comment]
#655
