### ISSUE TITLE
🙏单行数据的小记行单独显示

### ISSUE THREAD

**Issue by ArranZeyuWang** [antvis/S2#550]
### 🖋 Description
为单行数据的小记行提供单独显示功能

### 🏞 What problem does this feature solve
目前对单行数据不显示小记：
![image](https://user-images.githubusercontent.com/31071085/138651804-b5a41d70-6290-4db0-88e0-fb714e2b8bcf.png)

期望的状态：
![image](https://user-images.githubusercontent.com/31071085/138651703-abeb337c-7795-4914-912e-7e202796230b.png)

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by xingwanying** [comment]
ref: 
https://github.com/antvis/S2/pull/1086
https://github.com/antvis/S2/pull/1111
