### ISSUE TITLE
🐛 S2  CDN 使用异常

### ISSUE THREAD

**Issue by lxfu1** [antvis/S2#605]
### 🏷 Version

0.2.5

### 🖋 Description

CDN 方式使用时，全局 S2 上没有挂载相关组件，例如 PivotSheet。

`<script src="https://unpkg.com/@antv/g2@latest/dist/g2.min.js"></script>`

![image](https://user-images.githubusercontent.com/31396322/139812577-e69a32a6-8d4c-4a7a-a513-b125e7d95e75.png)

**Comment by lijinke666** [comment]
@lxfu1 使用 1.0.0-beta.5 呢?

**Comment by qubaomingg** [comment]
我领了
