### ISSUE TITLE
🐛 SheetComponent adaptive={true} 初次渲染未自适应

### ISSUE THREAD

**Issue by neoddish** [antvis/S2#609]
### 🏷 Version
0.2.5
### 🖋 Description
SheetComponent 组件设置 adaptive 后展示异常。
### 🖥 Steps to Reproduce
```js
const ShowTable = (data, { height, width }) => {
  const s2DataConfig = { fields: { columns: Object.keys(data[0]) }, data };
  const s2options = { width, height };

  return (
    <SheetComponent
      dataCfg={s2DataConfig}
      options={s2options}
      sheetType="table"
      themeCfg={{ name: 'simple' }}
      adaptive={true}
    />
  );
};
```

```js
      <div style={{ height: '300px', overflowY: 'scroll', border: '2px solid #eee', padding: '20px' }}>
        {ShowTable(data, { height: 300, width: 300 })}
      </div>
```

### 😊 Expected Behavior
宽度撑满父容器
### 😅 Current Behavior
![lQLPDhrU1_nU1BjNBCLNBliwCi3nPSTdH-8BifdBQcBBAA_1624_1058 png_720x720g](https://user-images.githubusercontent.com/6898060/139902694-f58a3fc9-4bda-4dd1-85ce-e9d6b4646dc3.jpg)

不设 adaptive 还好：
![lALPJwKtwvEzA0fNA9jNBj4_1598_984 png_720x720g](https://user-images.githubusercontent.com/6898060/139903389-2ca88177-10c1-40cc-9598-119880470abc.jpg)

### 💻 System information

另外，设了 adaptive 是不是可以不用必选 s2options 里的 height 和 width 了?

**Comment by neoddish** [comment]
又测试了一下，手动变化浏览器大小导致重新渲染以后可以生效。但也不是100%生效。

**Comment by lijinke666** [comment]
感动, 第一次有人完整按照 issue 模板提问

**Comment by lijinke666** [comment]
目前的设计是 开启 `adaptive` 后是在 窗口大小发生改变后 才会触发自适应

**Comment by neoddish** [comment]
坐等更新~
