### ISSUE TITLE
🐛明细表自定义icon位置错误

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#675]
### 🏷 Version
1.0.0-beta.8
### 🖋 Description
beta.7
![image](https://user-images.githubusercontent.com/15276351/141259272-8d46562e-a6da-4352-aab1-7eafda6d2b98.png)
beta.8
![image](https://user-images.githubusercontent.com/15276351/141259346-9261b87a-2e15-442c-b18f-853b89f3a75f.png)

**Comment by Chasen-Zhang** [comment]
@Esorakouki 怎么右对齐呢？
