### ISSUE TITLE
🐛明细表切换分页后显示内容有错位

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#686]
### 🏷 Version
1.0.0-beta.8
### 🖋 Description
初始分页大小为30条
![image](https://user-images.githubusercontent.com/15276351/141298396-0cb1d5f5-c2c3-447a-aef2-3ff8c65af456.png)

调整至10条后 会有一个偏移 同上面切换前的偏移量

![image](https://user-images.githubusercontent.com/15276351/141298544-9b3f15de-f893-4e13-9db3-4381a94e5f43.png)

**Comment by xingwanying** [comment]
目前的分页其实就是定位到对应滚动位置呢👀，这里希望的效果是什么呢？可以把 `showSeriesNumber` 配置项打开看下滚动是否符合预期呢
