### ISSUE TITLE
🐛明细表内容不满高度时分页组件不紧贴

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#692]
### 🏷 Version
1.0.0-beta7
### 🖋 Description
![image](https://user-images.githubusercontent.com/15276351/141403474-eb8b37e2-050e-4777-b508-c7f0bc16463a.png)

**Comment by lijinke666** [comment]
canvas 实际渲染高度 比 配置的高度 小

**Comment by zxc0328** [comment]
在分页切换时，需要手动重置一下表格的高度，可以监听一下这个事件 S2Event.LAYOUT_PAGINATION。不然表格本身的高度是不会变的，显示的内容少了（从 50 页/条 切到 10 页/条）的话，就会底下空出来一点。

**Comment by lijinke666** [comment]
> 在分页切换时，需要手动重置一下表格的高度，可以监听一下这个事件 S2Event.LAYOUT_PAGINATION。不然表格本身的高度是不会变的，显示的内容少了（从 50 页/条 切到 10 页/条）的话，就会底下空出来一点。

感觉这个逻辑我们内置是不是要好一点? 不然用户使用成本有点高

**Comment by zxc0328** [comment]
但我们其实不知道用户想要多少的高度。如果直接帮他改掉的话，可能不符合他的预期。可能有些用户就是希望他配置多少高度，就永远是多少高度。

**Comment by lijinke666** [comment]
有道理, 赞同

**Comment by lijinke666** [comment]
cc @Esorakouki
