### ISSUE TITLE
🤔源码 import 使用了 `paths` 别名替换，是不是不妥？

### ISSUE THREAD

**Issue by susiwen8** [antvis/S2#700]
### 🖋 Description
源码中出现很多 `import { *** } from '@/**'  `, 但一般第三方库的开发是最好不要用 `alias` 别名替换，可能导致使用者构建解析失败。
莫非是用了什么方法解决这个问题了吗？

**Comment by zxc0328** [comment]
可以参考下我们的打包配置 https://github.com/antvis/S2/blob/master/packages/s2-core/rollup.config.js。在编译出来的代码和类型定义里是没有别名的。
