### ISSUE TITLE
🐛 行列头冻结数量超过columns数量时页面卡死

### ISSUE THREAD

**Issue by wjgogogo** [antvis/S2#714]
### 🏷 Version
1.0.0-beta.9

### 🖋 Description
columns只有4个，此时将`frozenTrailingColCount `不断增加，达到4时页面卡死

![2021-11-16 15 22 57](https://user-images.githubusercontent.com/17964556/141939408-ca403961-1205-4d18-a5bb-5b3e7df2cc6f.gif)

**Comment by lijinke666** [comment]
fixed: #933
