### ISSUE TITLE
🤔在父级元素使用了transform: scale后,导致鼠标移至图表上鼠标位置不正确

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#794]
### 🖋 Description
在父级元素使用了transform: scale后,导致鼠标移至图表上不能正确响应鼠标事件

**Comment by cylnet** [comment]
![image](https://user-images.githubusercontent.com/24189636/142977983-3dea4932-cf7e-481f-8327-16f1b528ca25.png)

**Comment by lijinke666** [comment]
为什么需要在父元素缩放呢? 场景是什么?

**Comment by cylnet** [comment]
大屏自适应，父级会有transform: scale

> 为什么需要在父元素缩放呢? 场景是什么?

**Comment by cylnet** [comment]
> 大屏自适应，父级会有transform: scale
> 
> > 为什么需要在父元素缩放呢? 场景是什么?

拖拽的页面布局

**Comment by xingwanying** [comment]
> > 大屏自适应，父级会有transform: scale
> > > 为什么需要在父元素缩放呢? 场景是什么?
> 
> 拖拽的页面布局

那是不是可以直接根据终态的父元素宽高去 update 表格宽高？

**Comment by lijinke666** [comment]
图表基于 canvas 绘制的, 目前还做不到父元素缩放或旋转等同时同步鼠标坐标, 如果需要自适应, 有两种方式

react 组件层: 可以使用 react 组件 提供的 `adaptive` 根据父容器自适应

```tsx
import { SheetComponent } from '@antv/s2-react'

<SheetComponent adaptive/>
```

基础类: 可以拿到表格实例, 自行监听 窗口 resize 改变表格大小

```ts
import { PivotSheet } from '@antv/s2'
const s2 = new PivotSheet(...)

s2.changeSize(width, height)
```

react 组件:

**Comment by lijinke666** [comment]
后面我们会完善下文档, 提供相关示例

**Comment by cylnet** [comment]
> 后面我们会完善下文档, 提供相关示例

我先试试s2.changeSize(width, height) 这个方法，感谢

**Comment by xiaochong44** [comment]
@lijinke666 G2不也是canvas，以前也有这个bug，后面增加个supportCSSTransform的属性解决了这个bug
