### ISSUE TITLE
在父级元素使用了transform: scale后,导致鼠标移至图表上位置不正确解决方案，有需要朋友参考

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#808]
vue使用 
例如：transform: scale(0.8)
```
<div id="table" :style="`transform: scale(${zoom});transform-origin: 0 0 0`"></div>
let s2 = new PivotSheet(table, s2DataConfig, s2options)
this.zoom = 1 / 0.8
s2.changeSize(width * 0.8, height * 0.8)
```

**Comment by cylnet** [comment]
<div :id="table" :style="`transform: scale(${zoom});transform-origin: 0 0 0`"></div>

**Comment by cylnet** [comment]
`<div id="table" :style="`transform: scale(${zoom});transform-origin: 0 0 0`"></div>`

**Comment by lijinke666** [comment]
感谢反馈, 我们后面把这个加到官网的常见问题里面 😁

**Comment by xingwanying** [comment]
https://s2.antv.vision/zh/docs/manual/faq/#%E7%88%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E4%BD%BF%E7%94%A8%E4%BA%86-code-classlanguage-texttransform-scalecode-%E5%90%8E-%E5%9B%BE%E8%A1%A8%E9%BC%A0%E6%A0%87%E5%9D%90%E6%A0%87%E5%93%8D%E5%BA%94%E4%B8%8D%E6%AD%A3%E7%A1%AE

感谢大佬～
![image](https://user-images.githubusercontent.com/10885578/143206014-b619d1e6-edb1-45c6-b34b-07e1bfea77b9.png)
