### ISSUE TITLE
🐛table 切至grid或者tree 卡顿时间过长

### ISSUE THREAD

**Issue by Esorakouki** [antvis/S2#812]
### 🏷 Version
1.0.0-beta.7、1.0.3
### 🖋 Description
10000条数据下  4指标 2维度
grid、tree之间切换约4s
table 切至 grid或者tree 会卡顿15s左右

### 🔗 Reproduce Link
（内部链接  DM）

**Comment by lijinke666** [comment]
麻烦 @qubaomingg 大佬看一下

**Comment by Esorakouki** [comment]
发现是使用不合理的问题！打扰了！
