### ISSUE TITLE
🙏在交叉表里面需要支持单击右键弹出自定义弹框

### ISSUE THREAD

**Issue by mlf75** [antvis/S2#820]
### 🖋 Description

![image](https://user-images.githubusercontent.com/9053195/143215531-b38343d0-ebb1-468d-9353-e21bbee9b88a.png)

如上图，需要在用户手动框选单元格后右键单击触发自定义弹框出现

希望能支持 onContextMenu 这个事件

### 🧐 Suggest the API
|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by YardWill** [comment]
onContextMenu 事件有暴露的

**Comment by lijinke666** [comment]
@mlf75 你好, 表格是支持 `onContextMenu`

请参考这篇文章: https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E5%85%A8%E5%B1%80

![image](https://user-images.githubusercontent.com/21015895/144584860-75cc03c6-19ea-4ab6-9db6-78c87023e010.png)
![image](https://user-images.githubusercontent.com/21015895/144584907-79da30bc-b610-4a00-99e0-7d886cf7d286.png)

**Comment by lijinke666** [comment]
如果是使用的 react 版本, 监听 `onContextMenu`

```
<SheetComponent onContextMenu={...}/>
```
