### ISSUE TITLE
🙏行头or 列头支持自定义icon，icon希望支持hover事件

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#821]
### 🖋 Description
行头or 列头支持自定义icon，icon希望支持hover事件，目前只支持click事件

### 🏞 What problem does this feature solve
交叉表里面行头列头的部分字段需要给用户解释说明一下，解释说明的icon一般是hover触发提示tooltip🙏🙏

**Comment by xingwanying** [comment]
原生可以监听 S2Event.GLOBAL_ACTION_ICON_HOVER事件，react 组件可以使用 onActionIconHover 回调函数

```ts
  <SheetComponent dataCfg={dataCfg} options={s2Options} onActionIconHover={(data) => {console.log(data)}} />,
```

https://s2.antv.vision/en/docs/api/components/sheet-component#sortfuncparam
