### ISSUE TITLE
🐛 tooltip 配置无效

### ISSUE THREAD

**Issue by WeiShengv99** [antvis/S2#848]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -     1.1.2    |
| @antv/s2-react | -     1.1.1    |

### 🖋 Description
tooltip配置无效

### ⌨️ Code Snapshots

![image](https://user-images.githubusercontent.com/35689628/144166579-fa105429-118f-4cdf-8d1a-58f24800e1cf.png)

### 🔗 Reproduce Link

https://codesandbox.io/s/cool-kirch-qs5vk?file=/src/App.tsx

### 🤔 Steps to Reproduce

点击展示 tooltips

### 😊 Expected Behavior

展示自定义 tooltips

### 😅 Current Behavior

配置不生效

### 💻 System information

chrome  96.0.4664.55

**Comment by lijinke666** [comment]
你好, @WeiShengv99 最新版本 tooltip 有一点修改, 自定义通过  `content` 透出, 即 `tooltipComponent` 修改成 `content` 即可

```diff
const s2Options = {
  tooltip: {
-   tooltipComponent: ""
+   content: ""
  }
}
```

```diff
const s2 = new PivotSheet()

- s2.showTooltip({ element: "" })
+ s2.showTooltip({ content: "" })
- s2.tooltip.show({ element: "" })
+ s2.tooltip.show({ content: "" })
```

**Comment by lijinke666** [comment]
给提issue的方式点赞, 终于有一个是按照模板填写的了 👍🏻

**Comment by WeiShengv99** [comment]
@lijinke666  
非常感谢你的回复
顺便问一下 ， tooltips 目前支持  hover 事件触发展示吗，没有找到相关的文档。

**Comment by xingwanying** [comment]
> @lijinke666 非常感谢你的回复 顺便问一下 ， tooltips 目前支持 hover 事件触发展示吗，没有找到相关的文档。

目前还没有自定义hover方式的透出，关注下这个 issue，https://github.com/antvis/S2/issues/821
