### ISSUE TITLE
🐛   单元格 默认点击展示tooltips行为异常 / 框选功能 / 右键/选择单元格 

### ISSUE THREAD

**Issue by WeiShengv99** [antvis/S2#852]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -      1.1.2   |
| @antv/s2-react | -    1.1.1     |

### 🖋 Description
1.  单元格的默认点击行为 会触发 tooltips 的展示， 再点击该单元格的时候， tooltips 有时会隐藏，有时会隐藏后再展示，行为不一致。
2.  单元格框选功能在边缘情况下 会有框选异常
3.  异常操作失焦等。。会导致tooltips 不再展示，刷新后恢复
4.  自定义 tooltips key 问题

### ⌨️ Code Snapshots

https://user-images.githubusercontent.com/35689628/144232243-0d16d9e4-db88-4536-a8cf-46461c1b13fc.mov

https://user-images.githubusercontent.com/35689628/144232753-72045c90-0a53-4920-bd47-05ddbd0035f5.mov

https://user-images.githubusercontent.com/35689628/144232953-76c8d254-e015-4822-a1a3-884b6af25c41.mov

### 🔗 Reproduce Link

https://antv-s2.gitee.io/zh/examples/react-component/switcher#pivot-with-children

### 🤔 Steps to Reproduce
问题： 框选问题
1. 点击单元格  展示tootips
2. 右键单元格   展示右键菜单
3.  点击任何地方 让 右键菜单失焦     错误进入框选模式。

问题： 意外操作失焦
1.	mac 的comand + shift + 5 进入录屏模式 就会导致tootips 不展示

问题： tooltips 的行为不一致
1. 重复点击单元格就可以试出来

问题： react key 报错
[使用来源](https://github.com/antvis/S2/discussions/849#discussioncomment-1727212)
```
this.spreadsheet.tooltip.show({
        position: { x: event.clientX, y: event.clientY },
        content: (
          <div
            className={Style.row_cell}
            key={`${item?.id}${item?.description}`}
          >
            <div>{item?.dimensionName}</div>
            <div>{item?.description}</div>
          </div>
        ),
      });
```
![image](https://user-images.githubusercontent.com/35689628/144206568-e846f72d-55fc-42ad-9562-3a866a2de943.png)

这里是复现的 [demo](https://codesandbox.io/s/hardcore-booth-q26q1?file=/src/App.tsx)
大概原因是因为   自定义组件里有2个 子元素 就会有key 问题

### 😊 Expected Behavior
1. 不进入框选模式
2. tooltips 行为一致，没有迷惑性
3. 没有报错

### 😅 Current Behavior
可见上面的视频

### 💻 System information

 chrome: v96.0.4664.55   macos Big Sur 11.6  (arm64)

**Comment by lijinke666** [comment]
> 单元格框选功能在边缘情况下 会有框选异常
@WeiShengv99 这种情况有复现步骤吗?

**Comment by WeiShengv99** [comment]
> @WeiShengv99 这种情况有复现步骤吗?
@lijinke666    这个问题描述对应着  Steps to Reproduce里的   问题1 和 问题2，还有一些非常边缘的case  比较难以复现。现在不清楚是因为什么原因导致的，出现的场景大概率和分屏有关，我能稳定复现再提issue吧

**Comment by lijinke666** [comment]
好的, 这三个问题已经修复, 非常感谢你的细致反馈
![image](https://user-images.githubusercontent.com/21015895/144555395-131ebbaf-9c25-4c5d-9ce7-2c0b50d0dddf.png)

**Comment by lijinke666** [comment]
@WeiShengv99 欢迎使用 1.2.0
