### ISSUE TITLE
🤔能否禁用调整行高

### ISSUE THREAD

**Issue by FrankPaul1** [antvis/S2#855]
### 🖋 Description
我们的场景里行高是固定的，因此想禁用调整行高的交互（但是保留调整列宽）

### 😊 Expected Behavior
hover 行表头不显示调整行高的效果，移动行高保持不变

### 😅 Current Behavior
![image](https://user-images.githubusercontent.com/9024308/144410231-62d298bd-daed-47fd-b858-db3fad71c2d4.png)

**Comment by lijinke666** [comment]
什么场景下不希望调整行高? 或者说 如果调整了行高会怎么样?
目前还不支持, 不过感觉可以安排

**Comment by FrankPaul1** [comment]
@lijinke666 感谢
场景是：因为内容都是一行，且行高是确定的，因此没有用户调整的诉求
调整了行高会怎么样：主要的影响是，在没有这个诉求的情况下，有这个交互会有一定的干扰，比较奇怪

**Comment by wjgogogo** [comment]
@FrankPaul1 v1.2.0中已经支持禁用resize功能，请参考 [resize文档](https://s2.antv.vision/zh/docs/manual/advanced/interaction/basic#%E8%87%AA%E5%AE%9A%E4%B9%89-resize-%E5%BC%80%E5%90%AF%E8%8C%83%E5%9B%B4) ，[ resize demo](https://s2.antv.vision/zh/examples/interaction/advanced#resize-active)
