### ISSUE TITLE
🐛  react 表自适应行为优化

### ISSUE THREAD

**Issue by WeiShengv99** [antvis/S2#870]
### 🏷 Version
| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.2.0     |
| @antv/s2-react | -   1.2.0      |

### 🖋 Description

目前的 react 版本表格在自适应的时候 的行为不一致
### ⌨️ Code Snapshots
```
<SheetComponent adaptive />
```
### 🔗 Reproduce Link
https://antv-s2.gitee.io/zh/examples/react-component/sheet#pivot

### 🤔 Steps to Reproduce

在官方demo 里添加 adaptive 可以看到， 透视表 和 明细表 在自适应的时候 表现不一致，

透视表 不论放大还是缩小  列都会重新计算宽度

明细表 只有在放大的时候会重新计算宽度， 而缩小的时候并不会重新计算，只会添加一个滚动条

### 😊 Expected Behavior
明细表 在缩小 的时候会重新计算宽度

### 😅 Current Behavior
明细表 在缩小 的时候会没有重新计算宽度

**Comment by WeiShengv99** [comment]
另外

当我设置 adaptive 的时候， option里的width 属性 在第一次渲染的时候会生效，导致 一次闪烁，体验不够友好。
这里是不是可以做一点优化？ 或者说有什么最佳实践

我当前是采用 ResizeObserver 来 计算宽度避免这个问题

**Comment by WeiShengv99** [comment]
还有一个问题

当使用 adaptive 属性进行自适应的时候，如果改变了 columns ，会导致一次闪烁，如果通过 <ResizeObserver> 组件包裹的方式可以避免这个问题

这里是复现的 [demo](https://codesandbox.io/s/nifty-browser-i70c4?file=/src/App.tsx)

**Comment by WeiShengv99** [comment]
@zxc0328  这个问题有什么进度吗，是否是我的打开方式错误。

**Comment by zxc0328** [comment]
设置一下 options.style.cellCfg.width。这个默认是 96，然后如果自适应列宽小于 96，就还是会用默认的 96。所以你如果想要更小的自适应列宽，就把默认的 options.style.cellCfg.width 改小一点。比如 20.

**Comment by zxc0328** [comment]
> 还有一个问题
> 
> 当使用 adaptive 属性进行自适应的时候，如果改变了 columns ，会导致一次闪烁，如果通过 `<ResizeObserver>` 组件包裹的方式可以避免这个问题
> 
> 这里是复现的 [demo](https://codesandbox.io/s/nifty-browser-i70c4?file=/src/App.tsx)

这个最好单独再提一个 issue，因为和你这个问题不是同一个问题，

**Comment by zxtzelnpl** [comment]
明细表 只有在放大的时候会重新计算宽度， 而缩小的时候并不会重新计算，只会添加一个滚动条
https://codesandbox.io/s/nervous-jepsen-qpmqo?resolutionWidth=736&resolutionHeight=675&file=/index.tsx

**Comment by lijinke666** [comment]
fixed #932
