### ISSUE TITLE
🤔色板颜色中文翻译，有几个没看出哪的

### ISSUE THREAD

**Issue by cylnet** [antvis/S2#872]
### 🖋 Description
![image](https://user-images.githubusercontent.com/24189636/145177242-d481793f-84b9-44c0-9c68-dfbfeef048bd.png)

**Comment by cylnet** [comment]
basicColors: [
        '#ffffff', //头部字体颜色
        '#ffffff', //表格主体背景
        '#fff',//鼠标hover颜色
        '#2f75b5',//头背景
        'rgba(47, 117, 181, 1)',
        'rgba(47, 117, 181, 1)',
        'rgba(47, 117, 181, 1)',
        'rgba(47, 117, 181, 1)',
        'rgba(221, 235, 247, 1)',//偶行背景
        'rgba(47, 117, 181, 1)', //主体单元格线
        '#fff', //表头单元格线线
        '#000',  //竖线
        '#fff',
        'rgba(47, 117, 181, 1)',//偶行文字颜色
        'rgba(47, 117, 181, 1)', //左侧字体颜色
      ],

      // ---------- semantic colors ----------
      semanticColors: {
        red: '#FF4D4F',
        green: '#29A294',
      },

**Comment by xingwanying** [comment]
https://antv-s2.gitee.io/en/examples/theme/custom#custom-palette

参考下这个看看呢?

![image](https://user-images.githubusercontent.com/10885578/145178822-f9c3dca7-c208-49ff-9da9-3390eacdcd65.png)

**Comment by wjgogogo** [comment]
@cylnet 可以访问查看色板每一项的含义：https://s2-preview-pr-926.surge.sh/zh/docs/manual/basic/theme#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%89%B2%E6%9D%BF
