### ISSUE TITLE
🐛复制格式化数据和导出格式化数据的时候出现的问题

### ISSUE THREAD

**Issue by bailuren** [antvis/S2#875]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | - ^1.2.0        |
| @antv/s2-react | - ^1.2.0        |

### 🖋 Description
1、复制格式化数据和导出格式化数据的时候，会将url重定向到%60javascript:void(0)%60

![1639014265596_5E42A88F-6179-45d4-B4BE-E13529AD483E](https://user-images.githubusercontent.com/28099704/145323671-29f40d31-71c7-4e7e-9cbc-ac1cd180e549.png)
2、导出的时候，是否将标题导出可以让客户进行选择。
3、导出的csv文件，编码问题解决一下，打开后，中文都是乱码显示
![image](https://user-images.githubusercontent.com/28099704/145326769-d963f07b-5f41-47fa-b009-da4dce7ab545.png)

**Comment by wangwufan** [comment]
在低版本的office(比如2006)打开导出的csv时，这个问题仍然存在
