### ISSUE TITLE
🐛s2Options会跨组件影响

### ISSUE THREAD

**Issue by kilik52** [antvis/S2#886]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.2.0         |
| @antv/s2-react | 1.2.0        |

### ⌨️ Code Snapshots

两个SheetComponent的s2Options会互相影响

### 🔗 Reproduce Link

我录了个视频，见：

https://cdn.zeroetp.com/s2bug.mp4

### 😊 Expected Behavior

不同component配置之间不影响

**Comment by lijinke666** [comment]
方便给一个简单的复现地址吗?

**Comment by kilik52** [comment]
https://codesandbox.io/s/tender-parm-diolh?file=/src/App.js

我在一个页面放了2个SheetComponent。第一个是设了showSeriesNumber: true。 第二个没有设（应该为默认的false）。

右侧页面你往下拉，可以看到第二个sheet也有了序号.

然后你把第一个的component再改为showSeriesNumber: false。 重新刷新页面（有时可能需要刷新两次），序号就又都有了。
