### ISSUE TITLE
🐛表格滚动失效，width设置大一点反而显示不全也无法滚动了

### ISSUE THREAD

**Issue by xdddst** [antvis/S2#889]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |latest         |
| @antv/s2-react | - latest      |

### ⌨️ Code Snapshots

riddle ID:  be030002

**Comment by xingwanying** [comment]
可以描述详细一些么? 我这边把代码跑了下,没get到问题是什么

![image](https://user-images.githubusercontent.com/10885578/145804550-17ff1aa8-0687-4fa1-97cc-d77205b7ec87.png)

**Comment by xdddst** [comment]
内网链接不方便贴出来，贴个riddle ID: be030002

正常滚动: 设置width 600

无法正常滚动：设置width 800

**Comment by lijinke666** [comment]
在 13 寸 电脑, 或者把浏览器窗口宽度缩小时 可以复现
