### ISSUE TITLE
🐛透视表的行维度合并问题

### ISSUE THREAD

**Issue by trace59** [antvis/S2#900]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -     1.3.0    |
| @antv/s2-react | -   1.3.0      |

### 🖋 Description
 透视表的行维度合并存在问题，当存在一个行维度时，且数据的第一个行维度都相同时，会被合并为一行数据

### result
![image](https://user-images.githubusercontent.com/24761764/146184403-9fd4ba53-9167-43f6-bc12-17eae3b5e8ab.png)

### ⌨️ Code Snapshots

import { PivotSheet } from "@antv/s2";

const s2DataConfig = {
  fields: {
    rows: ["province"],
    values: ["city", "type", "price"]
  },
  data: [
    {
      province: "浙江",
      city: "杭州",
      type: "笔",
      price: "1"
    },
    {
      province: "浙江",
      city: "杭州",
      type: "纸张",
      price: "2"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "笔",
      price: "17"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "纸张",
      price: "0.5"
    }
  ]
};

const s2options = {
  width: 800,
  height: 600,
  hierarchyType: "grid"
};

const rootElement = document.getElementById("root");

const s2 = new PivotSheet(rootElement, s2DataConfig, s2options);

s2.render();

### 🔗 Reproduce Link

  https://codesandbox.io/s/blissful-sid-54sbc?file=/src/index.js

### 🤔 Steps to Reproduce
 https://codesandbox.io/s/blissful-sid-54sbc?file=/src/index.js

### 😊 Expected Behavior
预期行为： 应该正常展示，列维度正常合并，数据源展现不应该缺失
### 😅 Current Behavior
当前行为： 列维度合并异常，数据源展示缺失，只展示了一条数据

**Comment by stone-lyl** [comment]
我这边理解你想展示成下面这个样子哈，只需要调整 rows, values 就好了：
![image](https://user-images.githubusercontent.com/20497176/146860702-639369be-a161-4750-94cc-8a444a1f1602.png)

可以阅读 [基本概念](https://s2.antv.vision/zh/docs/manual/basic/base-concept) 加深对配置项的了解哈

**Comment by trace59** [comment]
> 我这边理解你想展示成下面这个样子哈，只需要调整 rows, values 就好了： ![image](https://user-images.githubusercontent.com/20497176/146860702-639369be-a161-4750-94cc-8a444a1f1602.png)
> 
> 可以阅读 [基本概念](https://s2.antv.vision/zh/docs/manual/basic/base-concept) 加深对配置项的了解哈

这个意思就是s2的透视表对单维度不支持吗？我对基本概念是了解的，只是对于你们的合并方式和展示方式有疑惑，个人理解不应该出现这种的展示方式，本质是对单个维度进行groupBy。

**Comment by trace59** [comment]
> 我这边理解你想展示成下面这个样子哈，只需要调整 rows, values 就好了： ![image](https://user-images.githubusercontent.com/20497176/146860702-639369be-a161-4750-94cc-8a444a1f1602.png)
> 
> 可以阅读 [基本概念](https://s2.antv.vision/zh/docs/manual/basic/base-concept) 加深对配置项的了解哈

还有一个问题是如果单维度用明细表来展示，s2后续有没有计划提供单列合并的功能呢？
