### ISSUE TITLE
🐛@antv/s2-react的自适应宽高的bug，会出现计算rowIndex计算为负值的问题，组件直接抛错

### ISSUE THREAD

**Issue by trace59** [antvis/S2#901]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -      1.3.0   |
| @antv/s2-react | -    1.3.0     |

### 🖋 Description
🐛@antv/s2-react的自适应宽高bug，**当组件开启adaptive 且 options的宽高设置为0时**，出现计算rowIndex计算为负值的问题
当不设置option的宽高时，表格会出现错误展示错位，且每列单列的宽度都和父元素等宽

### img
options的宽高设置为 0 的错误
![image](https://user-images.githubusercontent.com/24761764/146187897-45d508a0-2fa5-45e0-8d63-4c46f0206730.png)

options不设置宽高的展示行为：表格第一列前会出现空白间距，且每列单列的宽度都和父元素等宽
![image](https://user-images.githubusercontent.com/24761764/146190416-48409377-44f9-4cd8-8084-d7afd37c99d7.png)

### ⌨️ Code Snapshots

import React from "react";
import ReactDOM from "react-dom";
import { SheetComponent } from "@antv/s2-react";
import "@antv/s2-react/dist/style.min.css";

fetch(
  "https://gw.alipayobjects.com/os/bmw-prod/d62448ea-1f58-4498-8f76-b025dd53e570.json"
)
  .then((res) => res.json())
  .then((res) => {
    const s2DataConfig = {
      fields: {
        columns: [
          "org_name",
          "charge_item_name",
          "settle_date",
          "amount",
        ]
      },
      meta: [
        {
          field: "org_name",
          name: "机构名称"
        },
        {
          field: "charge_item_name",
          name: "收费项目名称"
        },
        {
          field: "settle_date",
          name: "结算日期"
        },
        {
          field: "amount",
          name: "收款金额"
        },
      ],
      data: []
    };

    ReactDOM.render(
      <div
        style={{
          width: 600,
          height: 400
        }}
      >
        <SheetComponent
          adaptive
          dataCfg={s2DataConfig}
          options={{
            width: 0,
            height: 0
          }}
          sheetType="table"
        />
      </div>,
      document.getElementById("container")
    );
  });

### 🔗 Reproduce Link
https://codesandbox.io/s/inspiring-field-fghin
### 🤔 Steps to Reproduce
https://codesandbox.io/s/inspiring-field-fghin

### 😊 Expected Behavior
预期行为： 开启 adaptive 优先读取容器宽高，应该忽略配置项设置的宽高{width: 0, height: 0}，且组件应正常展示
### 😅 Current Behavior
当前行为； 开启 adaptive 配置项设置为{width: 0, height: 0}，组件无法正常展示

**Comment by xingwanying** [comment]
自适应机制优化: 开启 adaptive 读取容器宽高, 关闭情况下再读取配置项

**Comment by trace59** [comment]
> 自适应机制优化: 开启 adaptive 读取容器宽高, 关闭情况下再读取配置项

看第一个截图，我开启adaptive，但组件展示错误，我这边debug看了一下，是rowIndex被计算负值了，不知道你那边能否复现。
复现地址可以看： https://codesandbox.io/s/inspiring-field-fghin?file=/index.tsx
