### ISSUE TITLE
🐛自定义主题中，colCell设置padding后，colCell高度不变化

### ISSUE THREAD

**Issue by lizhongkun** [antvis/S2#917]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -1.3.0      |
| @antv/s2-react | -1.3.0    |

### 🖋 Description
自定义主题中，colCell设置padding后，colCell高度不变化

### ⌨️ Code Snapshots
[https://s2.antv.vision/zh/examples/theme/custom#custom-schema](https://s2.antv.vision/zh/examples/theme/custom#custom-schema)

### 🤔 Steps to Reproduce
      colCell: {
        cell: {
          padding: {
            top: 12,
            right: 8,
            bottom: 12,
            left: 8,
          }
        }
      }

### 😊 Expected Behavior
colCell设置padding后，colCell高度变化
### 😅 Current Behavior
colCell设置padding后，colCell高度无变化

**Comment by wjgogogo** [comment]
@lizhongkun 请通过 colCfg控制高度
```
   const s2Options = {
      width: 600,
      height: 480,
      style:{
        // 通过 colCfg控制高度
        colCfg:{
          height:70
        }
      }
    };
```
