### ISSUE TITLE
🐛表格自适应布局，改变浏览器窗口大小，颜色错乱

### ISSUE THREAD

**Issue by qzp199510** [antvis/S2#928]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -    v1.2.0     |
| @antv/s2-react | -         |

### 🖋 Description
表格自适应布局，改变浏览器窗口大小，颜色错乱

https://user-images.githubusercontent.com/39547706/147030260-f780dd0f-c5c5-45f4-855e-fda4793b4ba4.mp4

### 💻 System information
chrome:96.0.4664.110

**Comment by lijinke666** [comment]
我在 window 电脑上没有复现这个问题, 有复现链接吗?
