### ISSUE TITLE
🐛明细表autoResetSheetStyle配置为false时，且表格无选中状态，鼠标移出画布后，画布未重置交互样式。

### ISSUE THREAD

**Issue by zxtzelnpl** [antvis/S2#938]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.4.0         |
| @antv/s2-react | 1.4.0       |

### 🖋 Description

明细表autoResetSheetStyle配置为false时。
鼠标移入画布，画布有hover的hoverHighlight效果。
画布无选中状态。
鼠标移出画布，画布未清空最后的hover的hoverHighlight效果。

### ⌨️ Code Snapshots

`  
export const options: S2Options = {
  interaction: {
    autoResetSheetStyle: false,
    hoverHighlight: true,
    enableCopy: false,
    selectedCellsSpotlight: true, // highlight click
    brushSelection: false,
    resize: {
      colCellHorizontal: true,
    },
  },
}
`

### 🔗 Reproduce Link
https://codesandbox.io/s/solitary-fog-7eos8?file=/index.tsx:390-409

### 🤔 Steps to Reproduce
明细表autoResetSheetStyle配置为false时。
鼠标移入画布，画布有hover的hoverHighlight效果。
画布无选中状态。
鼠标移出画布，画布未清空最后的hover的hoverHighlight效果。

### 😊 Expected Behavior
明细表autoResetSheetStyle配置为false时，且表格无选中状态，鼠标移出画布后，画布重置交互样式。

### 😅 Current Behavior
明细表autoResetSheetStyle配置为false时，且表格无选中状态，鼠标移出画布后，画布未重置交互样式。

**Comment by lijinke666** [comment]
你配置的 `autoResetSheetStyle: false` 预期就是不重置样式啊, 没懂你的意思

**Comment by zxtzelnpl** [comment]
> 你配置的 `autoResetSheetStyle: false` 预期就是不重置样式啊, 没懂你的意思

那是我理解的问题：
我的理解是 autoResetSheetStyle 重置的是我 刻意**操作** 的样式，比如点击选中，刷新选中。
hover出现的高亮，我认为无论是否设置autoResetSheetStyle，鼠标移除后都应该是被重置的。
