### ISSUE TITLE
🐛明细表自定义数据单元格导致点击序号列行高亮效果消失

### ISSUE THREAD

**Issue by LHC8888** [antvis/S2#941]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.3.0         |

### 🖋 Description

明细表自定义数据单元格，点击序号列，仅高亮序号单元格，同一行上的其他单元格高亮效果消失

### ⌨️ Code Snapshots

```javascript
// S2Options  

dataCell: (viewMeta) => {
    return new CustomDataCell(viewMeta, viewMeta?.spreadsheet);
}
```

```javascript
// CustomDataCell.js
export class CustomDataCell extends DataCell {}
```

### 😊 Expected Behavior

明细表自定义数据单元格，点击序号列，高亮当前行

### 😅 Current Behavior

明细表自定义数据单元格，点击序号列，仅高亮序号单元格，同一行上的其他单元格高亮效果消失

**Comment by zxc0328** [comment]
如果有序列号，自定义时需要对第一列返回序列号格子。

```typescript
import { TableRowCell } from "@antv/s2" 

// S2Options  

dataCell: (viewMeta) => {
    if (viewMeta.colIndex === 0) {
        return new TableRowCell(viewMeta, viewMeta?.spreadsheet)
    }
    return new CustomDataCell(viewMeta, viewMeta?.spreadsheet);
}
```

**Comment by LHC8888** [comment]
v1.20.0+ 需要将 TableRowCell 改成 TableSeriesCell
