### ISSUE TITLE
🐛明细表在列冻结的情况下，即使表格没有出现滚动，也会有分割线

### ISSUE THREAD

**Issue by zxtzelnpl** [antvis/S2#945]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.3.0       |

### 🖋 Description

明细表在列冻结的情况下，即使表格没有出现滚动，也会有分割线
![image](https://user-images.githubusercontent.com/17529046/147312363-caebf6de-d59b-468b-929a-35467399bf49.png)

### ⌨️ Code Snapshots

https://codesandbox.io/s/j54i8?file=/index.ts

### 🔗 Reproduce Link
https://codesandbox.io/s/j54i8?file=/index.ts:0-966

### 😊 Expected Behavior
明细表在列冻结的情况下，即使表格没有出现滚动，不有分割线
### 😅 Current Behavior
明细表在列冻结的情况下，即使表格没有出现滚动，也会有分割线

**Comment by lijinke666** [comment]
ref: https://github.com/antvis/S2/pull/898
