### ISSUE TITLE
🙏【明细表】支持【高级筛选】功能

### ISSUE THREAD

**Issue by kakacookie** [antvis/S2#962]
### 🖋 Description
希望【明细表】支持【高级筛选】功能，【手动排序-设置顺序】列出枚举值，通过拖拽自定义顺序。

### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

**Comment by wjgogogo** [comment]
可以在业务层增加筛选逻辑，把筛选后端数据传入到表格中，以实现你的需求
