### ISSUE TITLE
H5: 滑动屏幕时表格内容没有跟着变化🐛

### ISSUE THREAD

**Issue by bobby-ai** [antvis/S2#985]
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.5.0       |
| @antv/s2-react | 1.5.0         |

### 🖋 Description

在安卓/IOS手机浏览器打开官方给的明细表[例子](https://codesandbox.io/embed/nr80m?codemirror=1)，滑动表格所在屏幕区域，发现表格内容响应非常慢，体验卡顿

### 🔗 Reproduce Link
https://codesandbox.io/embed/nr80m?codemirror=1

### 🤔 Steps to Reproduce

- 手机浏览器打开链接
- 滑动表格时，内容没有跟着滑动

### 😊 Expected Behavior
滑动表格体验和PC保持一致

### 💻 System information

华为Meta40官方自带浏览器

**Comment by lijinke666** [comment]
目前 S2 移动端没有很好的适配, 请问是有很强的移动端诉求吗?

**Comment by bobby-ai** [comment]
移动端诉求比较强烈，通过调试大概定位到问题，如下代码片段：
`
路径：packages/s2-core/src/facet/base-facet.ts
821行：cancelAnimationFrame(this.scrollFrameId);
影响：在移动端wheel比较频繁情况下，两帧之间，下一帧取消上一帧设置的requestAnimationFrame逻辑，该逻辑没有机会执行，导致pivot-table没有滚动效果
改进：
在821行代码改为如下：
  // cancelAnimationFrame(this.scrollFrameId);
  if (this.scrollFrameId) return;
  const scrollFrameId = requestAnimationFrame(() => {
    // 保留老的逻辑
    this.scrollFrameId = null;
  });
  this.scrollFrameId = scrollFrameId;
`
测试后发现手机端可以滚动

**Comment by lijinke666** [comment]
@bobby-ai 由于是虚拟滚动, cancelAnimationFrame 是为了解决PC端快速滚动时导致的白屏, 如果你验证了 pc 和 mobile 都没问题, 直接来个 PR ?
