### ISSUE TITLE
🐛format作用范围

### ISSUE THREAD

**Issue by yanhcao** [antvis/S2#998]
### 🖋 Description
目前列头宽度小于文字应该显示的宽度时，会出现hover列头时tooltip内容错误的问题
![image](https://user-images.githubusercontent.com/33095737/149451573-841b27c2-3b28-4bfb-8d15-9680481b4c29.png)

猜测：meta中对于部分列做了format，format作用content单元格的同时作用到了列上，导致的宽度内容不够时，hover内容出错

**Comment by lijinke666** [comment]
是一个bug, 下次请按照 issue 模板填写, 不然直接关闭了
